OpenMS/OpenMS

- src/openswathalgo/source/ANALYSIS/OPENSWATH/OPENSWATHALGO/DATAACCESS/Transitions.cpp
- src/openswathalgo/source/ANALYSIS/OPENSWATH/OPENSWATHALGO/OpenSwathAlgoFiles.cmake
This fixes the win32 compile issues from last nights win8 test builds. In general we should consider removing `DATAACCESS/Transitions.h` and `TestConvert.cpp` since it is not used anywhere else and the test itself is not a real test.
```
BOOST_AUTO_TEST_CASE(initializeXCorrMatrix)
{
OpenSwath::LightTargetedExperiment  lte;
OpenSwath::TargetedExperiment  te;
//OpenSwath::convert(lte, te);
//TODO (wolski): write tests
}
END_SECTION
```
> [FIX] intermediate fix for win32 systems

- cmake/modules/CheckLibArchitecture.cmake
Sometimes a nightly build fails (e.g. http://cdash.openms.de/viewConfigure.php?buildid=116278),
since dumpbin did not deliver the required information before timing out (3 seconds).
This PR fixes:
- not failing when dumpbin.exe was terminated after timeout (3 sec by default) -- we just assume its the correct arch and report a warning
- timeout  can be increased (e.g. for slow build machines).
- checking libs only once (and store result in CMake cache) -- when libs are exchanged, the user has to delete the cache to re-run the check.
> Make BuildSystem's LibCheck fail-safe

- tools/uncrustify_branch.sh
I moved the option to create a new branch to a flag.
Problem of the create branch behaviour by default was, that its a bit inconvinient if one forgets to create the uncrustify branch befor merging the original pull request. I changed it back to the old behavior but left it as an option.
> [FIX] added -b option to create new branch

- src/tests/topp/CMakeLists.txt
- src/tests/topp/PeptideIndexer_1.fasta
- src/tests/topp/PeptideIndexer_10_input.fasta
- src/tests/topp/PeptideIndexer_10_input.idXML
- src/tests/topp/PeptideIndexer_10_output.idXML
- src/topp/PeptideIndexer.cpp
fixed bug in 'I/L equivalent', causing usage of ambgious AA's for I/L (i.e. a peptide with more than 3 I or L would not have been matched by default)
Fix: replace I with L, and do not use 'J' since this is unknown in the Seqan Alphabet and will silently be converted to 'X'
fixed duplicate protein accession bug (only the second protein in the FASTA file would be used for mapping, but both would be reported, i.e. the first shows up as protein hit, but is never referenced)
Fix: only add one protein to the internal DB in the first place
> Fix issues in PeptideIndexer

- src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.h
- src/openms/source/APPLICATIONS/TOPPBase.cpp
- src/tests/class_tests/openms/data/PeakPickerHiRes_spectrum_selection.mzML
- src/tests/class_tests/openms/source/TOPPBase_test.cpp
- src/tests/topp/INIUpdater_1_noupdate.toppas
- src/tests/topp/INIUpdater_3_old_out.toppas
- src/tests/topp/WRITE_INI_OUT.ini
- src/tests/topp/WSDL_out.wsdl
- src/topp/FeatureFinderCentroided.cpp
- src/topp/FeatureFinderMetabo.cpp
- src/topp/FeatureFinderMultiplex.cpp
- src/topp/MSGFPlusAdapter.cpp
- src/topp/MascotAdapterOnline.cpp
- src/topp/OMSSAAdapter.cpp
- src/topp/PeakPickerHiRes.cpp
- src/topp/XTandemAdapter.cpp
Selected tools now throw an exception in the case an unexpected spectrum type is encountered (e.g. picked spectrum in HighResPeakPicker or profile spectrum in FeatureFinderCentroided). If the spectrum type is UNKNOWN, behavior is as before. This should allow to detect many otherwise hard to discover configuration errors that resulted in pipelines running through but producing results that were inferior (e.g. no ids). In other cases pipelines crashed because of extensive memory consumption.
To be conservative, no additional attempts to deduce spectrum type (e.g. from DataProcessing information or by PeakTypeEstimator is done).
> [FIX] throw exception if tools are run on wrong peak type

- src/tests/topp/THIRDPARTY/third_party_tests.cmake
There seems to be a small copy&paste bug in the FidoAdapter tests.
@hendrikweisser : Is this fix OK or did I get it wrong?
Also, I noticed that the TOPP_FidoAdapter_4 test runs forever on our linux cluster. I canceled it after half an hour. On my Macbook, it runs just fine. Timo said this might be because Fido is extremely slow if it can't use a graphics card. If this is true, I would rather remove TOPP_FidoAdapter_4.
> [FIX,TEST] FidoAdapter test

- src/openms/source/FORMAT/PepXMLFile.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/IDFileConverter_10_input.pepXML
- src/tests/topp/IDFileConverter_10_output.idXML
modifications for the C-terminus (e.g. smaller than electron mass). Which might be a result
from slightly different masses used in X!Tandem.
Additionally, code for fixed, terminal modifications was added.
> [FIX] pepXML does on some occassion contain very small fixed

- src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
this considers conversion from old id formats with insufficient data provision 
- nan value for spectrumreferenceid now equal on all platforms (fixing TOPP_IDFileConverter_9_out1 fail on win8-VS10_)
- added warning if such replacement is necessary
> [FIX] fix for the write out of mzid

- src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
After changes to mzTab output, the observed mass was not exported anymore.
This fixes it.
(along with some minor code cleanup).
> [FIX] AMS: export observed-Mass in mzTab as well

- src/tests/class_tests/openms/source/IndexedMzMLFile_test.cpp
- comment out test that doesnt really do what we want
- apparently it is not that easy to test the overflow of the position on
32 bit systems
disable test, I thought I was testing something for 32 bit systems but when I run it actually on a 32 bit system, it fails. Well so much for testing stuff on 64 bit systems and trying to be smart
> [TEST] fix test

- src/tests/class_tests/openms/source/Param_test.cpp
this fixes the issues on Ubuntu 14.04 for me
apparently if there are `TEST_EXCEPTION` macros in the code *and* the last `TEST` is not a `TEST_EXCEPTON` then I get an error of the sort `FATAL: uncaught exception!` so this seems to be an issue with the global exception handling and the `TEST_EXCEPTION` macro. Is this already known somewhere? 
Anyways, this fixes (half of) the #1030 issue on my machine
> [TEST,FIX] changing the order of the test fixes the issue

- src/tests/class_tests/openms/source/IndexedMzMLFile_test.cpp
fixes IndexedMzMLFile test by testing the size of streampos instead of streamsize
fixes the issue on my 32 bit machine (still does not test the code path)
> [TEST] fix

- src/tests/class_tests/openms/source/AccurateMassSearchEngine_test.cpp
- compare at numerical accuracy of 1e-8 seems reasonable and sufficient
for our purposes
- gcc 4.8.2 on Ubuntu 14.04 produced numerical differences on the order
of 1e-10 when run with -O0 or -O1
- fixes the first part of #1202 for me
> [TEST,FIX] set reasonable comparison tolerance

- src/tests/topp/CMakeLists.txt
- whitelist the base64 string if enough characters are equal in both
files
- note that this will actually *turn off* the most important test
(whether the PP finds the correct m/z) as long as the first characters
are equal
- partially addresses #1202
turning off the test was the only solution I could find right now, it basically still checks that `3bAxk01KjUAAAACgmVGNQIvf6JpEWo1Ah` is there but everything after that is not tested any more. This is really quite ugly, if somebody has a better idea / more time to investigate this please feel free to do so
better solutions
- find out why Ubuntu 14.04 release builds are different
- rewrite FuzzyDiff to specifically ignore lines that only occur in *one* file (not both)
- rewrite the CMake file to test against one file on Ubuntu systems and …
> [TEST] fix test error

- src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLinear.cpp
In #1098, TransformationModelLinear seems to have been forgotten to be reverted to the fixed WildMagic include conventions.
> [FIX] consistent use of wildmagic: TransformationModelLinear

- src/topp/FeatureFinderMultiplex.cpp
Both peptide similarity and averagine similarity are Pearson correlation coefficients. Only values in [0,1] are sensible choices. But in order to switch off these two filters completely, -1 needs to be possible.
> change parameter ranges in FeatureFinderMultiplex

- doc/doxygen/public/UTILS.doxygen
More documentation improvements:
- removed broken entry for PeakPickerRapid (tool removed)
- capitalized headers consistently
- sorted entries in sections alphabetically
- moved "Misc" section to just above "Deprecated"
> Clean-up of UTILS documentation

- cmake/knime_package_support.cmake
commit 2bc4435 introduced a change in param names of FidoAdapter. This was not yet done for the remove_param_from_ctd case for the KNIME nodes.
> [KNIME] adapted parameter naming for FidoAdapter in KNIME

- src/topp/IDFilter.cpp
if used as filter for uniqueness without the input having been run through 'PeptideIndexer'.
All you get is:
IDFilter: Warning, filtering with 'unique_per_protein' can only be done after indexing the file with 'PeptideIndexer' first.
This can be easily overlooked.
Elevated warning to Error.
@lars20070 : can you check if this fixes your issue?
> IDFilter reports empty results

- src/openms/include/OpenMS/KERNEL/MSExperiment.h
sometimes FFMetabo (or any other tool which assembles mass traces) cannot determine charge, which then remains 0 for any features reported.
Converting a featureXML like that to mzML can lead to div/0 if m/z of mass traces is computed in TOPP-FileConverter. The m/z value is then 'nan' and the data obviously useless.
This PR fixes this behaviour by assigning charge 1 to such features.
> [FIX] fix conversion from Feature with Masstraces to MSExperiment

- src/openms/source/ANALYSIS/QUANTITATION/IsobaricChannelExtractor.cpp
- src/tests/class_tests/openms/source/IsobaricChannelExtractor_test.cpp
- src/tests/topp/IsobaricAnalyzer_output_1.consensusXML
Previously, IsobaricAnalyzer did not set the charge states of the consensus features it produced, but it stored the precursor charges as meta values ("precursor_charge"). However, since the centroid position (RT, m/z) of a consensus feature was already chosen to be the precursor position, it makes sense to also set the charge state to the precursor charge (and dispense with the meta value). This makes it possible to keep track of the charge information e.g. when using TextExporter, which is useful for post-processing.
> [FIX] IsobaricAnalyzer: set charge states of consensus features

- src/utils/TopPerc.cpp
might fix build error on windows
> [FIX] lexical cast is discouraged. Use of build in functions.

- src/openms/include/OpenMS/ANALYSIS/QUANTITATION/IsobaricChannelExtractor.h
- src/openms/source/ANALYSIS/QUANTITATION/IsobaricChannelExtractor.cpp
- src/openms/source/ANALYSIS/QUANTITATION/ItraqEightPlexQuantitationMethod.cpp
- src/openms/source/ANALYSIS/QUANTITATION/ItraqFourPlexQuantitationMethod.cpp
- src/openms/source/ANALYSIS/QUANTITATION/TMTSixPlexQuantitationMethod.cpp
- src/openms/source/ANALYSIS/QUANTITATION/TMTTenPlexQuantitationMethod.cpp
- src/tests/topp/IsobaricAnalyzer_output_1.consensusXML
- src/topp/IsobaricAnalyzer.cpp
Extended documentation of IsobaricAnalyzer (e.g. added TMT 10-plex, note about zero-intensity features, ID mapping hints) and fixed the "1 invalid unique ids" warning.
> IsobaricAnalyzer: documentation, warning fix

- src/pyOpenMS/pxds/PepXMLFile.pxd
This commit enables PeptideProphet-like pep.xml export from pyOpenMS.
> [PYOPENMS] Better PepXMLFile write support

- cmake/knime/binaries_mac.ini
Shipped jre in KNIME is located in a subfolder on Mac.
> [FIX] Ammend to #1284

- src/openms_gui/source/VISUAL/TOPPASInputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
This pull request removes OS X specific code for opening folders. It resolves the TOPPAS issue #1299.
> remove OS X specific code for opening folders

- doc/TOPP_tutorial/TOPPView_interface.doxygen
- src/openms_gui/include/OpenMS/VISUAL/Spectrum2DCanvas.h
- src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
- src/openms_gui/source/VISUAL/SpectrumCanvas.cpp
TOPPView's data point size estimation for 2D data is not very good:
it will show huge squares when only a handful of data are within the visible area,
but on the other hand will use the most tiny pixels when there is lots of data in one dimension, but almost none in the other (i.e. showing only a handful of scans over the whole RT range).
This PR fixes:
* point size estimation for the above scenarios by computing a 'coverage' for each dimension: if there is lots of blank background, the pixel size is increased until reaching a sensible maximum (here: 20 pixel).
* speedup of plotting: when plotting lots of data, there was a bug that collected (and maximised over) all RT scans, irrespective of whether they are visible. This can have tremendious speed implications when viewing only partial …
> Fix toppview pen size in 2D View

- src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/ContinuousWaveletTransformNumIntegration.h
- src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerCWT.h
- src/openms/source/TRANSFORMATIONS/RAW2PEAK/ContinuousWaveletTransformNumIntegration.cpp
- src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerCWT.cpp
- src/tests/topp/WRITE_INI_OUT.ini
- massive speedup of PPCWT (~50%)
- fixed potential bug in deconvolution which used MS1 peak bounds irrespective of MS level
> [FEATURE] PeakPicker-Wavelet speedup

- src/openms/include/OpenMS/FILTERING/DATAREDUCTION/FeatureFindingMetabo.h
- src/openms/include/OpenMS/KERNEL/MassTrace.h
- src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
- src/openms/source/KERNEL/MassTrace.cpp
- src/pyOpenMS/pxds/MassTrace.pxd
- src/tests/class_tests/openms/source/MassTrace_test.cpp
- src/tests/topp/FeatureFinderMetabo_2_noEPD.ini
- src/tests/topp/FeatureFinderMetabo_2_noEPD_output.featureXML
- src/topp/FeatureFinderMetabo.cpp
plus
* removal of confusing fwhm-disabling code;
* speedup when creating feature hypothesis (the old code has runtime N*N, the new has N)
> FFMetabo: quantify mass traces using median

- src/topp/OpenSwathAssayGenerator.cpp
This pull request addresses the issue of missing std::round() functionality in VS10.0: https://github.com/OpenMS/OpenMS/commit/89945b7aa0996bbaa9c762054cd19195e405f76f#commitcomment-10688815
> [FIX] OpenSwathAssayGenerator: Compatibilty with VS10.0

- src/openms/source/FORMAT/HANDLERS/IndexedMzMLDecoder.cpp
- instead of iterating through all <offset> elements using an algorithm with
O(n^2) complexity, use one that has O(n) complexity
- removes a major bottleneck in parsing large indexed files that have thousands of spectra
- resolves #1301
this improves parsing a large XML file and calculating its TIC substantially. Before this patch it took 75 minutes to parse through 78 000 spectra, now it takes 90 seconds
> [FEATURE] substantially faster indexed mzML access

- src/topp/MzTabExporter.cpp
Minute change csv to tsv for MzTabExporter output format. Excel and other programs now automatically recognize the format.
> change MzTabExporter output format from csv to tsv

- src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
- src/openms_gui/source/VISUAL/SpectrumWidget.cpp
Issue reported by Ana.Villar-Garea@vkl.uni-regensburg.de
If one clicks on the most right-side of the bar for the  rt axis (x-axis), the window is scrolled to the area with higher rt values, as expected. Consequently, if one clicks on the most left-side, it scrolls to lower rt values. However, for the m/z axis (y-axis), if one clicks on the most upper part of the scroll bar (higher m/z values), the window slides towards smaller m/z values (although one would expect the contrary). If one clicks on the most lower part of the bar, then the window slides to higher m/z values.
This PR fixes the scrollbar behaviour.
> TOPPView: fix vertical scrollbar behaviour

- src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASScene.cpp
- src/openms_gui/source/VISUAL/TOPPASVertex.cpp
- forward error messages to log window [fixes #1321]
- fix output file type naming if 'out_type' value is set (also supports more generic '<outname>_type' values (fixes #709)
> TOPPAS: better error messages and suffix for output filenames

- share/OpenMS/TOOLS/EXTERNAL/msconvert.ttd
- src/topp/GenericWrapper.cpp
Individual mappings can now be used in the file_post tag, i.e.
a mapping can used to generate a unique temp directory name, which can then be reused
multiple times. RawFileConvert.tdd was adapted accordingly.
Addressing #1386
> enable individual temp directory in file_post tags of TTD files

- src/openms/source/KERNEL/ConsensusMap.cpp
- src/topp/FeatureFinderMultiplex.cpp
In the case of knockouts (one or more peptides missing), the labels can only be determined with the help of IDs. The labels in consensusXML were previously left empty. Now a unique identifier is used.
> labels in consensusXML for knockouts added

- src/openms/include/OpenMS/MATH/MISC/CubicSpline2d.h
- src/openms/source/MATH/MISC/CubicSpline2d.cpp
Construction of the spline is especially slow, compared to evaluating it.
This PR allows a speedup of ~3-4x for construction, and a minor speedup in evaluating (5%).
10 million constructions:
old: 46s
new: 13s  (3.5x faster)
This also speeds up downstream tools, e.g. PeakPickerHiRes' picking step:
6.52s vs 8.22s (26% speedup)
> Speedup (x 3-4) cubic spline 2d

- doc/TOPP_tutorial/TOPPAS.doxygen
- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
TOPPAS used to call each tool with --no_progress, i.e. the user had no option of seeing the status of a tool, no matter how -no_progress was set in the parameters.
This PR gives user control over -no_progress for each TOPP tool; progress is disabled by default
Plus:
Some minor documentation fix.
> TOPPAS tool progress

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
Empty spectra are now ignored and skipped in the filtering step of the FeatureFinderMultiplex algorithm.
> skip empty spectra in FeatureFinderMultiplex filtering step

- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASVertexNameDialog.h
- src/openms_gui/include/OpenMS/VISUAL/TOPPASOutputFileListVertex.h
- src/openms_gui/include/OpenMS/VISUAL/TOPPASScene.h
- src/openms_gui/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp
- src/openms_gui/source/VISUAL/TOPPASInputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASScene.cpp
- src/tests/topp/INIUpdater_1_noupdate.toppas
- src/tests/topp/INIUpdater_3_old_out.toppas
I've been thinking about this for quite some time, because the output folder keeps changing when new nodes are inserted into a pipeline.
Howto:
right-click on output vertices -> 'Set output folder name'
Restriction: allowed output characters are:  A-Z, 0-9, underscore and hypen. Nothing else -- ensuring that the output folder is valid on all supported platforms (e.g. Windows forbids ", <, >, ... see https://msdn.microsoft.com/en-us/library/aa365247?f=255&MSPPError=-2147217396)
Caveat/Feature: naming two folders equally will result in merged/overwritten output. Use at own risk :)
solves #1415
> TOPPAS: allow for custom output folder names 

- src/openms/include/OpenMS/METADATA/MetaInfoInterfaceUtils.h
- src/openms/include/OpenMS/METADATA/sources.cmake
- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
- src/tests/class_tests/openms/executables.cmake
- src/tests/class_tests/openms/source/MetaInfoInterfaceUtils_test.cpp
- src/topp/TextExporter.cpp
Metavalues with a certain user defined frequency (0-100%) can now be exported as additional columns for featureXML.
Some GUI code was adapted to use the new functionality.
This should also enable the export of Fido scores via TextExporter, as mentioned in #1381 (although support for idXML needs to be added in TextExporter).
> Meta value export for TextExporter

- src/openms/source/FORMAT/MascotRemoteQuery.cpp
- src/tests/topp/FileInfo_10_output.txt
- src/topp/FileInfo.cpp
One of the fields in FileInfo output renamed. Now in line with the name of the corresponding class (PeptideIdentification).
> FileInfo, field renamed

- src/openms/include/OpenMS/FILTERING/TRANSFORMERS/Normalizer.h
- src/openms/source/FILTERING/TRANSFORMERS/Normalizer.cpp
- src/tests/class_tests/openms/source/Normalizer_test.cpp
- src/topp/SpectraFilterNormalizer.cpp
- remove unneccessary restriction which removes meta-values from input data
- clean-up of main normalization method
- faster class test
- better doc
> Improvements to SpectraFilterNormalizer

- src/openms/source/FILTERING/TRANSFORMERS/SpectraMerger.cpp
- src/tests/class_tests/openms/source/SpectraMerger_test.cpp
On modern mass spectrometry machines (e.g. Q Exactive) two peaks can be considered distinct if they are roughly 5 ppm apart. The default params in SpectraMerger have been changed.
Resolves #1461.
> [PARAM] SpectraMerger default params changed

- src/openms/include/OpenMS/CHEMISTRY/EnzymesDB.h
- src/openms/source/CHEMISTRY/EnzymesDB.cpp
- src/openms/source/SYSTEM/File.cpp
- src/tests/class_tests/openms/source/EnzymesDB_test.cpp
- src/tests/class_tests/openms/source/File_test.cpp
- src/utils/OpenSwathWorkflow.cpp
fixed EnzymesDB:
- synonyms were not indexed correctly
- adding new enzymes was incomplete
- constness and double bookkeeping fixed
- extended tests (incomplete before)
While doing this, I found an inconvenience in File::find(), which could not be called recursively (as it happens here when using ::setEnyzmes(filename). Fixed as well (see test).
> [FIX, DOC, INTERNAL] Fix enzymesDB

- src/openms/include/OpenMS/MATH/STATISTICS/GaussFitter.h
- src/openms/source/MATH/STATISTICS/GaussFitter.cpp
- src/tests/class_tests/openms/source/GaussFitter_test.cpp
GaussFitter 
- returns valid sigma values now (only positive) ... in some rare cases sigma was negative and thus invalid. Using fabs() solves this (and is the correct solution).
- added an evaluation function, which uses the fitted model to predict data intensities
- test extended
- improved stopping criterion check of LevenbergMQ
- fitting-speed improvement by ~10% by restructuring formulas
When reviewing this, please verify that the formula reconstruction is actually correct (I'm reasonably sure that this is the case, since the results are identical on a large dataset, but one never knows :) ).
> [FIX, FEATURE] GaussFitter: return valid sigma values

- doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp
- src/openms/include/OpenMS/ANALYSIS/ID/ConsensusIDAlgorithmWorst.h
- src/openms/include/OpenMS/ANALYSIS/ID/sources.cmake
- src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithmWorst.cpp
- src/openms/source/ANALYSIS/ID/sources.cmake
- src/tests/class_tests/openms/executables.cmake
- src/tests/class_tests/openms/source/ConsensusIDAlgorithmWorst_test.cpp
- src/topp/ConsensusID.cpp
Added a new ConsensusID algorithm that, when combining ID runs, uses the worst score among all runs for each PSM. This is the opposite of the existing "best" strategy and allows for conservative merging.
> New ConsensusID algorithm "worst"

- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASInputFileDialog.h
- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASInputFilesDialog.h
- src/openms_gui/source/VISUAL/DIALOGS/TOPPASInputFilesDialog.cpp
TOPPAS InputNode:
- support Ctrl+C for selected items in the InputList
- support drag'n'drop of files from window manager (e.g. Windows Explorer)
- close InputFile window when pressing 'Escape'
Minor cleanup.
> [FEATURE] TOPPAS convenience functionality

- src/topp/ConsensusID.cpp
When the "filter:min_support" option is used in ConsensusID, peptide identifications without any peptide hits can be generated (if none of the hits pass the filter). Storing the resulting IdXML file would then produce this message:
> Omitted writing of ... peptide identifications due to empty hits.
To avoid this message (indicating a problem where there isn't one), peptide IDs with empty hits are now skipped when the final list of IDs is generated.
> ConsensusID: avoid warning message

- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.h
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
If a data point passes all filters, the corresponding peaks in the spectrum and the two neighbouring ones are blacklisted. In this pull request, the blacklisting is extended to +/-2 spectra. The FP detection rate should thereby be reduced.
> extended blacklisting in FeatureFinderMultiplex

- tools/b.bat
- tools/build.bat
for fast building of executables from command line.
This saves a lot of time, since Visual Studio IDE does not need to be opened (especially for class-tests).
After adding <OpenMS-src>/tools to %PATH% a Windows developer can:
Build all tests:
b -
b - r c   // same as above (build all class tests in release mode)
Build a specific executable
b FeatureFinderCentroided r t
Usage: 
```
b.bat <target(- for all)> [[<[r]elease|[d]ebug>] <Sln:[c]lass-test|[t]opp|[u]til|[g]ui>]
```
> WindowsOS: add a convenience batch file 

- CMakeLists.txt
Minor: add some a one-liner during CMake execution which tells the developer how to disable/enable git tracking
> [BuildSystem] better log when configuring

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureDistance.h
- src/openms/source/ANALYSIS/MAPMATCHING/FeatureDistance.cpp
- src/openms/source/ANALYSIS/MAPMATCHING/StablePairFinder.cpp
- src/tests/class_tests/openms/source/FeatureDistance_test.cpp
Docs were somewhat confusing, and tests not very exhaustive. Fixed.
TOPP: affects FeatureLinkerUnlabeled
> [DOC,TEST] for StablePairFinder / FeatureDistance

- src/topp/MSGFPlusAdapter.cpp
The installation of java is now only checked, if the `force` flag is not set. That allows to circumvent time-out crashes when the system is very busy. Resolves #1517.
> force flag circumvents java time-outs in MSGFPlusAdapter

- share/OpenMS/examples/simulation/FASTAProteinAbundanceSampling.py
- src/pyOpenMS/create_cpp_extension.py
- src/pyOpenMS/pyopenms/__init__.py
- src/pyOpenMS/pyopenms/sysinfo.py
- src/pyOpenMS/setup.py
This pull requests makes distributable pyopenms binaries work with Python 3, specifically I tested this on Ubuntu 12.04 and 14.04
These changes should be ported forward to develop at some point
> [BUILD] fixes for pyopenms 2.0

- src/topp/MapAlignerPoseClustering.cpp
Index variable changed from `Size` to `int` in  MapAlignerPoseClustering for OpenMP.
Attempt to fix #1566 by correcting #1531.
> index variable change in MapAlignerPoseClustering

- share/OpenMS/TOOLS/EXTERNAL/Rscript_generic.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PEP.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PRT.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PSM.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_qcfigures_acc.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_qcfigures_idmap.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_qcfigures_setid.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_qcfigures_tic.ttd
to avoid potential crash for TTD files when paths contain spaces
> [FIX] proper argument quoting in GenericWrapper-TTD's

- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASInputFilesDialog.h
- src/openms_gui/include/OpenMS/VISUAL/TOPPASInputFileListVertex.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/DIALOGS/TOPPASInputFilesDialog.cpp
- src/openms_gui/source/VISUAL/TOPPASInputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASScene.cpp
this PR collects three minor improvements to TOPPAS and TOPPView:
[TOPPView] add Tooltip in Layer Window, giving the full file path (helpful for duplicate layers with identical filename)
[TOPPAS] remember most recent directory when adding files to an Input-Vertex -- makes browsing easier
and somewhat a bugfix:
[TOPPAS] reset downstream pipeline when transferred params between nodes
> Some GUI convenience features

- src/openms_gui/include/OpenMS/VISUAL/TOPPASEdge.h
- src/openms_gui/source/VISUAL/DIALOGS/TOPPASOutputFilesDialog.cpp
- src/openms_gui/source/VISUAL/TOPPASEdge.cpp
- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASVertex.cpp
when working with input file lists, TOPPAS will now:
- use source filenames 1:1 if possible (new suffix if applicable)
- use a 0-filled counter if filenames are duplicated (from different directories), e.g. fileX.001.mzML
When possible TOPPAS will now also prefer input filenames from "-in" (this usually only affects workflows with multiple input edges, but a single round (ie file) only).
This fixes #620 and #1480.
> Toppas filename generation

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/PoseClusteringAffineSuperimposer.h
- src/openms/source/ANALYSIS/MAPMATCHING/PoseClusteringAffineSuperimposer.cpp
switch interface from `ConsensusMap` to `std::vector<Peak2D>` as this is a much cleaner interface and the algorithm only needs RT, m/z and int information. This potentially allows other code to use an easy interface for alignment that takes two simple 3D peaklist as input.
This should be merged after #1598
> Refactor PoseClustering: Redesign interface

- src/openms/include/OpenMS/DATASTRUCTURES/DRange.h
- src/openms_gui/source/VISUAL/SpectrumCanvas.cpp
- src/tests/class_tests/openms/source/DRange_test.cpp
> [FIX] TOPPView: add margins around data range (2%)

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentTransformer.h
- src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentTransformer.cpp
use of "interface" in our code as variable identifier
> [FIX] attempt to fix error C2332: 'struct' : missing tag name caused by

- src/openms/include/OpenMS/METADATA/SpectrumMetaDataLookup.h
> [FIX] fix bug in VS related to multiple static variable definitions in a

- src/topp/MascotAdapterOnline.cpp
So far, "OpenMS_search" has been used as the title for all Mascot searches performed via MascotAdapterOnline. This makes it almost impossible to identify a particular search if several are run at the same time. This change uses the name of the input file (minus extension) as the search title, which makes it easy to find the search on Mascot log pages.
Also adds some minor usability and code improvements.
> MascotAdapterOnline: use input file name as search title

- src/tests/topp/THIRDPARTY/FidoAdapter_4_input.idXML
- src/tests/topp/THIRDPARTY/FidoAdapter_4_output.idXML
- src/topp/FidoAdapter.cpp
Solves #1575. Instead of handling meta values/UserParams directly in FidoAdapter, this can now be done (better) using IDScoreSwitcher. The documentation and one test case were updated to reflect this.
> Fidoadapter: improved PEP handling, removed "prob_param"

- src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandlerHelper.h
- src/openms/source/FORMAT/HANDLERS/MzMLHandlerHelper.cpp
- proteowizard seems to not set the data type when using ms-numpress
even though this is required by the standard.
- as ms-numpress does not care about 32/64 bit, this seems to be the
safest course of action at the moment and makes converted files work
in OpenMS
- partial fix for #1618
- unsolved: how to deal with the general case when no attribute is provided about the identity of the array (now it at least outputs a warning)
Fixes #1618
> [FIX] handles invalid mzML without data type

- src/openms/include/OpenMS/FORMAT/DTAFile.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/MascotXMLHandler.h
- src/openms/include/OpenMS/FORMAT/MascotGenericFile.h
- src/openms/include/OpenMS/FORMAT/MascotInfile.h
- src/openms/source/FORMAT/HANDLERS/MascotXMLHandler.cpp
- src/openms/source/FORMAT/MascotGenericFile.cpp
- src/openms/source/FORMAT/MascotInfile.cpp
- src/tests/class_tests/openms/data/MascotInfile_test.mascot_in
- src/tests/class_tests/openms/source/MascotGenericFile_test.cpp
MGF parser would choke on
```
BEGIN IONS
123.1  456.7  # two spaces (allowed)
END IONS
```
and also if Tabs are used instead of spaces (strictly speaking not part of the standard, but a sensible extension).
Also, the error messages are now more explicit (mention line number etc).
Fix PR fixes this.
> Fix mgf space/tab while loading

- src/openms/include/OpenMS/KERNEL/ConsensusFeature.h
- src/openms/source/KERNEL/ConsensusFeature.cpp
- src/pyOpenMS/pxds/ConsensusFeature.pxd
- src/pyOpenMS/pxds/FileHandler.pxd
- src/pyOpenMS/pxds/MSExperiment.pxd
Currently it is not possible to access the individual FeatureHandle inside an ConsensusFeature using pyOpenMS which makes the wrapper rather pointless. This will allow to access a list of FeatureHandle for each ConsensusFeature (non-mutable). 
A possible extension is to also add a "set" function but right now this could be accomplished by `clear` and then `insert`
> [FEATURE] add function that returns simple list

- src/topp/MascotAdapterOnline.cpp
- src/topp/PhosphoScoring.cpp
The tool doesn't work if either of these parameters isn't set, so they should be defined as "required".
Unrelated: small change to MascotAdapterOnline log output.
> PhosphoScoring: marked "in"/"id" parameters as required

- share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PEP.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PRT.ttd
- share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PSM.ttd
There are three R scripts for the conversion of `*.mzTab` to better readable `*.tsv`. Previously, output files had the suffix `*.unknown`. After corrections of the `ttd`, it is now `*.tsv`.
> correction of generic R script wrappers for mzTab to tsv conversion

- src/openms/source/FORMAT/PepXMLFile.cpp
Blank was missing to write attribute mod_nterm_mass in tag modification_info.
modified:   ../src/openms/source/FORMAT/PepXMLFile.cpp
> [FIX] Fixed unreported error in FORMAT/PepXMLFile.cpp

- src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
most important fix here: the amino acid with the invalid modification was displayed wrong in the error message, taking the AA after the actual target, i.e. index, instead of index-1.
otherwise its just more instructive now (gives the sequence, for easier debugging)
> minor fix for warnings in mzidentml parser

- src/tests/topp/CMakeLists.txt
- src/utils/MzMLSplitter.cpp
> MzMLSplitter: include total number of parts in output file names

- src/openms/include/OpenMS/FORMAT/HANDLERS/XTandemInfileXMLHandler.h
- src/openms/include/OpenMS/FORMAT/XTandemInfile.h
- src/openms/source/FORMAT/HANDLERS/XTandemInfileXMLHandler.cpp
- src/openms/source/FORMAT/XTandemInfile.cpp
- src/tests/class_tests/openms/data/XTandemInfile_test_write.xml
- src/tests/class_tests/openms/source/XTandemInfile_test.cpp
- src/tests/topp/THIRDPARTY/XTandemAdapter_1.ini
- src/tests/topp/THIRDPARTY/third_party_tests.cmake
- src/topp/XTandemAdapter.cpp
- improve impl. of XTandemInfile 
- checks XML tag ordering now via recursion
- also empty-values parameters are loaded (to be able to preserve them when writing)
- better docs for Xtandem-Adapter (especially on the use of the default config)
- The param '-default_input_file' is renamed to '-default_config_file' and has a non-empty default now (the XML config in OpenMS/share). The behaviour is IDENTICAL to before, but the file is now explicitly mentioned. If the parameter is set empty, no config file will be loaded in the background (was not possible before).
- The user can set a flag 'ignore_adapter_param', which gives precendence to the XML config file for all but four parameters: -in -out -database and -xtandem_executable.
> Xtandem-Adapter usability

- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMasses.h
- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMassesGenerator.h
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMasses.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMassesGenerator.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexIsotopicPeakPattern.cpp
- src/tests/class_tests/openms/source/MultiplexClustering_test.cpp
- src/tests/class_tests/openms/source/MultiplexDeltaMassesGenerator_test.cpp
- src/tests/class_tests/openms/source/MultiplexDeltaMasses_test.cpp
- src/tests/class_tests/openms/source/MultiplexFilteringCentroided_test.cpp
- src/tests/class_tests/openms/source/MultiplexFilteringProfile_test.cpp
- src/tests/class_tests/openms/source/MultiplexFiltering_test.cpp
- src/tests/class_tests/openms/source/MultiplexIsotopicPeakPattern_test.cpp
- src/topp/FeatureFinderMultiplex.cpp
For the search of peptide multiplets, a complete set of all possible delta masses a.k.a. mass shifts are necessary. Previously, only the delta mass vectors were constructed. Now also the label sets giving rise to the shifts are stored.
See label sets in brackets in the triple-SILAC example below.
```
mass shift 1:    0 (no_label)    4.02511 (Lys4)    8.0142 (Lys8)    
mass shift 2:    0 (no_label)    6.02013 (Arg6)    10.0083 (Arg10)    
mass shift 3:    0 (no_label)    8.05021 (Lys4,Lys4)    16.0284 (Lys8,Lys8)    
mass shift 4:    0 (no_label)    10.0452 (Arg6,Lys4)    18.0225 (Arg10,Lys8)    
mass shift 5:    0 (no_label)    12.0403 (Arg6,Arg6)    20.0165 (Arg10,Arg10)    
mass shift 6:    6.02013 (Arg6)    10.0083 (Arg10)    
mass shift 7:    4.02511 (Lys4)    8.0142 (Lys8)    
mass …
```
> label sets for MultiplexDeltaMasses

- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMasses.h
> missing macro added to struct DeltaMass

- share/OpenMS/SCHEMAS/ConsensusXML_1_6.xsd
- share/OpenMS/SCHEMAS/FeatureXML_1_8.xsd
- share/OpenMS/SCHEMAS/IdXML_1_3.xsd
This PR is mainly a rearrangement of the schema and introduction of common XML types (e.g. PeptideHitType, SearchParametersType, etc.) to make the schema easier readable.
One addition is the adaption of the enzyme entry (changed from enum to a xs:string) as we now support arbitrary enzymes via EnzymeDB.
> [FIX] schema simplifications and adaptation of enzyme entry

- src/openms/include/OpenMS/CHEMISTRY/EnzymaticDigestion.h
- src/openms/include/OpenMS/DATASTRUCTURES/String.h
- src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
- src/tests/class_tests/openms/source/EnzymaticDigestion_test.cpp
strings (e.g. from fasta files)
Introduces a minimal version of boost::string_ref needed to remove string copies.
> [FEATURE] faster digestion of unmodified string

- src/openms/source/FILTERING/DATAREDUCTION/MassTraceDetection.cpp
The check for the length of the masstrace does not make sense if the
mass trace detection is followed by elution peak detection as in the
MassTraceExtractor where long mass traces are split up. Instead what
happens is that MTD is extremely slow since it finds the same masstraces
again and again but is prevented from adding them to the result and move
on.
This commit allows to set max_trace_length to -1 and skip the length
check.
> [FIX] allow user to turn off mass trace length check

- src/openms/include/OpenMS/COMPARISON/SPECTRA/SpectrumAlignment.h
- src/tests/class_tests/openms/source/SpectrumAlignment_test.cpp
alignment code contained parameter to set relative tolerances but this was not part of the implementation. This PR adds a simple peak matching algorithm using relative tolerances and tests.
> [FIX] added code for peak alignment with relative tolerances

- src/pyOpenMS/CMakeLists.txt
- sync autowrap version with OpenMS source code
- ensure current sources can be built
currently autowrap 0.7.0 is necessary to build pyOpenMS, make sure this is properly checked during build
> [BUILD] update autowrap version

- src/pyOpenMS/pyopenms/__init__.py
- src/pyOpenMS/pyopenms/sysinfo.py
- src/pyOpenMS/setup.py
- complete work from 286785c5775d3edc0e037a41e09e5a816b72ab66
- Python 3 simply uses "linux" as platform and was therefore not recognized.
> [BUILD] fix platform for Python 3

- src/pyOpenMS/CMakeLists.txt
- src/pyOpenMS/create_cpp_extension.py
- prevent autowrap from using its own boost headers
- requires a newer version of autowrap
- related to #1207 (provides a complete fix)
using its own boost headers led to conflicts when OpenMS used boost >= 1.55 and
pyOpenMS did not compile any more
NOTE: please wait with merge until autowrap version 0.7.1 is available on PyPI
> [BUILD] use only OpenMS boost headers

- src/openms/include/OpenMS/FORMAT/MzTab.h
- src/openms/include/OpenMS/FORMAT/MzTabFile.h
- src/openms/source/FORMAT/MzTab.cpp
- src/openms/source/FORMAT/MzTabFile.cpp
- src/tests/class_tests/openms/source/MzTabFile_test.cpp
- src/tests/class_tests/openms/source/MzTab_test.cpp
* create protein-, peptide-, and psm header based on all data instead of the first object in the list.
* check that the optional meta value is written in the correct column
* added class test to check if all header columns are existing
* added class test to check if the data fits to the header column
> [FIX-#1703] MzTabExporter: header columns doesn't match with data columns

- src/openms/source/ANALYSIS/OPENSWATH/SwathMapMassCorrection.cpp
- MSVS does not implement log2()
- but it should implement log()
hopefully fixes the Windows nightly build, see http://cdash.openms.de/viewBuildError.php?buildid=159277
> [FIX] fix for Windows

- src/tests/class_tests/openms/source/HyperScore_test.cpp
may fix issue with clang 5
```
/.../HEAD/src/tests/class_tests/openms/source/HyperScore_test.cpp:101:17: error: call to 'pow' is ambiguous
```
http://cdash.openms.de/viewBuildError.php?buildid=159354
> [FIX] fix pow issue

- src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h
This is a substantial speedup of the FeatureFinderMultiplex algorithm. It improves the runtime complexity of the clustering step (the current bottleneck) from quadratic to linear in the number of initial clusters. On a 800MB Velos run, this gave me a ~300x speedup of the clustering step (< 20s instead of 1h 24min) and thus a ~50x overall speed up for the entire TOPP tool run (< 2 min vs 1h 30).
The additional memory consumption of the two lookup tables is negligible. Results are identical except for occasional differences in the 12th decimal of m/z and RT values due to a slightly different order of computations.
> FeatureFinderMultiplex speedup

- src/topp/IDPosteriorErrorProbability.cpp
The search engine MS-GF+ is writing
```
search engine="MS-GF+"
```
in the `mzid`output. In the `MSGFPlusAdapter`, this tag is forwarded to `idXML`. The `IDPEP` tool expects
```
search engine="MSGFPlus"
```
instead. The pull request now allows for both cases.
> [INTERNAL] add another string as identifier for MS-GF+ search engine

- src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
- src/tests/topp/IDFileConverter_15_output.idXML
- src/tests/topp/IDFileConverter_8_output.idXML
- src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.mzid
- src/utils/IDScoreSwitcher.cpp
Previously, the `mzIdentML` handler stored scores as string cv params. The scores are now stored as float. This change fixes the `IDScoreSwitcher`.
> mzIdentML handler stores scores now as float

- src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.mzid
- src/topp/MSGFPlusAdapter.cpp
Since #1679, the MS-GF+ adapter converts `mzid` directly to `idXML`. The `mzid` handler sets `MS:1002049` (MS-GF raw score) as peptide identification score.
The `MSGFPlusAdapter` now re-sets the peptide identification score to `MS:1002052` (MS-GF spectral E-value) after the `mzid` to `idXML` conversion. Fixes #1691.
> MSGFPlusAdapter sets MS-GF+ e-value as peptide score

- src/topp/PeptideIndexer.cpp
Quick fix for #1793.
I haven't had time to implement the proper solution described in the ticket, but this is better than what we had (and I don't want to leave the problem without a fix until after the next release).
> Fix PeptideIndexer chymotrypsin/"IL_equivalent" problem

- doc/doxygen/public/TOPP.doxygen
SpectraMerger is now listed under the "Signal processing and pre-processing" section instead of "File Handling".
> Moves the SpectraMerger tool to the correct section

- src/openms/include/OpenMS/ANALYSIS/ID/AScore.h
- src/openms/include/OpenMS/DATASTRUCTURES/ListUtils.h
- src/openms/include/OpenMS/DATASTRUCTURES/StringUtils.h
- src/openms/source/CONCEPT/VersionInfo.cpp
- src/openms/source/DATASTRUCTURES/StringUtils.cpp
- src/openms/source/DATASTRUCTURES/sources.cmake
- src/openms/source/FORMAT/SequestOutfile.cpp
- src/tests/class_tests/openms/source/MRMIonSeries_test.cpp
- src/tests/class_tests/openms/source/PILISNeutralLossModel_test.cpp
- src/tests/class_tests/openms/source/StringUtils_test.cpp
- src/tests/class_tests/openms/source/String_test.cpp
- src/topp/MascotAdapter.cpp
we currently use Boost's qi::phrase_parse
to convert a string to any other type (usually double, float or int).
However, passing a string with trailing characters, e.g., "1.2   3.4" would lead to successful conversion,
to 1.2, but does not throw an error.
**This is bad!**
Imagine the following command:
`Filefilter -in infile.mzML  -peak_options:level "1 2" -out outfile.mzML`
MS-level 2 would be removed, without the user even noticing (you can make up more complicated cases ofc).
With this PR, the above command will fail with:
`Invalid parameter values: Prefix of string '1 2' successfully converted to an integer value. Additional characters found at position 3. Aborting!`
This allows to correct the above command to (removing quotes):
` ....   -peak_options:level 1 2  ... `
> fix silent conversion of incomplete strings

- src/openms/include/OpenMS/KERNEL/RangeUtils.h
- src/openms/source/METADATA/Precursor.cpp
- src/tests/class_tests/openms/source/RangeUtils_test.cpp
- src/tests/topp/CMakeLists.txt
- src/topp/FileFilter.cpp
additional option '-peak_options:pc_mz_list' for TOPP:FileFilter allows to provide a mass list.
All MS2 spectra whose precursor covers any of the given values is retained.
Other MS2 spectra are discarded.
Also:
- renamed precursor mass range filter from '-pc_mz' to '-peak_options:pc_mz_range'
> [Feature] MS/MS precursor filtering by mass list

- src/openms/include/OpenMS/FILTERING/SMOOTHING/FastLowessSmoothing.h
Compiling in debug mode (OSX 10.10.5, Apple LLVM version 7.0.0 (clang-700.0.72)) fails as std::greater is unknown.
> [FIX] add missing include

- src/openms/include/OpenMS/ANALYSIS/ID/AScore.h
- src/openms/source/ANALYSIS/ID/AScore.cpp
- src/tests/class_tests/openms/source/AScore_test.cpp
- src/topp/PhosphoScoring.cpp
Following changes were necessary: 
* Limitations: if too many phosphorylation events and sites are in a peptide, the number of permutations gets extremely big. Because of this the calculation times takes extremely long and also the used memory is increasing rapidly. These limitations are now the same as in LuciPHOr.
* Adapt PhosphoScoring output format to LuciphorAdapter output format: the main score of the peptide hit is now the lowest AScore
* Per theoretical spectrum peak only one match to the experimental spectrum per window is allowed. Otherwise it can happen that the number of site determining ion matches are more than the number of site determining ion matches.
* Corrected calculation of number of matched peaks (iteration limit was set wrong)
if the peptide score of the two best …
> Fix phospho scoring

- src/openms/include/OpenMS/FORMAT/HANDLERS/MzIdentMLHandler.h
- src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
- src/tests/topp/IDFileConverter_9_output.mzid
The `<ModificationParams>` and `<Enzymes>` sections were moved to the correct positions.
Required for valid `mzid`.
> ModificationParams and Enzymes section in mzid moved

- src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
The N-terminal character `[` and C-terminal character `]` are changed to `-` in accordance with [1].
[1] see `pre=` and `post=` in 6.46 https://github.com/HUPO-PSI/mzIdentML/blob/master/specification_document/specdoc1_1/mzIdentML1.1.1.doc
> change of N- and C-terminal characters in mzid output

- src/topp/PeptideIndexer.cpp
Addresses issue #1824; see the discussion there. Changes implemented:
- The tolerant search does not need to run at all if no mismatches or matches to ambiguous amino acids (AAAs) are allowed, i.e. if the parameters "mismatches_max" and "aaa_max" are both zero.
- If only AAAs are allowed during the tolerant search, only proteins with AAAs need to be considered.
This PR clashes with #1833. I'll update it when #1833 is merged.
> PeptideIndexer performance optimizations

- src/tests/topp/CMakeLists.txt
- src/tests/topp/FileInfo_14_input.mzid
- src/tests/topp/FileInfo_14_output.txt
- src/tests/topp/FileInfo_15_input.mzid
- src/tests/topp/FileInfo_15_output.txt
Two new `FileInfo` TOPP tool tests for the validation of `mzid`.
> FileInfo tests for mzid validation

- share/OpenMS/GUISTYLE/qtStyleSheet.qss
- src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPAS.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/MISC/QApplicationTOPP.cpp
- introduce CSS-like stylesheets 
- make background items more prominent (the initial reason to make this PR)
example (rows which are out of focus are not better visible -- so the user can select the next row more conveniently):
> [GUI] customizable TOPP[as/view] look and feel

- src/openms/include/OpenMS/CHEMISTRY/ModificationsDB.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/MascotXMLHandler.h
- src/openms/source/CHEMISTRY/ModificationsDB.cpp
- src/openms/source/FORMAT/HANDLERS/MascotXMLHandler.cpp
- src/tests/class_tests/openms/data/MascotXMLFile_test_out_3.idXML
- src/tests/class_tests/openms/source/MascotXMLFile_test.cpp
- src/tests/topp/IDFileConverter_1_output.idXML
- src/tests/topp/IDFileConverter_5_output.idXML
[FIX-#1740] Split Phospho (ST) to Phospho (S), Phospho (T)
When Mascot output XML parsed, split the fixed modifications immediately after parsing, because identifier information don't needs to be preserved.
The order of variable modifications needs to be preserved, because the position of the modification in the list indicates the index of these pattern:
pep_seq: QKAAGSK
pep_var_mod_pos: 4.0000000.0
=> modification on the 4th position is the n-terminal modification.
Fixed in addition Mascot XML Parser - Terminal Modifications:
[FIX 1] Mascot adds fixed modifications, which cannot be set, additionally as variable modification.
Error example: Fixed mod: "Gln->pyro-Glu (N-term Q)"
<warning number="1">&apos;Gln-&gt;pyro-Glu (N-term Q)&apos; can only be used as a variable modification; setting …
> [FIX-#1740] MzTabExporter: modification "Phospho (ST)" throws error

- src/pyOpenMS/pxds/ConsensusMapNormalizerAlgorithmMedian.pxd
- src/pyOpenMS/pxds/ConsensusMapNormalizerAlgorithmThreshold.pxd
Should fix #1854.
PyopenMS did not build completely because of parsing errors. This lead to all the failing tests.
> [PYOPENMS][FIX] fixes parsing error for pyopenms

- src/openms/source/ANALYSIS/ID/AScore.cpp
Bug correction: if first and second peptide score are equal, set main score to 0 instead of leaving it at -1.
modified:   ../src/openms/source/ANALYSIS/ID/AScore.cpp
> [FIX] PhosphoScoring

- src/topp/LuciphorAdapter.cpp
Removed parameter 'selection_method' and set it automatically depending on the previous tool. if the selection method cannot be set an exception will be thrown.
modified:   ../src/topp/LuciphorAdapter.cpp
> [FEATURE] LuciphorAdapter

- src/openms/include/OpenMS/FORMAT/Base64.h
- src/openms/source/FORMAT/HANDLERS/MzMLSpectrumDecoder.cpp
- src/tests/class_tests/openms/source/Base64_test.cpp
- src/tests/class_tests/openms/source/MzMLSpectrumDecoder_test.cpp
- catch case of empty <binary> element
- ensure we have valid mzML with exactly one element inside <binary>
- ensure that <binary> is present
- add tests
> [FIX] fix XML parsing in MzMLSpectrumDecoder

- src/tests/topp/CMakeLists.txt
- ensure that temporary files do not overlap and are unique for each
test executed
- rebased from #1909 against master
> [FIX] fix names of temporary files

- src/topp/ConsensusID.cpp
minor change in #1932 (making one iterator non-const)
Resolves #1914. All tests pass.
> iterator change in ConsensusID

- tools/make_source_package.sh
Switched to git. Introduced a small CLI and the option to give precloned source folders. Made it compatible for Mac and Lnx.
Structure of the tar was kept.
> [BUILD] Update make_source_package_script.sh to Git and with small CLI.

- src/openms_gui/include/OpenMS/VISUAL/SpectraViewWidget.h
- src/openms_gui/include/OpenMS/VISUAL/Spectrum1DCanvas.h
- src/openms_gui/source/VISUAL/APPLICATIONS/MISC/QApplicationTOPP.cpp
- src/openms_gui/source/VISUAL/SpectraViewWidget.cpp
- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
- enable searching of subitems in ScanView (useful for e.g. searching for a precursor mass)
- make names of columns match the filter names
- spectrum is shown upon pressing `Enter` (see "What's This" help text)
(minor) - peak annotations are now colored in the layer color. Labels are still black, giving the user a free choice of color.
> [FEAT] TOPPView: search ScanView

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.h
- src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.cpp
- src/tests/topp/MapAlignerIdentification_parameters.ini
Fixes #1939 by removing the "peptide_score_threshold" algorithm parameter.
> [PARAM, FIX] MapAlignerIdentification peptide filtering (PEP scores) issue

- src/topp/PeptideIndexer.cpp
A message like this would get printed whenever PeptideIndexer was run (introduced with #1833):
```
Unknown (or deprecated) Parameter 'in' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'fasta' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'out' given in old parameter file! Ignoring ...
Overriding Default-Parameter 'decoy_string' with new value 'XXX_'!
Overriding Default-Parameter 'prefix' with new value 'true'!
Overriding Default-Parameter 'missing_decoy_action' with new value 'warn'!
Overriding Default-Parameter 'allow_unmatched' with new value 'true'!
Overriding Default-Parameter 'IL_equivalent' with new value 'true'!
Unknown (or deprecated) Parameter 'threads' given in old parameter file! Ignoring ...
Unknown (or deprecated) …
```
> [LOG] PeptideIndexer: suppress uninformative param update message

- src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
- src/tests/topp/degenerate_cases/empty.idXML
- src/topp/IDMerger.cpp
- src/topp/PeptideIndexer.cpp
This PR addresses two problems that can occur in pipelines that generate empty idXMLs (using IDFilter):
1. PeptideIndexer drops meta data of the ID run (e.g. search engine, date/time) when used on an idXML without peptide IDs.
2. IDMerger gets stuck on idXMLs with invalid search times ("0000-00-00T00:00:00"), like the empty ones produced by PeptideIndexer.
> Fixes for problems with empty idXML files

- src/openms/source/CHEMISTRY/TheoreticalSpectrumGenerator.cpp
- src/tests/class_tests/openms/source/TheoreticalSpectrumGenerator_test.cpp
Fixed an error in m/z value calculation in the TheoreticalSpectrumGenerator.
The mass was divided by the charge two times in some cases.
Once on initializing the monoisotopic mass and again for each isotopic peak.
> [FIX] Fixed an error in m/z value calculation

- src/openms/source/FORMAT/MascotGenericFile.cpp
- src/openms/source/FORMAT/MascotRemoteQuery.cpp
- src/tests/class_tests/openms/source/MascotGenericFile_test.cpp
- src/topp/MSGFPlusAdapter.cpp
1. When writing MGF (e.g. submitting data to Mascot), use fixed numbers of digits after the decimal point (3 for RT and intensity values, 5 for m/z), rather than a fixed (minimal) number of total digits. This keeps the RT precision adequate even for very long gradients (> 10,000 s) and fixes #1961.
2. Add a Mascot export parameter ("_ignoreionsscorebelow=0") to the defaults in OpenMS. Without this, some PSMs may be filtered out from the Mascot results in the export step.
> [FIX] Improvements for running Mascot searches (MascotAdapterOnline)

- src/openms/include/OpenMS/FILTERING/ID/IDFilter.h
- src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithm.cpp
- src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithmIdentity.cpp
- src/openms/source/FILTERING/ID/IDFilter.cpp
- src/tests/class_tests/openms/source/ConsensusIDAlgorithmBest_test.cpp
- src/tests/class_tests/openms/source/IDFilter_test.cpp
- src/topp/ConsensusID.cpp
Two fixes:
- remove duplicate peptide hits, if there are any (extended IDFilter for this purpose)
- added a special case for calculating agreement between searches ("support") with only one successful search
> [FIX-#2020] ConsensusID: fix problems causing "nan"/"inf" support values

- share/OpenMS/SCRIPTS/mzTab2tsv_PEP.R
- share/OpenMS/SCRIPTS/mzTab2tsv_PRT.R
- share/OpenMS/SCRIPTS/mzTab2tsv_PSM.R
This pull request combines two minor changes to the R scripts that convert `mzTab` output to better readable text files.
(1) The functionality is wrapped in functions `readMzTabPSM`, `readMzTabPEP` and `readMzTabPRT`. 
(2) The `PSM` script collapses each PSM to a single row. (In `mzTab` PSMs are reported in multiple lines, one for each protein accession.)
> refactor R scripts for mzTab postprocessing

- src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
- src/openms/source/FORMAT/IndexedMzMLFile.cpp
may fix the MSVS compile error
see the current compilation errors:
http://cdash.openms.de/viewBuildError.php?buildid=183885
```Error 	
3>/.../OpenMS/src/openms/source/FORMAT/IndexedMzMLFile.cpp(50): error C2666: 'std::fpos<_Statetype>::operator ==' : 3 overloads have similar conversions
3>          with
3>          [
3>              _Statetype=_Mbstatet
3>          ]
3>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\iosfwd(102): could be 'bool std::fpos<_Statetype>::operator ==(std::streamoff) const'
3>          with
3>          [
3>              _Statetype=_Mbstatet
3>          ]
3>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\iosfwd(97): or       'bool std::fpos<_Statetype>::operator ==(const std::fpos<_Statetype> &) const'
Repository …
```
> [FIX] fix for compile error

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp
This change adds a small margin to the grid on which the filtering results are clustered.
Due to minute rounding errors, data points might fall outside the expected range of the grid. The margin prevents that. Resolves #2027.
> small margin for the clustering grid

- src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DItem.h
- src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DItem.cpp
- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
in 1D View to *edit* them  (instead of right-click context menu + "edit")
> [FEATURE] TOPPView: allow double clicking of AnnotationItems 

- share/OpenMS/SCRIPTS/InternalCalibration_Residuals.R
- src/openms/include/OpenMS/ANALYSIS/ID/AccurateMassSearchEngine.h
- src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
- src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
- src/openms/source/APPLICATIONS/TOPPBase.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
- src/tests/class_tests/openms/data/AccurateMassSearchEngine_output1.featureXML
- src/tests/class_tests/openms/source/AccurateMassSearchEngine_test.cpp
- src/utils/AccurateMassSearch.cpp
- allow to parse more than one DB during AccurateMassSearch
other minor fixes:
- avoid Exception (e.g. in TOPPViewIdentification) for unidentified AMS peak
- allow empty lines in Adduct.tsv file for AMS
> mutliple DB for AMS

- src/openms/source/FORMAT/PepXMLFile.cpp
- src/tests/class_tests/openms/data/PepXMLFile_test_out.pepxml
- src/tests/class_tests/openms/data/PepXMLFile_test_out_1.pepxml
- src/tests/class_tests/openms/data/PepXMLFile_test_out_mzML.pepxml
- src/tests/class_tests/openms/source/PepXMLFile_test.cpp
* Read spectrum scan_number from the spectrum metavalues instead of setting scan_number = scan_index + 1
> [FIX] PepXMLFile - scan number

- src/openms/include/OpenMS/DATASTRUCTURES/ListUtils.h
- src/openms_gui/include/OpenMS/VISUAL/TOPPASScene.h
- src/openms_gui/include/OpenMS/VISUAL/TOPPASToolVertex.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/TOPPASScene.cpp
- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASVertex.cpp
[FIX] TOPPAS: name temporary files with correct suffix if possible (when TOPPAS stops, the intermediate files will have a correct suffix); better error checking; better name choice for output files (source edge)
[FIX] TOPPAS: when copy&pasting nodes, insert new nodes next to existing ones & select the new nodes (to readily move them)
[FEATURE] TOPPAS: remember last main Window position for next start			
[FIX] TOPPView: omit modal & blocking Messagebox which warns for values <=0 (delays showing data, especially on large sets); instead show message in the status bar.
[FEATURE] TOPPView: remember last main Window position for next start
> Fixes/Features for TOPPAS/TOPPView

- src/openms/include/OpenMS/FILTERING/DATAREDUCTION/MassTraceDetection.h
- src/openms/source/FILTERING/DATAREDUCTION/ElutionPeakDetection.cpp
- src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
- src/openms/source/FILTERING/DATAREDUCTION/MassTraceDetection.cpp
- src/tests/topp/FeatureFinderMetabo.ini
- src/tests/topp/MassTraceExtractor.ini
- src/tests/topp/MassTraceExtractor_1_output.featureXML
- src/tests/topp/MassTraceExtractor_2_output.featureXML
- src/topp/MassTraceExtractor.cpp
[FIX] move quantification parameter from FF-Metabo into MTD (where it belongs)
As a side effect, TOPP-MTD also gets the option to quantify via either AREA (default) or MEDIAN (for direct injection)
Quantification values of TOPP_MTD are now consistent with TOPP_FF-Metabo (since both use trace.getIntensity() now).
New intensities are a little bit smaller, since getIntensity() uses the area under the FWHM, whereas the old method integrated the whole peak area (less robust).
> [FIX] move quantification parameter from FF-Metabo into MTD

- tools/build.bat
Extend capabilities of build.bat (make equivalent for VS solutions for command line)
Can build ALL targets now (without specifying a sub-sln file, eg. just TOPP)
> [FEATURE] extend capabilities of build.bat

- src/openms_gui/source/VISUAL/SpectrumCanvas.cpp
I still don't understand why the bug happened, but this fixes it and makes the code a bit clearer.
> [FIX-#837] Fix TOPPView crash on mouse-wheel zoom

- tools/checker.php
Re'source'
may fix:
````
Test output
Outdated source file 'src/openms_gui/source/VISUAL/TOPPASResource.cpp' (no header -> /group/ag_abi/OpenMS/nightly-builds/HEAD/src/openms_gui/include/OpenMS/VISUAL/TOPPASRe**include**/OpenMS.h)                
```
CDASH errors
> [FIX, TEST] fix checker script for files that contain 'source' as in

- src/topp/MapStatistics.cpp
removed possibility to provide '-' as output file parameter
> [FIX] parameter conformity of MapStatistics

- src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLowess.cpp
By the way, the documentation of the "delta" parameter doesn't say what effect the parameter actually has. Any suggestions to improve this (@hroest)?
> [DOC] TransformationModelLowess: fixed spelling mistake in parameter documentation

- src/pyOpenMS/CMakeLists.txt
we should include this hint as pyOpenMS does not seem to compile any more with lower Cython versions -- even better would be to have a strong check in cmake
> [BUILD] cython version

- src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp
- src/tests/class_tests/openms/source/QTClusterFinder_test.cpp
- src/tests/topp/FeatureLinkerUnlabeledQT_2_parameters.ini
- src/tests/topp/FeatureLinkerUnlabeledQT_3_parameters.ini
I have run a couple of benchmarks that showed rather consistently that 100 is a good number of partitions. In most cases, 100 was faster than 20 or 9999 partitions. In general, values of 100+ seem to be good and result in similar runtimes. The performance of FLQT if only 1 partition is used (the current default) is extremely poor for larger datasets. Thus I would strongly suggest to change the default of this parameter. For a number of small and large datasets, I have verified that the number of partitions does not have an impact on the results (anymore, since https://github.com/OpenMS/OpenMS/pull/2207).
> [PARAM] set default for FLQT nr_partitions to 100

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.h
- src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.cpp
Inspired by #2201, this logs the number of potential data points (peptides) that were removed as outliers during the alignment. Might help to avoid some confusion.
(I also simplified parts of the code for inserting elements at the end of maps. Interestingly, the semantics for insertion hints changed between C++98 and C++11: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1780.html
I switched to the saner C++11 version.)
> [LOG] more logging output for MapAlignerIdentification

- src/openms_gui/source/VISUAL/Spectrum3DOpenGLCanvas.cpp
In "normal" intensity mode (IM_NONE), the intensity axis shows "inf" values and a bogus exponent if negative intensities are present in the dataset (as is the case, e.g., in the TOPPView example `LCMS-centroided.mzML`). This fixes it.
> [FIX] "normal" mode for intensity axis in 3D view

- src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DCaret.h
- src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DCaret.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
draw the connecting line of identifications using the color of the layer instead of black -- makes it much easier to discern multiple layers
> [FEAT] TOPPView: identical color for connecting lines

- src/openms/include/OpenMS/APPLICATIONS/MapAlignerBase.h
> [FIX] MapAlignerIdentification: allow 'lowess' as 'model:type'

- doc/doxygen/public/PyOpenMS.doxygen
> Removed outdated pyOpenMS install instructions. Linked to PyPI only.

- doc/OpenMS_tutorial/refman_overwrite.tex.in
- doc/TOPP_tutorial/refman_overwrite.tex.in
Only newer versions of the newly introduced newtxtext package include the textcomp package but load it with options. I looked up the options and activated the include. If the package is loaded previously with the same options, Latex will skip it.
> [DOC] Made changes to package loading in tutorials backwards compatible

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
Allow TOPPView to read mzIdentML files and use them for annotation and for a new layer
> [FEATURE] support mzIdentML in TOPPView

- .travis.yml
due to repeated timeouts and other issues with the OSX build, remove it
for now
I dont think there is much sense in having failed tests all the time. It makes more sense to have Windows and OSX in the nightly tests but I prefer to have quick Linux-only travis but at least they tell me when something is really broken instead of having false positive build failures all the time due to OSX timeouts
> [BUILD] remove OSX from continous testing

- src/openms/include/OpenMS/FILTERING/CALIBRATION/InternalCalibration.h
- src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp
- src/tests/class_tests/openms/source/InternalCalibration_test.cpp
- src/topp/InternalCalibration.cpp
This PR fixes the overlooked correction of precursor m/z for spectra which are not explicitly targeted,
e.g. if -ms_level == 1, then MS2 precursor information now gets calibrated according to the model applied to MS1. MS2 m/z itself is not changed (unless -ms_level 1 2).
> [FIX] InternalCalibration: calibrate m/z of precursor peaks as well

- src/utils/OpenMSInfo.cpp
Calling `OpenMSInfo[.exe]` now gives:
>  Build information:
>  = = = = = = = = = = =
>  Source path  : M:/dev/oms2/src/openms
>  Binary path  : M:/dev/oms2_build/src/openms
>  **Binary arch  : 64 bit**                   <-- new line
(or 32bit, on 32bit binaries). This is independent of OS! (insofar as 64bit binary cannot run on 32bit OS).
> [FEATURE/DOC] teach OpenMSInfo to tell its own architecture (32bit or 64bit)

- src/openms/source/CHEMISTRY/ModificationsDB.cpp
- src/openms/source/FORMAT/PepXMLFile.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/IDFileConverter_16_input.pepXML
- src/tests/topp/IDFileConverter_16_output.idXML
Note to reviewers: The part that was deleted in PepXMLFile.cpp (`if (!desc.empty()) ...`) is repeated later (https://github.com/OpenMS/OpenMS/compare/develop...hendrikweisser:fix-pepxml-mods?expand=1#diff-0ce89f78310b558a3cb2058c1337de32L1269). It was redundant after I fixed the `desc = ...` line.
> [FIX] fixes for parsing modification information in pepXML files

- src/openms/include/OpenMS/ANALYSIS/XLMS/OpenXQuestScores.h
- src/openms/source/ANALYSIS/XLMS/OpenXQuestScores.cpp
- src/utils/PPXL.cpp
- src/utils/xQuest.cpp
Reduced memory demand for the enumeration of cross-linked peptides
by using a different structure to store them and by filtering
them using the precursor masses from the spectra.
Now uses less than 10 percent than previously for most cases,
but depends on precursors of MS2 spectra.
> [feature/ppxlink] Reduced memory demand of peptide pairs

- src/pyOpenMS/tests/unittests/test000.py
fix an error in the pyOpenMS tests
basically, nose imports everything once and then runs all the tests. This, however, has severe problems when we change a global variable. In essence, what happened was that we (for testing) deleted the whole, global, enzyme database and when we later wanted to access it when loading pepXML, there were no more Enzymes :-) 
- reported, among others, in #2246 
possible solutions
- do not run nose tests any more
- do not delete enzyme db any more
> [TEST] fix pyopenms test

- src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
might be a fix for #2328  and extended #2134 with the drawback, that further processing might turn sour when some exotic ontology is used as unit reference, which I'd deem unlikely, but still, possible.
> [FIX] fix #2328 by handling unit attributes in mzid with a little slack

- src/topp/FeatureFinderMultiplex.cpp
`FeatureFinderMultiplex` allows profile and centroided data as input. This pull request adds a hidden (advanced) switch `spectrum_type`. By default, it is set to `automatic` and the spectrum type is determined from the input `mzML`. Alternatively, it can also be set explicitly to `centroid` or `profile`.
> optional profile/centroid switch added to FeatureFinderMultiplex

- src/tests/class_tests/openms/source/EmpiricalFormula_test.cpp
The return type of estimateFromWeightAndComp was changed from Int to bool, but I forgot to update the test definition to reflect that.
> [FIX] Fixed return type in test function to match actual function

- src/openms/include/OpenMS/KERNEL/MSSpectrum.h
The MSSpectrum function sortByPosition only sorted DataArrays,
if a FloatDataArray is present and did not check for StringDataArrays
or IntegerDataArrays.
> DataArrays in MSSpectrum are now always sorted

- src/utils/RNPxlSearch.cpp
written out.
This fixes XL annotations in TOPPView
> [FIX] if no peak was aligned the meta data for peak annotations was not

- cmake/compiler_flags.cmake
Using CMAKE_CXX_COMPILER_VERSION, available since CMAKE 2.8.10.
Addresses https://github.com/OpenMS/OpenMS/issues/2372.
> [Fix] Since Gcc7 dumpversion might not have a minor version

- cmake/add_library_macros.cmake
[FIX] remove policy warning when using get_target_property [deprecated function]
lets hope the old cmake 2.8.x can cope...
> Remove Warnings for CMake 3.7.2

- src/openms/include/OpenMS/CONCEPT/Exception.h
- src/openms/source/CONCEPT/Exception.cpp
- src/openms_gui/include/OpenMS/VISUAL/TOPPASScene.h
- src/openms_gui/include/OpenMS/VISUAL/TOPPASToolVertex.h
- src/openms_gui/include/OpenMS/VISUAL/TOPPASVertex.h
- src/openms_gui/source/VISUAL/TOPPASInputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASMergerVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASScene.cpp
- src/openms_gui/source/VISUAL/TOPPASSplitterVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
- src/openms_gui/source/VISUAL/TOPPASVertex.cpp
Some GUI elements were not disabled in non-GUI mode (i.e. when running a Pipeline with ExecutePipeline).
The console would only show:
`"QWidget: Cannot create a QWidget when no GUI is being used"` and quit without showing the actual error.
This PR fixes it (see #954).
Additionally, filenames longer than 255 chars were truncated (with a warning, but still), which could lead to silently overwriting output files. This PR will throw an error message, asking the user to use less sub-directories or shorter input basenames (both will decrease the total filename length).
> fix TOPPAS & ExecutePipeline errors

- src/openms/include/OpenMS/SIMULATION/MSSim.h
- src/openms/source/SIMULATION/MSSim.cpp
- src/utils/MSSimulator.cpp
This fixes two minor flaws in MSSimulator:
- When RawTandemSignal is disabled (the default setting), the idXML file generated for the -out_id parameter is always empty. This is because identifications are generated for each MS2 spectrum (so not at all if no MS2 spectra are present). This PR makes MSSimulator generate an idXML containing all protein identifications and one peptide identification per feature (precursor at feature centroid position) if RawTandemSignal is disabled. This is useful if you want to, e.g., benchmark label-free workflows on simulated data and you want to be able to map peptide identifications to your quantification results but don't care for simulated MS2 spectra.
- The features' peptide annotations are missing the precursor m/z. Noticed this because I wanted to …
> Minor fixes for MSSimulator ID handling

- doc/doxygen/install/install-linux.doxygen
The installation guide for Linux had a few instructions missing. The document is updated to add the missing steps.
> [DOC] Updated the installation guide for linux

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp
The clustering grid allows for data points that lie on its border. Due to rounding errors, it is necessary to define a small margin around the clustering grid.
Previously, this margin was an absolute (magic) constant. In this pull request, this constant is replaced by a machine-epsilon-dependent margin.
@jpfeuffer Thanks for this good idea.
> replace absolute by machine-epsilon-dependent margin in MultiplexClustering

- src/openms/CMakeLists.txt
- src/openms/cmake_findExternalLibs.cmake
makes building against a static Crawdad the default (no new dependency on dynamic lib)
> [BUILD] linking against static crawdad

- src/topp/LuciphorAdapter.cpp
Fix for issue #2381
Prints warning and converts mz and intensity precision to 64-bit float if necessary.
> [FIX] LuciphorAdapter - precision warning and conversion 

- src/openms/include/OpenMS/FILTERING/ID/IDFilter.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/MzDataHandler.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandler.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/MzXMLHandler.h
- src/openms/include/OpenMS/KERNEL/MSExperiment.h
- src/openms/source/ANALYSIS/TARGETED/OfflinePrecursorIonSelection.cpp
- src/openms/source/FORMAT/HANDLERS/MzDataHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp
typedef typename caused error in VS 11 2012 when not part of template.
We'll need to check whether the fixed files work under linux
> fix msexperiment windows

- .gitignore
macOS generates `*.DS_Store` in any folder opened by Finder [1]. In future, these files will be ignored by `git`.  
[1] https://en.wikipedia.org/wiki/.DS_Store
> [INTERNAL] ignore macOS *.DS_Store files

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/ChromatogramExtractor.h
- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/ChromatogramExtractorAlgorithm.h
- src/openms/source/ANALYSIS/OPENSWATH/ChromatogramExtractor.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/FeatureFinderIdentification_1_output.featureXML
- src/tests/topp/FeatureFinderIdentification_2_output.featureXML
- src/tests/topp/FeatureFinderIdentification_3_output.featureXML
- src/topp/FeatureFinderIdentification.cpp
Following discussion here: https://github.com/OpenMS/OpenMS/pull/2387#issuecomment-286886978
This pull request refactors FeatureFinderIdentification to extract chromatograms (and then detect/score chromatographic peaks) for all peptides together, rather than one by one. This can save several hours of runtime.
The results should be the same as before (except for ordering).
There's a small addition to `ChromatogramExtractor::prepare_coordinates` for convenient use of varying RT start/end points.
> FeatureFinderIdentification runtime optimization

- src/openms/source/KERNEL/MRMTransitionGroup.cpp
may fix the windows build
we still have some issues with the windows build: http://cdash.openms.de/viewBuildError.php?buildid=217346
```
OpenSwathMRMFeatureAccessOpenMS_test.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall OpenMS::TransitionGroupOpenMS<class OpenMS::MSChromatogram<class OpenMS::ChromatogramPeak>,class OpenMS::ReactionMonitoringTransition>::TransitionGroupOpenMS<class OpenMS::MSChromatogram<class OpenMS::ChromatogramPeak>,class OpenMS::ReactionMonitoringTransition>(class OpenMS::MRMTransitionGroup<class OpenMS::MSChromatogram<class OpenMS::ChromatogramPeak>,class OpenMS::ReactionMonitoringTransition> &)" (__imp_??0?$TransitionGroupOpenMS@V?$MSChromatogram@VChromatogramPeak@OpenMS@@@OpenMS@@VReactionMonitoringTransition@2@@OpenMS@@QAE …
```
> [FIX] windows build fix

- share/OpenMS/CV/psi-ms.obo
- src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
- src/tests/topp/IDFileConverter_9_output.mzid
has quite a selection of goodies, including some that we need
```
+[Term]
+id: MS:1002746
+name: MS-Numpress linear prediction compression followed by zlib compression
```
this will allow us to write substantially smaller mzML files. We have to check whether this breaks things, maybe @mwalzer can comment. If any of the names of the CV terms has changed, we may get warnings in our tests ...
> [OBO] update to psi-ms 4.0.10

- src/openms/include/OpenMS/CHEMISTRY/ResidueModification.h
- src/openms/include/OpenMS/FORMAT/PercolatorOutfile.h
- src/openms/include/OpenMS/FORMAT/XTandemInfile.h
- src/openms/include/OpenMS/FORMAT/XTandemXMLFile.h
- src/openms/source/CHEMISTRY/ModificationDefinitionsSet.cpp
- src/openms/source/FORMAT/PercolatorOutfile.cpp
- src/openms/source/FORMAT/XTandemInfile.cpp
- src/openms/source/FORMAT/XTandemXMLFile.cpp
- src/tests/class_tests/openms/data/XTandemInfile_test_write.xml
- src/tests/class_tests/openms/source/XTandemInfile_test.cpp
- src/tests/class_tests/openms/source/XTandemXMLFile_test.cpp
- src/topp/IDFileConverter.cpp
- src/topp/XTandemAdapter.cpp
This addresses problems in XTandemAdapter and with the reading of Percolator result files (derived from X! Tandem searches).
In XTandemAdapter, support for X! Tandem's default N-terminal mods (pyro-Glus and acetylation), which are covered by special parameters, was improved. When reading results, these mods are now added to the search parameters when found. When running searches, they should now be handled correctly when set by the user (in particular, there's an annoying interaction with other variable N-terminal mods).
In the Percolator results, the problem was that N-terminal modifications got attributed to the first residue (the notation in the X! Tandem output is ambiguous). The information about where the mod belongs is essentially lost at that point, so it takes a lot of heuristics …
> Fixes for X! Tandem and Percolator (modification handling)

- src/openms/source/ANALYSIS/TARGETED/OfflinePrecursorIonSelection.cpp
- fixes error message (due to removal of template code)
- "error: using 'typename' outside of template
> [FIX] typename fix

- src/openms/source/FORMAT/HANDLERS/MzMLHandlerHelper.cpp
- when using pic (positive integer compression), proteowizard uses the
1000519 tag (32-bit integer)
- since the result of a ms-numpress decompression is always a 64 bit
floating point number, this seems to be the safest course of action at
the moment and makes converted files work in OpenMS
- amends 22fc1cf6ff17498c86f148e6cd66494a63bd9492
> [FIX] handles mzML files with integer data type

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMAssay.h
- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.h
- src/openms/include/OpenMS/CHEMISTRY/ResidueModification.h
- src/openms/source/ANALYSIS/OPENSWATH/DATAACCESS/DataAccessHelper.cpp
- src/openms/source/ANALYSIS/OPENSWATH/MRMAssay.cpp
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp
- src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp
- src/openms/source/ANALYSIS/TARGETED/TargetedExperimentHelper.cpp
- src/openms/source/CHEMISTRY/CrossLinksDB.cpp
- src/openms/source/CHEMISTRY/ModificationsDB.cpp
- src/openms/source/CHEMISTRY/ResidueModification.cpp
- src/openms/source/FORMAT/HANDLERS/UnimodXMLHandler.cpp
- src/openswathalgo/include/OpenMS/ANALYSIS/OPENSWATH/OPENSWATHALGO/DATAACCESS/TransitionExperiment.h
- src/pyOpenMS/addons/CrossLinksDB.pyx
- src/pyOpenMS/pxds/LightTargetedExperiment.pxd
- src/pyOpenMS/pxds/ResidueModification.pxd
- src/tests/class_tests/openms/source/AASequence_test.cpp
- src/tests/class_tests/openms/source/MRMDecoy_test.cpp
- src/tests/class_tests/openms/source/ResidueModification_test.cpp
- src/utils/OpenSwathWorkflow.cpp
- consistently use unimod identifier as integer and only convert to "UniMod:XX" when necessary
- some stuff that was forgotten in #2059 
- some code paths still relied on CV terms
> Use UniMod id as integer

- src/topp/MSGFPlusAdapter.cpp
Fix for the creation of modification files for MS-GF+ searches, which got broken by the changes in #2504.
> Fix for MS-GF+ (addendum to #2504)

- .travis.yml
- remove from travis builds as they tend to time out
- running the tests takes too long when using the AS
- honestly, I am getting tired of time-outs on travis and the main reason is that building OpenMS is now pretty fast (20 min) but running the tests with AS is pretty slow since it adds extra code that makes the runtime go up a lot
> [BUILD] remove address sanitizer

- src/openms/source/CHEMISTRY/AASequence.cpp
- src/tests/class_tests/openms/source/AASequence_test.cpp
- src/tests/class_tests/openms/source/ModificationsDB_test.cpp
remove some dead code
basically we could remove `getBestModificationByMonoMass` from the code base as we dont really use it and its clunky - we only use `getBestModificationByDiffMonoMass` by simply calculating the mass difference first
> [FEATURE] cleanup of unused code

- src/openms/include/OpenMS/CHEMISTRY/ModificationDefinition.h
- src/openms/include/OpenMS/CHEMISTRY/ModificationDefinitionsSet.h
- src/openms/include/OpenMS/FORMAT/PercolatorOutfile.h
- src/openms/source/CHEMISTRY/ModificationDefinition.cpp
- src/openms/source/CHEMISTRY/ModificationDefinitionsSet.cpp
- src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
- src/openms/source/FORMAT/PercolatorOutfile.cpp
- src/pyOpenMS/pxds/ModificationDefinition.pxd
- src/pyOpenMS/pxds/ModificationDefinitionsSet.pxd
- src/tests/class_tests/openms/source/ModificationDefinition_test.cpp
- src/tests/class_tests/openms/source/ModificationDefinitionsSet_test.cpp
- src/tests/topp/IDFileConverter_9_output.mzid
As discussed in #2528:
When writing mzIdentML, infer fixed/variable modifications used from search results (peptide IDs), if none are defined in the search parameters.
> Infer fixed/variable modification definitions from data when necessary

- src/openms/source/FORMAT/PepXMLFile.cpp
- src/tests/topp/IDFileConverter_17_output.pepXML
LuciPhorAdapter (LuXor) needs the Posterior Probability / Phosphoprophet Probability for scoring. 
The score was not written in the PepXMLFile. This commit should fix the issue.
> [FIX] Posterior Probability in PepXML for LuciphorAdapter

- CMakeLists.txt
- tools/build.bat
[FIX] remove subprocess with low prio from build.bat since it caused trouble:
- it does not allow to cancel the job on the console (it will keep running in the background)
- it might trick MSBuild.exe into assuming only single-core CPU, even if /maxcpucount is specified
fixed now by just not spawning a child process
[FEATURE] convenience feature for Windows builds (to enable similar behaviour as in 'make ...') for MSVS generators.
before (in root binary dir): `$ ..\openms\tools\build.bat ....`
now: `$ build.bat ..`
This goes along nicely with other commands like `ctest ...` in the same directory
> fixes to build.bat on Windows

- src/topp/LuciphorAdapter.cpp
Issue #2381 was fixed on the LuXor side [1].
Right now the updated version is available on damians webserver [2].
[1] https://github.com/dfermin/lucXor/issues/2
[2] http://dfermin.com/files/downloads/luciphorUpdate.zip
> [FIX] LuciPhorAdapter - Delete internal conversion to 64bit  

- src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGenerator.h
- src/openms/source/ANALYSIS/ID/AScore.cpp
- src/tests/class_tests/openms/source/CompNovoIdentificationCID_test.cpp
- src/tests/class_tests/openms/source/CompNovoIdentification_test.cpp
- src/tests/class_tests/openms/source/CompNovoIonScoringCID_test.cpp
- src/tests/class_tests/openms/source/CompNovoIonScoring_test.cpp
- src/tests/class_tests/openms/source/MRMFragmentSelection_test.cpp
- src/tests/class_tests/openms/source/TheoreticalSpectrumGenerator_test.cpp
- src/utils/IDMassAccuracy.cpp
as discussed in #2613 
Removed charge default values for getSpectrum() and set mincharge = 1 and maxcharge = 1 everywhere getSpectrum() was called without specifying the charge.
> TSG without charge defaults

- src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerIterative.h
Error:
```
PeakPickerIterative.h:337:44: error: non-constant-expression cannot be narrowed from type 'Size'
(aka 'unsigned long') to 'int' in initializer list [-Wc++11-narrowing]
PeakCandidate pc = { /*.index=*/ k, /*.intensity=*/ picked_spectrum[j].getIntensity(), -1, -1, -1, -1};
```
Commit should fix the issue.
> [FIX] Compiling Clang OSX 12.5

- src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp
- fixes error when reading old CSV files
- when peptide sequences did not match, the modification was placed at
the wrong residue
- allows override with flag
> [FIX] reading of old CSV/TraML files

- CMakeLists.txt
-- Compiler checks for conversion: OFF
CMake Error at CMakeLists.txt:278 (file):
file COPY cannot copy file "C:/dev/OpenMS/tools/build.bat" to
"C:/dev/OpenMS_build/build.bat/build.bat".
-- Boost version: 1.61.0
> [FIX] fix error with CMake 3.8.1

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.h
- simply create a warning if the meta value is not present (instead of
throwing an exception)
- minor fix that removes an exception and replaces it with a warning - would be nice if it goes into master
> [FIX] warning instead of Exception

- src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
- src/tests/class_tests/openms/data/MzIdentML_XLMS_unlabelled.mzid
fixed an error with terminal modifications, that appeared when a cross-link modification would be possible at both the peptide terminal and the side chain of the terminal residue
> Fix/mzid XL-MS mods

- src/openms/source/ANALYSIS/ID/AScore.cpp
the binomial coefficient can overflow the `double` type,
if the scored spectrum has too many peaks and matches.
Fixed it by catching the exception and setting the coefficient to the maximal possible `double`.
> [FIX] caught an overflow error in AScore

- src/tests/topp/CMakeLists.txt
fix issue with parallel tests
- maybe to master?
- also, why do we not check the output of the TOF calibration? seems it was removed in 152959be40705be6a0b2429d0241661ee5fe6161
> [FIX] fix parallel test issue

- src/openms/include/OpenMS/FORMAT/HANDLERS/XQuestResultXMLHandler.h
- src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp
- src/tests/topp/XFDR_test_out1.idXML
- src/tests/topp/XFDR_test_out1.mzid
- src/tests/topp/XFDR_test_out2.idXML
- src/tests/topp/XFDR_test_out2.mzid
- src/tests/topp/XFDR_test_out3.idXML
- src/tests/topp/XFDR_test_out3.mzid
- src/tests/topp/XFDR_test_out4.idXML
- src/tests/topp/XFDR_test_out4.mzid
- src/utils/XFDR.cpp
> [FIX] Rename parameter small to tiny in XQuestResultXMLHandler

- cmake/knime_package_support.cmake
Deprecated in newer CMake versions.
> [FIX] Remove use of the LOCATION target property

- src/pyOpenMS/CMakeLists.txt
- since we now actually require Cython >= 25.2 and autowrap, we check for this in the config to avoid surprises later on
> [BUILD] pyOpenMS requirements

- src/pyOpenMS/setup.py
- add compile + linker flags for C++11
- only tested on Linux so far
- uses slightly different compiler flags than on Linux (`-std=gnu++11` vs `-std=c++11`)
> [FIX] compile pyOpenMS with C++11

- src/utils/Digestor.cpp
Post-filtering by length led to out of memory problems for unspecific cleavage.
This small change filters after every digest of a protein.
> [FIX] reduced memory consumption

- src/openms_gui/include/OpenMS/VISUAL/Spectrum2DCanvas.h
- src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
- when clicking in TOPPView 2D view on a data point, it currently looks
for close by fragment ion spectra.
- However, the current definition of close by is not very useful and
often it comes up empty (e.g. no fragment ion scans are found).
- This commit changes this by looking further if no data are found close
by, first within +/- 5 RT scans and then within the whole visible
window (this assumes the user clicked on something interesting in the
data such as a feature).
> [FEATURE] extended search for MS2 scans

- src/tests/topp/FileInfo_10_output.txt
- src/topp/FileInfo.cpp
[FIX]: percentage of modified peptides for idXML input had too many digits (e.g. 45.434242342 %) --> now fixed to 1 digit, e.g 45.4 %
[FEATURE] TOPP-FileInfo: compute average length of peptides in idXML
> [FIX] TOPP-FileInfo

- src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h
see #2793 
Include required for boost 1.64 occurs before including the other boost header files.
Fixes build on Debian distro.
> [FIX] fix for boost 1.64

- src/openms_gui/include/OpenMS/VISUAL/LayerData.h
- src/openms_gui/source/VISUAL/LayerData.cpp
- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
PeakAnnotations in PeptideHits are updated on pressing the save IDs button or when changing the selected spectrum or ID.
Charges are now only contained in the charge field and should not be part
of the annotation string.
> [GUI, FIX] more robust PeakAnnotations in TOPPView

- src/openms/source/CONCEPT/ClassTest.cpp
I think it causes hiccups with CTest sometimes, thinking it is a compiler error.
> Removes unreachable code warning

- src/openms/include/OpenMS/KERNEL/MSSpectrum.h
- src/pyOpenMS/pxds/MSSpectrum.pxd
- src/tests/class_tests/openms/source/MSSpectrum_test.cpp
New getters for meta data arrays in MSSpectrum.
I am not sure, what to return when no array with the given name exists,
for now an empty DataArray of the respective type is returned.
> [Feature] get data array by name

- src/openms/include/OpenMS/SYSTEM/File.h
- src/openms/source/SYSTEM/File.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
- src/tests/class_tests/openms/source/File_test.cpp
[FIX] augment #2582 which introduced a long-filename problem, by adding a new suffix in every TOPPAS TOPP node resulting in chained suffices, e.g. mzml.idxml.tsv....
This commit removes old file extensions before adding new ones, thus keeping file length small.
Also shortens the path further by shorter unique names and not using the redundant ./toppas_tmp/ subdir anymore.
Successfully tested with all TOPPAS example pipelines and 'LabelFree_Fusion_20170802.toppas' from @lars20070.
> Fix long filename issue in TOPPAS

- src/openms/include/OpenMS/FORMAT/FASTAFile.h
- src/openms/include/OpenMS/FORMAT/IdXMLFile.h
- src/openms/include/OpenMS/SYSTEM/SysInfo.h
- src/openms/source/APPLICATIONS/TOPPBase.cpp
- src/openms/source/CONCEPT/ProgressLogger.cpp
- src/openms/source/FORMAT/FASTAFile.cpp
- src/openms/source/FORMAT/IdXMLFile.cpp
- src/openms/source/MATH/STATISTICS/CumulativeBinomial.cpp
- src/openms/source/SYSTEM/SysInfo.cpp
- src/topp/FileInfo.cpp
- src/topp/FileMerger.cpp
this PR introduces of some of new features which are required for the new Aho-Corasick PeptideIndexer.
Its a smaller, more digestable chunk, to make the review a bit easier. Another PR is coming up soon.
The changes introduced here are not dramatic:
[FEATURE] 10% faster writing of idXML 
[FEATURE] idXML can now report timings when loading/storing (via ProgressLogger)
[NOOP] minor formatting of Progresslogger output
[FEATURE] move semantics for FASTAEntries (potentially faster) when loading FASTA files
[FEATURE] TOPP tools report their peak memory usage when using -debug
> [FEATURE] faster idXML store; memory consumption report

- src/utils/SiriusAdapter.cpp
Sirius 3.5 parameter update - SiriusAdapter was failing.
> [FIX] Remove database parameter (SiriusAdapter)

- src/tests/topp/THIRDPARTY/third_party_tests.cmake
- src/utils/SiriusAdapter.cpp
Error was introduced by wrong Sirius version without FingerID.
The Version with FingerID uses the database parameter. 
This right version can be found in THIRDPARTY.
> [FIX] database parameter used by CSIFingerID

- share/OpenMS/SCRIPTS/mzTab2tsv_PRT.R
Fixes R script for `mzTab` post-processing of the `PRT` section.
> fix mzTab2tsv_PRT script

- src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotations1DContainer.h
- src/openms_gui/include/OpenMS/VISUAL/LayerData.h
- src/openms_gui/source/VISUAL/ANNOTATION/Annotations1DContainer.cpp
- src/openms_gui/source/VISUAL/LayerData.cpp
- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
A selection of peak annotations deleted from the TOPPView spectrum canvas
using the DEL key
will now also be removed from the peak annotations of
the current PeptideHit.
> [FEATURE] deleting selections of peak annotations in TOPPView

- src/pyOpenMS/pxds/RNPxlReport.pxd
- src/pyOpenMS/tests/unittests/test_StandardTypes.py
Comment out a line in test_StandardTypes.py that causes unittests of pyOpenMS to fail. 
Also, pyOpenMS does not export the name 'Chromatogram':
```
import pyopenms
dir(pyopenms) 
```
https://www.dropbox.com/s/ufdq1vlqtv44a88/pyopenms_exported_identifiers.txt?dl=0
> [FIX,TEST] Comment out pyopenms. Chromatogram test line in pyopenms unittest

- License.txt
- src/tests/topp/THIRDPARTY/third_party_tests.cmake
Adds License of SpectraST to License.txt
Edit: Add `contrib` references to `License.txt`.  Update broken URLs in this file.
> Release_2_3/thirdparty licenses

- src/openms/source/SYSTEM/SysInfo.cpp
Changes the c header `stdlib.h `in `SysInfo.cpp` to the c++ header `cstdlib`. This fixes the error that I encountered on ElCapitan that abs is not a member of the std namespace. Also, I think the cpp header  `cstdlib` is preferred over the `stdlib.h` c header.
https://stackoverflow.com/questions/2900785/whats-the-difference-between-cstdlib-and-stdlib-h
> [FIX] In SysInfo.cpp, change c header stdlib.h to cpp header cstdlib

- src/openms/source/FORMAT/DATAACCESS/CsiFingerIdMzTabWriter.cpp
- src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp
- src/tests/topp/THIRDPARTY/SiriusAdapter_1_output.mzTab
- src/tests/topp/THIRDPARTY/third_party_tests.cmake
- src/utils/SiriusAdapter.cpp
fix: 
Add number parameter (how many candidates should be written) > there was the issue that the number parameter was overwritten and then not set back to the original number. 
TOPP_Test
refactor:
-fingerid parameter is now used if -out_fingerid  (output folder) is set.
> [FIX, REFACTOR] SiriusAdapter 

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.h
- src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp
- src/utils/OpenSwathWorkflow.cpp
This PR extends the OpenSWATH OSW SQLite format by adding support to store multiple runs in the same database. The tables are linked via unique identifiers. Unique identifiers are internally of type OpenMS::UInt64, however, they are stored as TEXT in the database to prevent problems for the downstream tools, because SQLite does not support UInt64. If anybody has a better idea how to solve this issue, I would be happy to implement the suggestions.
> [FEATURE] Improved OpenSWATH SQLite export

- doc/doxygen/install/install-win.doxygen
The doc still said:
have a Visual Studio 2005/2008/2010[SP1]/2012/2013/2015 installed
while we do not support anything older than 2015 anymore
> [DOC] updated required Visual Studio version for building on windows

- src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
- src/tests/class_tests/openms/data/AccurateMassSearchEngine_output1.consensusXML
- src/tests/class_tests/openms/data/AccurateMassSearchEngine_output1.featureXML
- src/utils/AccurateMassSearch.cpp
AccurateMassSearch(Engine) used to write the relative m/z deviation (in ppm) between a feature and a compound into a meta value "ppm_mz_error". It now writes both relative (ppm) and absolute (Da) deviations into "mz_error_ppm" and "mz_error_Da", respectively.
> AccurateMassSearch: write out m/z deviation in Da

- src/openms_gui/source/VISUAL/LayerData.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
Multiple annotation per peak are now possible.
Adding and editing peaks works as intended.
> [FIX] TOPPView, simplified synchronizing of peak annotations (fixes #2956)

- .gitignore
- .gitmodules
Mostly to keep track of the used commits.
Also helps in simplifying the quick_build scripts (later).
Problem: Since partial clones are not possible, you always have to check out the full THIRDPARTY independent of the platform.
Solution: Make the platform dependent folders separate repositories and add them as submodules of THIRDPARTY.
Will merge this into develop, too, after evaluation.
> [FEATURE] Add contrib and THIRDPARTY as submodules.

- src/topp/MapAlignerPoseClustering.cpp
that way it is not necessary to change output file type in KNIME
> [FIX] change order in restriction to make featureXML the default output format

- doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp
- src/openms/include/OpenMS/ANALYSIS/ID/AScore.h
- src/openms/source/ANALYSIS/ID/AScore.cpp
- src/pyOpenMS/pxds/AScore.pxd
- src/pyOpenMS/tests/unittests/test000.py
- src/tests/class_tests/openms/source/AScore_test.cpp
- src/topp/PhosphoScoring.cpp
Apart from some coding style adaptations, the main change is to use DefaultParamHandler for general AScore parameters (rather than passing them in every function) and the addition of the new "unambiguous_score" (advanced) parameter.
> PhosphoScoring: improve default score for unambiguous cases (solves #2051)

- src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
- src/tests/topp/IDFileConverter_8_input.mzid
- src/tests/topp/IDFileConverter_8_output.idXML
Reading in string type score for PeptideShaker mzid output.
Should fix #2921
> Fix/shaker scores, fixes #2921

- src/openms/include/OpenMS/METADATA/PeptideIdentification.h
- src/openms/source/METADATA/PeptideIdentification.cpp
the fix has been active for a few years now. Not needed any longer.
> fix #793 (metavalue check for PeptideIdentification)

- src/tests/class_tests/openms/source/SVMWrapper_test.cpp
I don't know, why this only shows up on macOS and why only since some time but:
IMHO the test was designed wrongly. According to my short research, at a tie, LibSVM assigns the first encountered
label in the training data, which is a different one in the second test.
Let's see what other platforms say.
> [FIX] Fixed SVMWrapper_test

- src/tests/topp/THIRDPARTY/third_party_tests.cmake
Alternative would be to generate a special output file to compare to on Win.
This here is easier, we just have to remember to remove it.
> [TEST] Disable Percolator test until new release on Win

- src/openms_gui/include/OpenMS/VISUAL/TOPPViewIdentificationViewBehavior.h
- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
In TOPPView's "Identification View", peak annotations stored for peptide hits can be visualized (as an alternative to generating a theoretical spectrum). Previously only labels with the annotations were added to peaks in the measured spectrum. With this change, a second spectrum containing the peaks from the annotations as well as the labels is generated (analogous to a theoretical spectrum). This highlights the actual peaks that are annotated.
(It would be really nice if different peaks could be shown in different colours, but currently that's only possible for the labels.)
@enetz: Can you please check if this still works for showing the special annotations for cross-linked peptides?
> TOPPView: better support for peak annotations in "Identification View"

- src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h
- src/openms/include/OpenMS/FORMAT/FASTAFile.h
[FIX] fix PeptideIndexer crash (division by 0) if 0 peptides are mapped to the protein DB.
[FEATURE] parse protein sequences which contain modifications as AASequence (since otherwise hits in regions with modfied AA would not be found) and emit a warning to user to fix his Protein Database (fixes #2594)
> minor fixes to PeptideIndexer

- src/openms/include/OpenMS/KERNEL/MSChromatogram.h
- src/openms/include/OpenMS/KERNEL/MSSpectrum.h
- src/openms/source/KERNEL/MSChromatogram.cpp
- src/openms/source/KERNEL/MSSpectrum.cpp
- src/tests/class_tests/openms/source/MSChromatogram_test.cpp
- src/tests/class_tests/openms/source/MSSpectrum_test.cpp
@timosachsenberg 
As discussed, I implemented methods `PosBegin()` and `PosEnd()`.
These are basically aliases for `RTBegin()` and `RTEnd()` (in `MSChromatogram`) and for `MZBegin()` and `MZEnd()` (in `MSSpectrum`).
This way it should be easier to build algorithms that use range methods and support both container classes.
> [FEATURE] PosBegin() and PosEnd() for MSChromatogram and MSSpectrum

- src/openms/include/OpenMS/KERNEL/ChromatogramPeak.h
- src/pyOpenMS/pxds/ChromatogramPeak.pxd
- src/tests/class_tests/openms/source/ChromatogramPeak_test.cpp
Allows the user to instantiate a `ChromatogramPeak` by passing a position and an intensity as arguments, as in:
`ChromatogramPeak p(3.0, 5.0);`
> [FEATURE] Add ChromatogramPeak constructor with position and intensity args

- src/openms/include/OpenMS/CHEMISTRY/AASequence.h
- src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPReader.cpp
- src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp
- src/openms/source/CHEMISTRY/AASequence.cpp
- src/tests/class_tests/openms/source/AASequence_test.cpp
- src/tests/topp/ConvertTraMLToTSV_output.tsv
- src/tests/topp/TargetedFileConverter_1_output.TraML
- src/tests/topp/TargetedFileConverter_2_output.TraML
This PR addresses issue https://github.com/OpenMS/OpenMS/issues/3042 reported by @bretttully. TargetedFileConverter now always stores modifications in UniMod format in PQP files, which improves compatibility with TraML.
This is implemented by the new function AASequence::toUniModString(), which works analogously to AASequence::toString(), except that known modifications are reported in UniMod format rather than the internal nomenclature.
> [FIX] OpenSWATH: Store UniMod sequence in PQP files

- .gitignore
If the quickbuild script is used folders (contrib-build & openms-build) will be located in the OpenMS-folder.
> [Update] .gitignore

- src/openms/include/OpenMS/FORMAT/CsvFile.h
- src/openms/source/FORMAT/AbsoluteQuantitationMethodFile.cpp
- src/openms/source/FORMAT/CsvFile.cpp
- src/openms/source/FORMAT/MRMFeatureQCFile.cpp
- src/tests/class_tests/openms/source/CsvFile_test.cpp
This PR adds two methods to the CsvFile class.
`addRow()` adds a row to the `buffer_` inherited from _TextFile_. It takes into account the values of `itemenclosed_` and `itemseperator_`.
`clearBuffer()` simply calls `buffer_.clear()`.
> [FEATURE] CsvFile::addRow() and CsvFile::clearBuffer()

- tools/quickbuild.sh
$@ has to be removed or make is called with invalid parameters. 
e.g., make -j 20 20
> [FIX] update quickbuild

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMDecoy.h
- src/openms/source/ANALYSIS/OPENSWATH/MRMDecoy.cpp
- src/pyOpenMS/pxds/MRMDecoy.pxd
- src/tests/class_tests/openms/data/MRMDecoyGenerator_output.TraML
- src/tests/class_tests/openms/source/MRMDecoy_test.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/OpenSwathDecoyGenerator_input.TraML
- src/tests/topp/OpenSwathDecoyGenerator_input_3.TraML
- src/tests/topp/OpenSwathDecoyGenerator_output_2.TraML
- src/topp/OpenSwathDecoyGenerator.cpp
Over the past years, we have made several adjustments to ``OpenSwathDecoyGenerator`` to deal with more complex spectral libraries. One particular problem was non-canonical PTMs, particularly at the C-/N-term. We introduced several new parameters for the TOPP tool, which were used in combination to exclude some of the difficult peptides when they failed checks. Finding the right combination was sometimes frustrating for users.
This PR attempts to remove most of these parameters and to enable only sensible combinations. Further, some changes to the algorithm ensure that for the vast majority of applications, the default parameters work reliably out of the box, without the need for tweaking.
Further, ``OpenSwathDecoyGenerator`` now supports all other formats for spectral libraries as well. …
> [FEATURE] OpenSwathDecoyGenerator improvements 

- src/openms/include/OpenMS/FORMAT/Base64.h
removes some warning on modern compilers
> [FIX] removed deprecated register storage class

- src/tests/class_tests/openms/source/LogStream_test.cpp
Indeed this test gave random errors in around 1 in 5 executions with OpenMP on Win10 VS2015.
I don't know the exact reason and probably big parts of the class are not really threadsafe (as found by @timosachsenberg ) but changing the pragma to parallel for gets rid of the random errors (at least there were 0 in 500 executions).
See #2275
> [FIX?] LogStream_test parallel for

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.h
- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TransitionPQPFile.h
- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TransitionTSVFile.h
- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/sources.cmake
- src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPFile.cpp
- src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPReader.cpp
- src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp
- src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp
- src/openms/source/ANALYSIS/OPENSWATH/sources.cmake
- src/openswathalgo/include/OpenMS/ANALYSIS/OPENSWATH/OPENSWATHALGO/UTILS/sources.cmake
- src/pyOpenMS/pxds/TargetedSpectraExtractor.pxd
- src/pyOpenMS/pxds/TransitionPQPFile.pxd
- src/pyOpenMS/pxds/TransitionTSVFile.pxd
- src/pyOpenMS/tests/unittests/test000.py
- src/tests/class_tests/openms/executables.cmake
- src/tests/class_tests/openms/source/TargetedSpectraExtractor_test.cpp
- src/tests/class_tests/openms/source/TransitionPQPFile_test.cpp
- src/tests/class_tests/openms/source/TransitionTSVFile_test.cpp
- src/topp/OpenSwathAssayGenerator.cpp
- src/topp/OpenSwathDecoyGenerator.cpp
- src/utils/OpenSwathWorkflow.cpp
- src/utils/TargetedFileConverter.cpp
This PR improves the conversion from TSV or TraML to PQP. Instead of ~20min (PHL), this takes now <2min. To achieve this, the necessary PQP indexes during conversion are based on different data structures.
Additionally, the classes TransitionTSVReader and TransitionPQPReader are renamed to TransitionTSVFile and TransitionPQPFile according to the request of @timosachsenberg.
> [FEATURE] Improvements for PQP conversion / Renaming of classes

- share/OpenMS/SCRIPTS/mzTab2tsv_PEP.R
- share/OpenMS/SCRIPTS/mzTab2tsv_PRT.R
- share/OpenMS/SCRIPTS/mzTab2tsv_PSM.R
This PR combines three improvements for the `mzTab2tsv` scripts.
- all columns now have automatically the correct types
- `readMzTabPSM` is faster
- when splitting `accession` and `gene` columns, `NA` entries are now allowed
> improvements of mzTab2tsv scripts

- src/openms/include/OpenMS/METADATA/AbsoluteQuantitationStandards.h
- src/pyOpenMS/pxds/AbsoluteQuantitationStandards.pxd
Changed the names of run_id and component_/IS_id to match the names in the other AbsoluteQuantitation classes (i.e., _id to _name).  This should make things more clear for developers and users alike.
> [FIX] changed names in AbsoluteQuantitationStandards to match

- share/OpenMS/SCRIPTS/mzTab2tsv_PEP.R
- share/OpenMS/SCRIPTS/mzTab2tsv_PRT.R
- share/OpenMS/SCRIPTS/mzTab2tsv_PSM.R
By default, square brackets in column names are substituted by dots. For example
```
best_search_engine_score[1]      -->      best_search_engine_score.1.
```
This PR corrects this behaviour.
> [INTERNAL] correct column names in mzTab2tsv scripts

- cmake/compiler_flags.cmake
a small fix to reduce clang warnings, see  #757
> [BUILD] remove double promotion warnings

- src/pyOpenMS/create_cpp_extension.py
It does not match the current contrib builds.
This change should be backwards compatible.
> [Fix] pyOpenMS glob for boost lib name fixes too strict

- src/openms/include/OpenMS/ANALYSIS/QUANTITATION/AbsoluteQuantitationMethod.h
- src/openms/source/ANALYSIS/QUANTITATION/AbsoluteQuantitationMethod.cpp
- src/pyOpenMS/pxds/AbsoluteQuantitationMethod.pxd
- src/tests/class_tests/openms/source/AbsoluteQuantitationMethod_test.cpp
I'm working on a class named _AbsoluteQuantitationMethodFile_ and I found this bug.
For now I'm only correcting this line, since I guess it is high priority.
I will also add tests that would catch this kind of bugs once I'm done with my other classes.
> [FIX] AbsoluteQuantitationMethod::getLLOD() getter correctly returns llod_

- src/topp/FileInfo.cpp
I have no idea how that got past CR.
but it effectively doubles memory usage when reporting ranges. Rather ugly, especially for large files.
> [FIX] avoid 2x memory usage in FileInfo

- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
scene() will return nullptr, since the TOPPASToolVertex is not registered as an object the scene yet (we're still constructing it.
Fixes #3179.
> [FIX] #3179 

- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
Currently, when IDs with stored peak/fragment annotations are opened in TOPPView's identification view, MS2 spectra are shown zoomed out to the "maximal m/z data range" (of any MS2 spectrum?), although there may not be any peaks covering the full range. With this change, the spectra are initially zoomed in to the range where there are actually peaks.
> TOPPView: fix initial zoom in identification view (stored annotations)

- doc/doxygen/public/TOPP.doxygen
- doc/doxygen/public/UTILS.doxygen
- src/utils/NovorAdapter.cpp
- src/utils/SiriusAdapter.cpp
[UPDATE] UTILS.doxygen
[UPDATE] TOPP.doxygen
had to do some smaller fixes (documentation related) in 
[FIX] SiriusAdapter
[FIX] NovorAdapter
#3186 
Documentation is missing in 
UTILS_RNPxlSearch
UTILS_MetaProSip
UTILS_OpenMSInfo
UTILS_SimpleSearchEngine
> [UPDATE] UTILS/TOPP doxygen

- src/openms/source/ANALYSIS/MAPMATCHING/LabeledPairFinder.cpp
taking the max of unsigned zero and a value is always equal to the other value
> [NOP] remove compile warning GCC7

- src/pyOpenMS/pxds/BinnedSpectrum.pxd
pyOpenMS seems to have problems with deleted constructors
> [FIX] pyOpenMS deleted constructor

- src/openms/include/OpenMS/DATASTRUCTURES/StringUtils.h
- src/openms/include/OpenMS/FORMAT/Base64.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandlerHelper.h
- src/openms/source/ANALYSIS/XLMS/XQuestScores.cpp
- src/openms/source/FORMAT/Base64.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLHandlerHelper.cpp
- src/tests/class_tests/openms/source/String_test.cpp
- src/tests/class_tests/openms/source/SysInfo_test.cpp
[FEATURE] faster whitespace removal function (2x - 6x faster than before)
On string with no whitespaces (stringlen 3000, 1e5 iterations):
old: 4.46 s (wall), 4.46 s (CPU), 0.00 s (system), 4.46 s (user)
new: 2.68 s (wall), 2.68 s (CPU), 0.00 s (system), 2.68 s (user)
On string with whitespaces: (stringlen 3000, 1e5 iterations):
old: 25.03 s (wall), 25.02 s (CPU), 0.00 s (system), 25.02 s (user)
new: 3.37 s (wall), 3.37 s (CPU), 0.00 s (system), 3.37 s (user)
[FIX] some cleaning up in XML parsing code, e.g. Base64 uses static functions only, so we can remove instanciation
In total, mzML parsing (FileInfo -in ...) is about 6% faster (~60 vs 63 MB/sec) on my machine.
There is a lot more potential IMHO, but I take what I can get :)
> some performance optimizations (especially XML parsing)

- src/utils/MetaProSIP.cpp
Removes a special character from the docu for easier Galaxy deployment.
> removed special character from documentation

- src/tests/class_tests/openms/source/Bzip2InputStream_test.cpp
- src/tests/class_tests/openms/source/CompressedInputSource_test.cpp
- src/tests/class_tests/openms/source/GzipInputStream_test.cpp
- src/tests/topp/THIRDPARTY/CruxAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/third_party_tests.cmake
Don't know why this showed up only when linking to static Xerces. Or the newer version?
But I think this here is the correct way.
One could discuss of course where to correctly put the initialization. In the class?
This here solves it on win for me.
And oops. Since I tested this on the Crux test fix PR, it includes its commits, too.
> [Fix] xerces platform init win

- src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp
- src/openms/source/ANALYSIS/QUANTITATION/AbsoluteQuantitation.cpp
- src/tests/class_tests/openms/source/AbsoluteQuantitation_test.cpp
- src/tests/class_tests/openms/source/MRMFeatureFilter_test.cpp
_MRMFeatureFilter_ and _AbsoluteQuantitation_ methods to calculate the ratio between two components (i.e., subfeatures) is only supported for `metaValue`s. 
However, there should be an option to calculate the ratio by intensity.  The intensity (i.e., peak area) is given a dedicated attribute in the `Feature` class, and can only be accessed by `getIntensity()`.
This PR implements the functionality for intensity.
> [FIX] Quantify and calculate ion ration by intensity

- src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp
- src/openms/source/ANALYSIS/QUANTITATION/AbsoluteQuantitation.cpp
- src/tests/class_tests/openms/source/AbsoluteQuantitation_test.cpp
- src/tests/class_tests/openms/source/MRMFeatureFilter_test.cpp
- added additional conditionals to calculateRatio and calculateIonRatio methods
- added tests to test for the case of feature_name = intensity and no IS
> calculateRatio fails when feature_name = intensity and there is no IS

- src/openms_gui/include/OpenMS/VISUAL/LayerData.h
- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
Extension of #3007 by @hendrikweisser .
A new vector for peak colors has been added to LayerData.
Peaks are colored by the colors stored in there, if its length equals the length of the spectrum.
Currently it is filled by label content, in the same way the colors for the labels were determined.
In the future we can also use information in DataArrays or other sources to set colors for different kinds of data.
Screenshot (for Cross-Linking MS data):
> [FEATURE] TOPPView: peaks colored by label content

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFilter.h
- src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp
- src/tests/class_tests/openms/source/MRMFeatureFilter_test.cpp
Metavalues `"QC_transition_score"` and `"QC_transition_group_score"` are added to features and sub-features.
The score is simply:
_(number of QC tests passing) / (number of QC tests)_
A small change was applied to `checkMetaValue()`, which now also informs the caller whether the metavalue actually exists (necessary for counting the number of tests involved).
> [FEATURE] MRMFeatureFilter: Add score to component and component groups

- src/openms/include/OpenMS/ANALYSIS/QUANTITATION/AbsoluteQuantitation.h
- src/openms/source/ANALYSIS/QUANTITATION/AbsoluteQuantitation.cpp
- src/pyOpenMS/pxds/AbsoluteQuantitation.pxd
- src/tests/class_tests/openms/source/AbsoluteQuantitation_test.cpp
It not straight forward to determine based on the output of Absolute Quantitation if an optimal calibration curve was found.
- Added a boolean output to `OptimizeCalibrationCurvesIterative` to indicate if an optimal fit was found or not
- Set the `n_points` and `correlation_coefficient` to default values of 0 if an optimal fit was not found to clearly indicate that an optimal was not found
- Updated the transformation model params only if an optimal fit was found.  Otherwise, the user provided params (if any) are returned)
> Easy indication if Absolute Quantitation found an optimal calibration or not

- src/openms/include/OpenMS/SYSTEM/File.h
- src/openms/source/SYSTEM/File.cpp
- src/tests/topp/FileInfo_17_output.txt
- src/topp/CometAdapter.cpp
- src/topp/FileInfo.cpp
- src/topp/MSGFPlusAdapter.cpp
- src/topp/MascotAdapterOnline.cpp
- src/topp/XTandemAdapter.cpp
[FIX] FileInfo's FASTA summary uses hashes to detect duplicates (old: quadratic runtime; new linear at the cost of 10% more memory; reporting of duplicate and AAA stats)
[FIX] minor changes to CometAdapter: remove excess includes; check for comet.exe before expensive mzML loading;
[FEATURE] add support for file rename in File.cpp (avoids inclusion of QDir in tools)
> FileInfo and Comet optimizations

- src/topp/MSGFPlusAdapter.cpp
Change of protocol `none` to `automatic` as used in MS-GF+ API.
> rename param in MSGFPlus adapter conforming with MS-GF+ API

- src/openms/source/ANALYSIS/OPENSWATH/PeakIntegrator.cpp
- src/tests/class_tests/openms/source/PeakIntegrator_test.cpp
The same formula was used for both `base_to_base` and `vertical_division` cases of the parameter `baseline_type`.
Now the following is used instead:
`height = std::min(int_r, int_l) + delta_int_apex;`
or
`height = std::min(int_r, int_l);`
> [FIX] PeakIntegrator::estimateBackground() correct formula for vertical division height

- src/openms/include/OpenMS/ANALYSIS/ID/IDConflictResolverAlgorithm.h
- src/openms/include/OpenMS/ANALYSIS/ID/sources.cmake
- src/openms/source/ANALYSIS/ID/IDConflictResolverAlgorithm.cpp
- src/openms/source/ANALYSIS/ID/sources.cmake
- src/tests/topp/IDConflictResolver_1_output.featureXML
- src/tests/topp/IDConflictResolver_2_output.consensusXML
- src/tests/topp/IDConflictResolver_3_output.consensusXML
- src/topp/IDConflictResolver.cpp
Aim of this PR:
- move tool code to algorithm
- keep conflicting IDs but move all but the best to "unmapped" 
- annotate feature identifier as meta value ("feature_id"="17962861576887891871")
> [FEATURE] move IDConflict resolver to algorithm, keep conflicting (make unmapped)

- src/pyOpenMS/CMakeLists.txt
- tools/travis/lnx-cibuild.before.sh
seems like Cython 0.28 creates trouble:
the error logs are full of warnings instead of errors:
```
warning: /.../OpenMS/src/pyOpenMS/pxds/ControlledVocabulary.pxd:80:8: 'NONE' redeclared
```
this is potentially because the warnings are reported to stderr instead of stdout ?
> [FIX] fix Cython

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/PeakIntegrator.h
- src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp
- src/openms/source/ANALYSIS/OPENSWATH/PeakIntegrator.cpp
- src/tests/class_tests/openms/source/MRMTransitionGroupPicker_test.cpp
- src/tests/class_tests/openms/source/PeakIntegrator_test.cpp
Added a further method for background subtraction, based on what Skyline and EncyclopeDIA is apparently doing. See for example: https://www.biorxiv.org/content/early/2018/03/07/277822
```
We calculate trapezoidal
peak areas across Savitsky-Golay smoothed chromatograms. Analogous to Skyline,
peak intensities are background subtracted by removing a peak area rectangle with a
height equal to the largest intensity of either of the boundary edges. If the area of the
rectangle is larger than the area of the peak the intensity is set to zero.
```
@dmccloskey @pasqoo I would also like to change "vertical division" to "rectangular" as that is what we are really doing, a rectangular background subtraction. Any thoughts on this?
> Background subtraction

- CMakeLists.txt
- doc/CMakeLists.txt
- doc/doxygen/install/install-linux.doxygen
- src/tests/class_tests/openms/CMakeLists.txt
Solution proposal for https://github.com/OpenMS/OpenMS/issues/3290
I don't have experience with CMake so there is a high chance the solution is very hacky / not elegant. :smile: 
I avoided adding indentation where necessary, to make the diffs easier to read. If the solution is ok, I'd take care of fixing the indentation (or do you have a better idea? It'd be many lines getting more indentation)
EDIT:
So users can now add `-DBUILD_DOCS=Off` to their `cmake` command in order to not build documentation.
> [BUILD]: Implement CMake flag to build documentation (BUILD_DOCS)

- src/openms/source/ANALYSIS/TARGETED/MRMMapping.cpp
- src/openms_gui/source/VISUAL/SpectraViewWidget.cpp
- src/tests/topp/MRMMapping_output.chrom.mzML
- src/tests/topp/MRMMapping_output_2.chrom.mzML
Make sure that if transition group-level data is available that it will
be used to analyze the whole transition group (peptide precursor).
> [FIX] Mapping MRM data and display peptide/transition names properly

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathWorkflow.h
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp
- src/utils/OpenSwathWorkflow.cpp
Until now OpenSwathWorkflow wrote the debugging output file containing iRT peptides in the current working directory with the fixed filename:  "debug_irts.mzML". The filename can now be set with the parameter -Debugging:irt_mzml
> [FIX] make Debugging:irt_mzml parameter functional

- src/topp/MSGFPlusAdapter.cpp
- src/topp/PercolatorAdapter.cpp
Set dots in the AA sequence only, if no N/C terminal mods are present.
Fixes #3188.
> fix PercolatorAdapter

- src/pyOpenMS/setup.py
Would be cool if we just would take over the OpenMS compile/macro definitions. This solves that for now without renaming the libs.
> [FIX] Missing win boost macro

- src/openms_gui/source/VISUAL/Spectrum3DCanvas.cpp
- src/openms_gui/source/VISUAL/Spectrum3DOpenGLCanvas.cpp
- re-enables scrolling in 3D view using the OpenGL Canvas
- works around a bug that caused black / black windows during scrolling
or when opening multiple 3D windows
> [FIX] enable scrolling again while preventing bug

- src/openms/source/ANALYSIS/OPENSWATH/PeakIntegrator.cpp
- leads to extensive warnings in real data
- leads to segfaults due to writing to the same output stream
> [FIX] remove warning inside lamda function

- cmake/MacOSX/fix_dependencies.rb
pyOpenMS currently doesn't build on my macOS system. Specifically, ``fix_dependencies.rb`` tries to patch ``__init__.py`` using ``handleDyLib()``. This fix ensures that only ``dylib`` or ``so`` files are being patched.
> [FIX] pyOpenMS fix for macOS

- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
if spectrum is annotated as centroided, we don't do a peak type estimation based on the data (which often goes wrong)
> [FIX] determine peak/profile type from meta data (if possible)

- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
Changes the default colors in the 1D spectral view:
- the default color was switched to black here fa46276d6293b90bc09ae47 which I dont particularly like
- the colors for the additional layers were way to bright and hard to see, so I made them more dark
- in the future it would be nice to be able to control the pen width for the `DM_CONNECTEDLINES` settings
we may want to look into real color schemes, such as http://colorbrewer2.org/ or http://paletton.com/#uid=7000u0kllllaFw0g0qFqFg0w0aF
> [GUI] different default colors for the layers

- src/topp/CometAdapter.cpp
- 20 000 seems like a much better tradeoff between speed and memory consumption.
- Adopted the warning for low-res data where anything below 0.2 for the fragment_bin_offset is clearly detrimental
- fixes #3470
Based on the analysis in this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4607604/figure/F3/
> [FIX] fix speed issues with CometAdapter

- src/openms/include/OpenMS/KERNEL/MRMTransitionGroup.h
Hi,
I hope that this is not solely on my end, but rather a problem for everyone ;)
The following compiler error occurs when trying to build OpenMS in debug mode: /home/lheumos/CLionProjects/OpenMS/src/openms/include/OpenMS/KERNEL/MRMTransitionGroup.h:258:96: error: no match for 'operator[]' (operand types are 'const std::map<OpenMS::String, int>' and 'const OpenMS::String')
It is not allowed to access const maps keys with parentheses [], because values not present in the map will get inserted using the [] operator. Therefore, it is recommended to use .at, which checks whether or not the key is present in the map and does not insert any new keys.
> [FIX] Fixing debug build, accessing const map key with .at instead of []

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.h
- src/openms/source/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.cpp
- src/pyOpenMS/pxds/TargetedSpectraExtractor.pxd
- src/tests/class_tests/openms/source/TargetedSpectraExtractor_test.cpp
This PR implements a way to fully support usage of each of the class' methods without relying on the presence of a `FeatureMap` in input/output.
To avoid duplicating code, I decided to add a `bool` argument `compute_features` to existing methods, which decides on the computation of the `FeatureMap` in input.
I found some small details that I could improve on (like avoiding copying variables when references `&` could be used, or postponing copy of data only when really it is necessary).
In tests, I avoid the use of a global pointer and I instantiate a new `TargetedSpectraExtractor` object for each test.
> [FEATURE] TargetedSpectraExtractor: "no feature" support for all methods

- src/openms/source/CONCEPT/FuzzyStringComparator.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLSqliteHandler.cpp
- src/tests/class_tests/openms/source/ProtXMLFile_test.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/FuzzyDiff_1_in1.featureXML
- src/tests/topp/FuzzyDiff_1_in2.featureXML
- src/tests/topp/FuzzyDiff_3_in1.featureXML
- src/tests/topp/FuzzyDiff_3_in2.featureXML
fixes a pretty serious bug in FuzzyDiff:
- Fixes the following bug: when a large ratio was found but does not
lead to failure (due to small absolute difference) then smaller ratios
than the original one that *should* lead to failure are ignored.
- adds tests for FuzzyDiff (really, we did not have tests so far?)
>  Fix/fuzzy

- tools/scripts/git_showdiff.sh
small tool that allows calculation of line changes between releases:
```
$ bash tools/scripts/git_showdiff.sh Release2.0.0 Release2.0.1
Usage: git_showdiff.sh REV1 REV2
2207 files changed, 43543 insertions(+), 19816 deletions(-)
182 files changed, 9660 insertions(+), 4476 deletions(-)
$ bash tools/scripts/git_showdiff.sh Release2.0.1 Release2.1.0
Usage: git_showdiff.sh REV1 REV2
1651 files changed, 21921 insertions(+), 25841 deletions(-)
$ bash tools/scripts/git_showdiff.sh  Release2.1.0 Release2.2.0
Usage: git_showdiff.sh REV1 REV2
2257 files changed, 42708 insertions(+), 22749 deletions(-)
281 files changed, 8931 insertions(+), 4911 deletions(-)
$ bash tools/scripts/git_showdiff.sh  Release2.2.0 Release2.3.0
Usage: git_showdiff.sh REV1 REV2
750 files changed, 29401 insertions(+), 8575 …
```
> small tool for git diffs

- src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
Seems to fail on some compilers otherwise.
> [FIX] Include instead of forward declare QStringList

- doc/doxygen/public/Main.doxygen
some quite embarrassing fixes - some links were dead and others were missing, e.g. no link to gitter or github
> [FIX] repair broken links, add Gitter+Github

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.h
This PR fixes a bug in the OSW export functionality if transition-level scoring is enabled but MI scores are not used.
> [FIX] OpenSWATH: OSW transition-level reports without MI scores

- cmake/knime_package_support.cmake
Necessary on Ubuntu Xenial (16.04) to avoid QT errors when building custom KNIME
plugins for OpenMS. See also: https://gitter.im/OpenMS/OpenMS?at=5b2bba007da8cd7c8c60a5d5
> [FIX] make `knime_package_support.cmake`  reissue `find_package` for QT to reload variables

- src/openms/source/FORMAT/MSPGenericFile.cpp
The `develop` version of this class parses multiple metadata on the same line, assuming they are separated by a `;`.
I noticed that some libraries use the character `;` within the `Comments` metadatum, and that breaks the implementation.
If one exports the NIST library to msp format (demo: https://chemdata.nist.gov/dokuwiki/doku.php?id=chemdata:nist17), he/she'll find that `CAS#` and `NIST#` are on the same line, separated by a `;`.
It is nice to support an important library as NIST's, therefore I went for a simple solution: keep supporting the above line, but do not assume multiple metadata on a single line anywhere else, because character `;` is not universally used as a separator for metadata.
> [FIX] MSPGenericFile: Assume one metadatum per line

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/PeakIntegrator.h
- src/openms/include/OpenMS/MATH/MISC/EmgGradientDescent.h
- src/openms/source/ANALYSIS/OPENSWATH/PeakIntegrator.cpp
- src/openms/source/MATH/MISC/EmgGradientDescent.cpp
- src/pyOpenMS/pxds/EmgGradientDescent.pxd
- src/pyOpenMS/pxds/PeakIntegrator.pxd
_EmgGradientDescent_ now supports `left` and `right` arguments.
_PeakIntegrator_ has a `"fit_EMG"` parameter that, if `true`, fits the EMG peak model to the interested peak part. The integration/bg_estimation/metrics computation continues on the interested part.
> [FEATURE] Integrate EMG into PeakIntegrator workflow

- src/topp/PercolatorAdapter.cpp
If an isotope error is given (e.g. when using the search engine MSGF+), the calulated mass is corrected by subtracting `(isotopeError * protonMass) / charge`.
> [FIX] Correction of the observed mass if isotope error is given

- src/openms/include/OpenMS/METADATA/PeptideHit.h
- src/openms/source/FORMAT/IdXMLFile.cpp
- src/openms_gui/include/OpenMS/VISUAL/SpectraIdentificationViewWidget.h
- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
The column appears when "Show advanced annotations" is ticked and `PeakAnnotations` exist in the `PeptideHits`.
Adresses #3588 .
For me it looks like the resizing of the column may not work correctly, it resizes to the longest annotation for one dataset with shorter annotations, but not for another with some much longer strings.
There may be a maximal limit to the automatic resizing with `table_widget_->resizeColumnsToContents()`
Also the horizontal scrolling method that sticks to columns makes it difficult to scroll this wide column.
At least exporting the table as .csv exports all the annotations correctly, regardless of the column size.
> [FEATURE] TOPPView column showing peak annotations as text

- src/tests/topp/CMakeLists.txt
- src/topp/OpenSwathDecoyGenerator.cpp
This PR changes the default of ``switchKR`` to ``true``. This tweak was [found](http://www.mcponline.org/content/early/2017/10/25/mcp.RA117.000314.abstract) to generate decoy sequences that are less biased in difficult cases, e.g. AAAAAAAK, where shuffling alone can't generate sufficiently different sequences.
> [FEATURE] OpenSwathDecoyGenerator: New default for switchKR

- src/topp/PercolatorAdapter.cpp
but still write out the meta values (for consistency)
> [FIX] add warning if ID can't be mapped back

- src/openms/include/OpenMS/CHEMISTRY/EmpiricalFormula.h
- src/openms/include/OpenMS/CHEMISTRY/ISOTOPEDISTRIBUTION/CoarseIsotopePatternGenerator.h
- src/openms/include/OpenMS/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.h
- src/openms/source/CHEMISTRY/EmpiricalFormula.cpp
- src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/CoarseIsotopePatternGenerator.cpp
- src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/IsotopeModel.cpp
- src/pyOpenMS/pxds/EmpiricalFormula.pxd
- src/pyOpenMS/pxds/IsotopeDistribution.pxd
- src/pyOpenMS/tests/unittests/test000.py
- src/tests/class_tests/openms/source/CoarseIsotopeDistribution_test.cpp
- src/tests/class_tests/openms/source/EmpiricalFormula_test.cpp
- src/tests/class_tests/openms/source/IsotopeDistribution_test.cpp
fixes #3589
CoarseIsotopePatternGenerator used to output atomic numbers (# protons + # neutrons) for the mass of each isotope. This can be quite different from the rounded mass of an isotope (see #3589)
I added a calc_mass_ flag that can be set during initialization of the CoarseIsotopePatternGenerator or afterwards. It determines if the expected masses (new functionality) or atomic numbers (old functionality) should be returned. By default, the calc_mass_ is set to true. The previous behavior can be achieved by setting calc_mass_ to false.
Expected masses are the monoisotopic mass of the molecule + (C13_C12_MASS_DIFFERENCE * isotope number). I'm assuming that most of a coarse isotopic peak is due to C13 molecules.
Currently, OpenMS has the following capabilities:
- With a known …
> [FIX, API, TEST] mass calculations for isotope distributions

- src/openms/source/FORMAT/DATAACCESS/CsiFingerIdMzTabWriter.cpp
- src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp
- src/tests/topp/THIRDPARTY/SiriusAdapter_4_foutput.mzTab
- src/utils/SiriusAdapter.cpp
Feature_id was not reported correctly in the CsiFingerIdMzTabWriter.
Use the number of candidates for Sirius Output.
Use the number of top hits for CSIFingerID Output.
Fix corresponding CSIFingerID-test.
> [FIX] CsiFingerIdMzTAbWriter, SiriusMzTabWriter 

- src/openms/include/OpenMS/FORMAT/MzIdentMLFile.h
- src/openms/source/FORMAT/MzIdentMLFile.cpp
- src/pyOpenMS/pxds/MzIdentMLFile.pxd
- src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp
There does not seem to be a test for `void MzIdentMLFile::load(const String& filename, Identification& id)` and I have tried to add one in 0fc26e1 but it seems that the result is empty.  So does the `void MzIdentMLFile::load(const String& filename, Identification& id)` not work? It does not seem tested. If it is broken, can we remove it?
> void MzIdentMLFile::load(const String& filename, Identification& id) is broken

- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
writes out the status of the "Curated" checkboxes as "1" for checked and "0" for unchecked
> [FIX, GUI] fixed output of "Curated" column in TOPPView csv export

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
allow multiple different values for the ion mobility array, including 
```
[Term]
id: MS:1002893
name: ion mobility array
def: "An array of ion mobility data." [PSI:PI]
is_a: MS:1000513 ! binary data array
```
> [FIX] allow multiple array names for IM

- src/tests/class_tests/openms/source/OPXLHelper_test.cpp
made test more robust by using local objects
and explicitly setting a precursor correction
> fixed OPXLHelper test to fix nightly build

- src/tests/topp/FeatureFinderMetabo_1_output.featureXML
- src/tests/topp/FeatureFinderMetabo_2_noEPD_output.featureXML
- src/tests/topp/FeatureFinderMetabo_4_output.featureXML
- src/topp/FeatureFinderMetabo.cpp
Annotation was set beforehand but lost on the way.
This will fix the issue. The fix is critical for the Release 2.4.0, since the Pipeline using the FeautreFinderMetabo will otherwise not annotate the filenames correctly.
The tools used further downstream will use "UNKOWN" instead.
(cheery-picked commit 35caee889efd87002dbb1243e1d3c9b9e769c772)
@hroest thank you for the suggestion
> [FIX] annotate "spectra_data"

- src/utils/MetaProSIP.cpp
not really a bug as intensities are integers stored as doubles but this way it is correct regarding the value type
> fix accumulate

- src/openms/include/OpenMS/ANALYSIS/ID/IDConflictResolverAlgorithm.h
As accordance to section: [Coding conventions - Coding Style - General Rules - Namespaces](https://github.com/OpenMS/OpenMS/wiki/Coding-conventions#gen_rules).
.
> [INTERNAL] Removed namespace std header declaration

- src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
This PR provides a hotfix to prevent a segmentation fault for OpenSwathWorkflow when transition-level scoring is enabled but the MI scores are disabled.
> [FIX] OpenSWATH: Disabling transition-level MI scores

- src/openms/include/OpenMS/METADATA/MetaInfo.h
Small change to reduce the size of meta info interface
before:
Memory usage (loading consensusXML): 2205 MB (working set delta)
FileInfo took 02:41 m (wall), 02:41 m (CPU), 2.10 s (system), 02:39 m (user).
after:
Memory usage (loading consensusXML): 1638 MB (working set delta)
FileInfo took 02:32 m (wall), 02:32 m (CPU), 1.72 s (system), 02:30 m (user).
> [FIX] reduce size of meta data

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/SwathWindowLoader.h
- src/openms/include/OpenMS/APPLICATIONS/OpenSwathBase.h
- src/openms/source/ANALYSIS/OPENSWATH/SwathWindowLoader.cpp
- src/openswathalgo/include/OpenMS/OPENSWATHALGO/DATAACCESS/SwathMap.h
- src/pyOpenMS/pxds/SwathWindowLoader.pxd
- src/tests/class_tests/openms/source/SwathWindowLoader_test.cpp
- src/utils/OpenSwathWorkflow.cpp
[FEATURE] OpenSwathWorkflow: better checking of swath_window_file ranges before overwriting the data ranges 
- only narrowing of isolation window ranges is allowed (unless -force flag is specified)
- new window range constraint: lower < upper
> [FEATURE] OpenSwathWorkflow: better checking of swath_window_file

- doc/doxygen/install/install-win.doxygen
to avoid linker error `LNK1210: exceeded internal ILK size limit; link with /INCREMNTAL:NO`
(usually only during repeated incremental links during development)
> [DOC] use x64 link flags for Win64 builds 

- src/openms/thirdparty/IsoSpec/IsoSpec/marginalTrek++.cpp
- src/tests/class_tests/openms/source/FineIsotopeDistribution_test.cpp
- currently a ptr to the *current* configuration was stored in "visited"
which meant the *same* ptr was stored N times instead of storing the
different configurations. This meant that visited.count(currentConf)
would not work reliably.
- this PR is to test whether this fixes the issues with the calculations of C100
> [TEST] Fix/bugfix subisotope

- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.h
- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.h
- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.h
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
PR #3644 fixed a bug by simply removing a [pre-filtering step](https://github.com/OpenMS/OpenMS/compare/develop...lars20070:fix/FFM_performance?expand=1#diff-d07005aa96a93e57990ba6d481c8425eR66). (The peak map is pre-filtered using an intensity cutoff. This step reduces memory footprint and runtime.)
This PR re-introduces the pre-filtering step and fixes the old bug by passing the filtered peaks and peak boundaries to the subsequent `featureXML` and `consensusXML` map construction.
Results remain the same, see unchanged `TOPP` tests.
> performance improvements for FeatureFinderMultiplex

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.cpp
Minor simplification of the code for blacklist initialisation.
Thanks for spotting this, @pasqoo.
> simplify blacklist initialisation in FeatureFinderMultiplex

- src/utils/SiriusAdapter.cpp
Added recently to SIRIUS.
May come in handy when processing locally.
edit:
Use OpenMP check number of processors.
If OpenMP is not available - SIRIUS default -> all possible CPUs
If OpenMS is available parameter "threads" used for the number of processors.
If threads was set too high -> reset to maximal numbers of processors.
@jpfeuffer  Is it OK, to abuse the threads parameter that way?
> [ADD] Param: processors (SiriusAdapter)

- src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLHelper.h
- src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp
- src/utils/OpenPepXL.cpp
- src/utils/OpenPepXLLF.cpp
race conditions caused crashes, when LOG_DEBUG was written in from different threads.
Now all LOG_DEBUG writing operations are in critical sections and only compiled and run if they are activated using the `#define DEBUG_...`and `#ifdef DEBUG_...`conditions.
> release/2.4.0 fixed OpenPepXL parallelization errors

- src/openms/cmake_findExternalLibs.cmake
- src/utils/CMakeLists.txt
my local builds were not completely linking anymore - FFSuperHirn failed, which was due to missing pthreads, which is now required.
> added pthread find to cmake

- src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp
- src/tests/class_tests/openms/data/MetaboliteFeatureDeconvolution_easy_output.consensusXML
- src/tests/class_tests/openms/data/MetaboliteFeatureDeconvolution_neg_output.consensusXML
- src/tests/class_tests/openms/data/MetaboliteFeatureDeconvolution_test.featureXML
Turned out that previously, negative mode decharging was only tested (to work correctly) on input features with charge=0. This fix adds support for input features with non-zero charges, to make negative mode decharging fully functional.
By design (as FeatureFinding methods don't consider negative charges), we have to look at compare the absolutes of charges at several points. Extension of use of dc_charge_adduct* MetaValues ensures correct computation of neutral mass for charged but ungrouped features (given assumed default adducts and absolute charge).
> fixed negative mode decharging for charge!=0 features from FF

- src/topp/CometAdapter.cpp
I realized that the comet version shouldnt be constrained with valid strings as otherwise all other comet versions will fail with this adapter.
> delete valid strings for comet version

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
Fixes #3424 
Somehow, opening the file dialog invalidates the current active sub window in the enhanced tab bar.
This fix saves and restores it.
> fix #3424 in TOPPViewBase.cpp

- src/openms/source/FORMAT/PepXMLFile.cpp
Conversion of idXML files to pepXML files results in reannotation of scan ids.
When providing the original mz_file scan index lookup is carried out using an RT lookup.
Since the RT can change upon transformation a scan_index based lookup should be preferential.
> IDFileConverter - NativeID prior to RT lookup

- src/pyOpenMS/fix_pyopenms_dependencies_on_mac.sh
- src/pyOpenMS/mac_fix_automation_mojave.sh
[FIX] fix find command in `fix_pyopenms_dependencies_on_mac.sh`
[ADD] mac_fix_automation_mojave.sh
mac_fix_automation_mojave.sh
Can be run in the PyOpenMS folder after compiling. 
1) backup the current whl -> .original.
2) unzip  `.whl` in the `dist` folder
3) move QtNetwork/QtCore from framework to main folder and delete frameworks.
3) fix the paths via `fix_pyopenms_dependencies_on_mac.sh`
4) zip the whl again 
The unzipped version and the .original will be retained - if someone wants to check the paths or need the original again 
e.g. `otools -L libOpenMS.dylib``
Was tested on MacOS 10.14.1 (python2.7, 3.7)
> [FIX][ADD] pyOpenMS whl mac

- src/openms/source/FORMAT/MascotRemoteQuery.cpp
Was replacing all occurrences of the hostname. Wrong in case of equal servername.
This is on top of my head. Changes untested.
fixes #3611 if successful
> [FIX] replace hostname in mascot query

- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.h
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.cpp
- src/tests/class_tests/openms/source/FeatureFinderMultiplexAlgorithm_test.cpp
- src/tests/topp/FeatureFinderMultiplex_1_output.consensusXML
- src/tests/topp/FeatureFinderMultiplex_1_output.featureXML
- src/tests/topp/FeatureFinderMultiplex_2_output.consensusXML
- src/tests/topp/FeatureFinderMultiplex_2_output.featureXML
- src/tests/topp/FeatureFinderMultiplex_3_output.consensusXML
- src/tests/topp/FeatureFinderMultiplex_3_output.featureXML
- src/tests/topp/FeatureFinderMultiplex_4_output.consensusXML
- src/tests/topp/FeatureFinderMultiplex_4_output.featureXML
- src/tests/topp/FeatureFinderMultiplex_5_output.consensusXML
- src/tests/topp/FeatureFinderMultiplex_5_output.featureXML
Previously, `FeatureFinderMultiplex` determined the reported peptide intensities by merely summing the spectral intensities of all filtered data points. The following three changes were made to improve on these results.
(1) The simple intensity sum is replaced by [trapezoid area](https://github.com/OpenMS/OpenMS/pull/3888/files#diff-a4a0a740e6b1905e206e7f5a0ea51757R415) under the curve of all mass traces
(2) Peptide ratios i.e. fold changes are calculated directly from the filter results using [linear regression](https://github.com/OpenMS/OpenMS/pull/3888/files#diff-a4a0a740e6b1905e206e7f5a0ea51757R299).
(3) The [RT shift](https://github.com/OpenMS/OpenMS/pull/3888/files#diff-a4a0a740e6b1905e206e7f5a0ea51757R281) is taken into account when calculating (2). Possible due to the novel …
> improve peptide intensities in FeatureFinderMultiplex

- src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h
- src/openms/source/DATASTRUCTURES/LPWrapper.cpp
- src/tests/class_tests/openms/source/LPWrapper_test.cpp
A few improvements to the class. I'm using it in some code of mine and it was very annoying to have to pass non-`const` variables to functions/methods that actually did not need to change the passed data.
This cleanup does not change the behaviour of the class.
**Advantages**
- the user is not required to passo non-`const` variables
- it better informs the user, because `const`-correctness assures that passed data won't be changed
- in some cases, copying of data is avoided (or delayed, when the right conditions are `true`, i.e. `if (solver_ == SOLVER_GLPK)`)
- avoid usage of `new`, no need of `delete`-ing memory
- it should be easier to spot out-of-range bugs (which I suspect might be present: glpk's routines assume 1-indexed arrays while we commonly assume 0-indexed arrays/vectors. It's …
> [STYLE] LPWrapper: avoid pointers, use const, use STL containers

- src/openms/source/FORMAT/ChromeleonFile.cpp
- src/tests/class_tests/openms/source/ChromeleonFile_test.cpp
Parse the `Channel` info from the data file and add it to the experiment as a new metavalue named `"acq_method_name"`.
The `Channel` info is found twice within the file (the first time at line 2, and then within the raw information data). Same info repeated. The code would simply overwrite the first "set" value.
> [FEATURE] add "acq_method_name" metavalue to ChromeleonFile parser

- share/OpenMS/CHEMISTRY/Elements.xml
- src/openms/include/OpenMS/CHEMISTRY/ElementDB.h
- src/openms/source/CHEMISTRY/ElementDB.cpp
ASAN reported mem leaks for ElementDB. This fixes it, and some other issues:
[FIX] ElementDB: memory leak (lost pointer, [1], e.g. when atomic number already exists (e.g. Hydrogen vs. Deuterium have both '1') and double free (duplicate pointer to same Element [2])
[FIX] fix mass of Pb208 in Elements.xml (also fixes a mem-leak)
[FIX] ElementDB: fix properties of last element 'Samarium' in File (not constructed correctly)
And to avoid future issues:
[FEATURE] ElementDB now reports inconsistencies in Elements.xml (or future versions of it) to avoid mem-leaks
[FIX] make construction of ElementDB thread-safe (using Myers Singleton -- instead of a pointer)
[1] https://github.com/OpenMS/OpenMS/blob/ac4c8767657504e98572baf453c41dcf1d7fff15/src/openms/source/CHEMISTRY/ElementDB.cpp#L197
[2] …
> Fix ElementDB and Elements.xml

- share/OpenMS/examples/simulation/FASTAProteinAbundanceSampling.py
- src/openms/source/CONCEPT/LogStream.cpp
- src/openms/source/SIMULATION/IonizationSimulation.cpp
- src/openms/source/SIMULATION/RTSimulation.cpp
- src/tests/class_tests/openms/source/IonizationSimulation_test.cpp
on rare occasions, MSSimulator would crash when using >1 threads, since Boost RNGs are not threadsafe.
This is fixed now.
Also fixes a `bad_alloc` when the user specifies protein intensities manually which are numeric_limits<uint>. This is now resulting in
```
exception of type InvalidValue occured in line 325, function void __cdecl OpenMS::IonizationSimulation::ionizeEsi_(class OpenMS::FeatureMap &,class OpenMS::ConsensusMap &) of C:\dev\openmsqt5\src\openms\source\SIMULATION\IonizationSimulation.cpp
error message: the value '6.67539e+18' was used but is not valid; Protein abundance is too high. Please use values in [0,4294967295]!
```
> [FIX] MSSimulator thread-safe now

- src/openms/include/OpenMS/DATASTRUCTURES/StringUtils.h
- src/pyOpenMS/addons/ADD_TO_FIRST.pyx
- src/pyOpenMS/addons/String.pyx
- src/pyOpenMS/pxds/String.pxd
- src/pyOpenMS/tests/unittests/test000.py
- src/tests/class_tests/openms/source/String_test.cpp
- Allow generation of unicode strings from a `char*` which was not possible before as the conversion would abort at zero bytes, thus truncating data
- Adds tests for the new behavior
- Add pyOpenMS wrappers that utilize the new behavior
This basically makes the two constructors
```
String(const char* s, size_type count)
std::string(const char* s, size_type count)
```
behave the same way as before the `std::string` would not stop at zero bytes while the `OpenMS::String` would. Quite a bit of surprising behaviour there! See
https://en.cppreference.com/w/cpp/string/basic_string/basic_string
"Constructs the string with the first count characters of character string pointed to by s. s can contain null characters. The length of the string is count. The behavior is undefined if [s, s + count) is …
> Storing Unicode in OpenMS::String

- src/openms/include/OpenMS/SYSTEM/StopWatch.h
- src/openms/source/CONCEPT/FuzzyStringComparator.cpp
- src/openms/source/SYSTEM/StopWatch.cpp
- src/tests/class_tests/openms/source/StopWatch_test.cpp
- src/utils/FuzzyDiff.cpp
comparing "large" files (6MB) using FuzzyDiff takes about 9 seconds on VS2015 Release(!), whereas its rather fast (0.3 sec) on GCC.
This PR speeds up FuzzyDiff by avoiding the  `stringstream>>double operator` which is awfully slow on VS.
Test time on Windows is now also 0.3 secs for this special case.
In general the combined time of TOPP+UTIL tests (1117 tests), many of which use FuzzyDiff, went from 55 sec to 36 sec (10 jobs parallel) on VS. GCC builds also profit, but not as much (102 sec --> 82 sec).
12 sec to 0.5 sec by reducing waiting time
> FuzzDiff Performance improvements

- src/openms/source/METADATA/SpectrumLookup.cpp
- src/tests/class_tests/openms/source/IonizationSimulation_test.cpp
[FIX] SpectrumLoopUp - last match
As a workaround to get the scan number it is encoded in the temporary path of the SIRIUS directory structure. e.g.
1_20190116_111724_MacBook-Pro.local_36861_2_0-2165004-UNKNOWN2
So we would have UNKOWN with the index 2 and the scan number (nativeID) 2165004, which is extracted via a regex expression.
My best guess is that the temporary path of SIRIUS in travis has another motif for this regex "-xxx-" - this would explain the different numbers in multiple runs.
I can try to fix it by always using the last group.
The next SiriusAdapter Version with SIRIUS 4.04 will most likely deprecate the current mzTab writers due to a switch of SIRIUS to mztab-m output.
> [TEST] FIX SiriusAdapter travis  

- src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLDataStructs.h
- src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLHelper.h
- src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp
- src/openms/source/ANALYSIS/XLMS/OpenPepXLAlgorithm.cpp
- src/openms/source/ANALYSIS/XLMS/OpenPepXLLFAlgorithm.cpp
- src/openms/source/CHEMISTRY/SimpleTSGXLMS.cpp
- src/openms/source/CHEMISTRY/TheoreticalSpectrumGeneratorXLMS.cpp
- src/pyOpenMS/pxds/ProteinProteinCrossLink.pxd
- src/tests/class_tests/openms/source/OPXLDataStructs_test.cpp
- src/tests/class_tests/openms/source/OPXLHelper_test.cpp
- src/tests/class_tests/openms/source/SimpleTSGXLMS_test.cpp
- src/tests/class_tests/openms/source/TheoreticalSpectrumGeneratorXLMS_test.cpp
- Improved memory efficiency by using pointers: Enumeration of candidates of peptide pairs now points to the list of single peptides instead of copying the AASequences for each pair.
- Reduced memory usage by reworking the parallelization: previously the parallelized loop was looping over the spectra. The lists of candidates and results for each spectrum had to be enumerated and computed for each spectrum in parallel and this increased the memory usage proportional to the number of used threads. Now several parallelized loops loop over the candidate enumeration and result computation for one spectrum. This makes the parallelization slightly less efficient, but it removes the increase in memory usage for multiple threads.
I tested it on a data set with a 256 protein database, where some …
> [FEATURE] OpenPepXL: more efficient memory usage

- src/topp/LuciphorAdapter.cpp
Adds local and global false localization rate to the idXML output.
For an explanation of the available scores see:
http://luciphor.sourceforge.net/output_fields.html
> [ADD] additional scores to LuciPhorAdapter ouptut

- src/tests/class_tests/openms/source/String_test.cpp
From cppreference:
Hexadecimal escape sequences have no length limit and terminate at the first character that is not a valid hexadecimal digit. If the value represented by a single hexadecimal escape sequence does not fit the range of values represented by the character type used in this string literal (char, char16_t, char32_t, or wchar_t), the result is unspecified.
> [FIX] ASan error

- cmake/compiler_flags.cmake
- doc/doxygen/install/common-cmake-parameters.doxygen
this PR allows to augment CXX compile flags via
`cmake -DMY_CXX_FLAGS="..." ...`
Useful for a lot of scenarios without resorting to hacks or changing a CMakeLists.txt.
> [FEATURE] custom CXX flags via CMake

- src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
the message box paused the execution of the rest of the function prematurely
fixes #213 
I think this is a multi-threading issue:
The function Spectrum2DCanvas::finishAdding_() is supposed to update ranges and initialize the color gradient before anything is drawn on the Canvas. The function was paused at the position where the warning about negative intensities in a feature map was evoked and another thread started drawing the features already, leading to a segfault when accessing the color gradient.
The negative intensities themselves don't seem to cause any issue, it was the warning about them at the wrong place.
I moved the warning to the end of the function, so that the update of ranges and color gradients is finished before the warning pops-up.
As a side note:
I could not figure out …
> [FIX, GUI] moved a warning message box to the end of the function

- src/openms/include/OpenMS/FORMAT/PepXMLFile.h
- src/openms/source/FORMAT/PepXMLFile.cpp
- src/topp/LuciphorAdapter.cpp
Workflow using multiple search engines lead to small differences in the retention time (identification vs. spectra). Error in LuciphorAdapter.
Using the ConsensusID - PepXMLFile will use the RT for mapping - here the default rt in SpectrumLookup is 0.01.
To be able to use a higher rt_tolerance:
- the parameter was introduced to LuciphorAdapter
- the variable was added to PepXMLFile::store (with the same default as used in SpectrumLookup) 
e.g.
rt_tolerance: 0.05
spectrum_rt: 1724.67
lower_diff: 0.02492
upper_diff: 0.1117
> [FIX] LuciphorAdapter - ConsensusID 

- src/openms/source/FORMAT/PepXMLFile.cpp
- src/pyOpenMS/pxds/PepXMLFile.pxd
- src/topp/LuciphorAdapter.cpp
Adjust LuciphorAdapter/PepXMLFile to work with "pep" score type.
Workflow for multiple search engines -> FileMerger -> PSMFeatureExtractor -> PeptideIndexer -> PercolatorAdapter -> IDFilter -> LuciPhorAdapter. 
Add previously added parameter "rt_tolerance" to PepXMLFile.pxd
> [FIX] LuciphorAdapter 

- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
PeakAnnotations are not shown in the TOPPView IdentificationView directly,
so they were not exported into CSV tables. Now they are also exported.
Since that can make the CSV files very large, the CSV export function now ignores data from hidden columns (hidden by right-clicking column headers). This gives users precise control over what gets exported.
> [FEATURE] TOPPView: export annotations and hide columns for export

- src/openms/source/CHEMISTRY/AASequence.cpp
- src/tests/class_tests/openms/source/AASequence_test.cpp
- fix for N-terminal modifications that are only allowed on specific
amino acids, they can now be parsed properly.
- can now parese `C[143]PEPTIDEK` and `Q[111]PEPTIDEK`
> [FIX] fix for N-terminal modifications

- src/openms/source/CHEMISTRY/ElementDB.cpp
augments and fixes #3906.
If an old ElementDB was used, this would trigger a segfault because the wrong element would be deleted....
> [FIX] ElementDB segfault

- src/openms/source/CHEMISTRY/AASequence.cpp
- src/tests/class_tests/openms/source/AASequence_test.cpp
fix https://github.com/OpenMS/OpenMS/pull/3957 - now also floating point numbers work, e.g. AASequence::fromString("Q[-17.0265]PEPTIDEK")
> [FIX] bugfix

- src/openms_gui/source/VISUAL/LayerData.cpp
- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
fixes #3970 
There is still one weird behaviour that I can't explain. The line breaks don't work in the PeakAnnotation tables for me, the names containing a line break are not centered in the column and in one line:
It looks correct in the labels on the peaks:
I inserted "\n" for the line breaks, am I missing something here?
> [FIX, GUI] fixed parsing charges from automatic spectrum labeling

- src/tests/topp/FileInfo_1_output.txt
- src/tests/topp/FileInfo_2_output.txt
- src/tests/topp/FileInfo_4_output.txt
- src/tests/topp/FileInfo_5_output.txt
- src/tests/topp/FileInfo_6_output.txt
- src/tests/topp/FileInfo_9_output.txt
- src/topp/FileInfo.cpp
FileInfo now reports the *total* (spec + chrom) number of peaks first.
Before, one might get the impression that the number of peaks is prely from spectra (which it is not).
> better wording for FileInfo

- src/tests/class_tests/openms/source/IdentificationDataConverter_test.cpp
probably fixes nightly failing test: http://cdash.openms.de/testDetails.php?test=54975401&build=301147
```
+  line 71:  TEST_EQUAL(peptides_in.size(),peptides_out.size()): got '3', expected '3'
+  line 81:  TEST_EQUAL(hits_in.size(),hits_out.size()): got '5', expected '5'
+  line 86:  TEST_EQUAL(find(hits_in.begin(), hits_in.end(), hit) != hits_in.end(),true): got '1', expected '1'
+  line 86:  TEST_EQUAL(find(hits_in.begin(), hits_in.end(), hit) != hits_in.end(),true): got '1', expected '1'
+  line 86:  TEST_EQUAL(find(hits_in.begin(), hits_in.end(), hit) != hits_in.end(),true): got '1', expected '1'
+  line 86:  TEST_EQUAL(find(hits_in.begin(), hits_in.end(), hit) != hits_in.end(),true): got '1', expected '1'
+  line 86:  TEST_EQUAL(find(hits_in.begin(), hits_in.end(), hit) != …
```
> [TEST] sort proteins

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFilter.h
- src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp
- src/tests/class_tests/openms/source/MRMFeatureFilter_test.cpp
The code would output the failure messages as a contatenation of all messages, delimited by a character.
In this PR I am replacing that logic with `StringList`, so that the end-user can decide how to separate/deal with the messages.
> feat: MRMFeatureFilter failure messages as StringList

- src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandler.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandlerHelper.h
- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLHandlerHelper.cpp
Ensure that we actually use 64 bit integers to store spectra / chromatogram offsets on all platforms
I have confirmed this on Windows that it fixes #4009 
There is currently no test for it as it would require to write a 2+ GB file to disk which we probably dont want to do routinely
> [FIX] fix overflow on Windows

- doc/doxygen/public/UTILS.doxygen
Slight overhaul of the main "UTILS documentation" page. Added new categories for "Targeted Experiments and OpenSWATH" and "RNA", and tried to move as many tools as possible out of "Misc" into more descriptive categories.
We (i.e. the respective authors/maintainers) should really add documentation to the tools that currently don't have any, even if it's just minimal: OpenMSInfo, SimpleSearchEngine, RNPxlSearch and MetaProSIP. I don't like that we have "secret" tools that don't appear on the documentation page.
> Improved categorisation of UTILS tools on documentation page

- src/openms/source/CHEMISTRY/EmpiricalFormula.cpp
- src/tests/class_tests/openms/source/EmpiricalFormula_test.cpp
This makes `getAverageWeight` consistent with `getMonoWeight` (which was fixed previously as part of  #2874).
In all cases, protons are assumed to be the charge carriers that are gained/lost (which is problematic, but not addressed here - see #1042).
Also added tests for `getAverageWeight` and `getMonoWeight` with charges and removed some unnecessary whitespace.
> Support negative charges in 'EmpiricalFormula::getAverageWeight' (fixes #1041)

- src/openms/source/CHEMISTRY/NucleicAcidSpectrumGenerator.cpp
Additional testing confirmed that using the theoretically correct mass value (of a proton, not intact hydrogen) didn't lead to worse results after all - so I've made the corresponding change here.
> Addendum to PR #4020: use proton mass for charges

- src/openms/include/OpenMS/DATASTRUCTURES/DPosition.h
- src/tests/class_tests/openms/source/AveragePosition_test.cpp
Fixes segfault on windows nightlies (tested on the machine itself).
Change in test unrelated. will change back.
Not sure if this is the best solution and why it occurred at all. Shouldn't this be what the
default move is doing?
I'll have another look at it later.
> [FIX] move DPosition

- src/pyOpenMS/pyopenms/Constants.py
- src/pyOpenMS/pyopenms/python_extras.py
should allow `pyopenms.Constants` to be populated with the OpenMS physical constants as well.
> [PYOPENMS] add physical and chemical constants

- src/openms/include/OpenMS/ANALYSIS/ID/SimpleSearchEngineAlgorithm.h
- src/openms/include/OpenMS/ANALYSIS/RNPXL/ModifiedPeptideGenerator.h
- src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLHelper.h
- src/openms/include/OpenMS/CHEMISTRY/AASequence.h
- src/openms/source/ANALYSIS/ID/SimpleSearchEngineAlgorithm.cpp
- src/openms/source/ANALYSIS/RNPXL/ModifiedPeptideGenerator.cpp
- src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp
- src/openms/source/ANALYSIS/XLMS/OpenPepXLAlgorithm.cpp
- src/openms/source/ANALYSIS/XLMS/OpenPepXLLFAlgorithm.cpp
- src/pyOpenMS/pxds/ModifiedPeptideGenerator.pxd
- src/pyOpenMS/pxds/OPXLHelper.pxd
- src/tests/class_tests/openms/source/ModifiedPeptideGenerator_test.cpp
- src/tests/class_tests/openms/source/OPXLHelper_test.cpp
- src/utils/RNPxlSearch.cpp
Before:
Generating 29 * 1e5 peptides took:
1 thread: 16s
20 threads: 17s
After:
1 thread 15s
20 threads 0.6s
> lockfree generation of modified peptides

- cmake/Windows/NSIS.template.in
Seems like Microsoft loves to change their parameters for silent installs:
http://asawicki.info/news_1597_installing_visual_c_redistributable_package_from_command_line.html
> [FIX] Silently install Redists

- src/openms/include/OpenMS/FORMAT/MzTab.h
- src/openms/source/FORMAT/MzTab.cpp
- src/openms/source/FORMAT/MzTabFile.cpp
- src/topp/MzTabExporter.cpp
When exporting `consensusXML` to `mzTab`, the individual peptide intensities for each study variable are exported. With this PR, the individual `m/z` and `RT` are now exported as well.
Resolves #3705.
> columns for mz and rt for individual feature handles to mzTab

- cmake/package_rpm.cmake
I was recently building on a CentOS machine and thought I would bring the rpms back to life.
Initial attempt without GUI tools worked great (also the autodependency resolution).
Could be refactored to join duplicate variables with the Debian package.
> [FEATURE] Update rpm package.

- share/OpenMS/CHEMISTRY/Modomics.tsv
- src/openms/include/OpenMS/METADATA/ID/IdentificationDataConverter.h
- src/tests/topp/NucleicAcidSearchEngine_11_out.idXML
- src/tests/topp/NucleicAcidSearchEngine_12_out.mzTab
- src/utils/NucleicAcidSearchEngine.cpp
Using the parameter "precursor:isotopes", NASE can try different offsets between the monoisotopic mass and the precursor mass when matching oligonucleotides to MS2 spectra. The offset value that led to an identification is now included in the mzTab output (column "opt_isotope_offset" on the "OSM" level).
In addition, the Modomics resource file that contains data on available RNA modifications has been updated to include a mod. that was previously missing.
> NucleicAcidSearchEngine: include isotope offset in mzTab output

- src/openms/include/OpenMS/ANALYSIS/QUANTITATION/AbsoluteQuantitationMethod.h
- src/openms/source/ANALYSIS/QUANTITATION/AbsoluteQuantitationMethod.cpp
- src/tests/class_tests/openms/source/AbsoluteQuantitationMethod_test.cpp
In class `AbsoluteQuantitationMethod`:
- remove unnecessary code by applying the rule of zero and in-class initializers
- add tests for: default constructor, copy constructor and copy assignment operator
> [STYLE/TEST] AbsoluteQuantitationMethod: rule of zero, more tests

- src/openms/source/APPLICATIONS/TOPPBase.cpp
- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
if the upstream node of an output node only has a single allowed output type which at the same time has lower/uppercase differences to the default types in OpenMS, e.g. ConsensusXML vs. consensusXML, TOPPAS will try to rename the file, which fails, because it first deletes the target (if it exists).
Since this is the same file, we would be deleting the source file... bad...
This is only a problem on Windows since the file system is not case sensitive (and hence regards these files as equal).
> [FIX] prevent TOPPAS crash on Windows when copying output files 

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.h
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.cpp
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.cpp
- src/utils/OpenSwathWorkflow.cpp
This PR fixes an issue in OpenSwathOSWWriter, where some types of ``MetaValue`` were not correctly converted.
This PR further removes support for UIS scores from OpenSWATHTSVWriter, as the downstream tools (PyProphet & Percolator) now only support OSW and parsing of concatenated scores with different length was always suboptimal.
> [FIX] OpenSWATHOSWWriter: Separate score fix

- doc/doxygen/public/TOPP.doxygen
- doc/doxygen/public/UTILS.doxygen
- src/topp/GNPSExport.cpp
- src/utils/ClusterMassTraces.cpp
- src/utils/ClusterMassTracesByPrecursor.cpp
- src/utils/MSstatsConverter.cpp
- src/utils/MetaProSIP.cpp
- src/utils/RNPxlSearch.cpp
fix some issues in the TOPP / UTILS documentation - this is to find tools that are not listed in the documentation anywhere:
```
cat doc/doxygen/public/TOPP.doxygen doc/doxygen/public/UTILS.doxygen  > /tmp/both
for f in src/topp/*.cpp src/utils/*.cpp; do 
bn=`basename $f .cpp`; cnt=`grep -c $bn /tmp/both`; 
if [ "$cnt" -eq 0 ];then echo $f;fi ;
done 
```
> [DOC] topp/utils docu

- src/tests/topp/CMakeLists.txt
- src/tests/topp/IDFilter_22_output.idXML
- src/topp/IDFilter.cpp
The 'not equal' or `'ne'` option in the IDFilter MetaValue filtering was missing in a check for illegal parameters and did not actually work.
Added a regression test as well.
>  [FIX] IDFilter: fixed 'not equal' option in MetaValue filtering 

- src/openms/include/OpenMS/CONCEPT/LogConfigHandler.h
- src/openms/include/OpenMS/CONCEPT/LogStream.h
- src/openms/source/APPLICATIONS/TOPPBase.cpp
- src/openms/source/CONCEPT/LogConfigHandler.cpp
- src/openms/source/CONCEPT/LogStream.cpp
- src/openms/source/SIMULATION/MSSim.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPAS.cpp
- src/tests/class_tests/openms/source/LogStream_test.cpp
- src/tests/class_tests/openms/source/Param_test.cpp
- src/topp/ConsensusID.cpp
- src/topp/PeptideIndexer.cpp
- src/topp/PhosphoScoring.cpp
- src/utils/FeatureFinderMetaboIdent.cpp
- src/utils/OpenPepXL.cpp
- src/utils/OpenPepXLLF.cpp
This PR completes https://github.com/OpenMS/OpenMS/pull/4082
For some reason, I am experiencing name clashes in my codebase when it comes to those `extern` identifiers.
I might be proposing another PR soon, which would remove all the loggers' buffer logic and just redirect all streams to `std::cout`, as proposed by @hroest . Hopefully those changes will help in multi-threading scenarios.
> [STYLE] rename `extern` logging objects i.e. Log_debug

- src/utils/PSMFeatureExtractor.cpp
Fixes #4140
Adds out_type option to PSMFeatureExtractor to resolve ambiguity for idXML or mzid output, specifically in the interface between PSMFeatureExtractor and PercolatorAdapter.
> [FIX-#4140] Fixed PSMFeatureExtractor unknown output format issue. 

- src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
- src/openms/source/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.cpp
- src/openms/source/APPLICATIONS/TOPPBase.cpp
add a link to the online documentation from the tool output
- for completeness, add it to the top and the bottom :-) 
- fix the URL in the CTD XML
New output:
```
$ ./bin/OpenSwathWorkflow 
No options given. Aborting!
OpenSwathWorkflow -- Complete workflow to run OpenSWATH
Full documentation: http://www.openms.de/documentation/UTILS_OpenSwathWorkflow.html
Version: 2.4.0-feature-osw-params-2019-06-18 Jun 18 2019, 22:57:54, Revision: ff146b4
To cite OpenMS:
Rost HL, Sachsenberg T, Aiche S, Bielow C et al.. OpenMS: a flexible open-source software platform for mass spectrometry data analysis. Nat Meth. 2016; 13, 9: 741-748. doi:10.1038/nmeth.3959.
Usage:
OpenSwathWorkflow <options>
This tool has algorithm parameters that are not shown here! Please check the ini file for a detailed description …
```
> [FEATURE] add link to online docu

- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
by getting rid of static init check (lock) and heap alloc! 
whhhoohaaa! :)
Reading speed: 27 sec vs 26.5 sec (reproducible) for 1.8 GB file
> [FEATURE] 2% performance increase reading mzML 

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/DIAHelper.h
- src/openms/source/ANALYSIS/OPENSWATH/DIAHelper.cpp
- src/openms/source/FORMAT/ChromeleonFile.cpp
- src/tests/class_tests/openms/data/ChromeleonFile_new_header.txt
- src/tests/class_tests/openms/source/ChromeleonFile_test.cpp
- handle new `Chromatogram Data:` raw data header (tests included)
- handle possible string `n.a.` in the `Step` column
- `line` is now a dynamically allocated string instead of a fixed-size array
- using `regex_match` instead of `regex_search`
- do not include character `\r` in sub-match
Note: the first commit is part of another PR: https://github.com/OpenMS/OpenMS/pull/4191 I branched out of that otherwise I could not compile and test this PR's code locally.
> [FEATURE/FIX] ChromeleonFile handles raw data header

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/DIAHelper.h
- src/openms/source/ANALYSIS/OPENSWATH/DIAHelper.cpp
Small inconsistency found in the last few changes to the class.
I guess `Release` builds succeed because those do not include `OPENMS_PRECONDITION()` calls.
But once I tried building `develop` as `Debug`, I had compile errors.
> fix: rename mz_extraction_window to mz_extract_window in DiaHelper

- src/openms/include/OpenMS/FORMAT/MSstatsFile.h
- src/openms/source/FORMAT/MSstatsFile.cpp
- src/tests/topp/MSstatsConverter_2_out.csv
Some minor updates for the MSstatsConverter, due to changes in the next R package version (MSstatsTMT). 
Question: 
The class MSstatsFile, due to the addition of the TMT-method has a lot of code duplication, or at least code overlap, with small changes e.g. MSstatsFile::MSstatsLine and MSstatsFile::MSstatsTMTLine; storeLFQ and storeISO.
Here, I tried to do some refactoring, but I am a little bit lost - where do I start and what would be best to make the code a bit cleaner and more functional. 
I would be very happy if you could give me some pointers! 
This will then probably go to a new PR.
> [Update] MSstatsConverter (TMT)

- src/openswathalgo/source/OPENSWATHALGO/ALGO/MRMScoring.cpp
In very rare cases (e.g. with ultra-short gradients), the spectral angle score of OpenSWATH results in NaN values. This patch ensures that always numerical values are reported.
> [FIX] OpenSWATH: Patch to prevent NaN from spectral angle score

- .github/stale.yml
- src/tests/topp/NucleicAcidSearchEngine_11_out.idXML
- src/utils/FeatureFinderMetaboIdent.cpp
- src/utils/NucleicAcidSearchEngine.cpp
- Allow negative values for parameter "precursor:isotopes" (see issue #4168)
- Take precursor intensities into account when estimating target RTs for label-free quantification (see parameter "lfq_out") - this improves feature detection using FeatureFinderMetaboIdent
- Add log messages with number of identified spectra (before/after FDR filtering)
> NucleicAcidSearchEngine improvements

- src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPAS-resources/TOPPAS.plist.in
- src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView-resources/TOPPView.plist.in
Apps TOPPView and TOPPAS will be started in "aqua/light" mode instead of dark mode independent of system settings (MacOS).
I think if we want to support dark more work has to go into optimization - see #3785
> [FIX] Temporarily opt-out from dark mode feature (MacOS)

- src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandler.h
- src/openms/include/OpenMS/FORMAT/OPTIONS/PeakFileOptions.h
- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
- src/openms/source/FORMAT/OPTIONS/PeakFileOptions.cpp
- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
- src/tests/class_tests/openms/source/MzMLFile_test.cpp
- src/tests/topp/FileConverter_8_output.mzData
- src/tests/topp/FileMerger_10_output.mzML
- src/tests/topp/FileMerger_6_output.mzML
This addresses issue #4168 using the approach mentioned here: https://github.com/OpenMS/OpenMS/issues/4168#issuecomment-508520131
What remains is checking for the meta value "isolation window target m/z" in the isolation window visualisation code for TOPPView. Can anyone point me to where this should be changed?
> Improve handling of precursor m/z when reading/writing mzML

- src/openms/include/OpenMS/FORMAT/MzTab.h
- src/openms/source/FORMAT/MzTab.cpp
- src/openms/source/FORMAT/MzTabFile.cpp
- src/topp/MzTabExporter.cpp
- src/topp/ProteinQuantifier.cpp
- src/utils/ProteomicsLFQ.cpp
- When consensusXML is merged rowwise instead of colwise, files in the
ID structures might not exist in the quant structures anymore. Throw
better error.
- Allow first_run_inference_only also for consensusID and make it an
advanced flag for the manual export in MzTabExporter
- Make mzTab the default file suffix in ProteinQuantifier mzTab output.
Nonetheless allow tsv when storing mzTab files.
Signed-off-by: Julianus Pfeuffer <jpfeuffer@fu-berlin.de>
> Fixes bugs encountered in a full TMT pipeline:

- src/openms/source/ANALYSIS/ID/BayesianProteinInferenceAlgorithm.cpp
fixes a small bug where BayesianProteinInferenceAlgorithm.cpp will re-compile every time a git commit is made (due to a change in `openms_package_version.h`. Instead it now uses `VersionInfo::getVersion()` -> much faster compile time. (Also, BayesianProteinInferenceAlgorithm takes really long to compile probably due to all the templates).
> [FIX] use VersionInfo instead of Macro

- src/openms/source/KERNEL/MSSpectrum.cpp
- src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
I noticed a significant delay with my data when loading them in TOPPView and then opening the 1D view, I found that we are sorting all spectra when adding a new layer. This seems like redundant work and adds a noticeable delay. I wonder
- can we sort the spectra while reading them from mzML (using parallel OpenMP here)?
- can we sort them before display, so only sort those we need (instead of all)?
- can we sort them only once instead of each time they are used for a new layer (maybe keep a flag)?
PS: do not merge this
> Q: Why are we sorting all spectra in TOPPView?

- src/utils/AssayGeneratorMetabo.cpp
Compare input with PrimaryMSRunPath and introduce warning instead of an error.
see #4239
> [FIX] AGM Warning PrimaryMSRunPath

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
- src/utils/ProteomicsLFQ.cpp
> [FIX] only write protein ids once in assay generation. remove decoys

- doc/OpenMS_tutorial/refman_overwrite.tex.in
- doc/TOPP_tutorial/TOPP_scripting.doxygen
- doc/TOPP_tutorial/refman_overwrite.tex.in
fixes a bug in doxygen 1.8.13 which
when using 'colspan' in HTML. 
E.g.
`<TH colspan="2"> ...` will yield
```
l.173 \end{longtabu}
? 
! Emergency stop.
\multispan ->\omit 
\@multispan 
l.173 \end{longtabu}
```
Doxygen 1.8.16 does not seem to have this problem but break at another point:
```
! Undefined control sequence.
\DoxyCode ...}{0ex plus 0ex minus 0ex}\ifthenelse 
{\equal {#1}{0}} { {\lccod...
l.411 \begin{DoxyCodeInclude}{0}
```
fixed in 55e2ccc
> Fix broken PDF creation

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
- src/utils/ProteomicsLFQ.cpp
this reduces the featureXML produced (debug output) by about 10x, from > 250 MB to less than 25 MB and allows me to run iPRG 2015 study with about 2GB of system memory (measurement currently ongoing).
> [FEATURE] some memory fixes for ProteomicsLFQ

- src/utils/MetaboliteAdductDecharger.cpp
Minor fix. 
A lot of metabolomics workflows use the featureXML output of the MetaboliteAdductDecharger, but an output folder has to be specified every time since the consensusXML output was mandatory. 
-> set all outputs to optional.
> [FIX] MAD set primary output optional

- cmake/build_system_macros.cmake
- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/FeatureGroupingAlgorithm.h
- src/openms/include/OpenMS/KERNEL/BaseFeature.h
- src/openms/source/ANALYSIS/MAPMATCHING/FeatureGroupingAlgorithm.cpp
- src/openms/source/ANALYSIS/MAPMATCHING/FeatureGroupingAlgorithmKD.cpp
- src/openms/source/ANALYSIS/MAPMATCHING/FeatureGroupingAlgorithmQT.cpp
- src/openms/source/ANALYSIS/MAPMATCHING/FeatureGroupingAlgorithmUnlabeled.cpp
- src/openms/source/ANALYSIS/MAPMATCHING/StablePairFinder.cpp
- src/openms/source/KERNEL/BaseFeature.cpp
- src/openms/source/KERNEL/ConsensusFeature.cpp
- src/tests/topp/FeatureLinkerUnlabeledKD_1_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeledKD_2_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeledKD_3_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeledQT_1_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeledQT_2_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeledQT_3_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeledQT_4_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeled_1_output.consensusXML
- src/tests/topp/FeatureLinkerUnlabeled_4_output.consensusXML
- src/tests/topp/FileConverter_14_output.consensusXML
- src/tests/topp/ProteomicsLFQ_1_out.consensusXML
- src/topp/FeatureLinkerBase.cpp
- src/topp/FeatureLinkerUnlabeled.cpp
- src/topp/FileConverter.cpp
and fix indices for assigned PepIDs when linking consensusMaps.
Signed-off-by: Julianus Pfeuffer <jpfeuffer@fu-berlin.de>
> [FIX] Add map_index for Unassigned PeptideIdentifications for linking

- src/openms/include/OpenMS/CHEMISTRY/EmpiricalFormula.h
- src/openswathalgo/include/OpenMS/OPENSWATHALGO/DATAACCESS/ITransition.h
- src/openswathalgo/include/OpenMS/OPENSWATHALGO/DATAACCESS/MockObjects.h
- src/openswathalgo/source/OPENSWATHALGO/DATAACCESS/MockObjects.cpp
- src/tests/class_tests/openms/source/CrossLinksDB_test.cpp
- src/tests/class_tests/openms/source/ModificationsDB_test.cpp
In VS2019 the standard libraries were refactored to not define std::string, which led to some compilation errors where string wasn't explicitly included. A comparison operator in two of the tests also needed to be defined const.
> Minor changes to allow compiling with Visual Studio 2019

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp
fixes bug when running a TOPP tool from TOPPView and the current temporary path contains spaces 
(which yields a message box saying that the TOPP tool could not be executed (when writing the default ini file)
fixes  #4164
> [FIX] TOPPView when running TOPP tool 

- src/openms/include/OpenMS/DATASTRUCTURES/String.h
- src/openms/include/OpenMS/FORMAT/SqliteConnector.h
- src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPFile.cpp
- src/openms/source/DATASTRUCTURES/String.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLSqliteHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLSqliteSwathHandler.cpp
- src/openms/source/FORMAT/OSWFile.cpp
- src/openms/source/FORMAT/SqliteConnector.cpp
- src/tests/class_tests/openms/source/String_test.cpp
Three main things:
1. Changed name of function `executePreparedStatement` to `prepareStatement`, because (in contrast to the other `execute...` functions) it doesn't actually run the statement against the database. I think that's quite an important distinction that should be reflected in the name.
2. Added a constructor from `unsigned char*` to String to simplify reading text results from SQLite.
3. Simplified the implementation of the `tableExists` function.
> Improvements to SqliteConnector

- src/openms/include/OpenMS/METADATA/CVTerm.h
- src/openms/include/OpenMS/METADATA/ID/ScoreType.h
- src/openms/source/ANALYSIS/ID/FalseDiscoveryRate.cpp
- src/openms/source/METADATA/ID/IdentificationData.cpp
- src/openms/source/METADATA/ID/IdentificationDataConverter.cpp
- src/tests/topp/NucleicAcidSearchEngine_11_out.idXML
- src/tests/topp/NucleicAcidSearchEngine_12_out.mzTab
A score type (e.g. from a database search engine) is identified by a CV term, which includes a name field. For simplicity, just use that field even if there's no full CV term for a score type, only a name.
Also clean up some whitespace issues in "CVTerm.h".
> Remove redundant field from IdentificationData::ScoreType

- src/openms/include/OpenMS/METADATA/ID/IdentificationDataConverter.h
- src/openms/include/OpenMS/METADATA/ProteinIdentification.h
- src/openms/source/ANALYSIS/ID/ConsensusMapMergerAlgorithm.cpp
- src/openms/source/KERNEL/MSExperiment.cpp
- src/openms/source/METADATA/ID/IdentificationDataConverter.cpp
- src/openms/source/METADATA/ProteinIdentification.cpp
- src/pyOpenMS/pxds/ProteinIdentification.pxd
- src/tests/topp/NucleicAcidSearchEngine_11_out.idXML
- src/tests/topp/OpenPepXLLF_output.idXML
- src/tests/topp/OpenPepXLLF_output2.idXML
- src/tests/topp/SimpleSearchEngine_1_out.idXML
- src/tests/topp/THIRDPARTY/MyriMatchAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/XTandemAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/XTandemAdapter_2_out.idXML
- src/utils/NucleicAcidSearchEngine.cpp
These changes unify the handling of primary MS run information in class `ProteinIdentification` and extend it to support keeping track of raw files (in addition to mzMLs).
This also avoids the warning in NucleicAcidSearchEngine mentioned in #4332.
> Support for raw files as primary MS runs (solves #4332)

- share/OpenMS/CHEMISTRY/Enzymes.xml
- src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h
- src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
- src/openms/source/FORMAT/MSPFile.cpp
- src/tests/class_tests/openms/data/PepXMLFile_test_out.pepxml
- src/tests/class_tests/openms/data/PepXMLFile_test_out_1.pepxml
- src/tests/class_tests/openms/data/PepXMLFile_test_out_mzML.pepxml
- src/tests/class_tests/openms/source/OPXLHelper_test.cpp
- src/tests/class_tests/openms/source/ProteaseDB_test.cpp
- src/tests/class_tests/openms/source/ProteaseDigestion_test.cpp
- src/tests/topp/PeptideIndexer_7_out.idXML
this PR fixes two issues:
1) removing restriction on x!tandem special cutting rule: cutting sites are now also valid in semi-specific and unspecific digest settings, since peptides like
D.PTDDIYNRQDFGWSFAGYGAPIMEDD.P would otherwise not be found in semi-tryptic (since both ends require the special cutting rule).
2) our regular expressions for all enzymes do not consider ambiguous amino acids (B, Z, J and X), thus a peptide
`K.ACDX.A` would not be considered fully tryptic (since the `X` at the c-term is not recognized as `K|R`).
This PR fixes all the regexes.
> PeptideIndexer does not match all peptides to DB

- src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp
- src/openms/source/CHEMISTRY/SimpleTSGXLMS.cpp
- src/openms/source/CHEMISTRY/TheoreticalSpectrumGeneratorXLMS.cpp
- src/tests/class_tests/openms/source/SimpleTSGXLMS_test.cpp
- src/tests/class_tests/openms/source/TheoreticalSpectrumGeneratorXLMS_test.cpp
- src/tests/topp/OpenPepXLLF_output2.idXML
1. Fixed theoretical fragmentation of Residue-Linked fragment type (a rare fragment that occurs at most twice per spectrum)
2. Avoid cross-linking residues that are already modified in the linear peptide database
> [FIX] fixed two minor issues in OpenPepXL

- src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp
- src/tests/topp/OpenPepXLLF_output2.idXML
- src/topp/OpenPepXL.cpp
- src/topp/OpenPepXLLF.cpp
1. Filtering out a few types of loop-linked candidates: A cross-link between two residues on the same peptide leads to fragmentation that leaves the peptide precursor mass intact most of the time. Only the residues before the first link position and after the second link position can really be sequenced. The change will enforce to have at least 3 residues on each side, making the minimal number of sequenceable residues 6 for this case. We also want to avoid cross-links between neighboring residues, since they are unlikely and practically useless.
2. Changing the order of output file formats: The order and descriptions are more in line with XFDR now and the new order reflects the likely usage of the output formats much better with idXML at the top. This will also make it more obvious that …
> [FEATURE] two fixes for the OpenPepXL pipeline

- src/tests/topp/THIRDPARTY/third_party_tests.cmake
because the -min_precursor_charge 4 -max_precursor_charge 3 parameters
do not exist it seems not useful to test for them to fail
> remove 1 myrimatchadapter test

- src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
- src/openms/source/APPLICATIONS/TOPPBase.cpp
- src/topp/InternalCalibration.cpp
- src/utils/MetaProSIP.cpp
- src/utils/NucleicAcidSearchEngine.cpp
augments #4381
fix behaviour of TOPPBase InputFile tags ('is_executable' and 'skipexists').
They are checked now more frequently, i.e. if the value is required or non-empty.
The checks happens when `getStringOption_()` is called.
> Opt include

- src/pyOpenMS/create_cpp_extension.py
This fixes https://github.com/OpenMS/OpenMS/issues/4229 by explicitly specifying the use of language_level=2.
> [fix] explicitly pass language_level=2 to autowrap, fixing issues with compilation

- src/utils/TICCalculator.cpp
this fixes #4389 (confirmed and fixed on VS2015).
by replacing the `omp critical` with `reduction(+,...`.
ATM I have **no** idea why the critical solution was broken.
The current solution works, as well as switching to `std::atomic` for TIC and nr_peaks.
Still puzzled why critical section breaks (since the final sums are lower, it seems that the addition is not atomic).
Somewhat confirming that this might be a VS bug: g++7.1 does not need this fix. It works as expected in both variants.
> fix TICCalculator

- src/openms/source/SYSTEM/File.cpp
> [FIX] findExecutable should skip directories in Env with same name

- cmake/compiler_flags.cmake
The conda builds with clang are almost impossible to read.
It is actually not even recommended by the clang developers.
https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything/
> Default from -Weverything to -Wall and -Wextra

- src/openms/include/OpenMS/ANALYSIS/ID/AScore.h
- src/openms/source/ANALYSIS/ID/AScore.cpp
- src/tests/class_tests/openms/source/AScore_test.cpp
This PR addresses #4358 and changes some scoring constants within the AScore class to help it fall more in line with Beausoleil et al. 
**Weighted average:**  
Within the weighted average step of the PepScore calculation, the algorithm was dividing by the wrong constant to make the dot product a weighted average at original line 396. I fixed this to be the true constant and added a couple tests to prove that this is a weighted average.
**Match Probability:**  
The interpretation I always had of Beausoleil et al. was that the probability of a match that you use for calculating the PepScore and AScore is based on the window size for matching. For mass units in mz, I made the probability based on 2 times the mass window. When the mass units are in ppm, the issue for this algorithm is that …
> Fix AScore Scoring

- src/openms/include/OpenMS/FORMAT/HANDLERS/MzXMLHandler.h
- src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp
minor fix which is required by MaxQuant when reading our mzXML:
activationMethod must be present in the xml file, e.g.
```
<precursorMz ... activationMethod="CID" >368.221862792969</precursorMz>
```
We wrote it out before, but when converting from mzXML to mzXML within OpenMS' Fileconverter we did not actually parse activationMethod, hence it was missing in the output.
(this bug can be circumvented when using mzML as an intermediate format).
> add activationMethod to Precursor when reading mzXML

- src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp
When updating conda packages and being forced to use LLVM clang and C17,
I had to fix the following.
Not sure why it ever worked. Previous typedef was not in the standard.
> [FIX] Clang and C17 stream_pos

- src/openms/source/ANALYSIS/XLMS/OpenPepXLAlgorithm.cpp
- src/openms/source/ANALYSIS/XLMS/OpenPepXLLFAlgorithm.cpp
The deisotoping and filtering of spectra is done in parallel and the spectra are collected out of order in a new map.
This will not affect the final results, but will make the process itself more reproducible and easier to compare between runs.
Without this the MS2 spectra might be analyzed in a different order every time, even with exactly the same inputs, and that might make it more difficult to identify problems in the future.
> [FIX] OpenPepXL: sort spectra by RT after parallel preprocessing

- src/topp/FileMerger.cpp
Currently merging works for fasta only if the outfile is named .tmp. 
Documentation on the possible combinations of input types and output types would be nice. I would need help for this.
> FileMerger: allow fasta output

- src/openms/source/ANALYSIS/DECHARGING/FeatureDeconvolution.cpp
- src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp
fixes #4439 (probably at least part of it)
> [FIX] make decharger safe for eval order of string manip. stmts

- src/openms/include/OpenMS/FORMAT/FileTypes.h
- src/openms/source/FORMAT/FileHandler.cpp
- src/openms/source/FORMAT/FileTypes.cpp
- src/topp/OpenPepXL.cpp
- src/topp/OpenPepXLLF.cpp
since https://github.com/OpenMS/OpenMS/blob/c19b545636e76a5770f095f944e0b196b9b56c82/src/openms/source/FORMAT/XQuestResultXMLFile.cpp#L97 will raise an error when a .xml file is given.
I suggest to remove xml also for spec.xml
> OpenPepXL, OpenPepXLLF: remove xml from valid extensions

- src/utils/MetaboliteSpectralMatcher.cpp
since the file is not included in the distribution
I guess its better to make the argument mandatory
see https://github.com/OpenMS/OpenMS/issues/2078
if at some point the data is available somewhere
(internet, submodule, ...) then it might be better
to have this info in the description?
> MetaboliteSpectralMatcher: make database mandatory

- src/openms/source/FILTERING/DATAREDUCTION/ElutionPeakDetection.cpp
according to the discussion in https://github.com/OpenMS/OpenMS/issues/2350
this should be represented by the restrictions being true,false
Would be nice to have a method to check if there are more such cases.
> masstrace_snr_filtering: is flag

- src/openms/include/OpenMS/CHEMISTRY/ModificationsDB.h
- src/openms/source/CHEMISTRY/ModificationsDB.cpp
- src/topp/OpenSwathAssayGenerator.cpp
this is a substantial improvement for performance on my machine, almost 100x fold for `static ModificationsDB* getInstance`. Basically on my Linux system the time before the fix was almost 100 ns and now is around 1-2ns -- it turns out this matters because people assumed `ModificationsDB::getInstance` is basically free and its all over the place. 
I am not sure why that is the case, there are no such issues with other singletons. It may be because of the default function arguments.
> ModificationsDB::getInstance performance fix

- src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
using the mzIdentMLValidator_GUI_v1.4.35 at
https://github.com/HUPO-PSI/mzIdentML/blob/master/validator/mzIdentMLValidator_GUI_v1.4.35-SNAPSHOT.zip
I got this error from semantic validation:
```
Message 1:
Rule ID: PeptideEvidenceObjectRule
Level: ERROR
Context(/MzIdentML/SequenceCollection/PeptideEvidence )
--> The PeptideEvidence (id='PEV_4952186547965636686') element at /MzIdentML/SequenceCollection/PeptideEvidence has wrong start and end attributes set (start must be >= 1 and end >=start, but < length of the protein sequence.
Tip: <PeptideEvidence> elements must have correct start and end attributes set, unless it's a de novo search.
```
because our internal Peptide Evidence starts at 0 and it looks like the mzid standard expects the indices to start at 1. Our files had 0s at start …
> [FIX] making MzIdentML pass through the validator

- share/OpenMS/SCRIPTS/InternalCalibration_Residuals.R
- src/openms/source/FORMAT/FeatureXMLFile.cpp
- src/openms/source/QC/MzCalibration.cpp
- src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.cpp
- src/tests/class_tests/openms/source/MzCalibration_test.cpp
- src/topp/PeakPickerHiRes.cpp
PP-HiRes now gives the user some feedback of which MS-levels were actually picked in `auto-mode`.
```
11:10:22 NOTICE: PeakPickerHiRes of node #4 started. Processing ...
Picked spectra by MS-level:
MS-level 1: 8259 / 8259
MS-level 2: 0 / 7482
```
> some minor fixes

- src/topp/MaRaClusterAdapter.cpp
This PR provides the option to keep the MaRacluster original output stored in a temp directory in a designated output directory.
> MaRaCluster: keep original output in temp directory

- .gitignore
- src/openms/include/OpenMS/METADATA/ProteinIdentification.h
- src/openms/source/ANALYSIS/ID/ConsensusMapMergerAlgorithm.cpp
- src/openms/source/ANALYSIS/ID/IDMergerAlgorithm.cpp
- src/openms/source/METADATA/ProteinIdentification.cpp
- src/tests/class_tests/openms/data/newIDMergerTest1.idXML
- src/tests/class_tests/openms/source/IDMergerAlgorithm_test.cpp
some workflow engine might symlink or copy databases around.
Better to just check the basename during merging.
> [Fix] check only db filename during merge

- src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
This fixes a TOPPView crash caused by accumulating DataLayers from theoretical spectra in IDView.
The parameter `caption` in `addData()` is not used as the layer name. The `filename` parameter is used for that and was set as an empty string. The removal of these temporary layers relies on using the caption as the layer name (to identify them as temporary layers), so they were not removed and caused several problems.
After adding exactly 10 layers TOPPView just crashes for some reason.
Now the `layer_caption` of the theoretical spectra is also used as the filename and the layers are removed correctly. This makes the IDView for normal proteomics data usable again.
Tested on Linux and Windows.
> [GUI,FIX] removal of temporary theoretical spectrum layers

- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
The `precursor error (|ppm|)` column in TOPPView IdentificationView is read from a MetaValue if it is available. For some reason it was always read from the first PeptideHit of the spectrum. This fixes this and shows the correct number for each PeptideHit.
> [GUI,FIX] precalculated ppm errors were always read from the first PeptideHit

- doc/doxygen/public/TOPP.doxygen
- src/topp/MapAlignerTreeGuided.cpp
adds MapAlignerTreeGuided to TOPP docu
@timosachsenberg  @jpfeuffer  any idea why our `\f$ \longrightarrow \f$` are shown as unrelated formula `1 + 10^-5` in our docs currently?
e.g. https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/a16150.html
> fix docu for MapAlignerTreeGuided

- src/openms/include/OpenMS/FORMAT/SVOutStream.h
- src/tests/class_tests/openms/source/SVOutStream_test.cpp
- src/tests/class_tests/openms/source/String_test.cpp
- src/topp/TextExporter.cpp
fixes #4518 
by using StringConversion mechanisms of Boost::Karma from @cbielow for all doubles.
Note that mzTab converts all floats to doubles and therefore will have different precision
for intensity until we change the behaviour of the mzTab writer.
I showed that behaviour in a new String_test, to show that this is currently intended.
> [Fix] precision text vs mz tab

- src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
- src/topp/FeatureFinderMetabo.cpp
Resolves the error `FF-Metabo: Internal error. The number of features 1214 and chromatograms 1218 are different! Aborting.` by only using chromatograms with a feature intensity != 0.
> FFM resolve discrepancy of number of features and chromatograms

- src/openms/source/ANALYSIS/OPENSWATH/PeakPickerMRM.cpp
- src/openms/source/FORMAT/ControlledVocabulary.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLHandlerHelper.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/FileConverter_32_input.mzML
- src/tests/topp/FileConverter_32_output.mzML
a couple of features:
- Keep the name of float data arrays (instead of deleting them)
- fix check for numerical value for data arrays (relates to content of array)
- store unit metadata for float data array descriptor
- add test for all of this
this is a partial PR based on #4436
> Store name of float data arrays and unit names

- src/openms/source/APPLICATIONS/TOPPBase.cpp
Happens already here https://github.com/OpenMS/OpenMS/blob/ca57038b730ba5995662476e64b4019130cc024e/src/openms/source/APPLICATIONS/TOPPBase.cpp#L1296
replaces https://github.com/OpenMS/OpenMS/pull/4526https://github.com/OpenMS/OpenMS/pull/4526
> Check only 1x if output file can be written

- src/utils/NovorAdapter.cpp
It apparently does in the test, but now also the help is consistent (seems that Novor is the only tool that uses mzml instead of mzML)
> Let NovorAdapter also use mzML

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.h
- src/openms/source/APPLICATIONS/TOPPBase.cpp
- src/tests/class_tests/openms/data/TOPPBase_test_write_ini_out.ini
- src/tests/class_tests/openms/data/TOPPBase_test_write_ini_subsec_out.ini
- src/tests/topp/CMakeLists.txt
- src/tests/topp/INIUpdater_1_noupdate.toppas
- src/tests/topp/INIUpdater_3_old_out.toppas
- src/tests/topp/MapAlignerIdentification_7_input1.idXML
- src/tests/topp/MapAlignerIdentification_7_input2.idXML
- src/tests/topp/MapAlignerIdentification_7_output2.trafoXML
- src/tests/topp/WRITE_INI_OUT.ini
- src/topp/MapAlignerIdentification.cpp
As requested by @timosachsenberg. When the "force" flag is set, MapAlignerIdentification will now finish by applying the "identity" transformation (i.e. no change to RTs) when there isn't enough suitable RT data to calculate an alignment. Previously (and still without "-force") it would fail with an error.
I think not having the expected data is actually an error condition, hence the requirement to use "-force".
> MapAlignerIdentification: option to use "identity" transformation when data is missing

- src/pyOpenMS/CMakeLists.txt
PyPI push not working due to unresolved variable ("OPENMS_GIT_LC_DATE").
Uploading pyopenms_nightly-2.6.0.devOPENMS_GIT_LC_DATE-cp35-cp35m-manylinux2014_x86_64.whl
> [FIX] pyopenms-nightly - variable for push 

- src/topp/ProteinQuantifier.cpp
Kind of an amendment to my last PR #4630
> [FIX] Correctly use inference run for mztab export in proteinquantifier

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmPicked.cpp
Worked once more at FeatureFinderCentroided. 
As the main runtime goes into `run()`, I focused on that. For exact changes look into the single commits. I think they explain quiet good, what happened.
As a result the runtime reduced from `1:21:54`  to `1:07:29` (Wall)
I compared the output file from the "develop"-Branch and from my "ffc-testzone"-Featurebranch with FuzzyFinder. For some reason the representation of the intensities changed in the output. This lead to some decimal points being cut off and to a slightly changed output:
```
PASSED.
relative_max:        1
relative_acceptable: 1
absolute_max:        0.009062
absolute_acceptable: 0.01
whitelist cases:
"completion_time"      1x
"feature id"         70791x
"featureMap version"   1x
"parameter"            1x
"software name" …
```
> [Feature] FFC/FeatureFinderAlgorithmPicked speedup

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFilter.h
Clash on Windows (and only Win) with forward declared struct for a later declared class when building an external application that calls OpenMS.
> fix: struct vs class

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmTreeGuided.h
- src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmTreeGuided.cpp
- src/tests/class_tests/openms/source/MapAlignmentAlgorithmTreeGuided_test.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/MapAlignerTreeGuided_parameters2.ini
- src/topp/MapAlignerTreeGuided.cpp
Because the alignment of large data sets can lead to an out of memory problem, I have changed the following:
1. internally the growing FeatureMap is no longer copied. Instead, all maps that are no longer needed are deleted from the temporary vector.
2. the user of the TOPP tool is given the option to choose whether the input data is copied or loaded twice during the alignment.
> MapAlignerTreeGuided: Better memory usage and new option

- doc/doxygen/install/install-win.doxygen
While building OpenMS on my Windows I chose to build QT from source. I discovered that the build directory will be located in a different folder (in comparison to using the QT-installer). 
- added a note and an example for this
- some minor other fixes
> Update of the Windows building guide

- src/openms/include/OpenMS/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.h
I wasn't able to pass a const IsotopeDistribution& to functions and read their peaks because the only operator[] was non-const. This adds the missing const operator[] to IsotopeDistribution.
> Add a missing const operator[] for IsotopeDistribution

- src/openms/source/MATH/MISC/EmgGradientDescent.cpp
There is an edge case in the calculation of the derivatives where no data points are found that are below the intensity threshold for calculating the derivatives.  This results in an attempt to access a location in a vector that is less than 0.
Added a check for the edge case where there would be an attempt to access a vector index of less than 0.
> fix: vector out of bounds in EMG derivative calculations

- src/openms/source/DATASTRUCTURES/QTCluster.cpp
- src/tests/class_tests/openms/source/QTClusterFinder_test.cpp
The reason for the failed test (`OPENMS_PRECONDITION`) was the follwing:
The `tmp_element_mapping` of the `QTCluster` class used to be a pointer to a map. When we implemented the hot-cold-splitting we decided that two indirections were unnecessary. We also wanted to increase the code quality by removing some `new`s and `delete`s. We then changed the `tmp_element_mapping` to be just a map inside the `BulkData` class.
In the preconditions there were a lot of checks whether `tmp_element_mapping` is or isn't a nullptr. This was the case whenever the cluster was in a finalized state (nullptr) or not (pointer to map). We changed these checks to ask whether it is empty (finalized) or not (not finalized). This does not work, because the `tmp_element_mapping` can be empty during a finalized state …
> Hotfix PRECONDITION after optimization for QTCluster

- src/openms/include/OpenMS/CONCEPT/Constants.h
- src/openms/include/OpenMS/KERNEL/ChromatogramPeak.h
- src/openms/include/OpenMS/KERNEL/MSChromatogram.h
- src/openms/source/CONCEPT/Constants.cpp
- src/openms/source/KERNEL/MSChromatogram.cpp
- src/tests/class_tests/openms/source/MSChromatogram_test.cpp
Added utility function MSChromatogram to allow merging the ChromatogramPeaks from two MSChromatograms. Function is useful for summing intensity of multiple isotope traces in an isotopic envelope.
> Cherry-picked commits for feature

- src/openms/include/OpenMS/CHEMISTRY/ResidueModification.h
- src/openms/include/OpenMS/FORMAT/PepXMLFile.h
- src/openms/source/CHEMISTRY/AASequence.cpp
- src/openms/source/CHEMISTRY/ResidueModification.cpp
- src/openms/source/FORMAT/PepXMLFile.cpp
- src/tests/topp/IDFileConverter_24_input.pep.xml
- src/tests/topp/IDFileConverter_24_output.idXML
AKA Avoid putting terminal modifications to internal AAs when reading pepXML. Instead put them as unknown delta_mass.
Also parses decoys from comet search. (Note: this is not well-tested with downstream tools).
Should fix #4751 though
Limitations: 
1) pepXML only encodes the location of the peptide in the first protein
2) depending on the settings, comet might not report all parent proteins
3) only works for decoys from comet, not pepxml in general
> [FIX] Comet pepXML modification parsing

- src/openms/include/OpenMS/FORMAT/MSstatsFile.h
This fix resolves the issue with skipped channels in the MSstatsConverter.
Thanks at @timosachsenberg and @jpfeuffer.
> FIX: MSstatsTMTline_ bool operator

- src/openms/source/ANALYSIS/ID/IDBoostGraph.cpp
Was not cleared correctly and sometimes led to type mismatch during get.
> [FIX] bug introduced when trying to reuse vector

- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
- src/tests/topp/CMakeLists.txt
Fixes 
```
unable to read file (<filename) ProteinIdentifications are not unique, which leads to loss of unique peptide assignment. Duplicated Protein-Id is: unique_run_identifier.
```
when adding the "candidates_out" option and chunking.
> [FIX] colliding ProteinIDRun  IDs

- src/tests/topp/ConsensusID_7_output.idXML
- src/topp/ConsensusID.cpp
Important for enzyme when you want to use the new PeptideIndexer auto-detection
> [FIX] Add rest of search params during ConsensusID

- src/tests/topp/ConsensusID_7_output.idXML
- src/topp/ConsensusID.cpp
In the case of a search engine overwritten from Percolator, it read and wrote the wrong meta values (at the ProteinID, not the SearchParams)
> [FIX] ConsenusID reading from wrong meta data

- src/openms_gui/source/VISUAL/Spectrum2DWidget.cpp
Switched the "m/z" and "RT" labels in `Spectrum1DCanvas.cpp`
This fixes the wrong labels in the projections as reported in #4828.
Previously `projection_horz_->canvas()->setSwappedAxis(true)` and `projection_vert_->canvas()->setSwappedAxis(true)` were always set. This caused the labels to be constant and independent from the orientation of the axes in the main MS1 map.
Now I set these both to `false` for one of the cases and the labels adapt to the MS1 map orientation correctly.
> [FIX, GUI] fixes OpenMS#4828, wrong labels in the projections

- src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h
- src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
- src/topp/PeptideIndexer.cpp
* make 'auto' mode for enzyme choice and specificity more explicit (`auto` instead of empty string)
* some doc fixes
> PeptideIndexer explicit 'auto' mode

- src/utils/PSMFeatureExtractor.cpp
The PR is adding a warning about the use of an idXML resulting from multiple merged runs. One should use the Flag merge_proteins_add_psms.
#4825 
Not tested yet, will check once more before merging
> Warn about multiple runs when using PSMFeatureExtractor

- src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
- src/tests/topp/CMakeLists.txt
- src/tests/topp/IDFileConverter_31_input.mzid
- src/tests/topp/IDFileConverter_31_output.idXML
This PR addresses #4607.
When writing an mzid that from PeptideHits that use a score that does not have a CV-term,
we add this CV-term without a value instead:
`<cvParam accession="MS:1001143" cvRef="PSI-MS" name="PSM-level search engine specific statistic"/>`
and then add the score as a `userParam`.
This will technically make an invalid mzid, but at least it still contains all the data. Previously this type of mzid could also not be parsed by OpenMS. The cvParam without a value caused an error.
This PR fixes the parsing somewhat. It generates PeptideHits with a score of 0.0 and the score type
`PSM-level search engine specific statistic`. The actual score is (most likely) automatically stored as a metaValue, like all other mzid userParams.
This way the mzid can be converted into an …
> [FIX] parsing mzid with nonstandard, non-CV-term scores, fixes #4607

- src/topp/OpenPepXL.cpp
- src/topp/OpenPepXLLF.cpp
- src/topp/PeptideIndexer.cpp
The OpenPepXL, OpenPepXLLF and PeptideIndexer tools pass all input parameters on to their algorithm classes.
This includes the TOPPBase parameters like `threads` and `test` as well as inout and output file parameters. The algorithm classes don't know about these parameters and a warning about unknown or deprecated parameters is thrown when `debug != 0`.
This PR is a simple workaround that removes those unknown parameters from the `Param` object that is passed to the algorithm.
This method is already used in e.g. `FeatureFinderMultiplex`.
The better option (at least for new tools) would be to add a node to the parameters for each tool that includes all parameters needed for the respective algorithm class, but that would add prefixes to most of their parameters and break all existing `.ini` …
> [FIX] suppress misleading warning messages about unknown parameters

- src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML
- src/topp/MSGFPlusAdapter.cpp
Otherwise downstream tools get confused by the slight differences between Trypsin and Trpysin/P
> [FIX] Let MSGFAdapter overwrite the enzyme from mzid w/ our nomenclature

- src/openms/source/ANALYSIS/ID/IDMergerAlgorithm.cpp
- src/tests/topp/ConsensusID_7_output.idXML
- src/topp/CometAdapter.cpp
- src/topp/ConsensusID.cpp
Important to have the same settings outcome, when executing ConsID on files in a different order. Before it was just taking first, now it takes the loosest settings.
Also please:
> [FEATURE] combine SE settings during ConsensusID (instead of taking 1st)

- src/topp/MRMMapper.cpp
- src/topp/OpenSwathAnalyzer.cpp
- src/utils/OpenSwathDIAPreScoring.cpp
- src/utils/SemanticValidator.cpp
- src/utils/XMLValidator.cpp
becomes anoying for autoconverters
seemingly traML is less common so I went for the majority
Seems that there are still some places left...
Also please:
> start to unify traML vs TraML

- src/openms/include/OpenMS/SYSTEM/StopWatch.h
- src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmSpectrumAlignment.cpp
- src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPFile.cpp
- src/openms/source/SYSTEM/StopWatch.cpp
- src/tests/class_tests/openms/source/StopWatch_test.cpp
- src/utils/RNPxlSearch.cpp
Cleans up the implementation and fixes a bug (querying a stopwatch without stop() would yield arbitrary numbers -- at least on Windows)
Also allows to `start()` ... `stop()` `<do not time this>` `resume()`  to allow for more fine-grained measurements (e.g. benchmarking).
It also prevents accidental wrong usage (e.g. stop()'ing twice) by throwing exceptions.
> re-implement StopWatch to allow for 'resume()' and querying time while still running

- src/pyOpenMS/addons/ConvexHull2D.pyx
- src/pyOpenMS/addons/MapAlignmentAlgorithmIdentification.pyx
We currently cannot use the addon functions of ConvexHull2D.pyx and MapAlignmentAlgorithmIdentification.pyx. In the pxd files, these functions are declared without "#wrap-ignore" declarative and hence are wrapped by autowrap. The overloaded definitions in addons for these functions seem to be ignored by cython.
Thus, changing the name of these functions is one viable solution for exposing these in pyopenms and eventually the R bindings.
Also please:
> Addon changes for pyopenms

- src/openms/include/OpenMS/FORMAT/IdXMLFile.h
document that ranks are not stored in idXML files.
Also please:
> [DOC] document that ranks are not stored

- src/openms_gui/include/OpenMS/VISUAL/SpectrumWidget.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/SpectrumWidget.cpp
White BG during 2D export in TOPPView.
Also, fixes assert errors introduced in recent TOPPView
> [FEATURE] White BG during 2D export in TOPPView.

- .github/workflows/pyopenms-wheels.yml
Cheery picked (missed in 2.6.0)
PR should fix QT import error
```
ImportError: dlopen(/usr/local/miniconda3/envs/build_pyopenms_36/lib/python3.6/site-packages/pyopenms/pyopenms_1.cpython-36m-darwin.so, 2): Library not loaded: @rpath/QtNetwork.framework/Versions/5/QtNetwork
Referenced from: /usr/local/miniconda3/envs/build_pyopenms_36/lib/python3.6/site-packages/pyopenms/libOpenMS.dylib
Reason: image not found
```
QtCore.framework
QtNetwork.framework
are missing in the pyopenms directory.
> [FIX] github actions pyopenms whl release 2.6.0 (macOS)

- tools/travis/lnx-cibuild.sh
- tools/travis/osx-cibuild.sh
Makes ctest print the tool output when a test fails.
> [CI] Add --output-on-failure to travis ctest invocations

- src/utils/OpenSwathDIAPreScoring.cpp
I think I forgot this in https://github.com/OpenMS/OpenMS/pull/4443
If not given causes a segfault because of the access to `outfile_list[i]`
Alternative would be to check before access
> make OpenSwathDIAPreScoring outputs mandatory

- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/ToolsDialog.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp
Addresses #558:
* Adds label to "Apply TOPP tool" dialog indicating the currently selected layer.
* Changes title of dialog from "TOPP tools" to "Apply TOPP tool to layer"
> ToppView: Show selected layer in Apply TOPP tool dialog (#558)

- AUTHORS
- src/openswathalgo/source/OPENSWATHALGO/ALGO/Scoring.cpp
OpenMS fails to compile with the aforementioned tools, the compiler complains about the missing header algorithm for the OpenSWATHAlgo, namely `Scoring.cpp`. The header was previously present as it's required by `std::sort`. See Issue #5020 .
The exact error is : `~\OpenMS\src\openswathalgo\source\OPENSWATHALGO\ALGO\Scoring.cpp(276,12): error C2039: 'sort': is not a member of 'std' [~\OpenMS\openms_build\src\openswathalgo\OpenSwathAlgo.vcxproj]`
- Reinstated `#include <algorithm>` in `OpenMS\src\openswathalgo\source\OPENSWATHALGO\ALGO\Scoring.cpp`.
- [x ] Make sure that you are listed in the AUTHORS file
> [FIX] Failed to compile with VS2019 MSVC 14.2

- src/openms_gui/include/OpenMS/VISUAL/LayerData.h
- src/openms_gui/include/OpenMS/VISUAL/SpectraViewWidget.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/LayerData.cpp
- src/openms_gui/source/VISUAL/Plot2DWidget.cpp
- src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
- src/openms_gui/source/VISUAL/SpectraViewWidget.cpp
- src/openms_gui/source/VISUAL/TVIdentificationViewController.cpp
- src/openms_gui/source/VISUAL/TVSpectraViewController.cpp
Some fixes, mainly for the spectra tree view widget:
- avoid useless conversion of numbers to qstring. Name roles properly.
- fix bug, which caused the LayerMenu not to refresh when clicking a single chrom transition in SpectraView
- get rid of unneeded and dangerous exposure to internal data
- allow drag'n'drop of single chromatogram data from SpecView table to new Window
- properly populate columns via enum indices (fixes wrong layout)
> Tv dia table

- src/openms/source/ANALYSIS/XLMS/OpenPepXLAlgorithm.cpp
Fixes a rare underflow error in OpenPepXL.
Same as  #5040, but for the algorithm for isotopically labeled cross-linkers.
> [FIX] rare underflow error in OpenPepXLAlgorithm

- src/openms/include/OpenMS/DATASTRUCTURES/OSWData.h
- src/openms/source/DATASTRUCTURES/OSWData.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLSqliteHandler.cpp
- src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h
- src/openms_gui/include/OpenMS/VISUAL/DIATreeTab.h
- src/openms_gui/include/OpenMS/VISUAL/LayerData.h
- src/openms_gui/include/OpenMS/VISUAL/MISC/GUIHelpers.h
- src/openms_gui/include/OpenMS/VISUAL/Plot1DCanvas.h
- src/openms_gui/include/OpenMS/VISUAL/PlotCanvas.h
- src/openms_gui/include/OpenMS/VISUAL/TVControllerBase.h
- src/openms_gui/include/OpenMS/VISUAL/TVDIATreeTabController.h
- src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/DIATreeTab.cpp
- src/openms_gui/source/VISUAL/DataSelectionTabs.cpp
- src/openms_gui/source/VISUAL/LayerData.cpp
- src/openms_gui/source/VISUAL/MISC/GUIHelpers.cpp
- src/openms_gui/source/VISUAL/Plot1DCanvas.cpp
- src/openms_gui/source/VISUAL/PlotCanvas.cpp
- src/openms_gui/source/VISUAL/TVDIATreeTabController.cpp
- src/openms_gui/source/VISUAL/TVSpectraViewController.cpp
- src/topp/FileInfo.cpp
- extend VerticalLineItem for 1D plot to show a band
- move data conversion for chomatogram to spectrum for 1D widget to a better place
- reduce redundant code (this is still not ideal)
- show the correct menu entries when chromatogram data is present
- enable double/single clicking of rows in DIA view
- show the transitions with bands marking the feature-groups
- faster sqMass reading (7%)
- allow Annotation1DVerticalItem to be a band (and actually use its color member)
- annotate OSW features using a band
- fix bug (peptides get repeatedly added when browing data)
- fix: map native IDs to chrom indices
> TOPPView DIA data browsing

- src/utils/ProteomicsLFQ.cpp
Correctly sync greedy resolution in PLFQ with quant data.
The test data did not cover this. So I think it will not fail. We need to think about a test.
> [FIX] Correctly sync greedy resolution in PLFQ with quant data

- doc/TOPP_tutorial/TOPPView_interface.doxygen
- src/openms/include/OpenMS/DATASTRUCTURES/OSWData.h
- src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h
- src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/SwathTabWidget.h
- src/openms_gui/include/OpenMS/VISUAL/DIATreeTab.h
- src/openms_gui/include/OpenMS/VISUAL/DataSelectionTabs.h
- src/openms_gui/include/OpenMS/VISUAL/LayerData.h
- src/openms_gui/include/OpenMS/VISUAL/MISC/GUIHelpers.h
- src/openms_gui/include/OpenMS/VISUAL/PlotCanvas.h
- src/openms_gui/include/OpenMS/VISUAL/SpectraIDViewTab.h
- src/openms_gui/include/OpenMS/VISUAL/SpectraTreeTab.h
- src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.cpp
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/DIALOGS/SwathTabWidget.cpp
- src/openms_gui/source/VISUAL/DIATreeTab.cpp
- src/openms_gui/source/VISUAL/DataSelectionTabs.cpp
- src/openms_gui/source/VISUAL/LayerData.cpp
- src/openms_gui/source/VISUAL/MISC/GUIHelpers.cpp
- src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
- src/openms_gui/source/VISUAL/SpectraTreeTab.cpp
- src/openms_gui/source/VISUAL/TVDIATreeTabController.cpp
- add nicer plotting to sqMass + OSW id view
- this includes a basic overlap detection algorithm which avoids overlapping text blocks
- lock TOPPView GUI when large data is loaded, so the user gets feedback why nothing is responding
- automatically select the appropriate ID tab, depending on what data is available
- support ID annotation from commandline via the new `!` operator, e.g. `TOPPView BSA.mzML ! BSA.idXML` (or for any other annotation data we support, e.g. sqMass + osw)
> TOPPView convenience (commandline, locking) and DIA plotting

- .gitignore
- src/openms/source/ANALYSIS/QUANTITATION/AbsoluteQuantitation.cpp
- src/tests/class_tests/openms/source/AbsoluteQuantitation_test.cpp
Small fix in `AbsoluteQuantitation`
- change the term that the `dilution_factor` is applied to (i.e., changed to the correct term :))
> fix: bug in AbsoluteQuantitation

- AUTHORS
- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
Added counting for the number of spectra and chromatograms that are stored by the MzMLHandler and output it to OPENMS_LOG_INFO. This closes #5061
> [Feature] Add info output to MzMLHandler store

- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/ToolsDialog.h
- src/openms_gui/source/VISUAL/DIALOGS/ToolsDialog.cpp
This PR adresses issue  ##5117. All available/compatible tools are now being detected automatically instead of being hardcoded for each layer type.
Some things still need to be fixed in my opinion but I want to discuss these changes first:
1. Generating an ini file for each tool for each file to determine with which layer types it is compatible with takes a considerable amount of time (~5 seconds). All these IO actions are quite a bottleneck. Maybe there exists a better/faster method?
2. Currently write errors in `getParamFromIni_` are caught but not properly reacted to. In case of an error the param object is still created (line 177, 182).
Note: If your PR is failing you can check out http://cdash.openms.de/index.php?project=OpenMS and look for your PR with detailed error messages.
> Automatically detected all avialable tools in ToolsDialog

- src/openms/source/FORMAT/FileHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
- src/openms/source/FORMAT/MascotGenericFile.cpp
- src/tests/topp/FileConverter_23_output.mzML
- src/tests/topp/FileConverter_28_output.mzML
- src/tests/topp/FileMerger_10_output.mzML
- src/tests/topp/FileMerger_6_output.mzML
Using FileHandler to load mzMLs with the flag for automatic filename reannotation
removed the native id format CV term. It is now preserved.
Note: If your PR is failing you can check out http://cdash.openms.de/index.php?project=OpenMS and look for your PR with detailed error messages.
> [FIX] preserve native id format in FileHandler

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathScores.h
- src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathScoring.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
- src/tests/topp/FeatureFinderIdentification_1_output.featureXML
- src/tests/topp/FeatureFinderIdentification_3_output.featureXML
See title. Let's see if we can get some speed back after activating the MS1 isotope scores.
> [FEATURE] Allow skipping MS2 isotope scores in SWATH and disable it in FFID.

- src/tests/topp/THIRDPARTY/NovorAdapter_1_out.idXML
- src/utils/NovorAdapter.cpp
NovorAdapter used to just write the scan number as a MetaValue.
Using `SpectrumLookup()` now the spectrum reference is written.
> Writting Spectrum Reference in NovorAdapter

- src/openms/source/KERNEL/MassTrace.cpp
This refers to Issue #5164
When running FeaturefinderMetabo with our data, we run into an exception, an OPENMS_PRECONDITION that is not satisfied in MassTrace::linearInterpolationAtY_:
```
OPENMS_PRECONDITION(yA < y_eval && y_eval < yB, "y_eval is not between yA and yB")
```
However, the values for yA and y_eval are equals: 284.00000000 (screenshot attached). 
The assertion passes by changing conditions to <= and everything gets executed until the end. 
On the issue discussion, it is suggested only to check yB > yA to avoid division per 0, however, this situation seems to be already handled in that method.
An even better precondition would be to test for the then needed more dangerous yB > yA so that it is not dividing by zero
we are launching FeatureFinderMetabo in a simple way: …
> Extends precondition check bounds to equality

- src/openms/source/ANALYSIS/ID/IDMapper.cpp
- src/utils/NovorAdapter.cpp
fixes #5178 
- fix NOVOR DOI
- [FIX] NOVORAdapter: also write MS2 spectra even if their metadata type is not annotated
- [FIX] NOVORAdapter: error if no MS2 spectra were passed to NOVOR
- [FEATURE] NOVORAdapter: report MS2 spectra written and annotation rate
> NOVORAdapter fixes

- tools/travis/lnx-cibuild.before.sh
Issue:
https://github.com/OpenMS/OpenMS/issues/5188
Autowrap FIX See uweschmitt/autowrap#99
Should work with python 3.6, cython 0.29.22 and autowrap 0.22.2.
> Revert changes due to cython 0.29.2

- src/openms/source/METADATA/SpectrumLookup.cpp
- src/tests/class_tests/openms/source/SpectrumLookup_test.cpp
Can not extract the scan_number based on the nativeId_accession from MS_Agilent_MassHunter_nativeID_format
> ADD: SpectrumLookup - MS_Agilent_MassHunter_nativeID_format

- src/openms/include/OpenMS/ANALYSIS/ID/SiriusAdapterAlgorithm.h
Added missing virtual deconstructor to `ParameterSection` class in `SiriusAdapterAlgorithm` whose absence previously caused issues with `SiriusAdapter` and `AssayGeneratorMetabo`.
> [Fix] Added missing virtual deconstructor to SiriusAdapterAlgorithm

- src/openms/include/OpenMS/CONCEPT/ProgressLogger.h
Avoid memory leaks in tests where we often create pointers of TOPPBase tools
> [FIX] Make ProgressLogger destructor virtual

- src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h
Needed for consensusID where old search engines are annotated in the metavalues.
Also, in the case of many runs, you should use the loosest settings so the special rules are now activated as soon as one run is a "special" SE.
> [FEATURE] allow auto-deduction of special rules in PepIdx for ConsID

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
Automatically annotates and maps spectra when an idXML file is openend and a reference to its associated mzML file is given in the `spectra_data` meta data or a mzML file with the same name is found in the same folder.  
> [Feature] Id mapping on open of idXML

- src/openms_gui/source/VISUAL/TVToolDiscovery.cpp
This PR aims to prevent the crashing of `TVToolDiscovery` when some tool/util executables listed in `ToolHandler` cannot be found as described in issue #5318.This is done by simply catching a `Exception::FileNotFound` error in `TVToolDiscovery::getParamFromIni_` and printing it to stderr. 
I don't know how common the use case of not having all tools/utils build is. Should this be common (especially among regular user)  it might be worth extending this PR. When not all tools are loaded during start, these tool params cannot be written to TOPPView.ini, so that on the next start these tool params are missing again (when loaded from the ini) however without any warning presented to the user. We could add a check to `TOPPViewBase::loadPreferences` which ensures that the tool params in the …
> [Fix] Prevent crash when TOPP tool/util executable cannot be found

- src/openms/source/SYSTEM/File.cpp
Make getOpenMSDataPath thread-safe
> make getOpenMSDataPath thread-safe

- src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp
... which was linked with `-flto=auto -ffat-lto-objects` on Linux which results in
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7893f00 in xercesc_3_2::XMLString::transcode(char const*, xercesc_3_2::MemoryManager*) () from /buffer/ag_bsc/build/openms_build/lib/libOpenMS.so
because xercesc::XMLString::transcode is called without being ready internally.
Fixes #5379
> fix segfault when starting any executable 

- src/openms_gui/source/VISUAL/Plot1DWidget.cpp
- src/openms_gui/source/VISUAL/PlotWidget.cpp
Stumbled over a deprecated warning, when exporting from TOPPView.
`QPixmap::grabWidget is deprecated, use QWidget::grab() instead`
> [FIX] QWidget::grab()

- src/pyOpenMS/setup.py
It had a weird logic before. Leading to non-c17 builds on Linux gcc before.
> [FIX] Correctly setup c17 for pyopenms

- src/utils/AssayGeneratorMetabo.cpp
Adds a more conservative default for precursor mass correction.
`PrecursorCorrection::correctToHighestIntensityMS1Peak
`
> [FIX] AGM default

- src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/IMSAlphabet.cpp
- src/openms/source/COMPARISON/CLUSTERING/ClusterAnalyzer.cpp
- src/openms/source/COMPARISON/SPECTRA/BinnedSpectrum.cpp
- src/openms/source/COMPARISON/SPECTRA/PeakAlignment.cpp
- src/openms/source/COMPARISON/SPECTRA/SpectrumAlignmentScore.cpp
- src/openms/source/COMPARISON/SPECTRA/SpectrumCheapDPCorr.cpp
- src/openms/source/COMPARISON/SPECTRA/SpectrumPrecursorComparator.cpp
- src/openms/source/COMPARISON/SPECTRA/SteinScottImproveScore.cpp
- src/openms/source/COMPARISON/SPECTRA/ZhangSimilarityScore.cpp
- src/openms/source/CONCEPT/ClassTest.cpp
- src/openms/source/CONCEPT/FuzzyStringComparator.cpp
- src/openms/source/CONCEPT/GlobalExceptionHandler.cpp
- src/openms/source/CONCEPT/Init.cpp
- src/openms/source/CONCEPT/LogStream.cpp
- src/openms/source/CONCEPT/ProgressLogger.cpp
- src/openms/source/CONCEPT/Types.cpp
- src/openms/source/CONCEPT/UniqueIdInterface.cpp
- src/openms/source/DATASTRUCTURES/Compomer.cpp
- src/openms/source/DATASTRUCTURES/ConvexHull2D.cpp
- src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp
- src/openms/source/FILTERING/CALIBRATION/MZTrafoModel.cpp
- src/openms/source/FILTERING/CALIBRATION/PrecursorCorrection.cpp
- src/openms/source/FILTERING/CALIBRATION/TOFCalibration.cpp
- src/openms/source/FILTERING/DATAREDUCTION/DataFilters.cpp
- src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
- src/openms/source/FILTERING/DATAREDUCTION/IsotopeDistributionCache.cpp
- src/openms/source/FILTERING/DATAREDUCTION/MassTraceDetection.cpp
code arrangement changes for better readability. 
> Code Arrangement Changes #7

- cmake/knime_package_support.cmake
- src/tests/topp/CMakeLists.txt
- src/utils/AssayGeneratorMetabo.cpp
- src/utils/SiriusAdapter.cpp
The default names were set incorrectly (windows), so KNIME was not able to get the path to the correct executable (see #5508). 
I also changed the "is_executable" to "skipexists". I hope with this step it is possible again to set the executable externally if KNIME is not able to find it. This should also be better for galaxy @timosachsenberg @jpfeuffer.
> [FIX] Sirius default executable names

- src/utils/ProteomicsLFQ.cpp
now treated as unfractionated
We previously decided to fall back to unfractionated but the initial implementation had a bug.
Should be fixed now with this PR
> fix bug if experimental design is not given

- src/openms/source/ANALYSIS/ID/BayesianProteinInferenceAlgorithm.cpp
double param values need to be converted to string
> fix bug in Epifany introduced by new ParamValue class

- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmPicked.h
- src/openms/source/CHEMISTRY/TheoreticalSpectrumGenerator.cpp
- src/openms/source/METADATA/PeptideHit.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmPicked.cpp
I had a look at the [remaining memory leaks](http://cdash.openms.de/viewTest.php?onlyfailed&buildid=170763) in the tests. Sadly almost all have them are due to leaks in third party dependencies and therefore hardly fixable.
| Name | Memory Leak source | Description |
|---|---|---|
| DetectabilitySimulation_test | libsvm | Unresolvable |
| FeatureFinderAlgorithmPicked_test | Raw pointer | Fixed by using a `std::shared_ptr`. Not sure if this introduces a relevant performance penalty. Thoughts? |
| FeatureFinderMetabo_test | libsvm | Unresolvable |
| LibSVMEncoder_test | libsvm | Unresolvable |
| MzMLFile_test | `xercesc_3_2::MemoryManagerImpl::allocate(unsigned long)` | Unresolvable |
| MzMLSpectrumDecoder_test | `xercesc_3_2::MemoryManagerImpl::allocate(unsigned long)`, ... | Unresolvable …
> [Fix] Remaining memory leaks in tests

- AUTHORS
- CHANGELOG
- src/pyOpenMS/pyopenms/__init__.py
I've got a lot of customizations (mostly to `unimod.xml` ) that I've set in a new directory that is referenced by `OPENMS_DATA_PATH` but PyOpenMS clobbers that on initialization. This simple modification should prevent it from doing so, if there is a path already set.
> Do not overwrite OPENMS_DATA_PATH in PyOpenMS if it is already set

- .gitpod.Dockerfile
- .vscode-gitpod/cmake-kits.json
- .vscode-gitpod/settings.json
- src/openms/include/OpenMS/FORMAT/PepXMLFile.h
- src/openms/source/ANALYSIS/ID/PercolatorFeatureSetHelper.cpp
- src/openms/source/FORMAT/PepXMLFile.cpp
- src/tests/class_tests/openms/data/combined.concat.perco.in.idXML
- src/tests/class_tests/openms/data/comet.topperc.idXML
- src/tests/class_tests/openms/data/comet.topperc_check.idXML
- src/tests/topp/IDFileConverter_10_output.idXML
- src/tests/topp/IDFileConverter_16_output.idXML
- src/tests/topp/IDFileConverter_24_output.idXML
- src/tests/topp/IDFileConverter_2_output.idXML
- src/tests/topp/IDFileConverter_6_output.idXML
- src/tests/topp/THIRDPARTY/CometAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/CometAdapter_2_out.idXML
- src/tests/topp/THIRDPARTY/CometAdapter_3_out.idXML
- src/tests/topp/THIRDPARTY/CometAdapter_4_out.idXML
- src/tests/topp/THIRDPARTY/MyriMatchAdapter_1_out.idXML
- src/topp/MSGFPlusAdapter.cpp
For use in Percolator, parse isotope error with round(neutralmassdiff/C12C13diff).
Also contains various fixes for terminal modifications once again.
Contains another try to make clangd work out of the box on Gitpod.
> [FEATURE] Export isotope errors when reading pepXML

- src/openms/include/OpenMS/FORMAT/PercolatorInfile.h
- src/openms/include/OpenMS/FORMAT/sources.cmake
- src/openms/include/OpenMS/METADATA/SpectrumLookup.h
- src/openms/source/FORMAT/PercolatorInfile.cpp
- src/openms/source/FORMAT/sources.cmake
- src/openms/source/METADATA/SpectrumLookup.cpp
- src/pyOpenMS/pxds/PercolatorInfile.pxd
- src/topp/PercolatorAdapter.cpp
- allows converting and store ID data in PIN files
> [refactor] moved percolator in file functionality into library

- src/pyOpenMS/pxds/PeakPickerHiRes.pxd
Wrap the check_spectrum_type parameter to make it accessible from Python
> [PYOPENMS] wrap check_spectrum_type parameter for pphires

- src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.h
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/ElutionModelFitter.cpp
- src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp
- Elution model fit now throws if no features provided (before segfault in median calculation)
- FFMetaboIdent now only calls fitting if at least one feature was found
> [fix] Elution peak detection: rare segfault if no features were detected (e.g., in blanks)

- src/pyOpenMS/pyopenms/dataframes.py
- src/pyOpenMS/tests/unittests/test000.py
Function peptide_identifications_to_df() crashed when decode_ontology was set False. Because meta values were not decoded to strings, checking meta values in the CV failed when calling startswith().
> [FIX] Decoding ontology in PeptideIdentification df conversion

- src/openms/include/OpenMS/FILTERING/SMOOTHING/GaussFilter.h
- src/openms/source/FILTERING/SMOOTHING/GaussFilter.cpp
Reduces warning in high throughput data.
> [FIX] add parameter to disable output of warnings in GaussFilter

- .gitpod.Dockerfile
> [gitpod] add python3-pip to use run-clang-tidy

- src/openms/include/OpenMS/SYSTEM/File.h
- src/openms/source/SYSTEM/File.cpp
- src/openms_gui/source/VISUAL/TableView.cpp
fixes a race condition when multiple threads call newFile() and the reference gets invalidated (happened in TOPPView, when requesting a temporary file for INI's)
> Fix race condition in TOPPView

- src/pyOpenMS/pyopenms/dataframes.py
- src/pyOpenMS/tests/unittests/test000.py
Peptides assigned to features can be exported together with meta values 'ID_native_id' (feature spectrum id) and 'ID_filename' (primary MS run path of corresponding protein id). Based on these values and feature ID the peptide and feature DataFrames can be merged later. 
> [FEATURE] peptide export from feature map for pyOpenMS

- src/openms/source/ANALYSIS/ID/PeptideProteinResolution.cpp
- src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathScoring.cpp
- src/openms/source/ANALYSIS/OPENSWATH/SwathMapMassCorrection.cpp
- src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp
- src/openms/source/FORMAT/DATAACCESS/SiriusFragmentAnnotation.cpp
- src/openms/source/FORMAT/MzTabFile.cpp
- src/openms/source/METADATA/ExperimentalDesign.cpp
> clang-tidy performance-inefficient-vector/string-operation

- src/openms/include/OpenMS/ANALYSIS/MRM/ReactionMonitoringTransition.h
- src/openms/include/OpenMS/CHEMISTRY/ISOTOPEDISTRIBUTION/IsoSpecWrapper.h
- src/openms/include/OpenMS/METADATA/ID/IdentificationData.h
- src/openms/source/ANALYSIS/MRM/ReactionMonitoringTransition.cpp
- src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsoSpecWrapper.cpp
- src/openms/thirdparty/IsoSpec/IsoSpec/isoSpec++.cpp
- src/openms/thirdparty/IsoSpec/IsoSpec/isoSpec++.h
- src/openms/thirdparty/IsoSpec/IsoSpec/marginalTrek++.cpp
- src/openms/thirdparty/IsoSpec/IsoSpec/marginalTrek++.h
clang-tidy fixes
cppcoreguidelines-virtual-class-destructor
misc-redundant-expression,
performance-trivially-destructible
performance-noexcept-move-constructor
> Hide IsoSpec using pimpl and add some clang-tidy performance fixes on top

- src/openms/include/OpenMS/MATH/MISC/MathFunctions.h
- src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h
- src/openms/source/KERNEL/ConsensusMap.cpp
- src/openms/source/KERNEL/FeatureMap.cpp
- src/openms_gui/include/OpenMS/VISUAL/LayerDataBase.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataChrom.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataConsensus.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataFeature.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataIdent.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataPeak.h
- src/openms_gui/include/OpenMS/VISUAL/PlotCanvas.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/LayerDataBase.cpp
- src/openms_gui/source/VISUAL/Plot1DCanvas.cpp
- src/openms_gui/source/VISUAL/Plot3DOpenGLCanvas.cpp
- src/openms_gui/source/VISUAL/PlotCanvas.cpp
- refactor `getIntensity` into layers
- some code cleanup and speed improvements
> Layer refactor #2

- share/OpenMS/CHEMISTRY/Modomics.tsv
- src/openms/source/CHEMISTRY/RibonucleotideDB.cpp
- src/tests/class_tests/openms/source/RibonucleotideDB_test.cpp
Fixes an existing issue where custom deoxyribose mods (with the naming convention [d*]) were not producing the correct masses for base loses.
> Correct a-B fragment masses for DNA

- src/openms/source/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.cpp
Might fix: https://github.com/OpenMS/OpenMS/issues/5678
> fix imputation bug on single peak mass traces

- src/openms/include/OpenMS/KERNEL/MSExperiment.h
- src/openms/source/KERNEL/MSExperiment.cpp
- src/pyOpenMS/pxds/MSExperiment.pxd
- src/tests/class_tests/openms/source/MSExperiment_test.cpp
Add helper for pyopenms to retrieve the index of the precursor spectrum
> [FEATURE] add python compatible get precursor spectrum

- src/openms/include/OpenMS/KERNEL/OnDiscMSExperiment.h
- src/openms/source/KERNEL/OnDiscMSExperiment.cpp
- src/topp/GNPSExport.cpp
Don't load files into memory in GNPS export
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect …
> use on disc experiment

- .github/workflows/openms_clang_format.yml
- .github/workflows/openms_clang_format_add_and_commit.yml
An error occurred in PR #5708, when trying to use "/format" 
https://github.com/OpenMS/OpenMS/runs/4537967682?check_suite_focus=true
It seems the issue was that by using the "created" type it is not clear which commits and the branch to use. 
This should be hopefully be fixed by adding the reference to PR and the fetch_depth.
Please see https://github.com/actions/checkout for additional information. 
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is …
> [FIX] clang format actions

- src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationModelLinear.h
- src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLinear.cpp
- src/topp/MapAlignerPoseClustering.cpp
> MapAlignerPoseClustering: print error message and fall back to identity if no data provided

- src/utils/CVInspector.cpp
While working on a test I realized that the mapping argument is not optional.
Speaking of a test... there is currently none. Does anyone has test data to formulate one?
> CVInspector: the mapping_file argument is mandatory

- src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGenerator.h
- src/openms/include/OpenMS/DATASTRUCTURES/Param.h
- src/openms/source/CHEMISTRY/TheoreticalSpectrumGenerator.cpp
- src/openms/source/DATASTRUCTURES/Param.cpp
- src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPViewPrefDialog.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/DIALOGS/TOPPViewPrefDialog.cpp
- src/openms_gui/source/VISUAL/DIALOGS/TOPPViewPrefDialog.ui
- src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
- src/openms_gui/source/VISUAL/TVDIATreeTabController.cpp
- src/openms_gui/source/VISUAL/TVIdentificationViewController.cpp
- src/openms_gui/source/VISUAL/TVSpectraViewController.cpp
Expose TSG parameters in TOPPView preferences and make parameter handling less manual.
Still, we should replace the whole TV Pref dialog with a ParamEditor at some point, because there are many points of failure ATM.
But this needs some more features in ParamEditor first, e.g. editing of ColorGradients.
also in this PR:
Some code renaming and documentation.
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., …
> TOPPView Preferences Dialog refactor

- src/utils/MSFraggerAdapter.cpp
Changed the deprecated parameter max_variable_mods_per_mod to the one used by MSFragger: max_variable_mods_per_peptide
Added the option 0/1/2 to isotope error (also as defined in MSFragger)
- /reformat (experimental) applies the clang-format style …
> Bugfix MSFraggerAdapter

- src/pyOpenMS/CMakeLists.txt
Still a minor error from the CMake restructue.
MacOS fix dependencies has to be run AFTER the pyopenms library build to fixup the DLLs in there too.
> [FIX] pyopenms mac fix dependency order

- src/openms/include/OpenMS/ANALYSIS/SVM/SVMWrapper.h
- src/openms/include/OpenMS/CHEMISTRY/SvmTheoreticalSpectrumGenerator.h
- src/openms/include/OpenMS/FILTERING/DATAREDUCTION/FeatureFindingMetabo.h
- src/openms/include/OpenMS/FORMAT/LibSVMEncoder.h
- src/openms/source/ANALYSIS/SVM/SVMWrapper.cpp
- src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGenerator.cpp
- src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGeneratorTrainer.cpp
- src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
- src/openms/source/FORMAT/LibSVMEncoder.cpp
- src/openms/source/SIMULATION/DetectabilitySimulation.cpp
- src/tests/class_tests/openms/source/LibSVMEncoder_test.cpp
- src/topp/PTModel.cpp
- src/topp/RTModel.cpp
- src/topp/RTPredict.cpp
- src/utils/SvmTheoreticalSpectrumGeneratorTrainer.cpp
removes svm.h includes from header files
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect …
> forward declare all svm types

- src/openms/source/CONCEPT/ClassTest.cpp
- src/tests/class_tests/openms/CMakeLists.txt
Output from successful tests clutter the log. In most cases this information is not needed. Optionally can now be enabled by setting the OPENMS_TEST_VERBOSE_SUCCESS environment variable
- /reformat (experimental) applies the clang-format style changes …
> Require OPENMS_TEST_VERBOSE_SUCCESS env variable set if output of successful test executions should be printed

- src/openms/include/OpenMS/CONCEPT/ClassTest.h
- src/openms/source/CONCEPT/ClassTest.cpp
- src/tests/class_tests/openms/source/MorphologicalFilter_test.cpp
Previously, test could produce a large outputs (e.g., if many peak positions where tested in a loop).
The new default is omitting line output of successful tests.
To get the old behavior:
Set the environment variable OPENMS_TEST_VERBOSE=True -> will print output of successful tests.
Note that we now inform users that some lines were suppressed (and how they can be printed).
```
83: Output of successful tests were suppressed. Set the env variable 'OPENMS_TEST_VERBOSE=True' to enable them.
83: PASSED
1/1 Test #83: MSSpectrum_test ..................   Passed    0.04 sec
```
Example:
running:  OPENMS_TEST_VERBOSE=True ctest -R MSSpectrum_test -VV
will print all lines (old behavior)
```
83: checking (MSSpectrum()) ... 
83:  +  line 81:  TEST_NOT_EQUAL(ptr,nullPointer): got '0x557102cbca60', …
```
> Disable successful test lines by default

- src/openms/source/ANALYSIS/ID/IDMapper.cpp
- src/openms/source/ANALYSIS/QUANTITATION/IsobaricChannelExtractor.cpp
- src/tests/topp/MS3TMT10Plex_test.consensusXML
Before, the IsobaricAnalyzer was annotating the charge of the first fragment ion. Now it uses the MS1 precursor ion.
Also, since the exact settings, "precursor" and "correct ppm" are hard to guess during IDMapping, annotate and compare the scan_ids
used for ID instead.
> [Fix] MS3 TMT IdMapping

- src/openms/source/ANALYSIS/TARGETED/PSLPFormulation.cpp
- src/openms/source/DATASTRUCTURES/MassExplainer.cpp
- src/tests/class_tests/openms/source/MetaboliteFeatureDeconvolution_test.cpp
Some fixes to disable extensive (debug like) test outputs
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that …
> more reduction of test output

- src/openms_gui/include/OpenMS/VISUAL/TableView.h
- src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
- src/openms_gui/source/VISUAL/TableView.cpp
After adding the protein table, protein accessions were not exported anymore because they are hidden by default.
This PR allows TableViews to define columns that are always exported irrespective of being visible or hidden.
- /reformat (experimental) …
> TV make sure that accessions are still exported

- src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
Fixes redrawing of tables in TOPPView caused by assigning a layout to a splitter.
- setting the label NoJenkins will skip tests for this PR on jenkins (saves …
> remove layout from splitter

- src/openms/include/OpenMS/ANALYSIS/ID/AhoCorasickAmbiguous.h
- src/openms/include/OpenMS/CHEMISTRY/DigestionEnzyme.h
- src/openms/source/ANALYSIS/ID/AhoCorasickAmbiguous.cpp
- src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
- src/openms/source/CHEMISTRY/DigestionEnzyme.cpp
- src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
- src/tests/class_tests/openms/source/AhoCorasickAmbiguous_test.cpp
This PR removes the costly storage of all peptide hits in a std::map and uses std::vector instead.
Also each hit takes up less space now.
For an (extreme) dataset with 1e9 hits (!), the runtime reduces from 1h to 15min, while the peak memory usage reduces from 134 GB to 91 GB. The resulting idXML is 34 GB in size.
There is further potential (since there is another map) but that is for another PR.
This change also surfaced a small bug in the new AC implementation (#5776), which may report hits twice (which was not discovered since the results were stored in a map). This is also fixed now.
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error …
> Optimize PeptideIndexer

- src/tests/class_tests/openswathalgo/Scoring_test.cpp
Added some tests for MIToolbox on calculating mutual information between 2 vectors of ranks. This is used to make sure the new implementation in PR #5795 is correct. …
> Mutual info test

- doc/code_examples/Tutorial_GUI_Plot1D.cpp
- src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h
- src/openms/source/FORMAT/CVMappingFile.cpp
- src/openms/source/FORMAT/ControlledVocabulary.cpp
- src/openms_gui/include/OpenMS/VISUAL/LayerDataBase.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataChrom.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataConsensus.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataFeature.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataIdent.h
- src/openms_gui/include/OpenMS/VISUAL/LayerDataPeak.h
- src/openms_gui/include/OpenMS/VISUAL/Painter1DBase.h
- src/openms_gui/include/OpenMS/VISUAL/Plot1DCanvas.h
- src/openms_gui/include/OpenMS/VISUAL/sources.cmake
- src/openms_gui/source/VISUAL/LayerDataBase.cpp
- src/openms_gui/source/VISUAL/LayerDataChrom.cpp
- src/openms_gui/source/VISUAL/LayerDataConsensus.cpp
- src/openms_gui/source/VISUAL/LayerDataFeature.cpp
- src/openms_gui/source/VISUAL/LayerDataIdent.cpp
- src/openms_gui/source/VISUAL/LayerDataPeak.cpp
- src/openms_gui/source/VISUAL/Painter1DBase.cpp
- src/openms_gui/source/VISUAL/Plot1DCanvas.cpp
- src/openms_gui/source/VISUAL/Plot2DWidget.cpp
- src/openms_gui/source/VISUAL/PlotCanvas.cpp
- src/openms_gui/source/VISUAL/sources.cmake
This PR is a first attempt to separate the plotting of layer data in Canvas1D from the layer type.
Painting is delegated to a separate class for the essential parts.
This will allow to add painters for chromatograms, mobilograms etc in the future (some more refatoring is needed).
Going in small pieces here, so this is the first PR or some more to come.
The Painter class is not fully fledged out yet. Expect some future changes there.
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI …
> A Painter1D class for Peaks

- src/openms/include/OpenMS/SYSTEM/BuildInfo.h
- src/pyOpenMS/pxds/BuildInfo.pxd
fixes #5794 
To set the number of threads in pyOpenMS, added and wrapped a Method to BuildInfo. That way the threads can be managed also in pyOpenMS directly.
- …
> [Feature] set OpenMP number of threads in pyOpenMS

- src/openms/include/OpenMS/CHEMISTRY/EmpiricalFormula.h
- src/tests/class_tests/openms/source/EmpiricalFormula_test.cpp
After reading #5843 I realized that our documentation is actually incorrect and we currently dont support "(14)C" since we do not have a representation for 14C (only 13C and 12C). This fixes the documentation
Note that currently any attempt to try
```
EmpiricalFormula("(14)C")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "pyopenms/pyopenms_4.pyx", line 6385, in pyopenms.pyopenms_4.EmpiricalFormula.__init__
File "pyopenms/pyopenms_4.pyx", line 6353, in pyopenms.pyopenms_4.EmpiricalFormula._init_2
RuntimeError: '(14)C' found. in: Unknown element '(14)C'
```
will not work as 14C is not known and unfortunately there is currently no way in ElementDB to even add an element, see #5851
> [DOC] fix documentation for isotopes

- src/openms/include/OpenMS/FORMAT/FileTypes.h
- src/openms/source/FORMAT/FileTypes.cpp
- src/openms_gui/include/OpenMS/VISUAL/LayerDataBase.h
- src/openms_gui/include/OpenMS/VISUAL/MISC/GUIHelpers.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/LayerDataBase.cpp
- src/openms_gui/source/VISUAL/MISC/GUIHelpers.cpp
- src/openms_gui/source/VISUAL/Plot1DCanvas.cpp
- src/openms_gui/source/VISUAL/Plot2DCanvas.cpp
- src/openms_gui/source/VISUAL/Plot3DCanvas.cpp
- src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
- src/tests/class_tests/openms/source/FileTypes_test.cpp
- src/tests/class_tests/openms_gui/CMakeLists.txt
- src/tests/class_tests/openms_gui/source/GUIHelpers_test.cpp
[FEATURE] add getSaveFilename function with predefined OpenMS data types for less boilerplate
[FIX] fix a bug in GUIHelpers::OverlapDetector (and add a regression test)
- `/reformat` (experimental) applies the clang-format style changes as additional …
> GUI: improvements, mostly better File-save dialogs

- AUTHORS
- CHANGELOG
- src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h
- src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
- src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
- src/tests/class_tests/openms/source/PeptideIndexing_test.cpp
- src/tests/class_tests/openms/source/ProteaseDigestion_test.cpp
- src/tests/topp/THIRDPARTY/CometAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/CometAdapter_2_out.idXML
- src/tests/topp/THIRDPARTY/CometAdapter_3_out.idXML
- src/tests/topp/THIRDPARTY/CometAdapter_4_out.idXML
- src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/XTandemAdapter_1_out.idXML
- src/tests/topp/THIRDPARTY/XTandemAdapter_2_out.idXML
- src/tests/topp/THIRDPARTY/XTandemAdapter_3_out.idXML
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on …
> Fix PeptideIndexer to handle no cleavage with full specificity

- src/openms/include/OpenMS/KERNEL/MSSpectrum.h
- src/pyOpenMS/addons/MSChromatogram.pyx
- src/pyOpenMS/addons/MSSpectrum.pyx
- src/pyOpenMS/pxds/MSChromatogram.pxd
- src/pyOpenMS/pxds/MSSpectrum.pxd
- src/pyOpenMS/tests/unittests/test000.py
- fixes bug #5876
- set_peaks() no longer clears data arrays, only clears the peak data
- …
> [FIX] do not clear data arrays when setting peaks

- src/pyOpenMS/tests/unittests/test000.py
- src/tests/class_tests/openms/source/AASequence_test.cpp
- after the change in monoisotopic mass, we have to adjust the test for
monoisotopic mass for selenocysteine from 74 to 80 (most abundant
isotope)
> [FIX] test fix after #5891

- src/utils/MzMLSplitter.cpp
- src/utils/OpenSwathFileSplitter.cpp
seems to be covered by tests:
https://github.com/OpenMS/OpenMS/blob/f3910ff6988b4910ced0787a964a8e48ced9262b/src/tests/topp/CMakeLists.txt#L2837
https://github.com/OpenMS/OpenMS/blob/f3910ff6988b4910ced0787a964a8e48ced9262b/src/tests/topp/CMakeLists.txt#L1762
ref https://github.com/OpenMS/OpenMS/issues/4404
- …
> MzMLSplitter and OpenSwathFileSplitter: use output-prefix

- src/openms/source/METADATA/SpectrumLookup.cpp
- src/tests/class_tests/openms/source/SpectrumLookup_test.cpp
In the IDFileConverter, when converting to pepXML with SpectrumLookup, we see a weird behaviour when the mzML
contains native IDs in the format "index=n".
Since spectrum metadata returns n as the scan number. Basically you end up with scan_number=n and index=n in the pepXML which is not correct.
Not sure if it is the right place to fix, but it should fix the problem.
> [FIX] scan number extraction

- .github/workflows/openms-ci.yml
If all contrib libraries are static build the old version failed because no dylib file is present. …
> add check for empty dylib list

- cmake/cmake_findExternalLibs.cmake
- doc/doxygen/install/install-linux.doxygen
fixes #5604
for the most part. As discussed, I think this is reasonable.
> [DOC] Require and document the actually required min Qt version

- src/pyOpenMS/pyopenms/dataframes.py
MSExperiment.get_massql_df failed on empty spectra. Setting initial value for np.amax solved the issue. …
> [FIX] massql df export empty spectrum

- .github/workflows/pyopenms-wheels.yml
Currently it is looking for python at: /opt/python/cp39-cp39/bin/python
but maybe /opt/python/cp39-cp39/bin/python3 works.
If that is not the case, the python executables are probables named /opt/python/cp39-cp39/bin/python3.9 etc.
Which would make things a bit more complex as we run the script for the last 3 python versions.
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are …
> attempt to fix linux pyopenms-wheel action

- src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DCaret.cpp
- src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DPeakItem.cpp
> [FIX] suppress [-Wdeprecated-declaration] warnings until Qt5.14

- src/tests/topp/CMakeLists.txt
- src/tests/topp/FeatureFinderIdentification_5_candidates.featureXML
- src/topp/FeatureFinderIdentification.cpp
The `-candidates_out` option seems unused. 
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not …
> FeatureFinderIdentification add test for `-candidates_out`

- src/openms_gui/source/VISUAL/InputFile.cpp
- src/openms_gui/source/VISUAL/OutputDirectory.cpp
> [FIX] deprecated QDirModel and update with QFileSystemModel

- src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.h
- src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.cpp
- src/tests/class_tests/openms/source/PeakPickerHiRes_test.cpp
When ion mobility is present, use intensity-weighted average in a peak picker. 
- This works well if the ion mobilities are close to each other, eg if the data is already binned
- This will fail when a full ion mobility frame is provided, for this a more advanced peak picker would be required that takes into account the full 2nd dimension. It is still an improvement compared to dropping the ion mobility completely
>  add intensity-weighted average peak picker 

- src/openms_gui/source/VISUAL/ParamEditor.cpp
> [FIX] deprecated QTreeWidgetItem::setTextColor

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
> [FIX] supress QT::splitbehaviour deprecated warning until 5.14

- src/openms_gui/source/VISUAL/ListEditor.cpp
> [FIX] warning setItemSelected is deprecated

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
> [Fix] qsort() is deprecated

- src/tests/class_tests/openms/source/AhoCorasickAmbiguous_test.cpp
This PR fixes Arrau Subscript Warning for char values by casting them to `(unsigned char)` since the indices can only take non-negative values. 
Warning - `src/tests/class_tests/openms/source/AhoCorasickAmbiguous_test.cpp:431:30: warning: array subscript is of type 'char' [-Wchar-subscripts] and 431:38: warning: array subscript is of type 'char' [-Wchar-subscripts]`
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure …
> fixes-array-subscript-for-char-values

- src/openms/source/FILTERING/CALIBRATION/TOFCalibration.cpp
- src/tests/class_tests/openms/source/LibSVMEncoder_test.cpp
Suppresses mac warnings for ```-Wunused-variable```. 
Fixed ``` src/openms/source/FILTERING/CALIBRATION/TOFCalibration.cpp:198:23: warning: unused variable 'spec_iter' [-Wunused-variable]```
Fixed ```src/tests/class_tests/openms/source/LibSVMEncoder_test.cpp:543:30: warning: unused variable 'it' [-Wunused-variable]```
Fixed 
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are …
> Suppress -Wunused-variable mac warnings

- src/openms_gui/source/VISUAL/MISC/FilterableList.cpp
> [FIX]suppressing warning toSet() is deprecated

- src/openms_gui/source/VISUAL/TVIdentificationViewController.cpp
> [FIX] suppress similar skipemptyparts

- src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
- src/openms_gui/source/VISUAL/Plot1DCanvas.cpp
- src/openms_gui/source/VISUAL/Plot2DCanvas.cpp
- src/tests/class_tests/openms_gui/source/GUI/TOPPView_test.cpp
> [FIX] various Qtime methods deprecated

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
> [FIX] suppress buttongroup(int) is deprecated

- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
> [FIX] screenGeometry is deprecated

- src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
- src/openms_gui/source/VISUAL/TVIdentificationViewController.cpp
> [FIX] suppress few left skipemptyparts

- src/openms_gui/source/VISUAL/TableView.cpp
- src/openms_gui/source/VISUAL/TreeView.cpp
> [FIX] few left toSet warnings

- .github/workflows/openms-ci.yml
- .github/workflows/pyopenms-wheels.yml
We use github package registry now to host our container used in CI. Previously those were on dockerhub …
> use contrib_manylinux container from github registry

- src/pyOpenMS/CMakeLists.txt
- src/pyOpenMS/MANIFEST.in
- src/pyOpenMS/setup.py
Fixes #5821
I am just having some problems with internal imports. I think in theory we somehow need to import each submodule in each submodule, such that the type engine finds all types from sibling modules. Maybe we need a __init__.pyi?
I tried that on PyCharm but it did not completely solve it. Trying mypy would be another TODO.
> [FEATURE] package type stubs with pyopenms

- src/openswathalgo/source/OPENSWATHALGO/ALGO/Scoring.cpp
- src/tests/class_tests/openms/source/IonMobilityScoring_test.cpp
Fix  https://github.com/OpenMS/OpenMS/issues/4339
IM tests that failed was the one that had 0 MS1 and 0 MS2 transitions
extracted.
To fix failing IM test allow standardize_data and
calculateCrossCorrelation to accept empty vectors (in Scoring.cpp)
- …
> Fix failing IM tests (issue #4339)

- src/openms/include/OpenMS/MATH/STATISTICS/BasicStatistics.h
- src/tests/class_tests/openms/source/BasicStatistics_test.cpp
`BasicStatistics` `mean_` and `variance_` returned `-nan` when given a vector of only zeroes, due to dividing by the sum.
This should fix #5981 and possibly a few other unexpected `nan` issues.
This is one possible solution, but more input would be appreciated.
Problems here are:
`sum_` and `mean_` would be zero for a vector like this as well: [-5, -3, 0, 3, 5], but the variance would not be zero.
Still we use `variance_ /= sum_` as a step in the calculation, which would cause a `nan`.
- Or click on the action: e.g., for …
> [FIX] BasicStatistics: reasonable results with vectors of zeroes

- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/SwathTabWidget.h
- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/WizardHelper.h
- src/openms_gui/include/OpenMS/VISUAL/DIALOGS/sources.cmake
- src/openms_gui/source/VISUAL/DIALOGS/SwathTabWidget.cpp
As suggested in the PR here: #5690, WizardHelper class is added to be shared between both SwathWizard and FLASHDeconvWizard
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits …
> added WizardHelper class to be shared with other Wizards

- .github/workflows/openms-ci.yml
- cmake/build_system_macros.cmake
- cmake/cmake_findExternalLibs.cmake
- src/openms/CMakeLists.txt
- src/tests/class_tests/openms/CMakeLists.txt
Try to use the official exports from Boost Cmake instead of the find module.
> [BUILD] Use Cmake exports from boost

- src/tests/class_tests/openms/executables.cmake
Fix the newly raised issue #6059 by myself :) Already confirmed that this fix worked on my local machine.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect …
> [FIX] Add FASTAContainer_test to Boost_dependent_tests

- PULL_REQUEST_TEMPLATE.md
- commenting with `rebuild jenkins` …
> Update PULL_REQUEST_TEMPLATE.md with information on reformat

- src/pyOpenMS/pxds/EmpiricalFormula.pxd
Fixes #5914 if it runs through. I have no idea why it was uncommented. …
> Uncomment wrapping of other operators in Empirical Formula

- src/openms_gui/source/VISUAL/PlotCanvas.cpp
Fixes #5987 
<details>
</details>
<details>
- commenting with `rebuild jenkins` will …
> [FIX]: suppressed deprecated QWheelEvent::x() const

- src/openms/source/FORMAT/PepXMLFile.cpp
Bugfix for the spectrum_reference, which was stated as scan number instead of the native_id when using the MSFraggerAdapter.
<details>
</details>
<details> …
> Add the native_id as spectrum reference when using the MSFraggerAdapter

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.h
- src/openms/include/OpenMS/FILTERING/DATAREDUCTION/SplineInterpolatedPeaks.h
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.cpp
- src/openms/source/FILTERING/DATAREDUCTION/SplineInterpolatedPeaks.cpp
- src/pyOpenMS/pxds/SplineInterpolatedPeaks.pxd
This PR (partly) fixes `-Wunused-private-field` warnings when compiling with `clang` on macOS.
There are two unused private fields:
1. `snoar_` in `OpenSwathOSWWriter.h`
2. `pos_min_` of `SplineInterpolatedPeaks::Navigator` in `SplineInterpolatedPeaks.h`
Both unused fields can be removed since they were not used anywhere in the code.
However, I feel that the first unused field should not be trivially removed since in `OpenSwathTSVWriter`, we utilized `sonar_` to determine whether we should write `var_sonar_<options>`  in the output or not:
```c++
if (sonar_)
{
ofs << "\tvar_sonar_lag\tvar_sonar_shape\tvar_sonar_log_sn\tvar_sonar_log_diff\tvar_sonar_log_trend\tvar_sonar_rsq";
}
```
But in OSW writer, we append `VAR_SONAR<options>` to `sql_feature_ms2` regardless of `sonar_` provided or …
> [FIX] Suppress -Wunused-private-field warnings 

- src/openms/source/METADATA/ID/IdentificationDataConverter.cpp
<details>
</details>
<details>
- commenting with `rebuild jenkins` will retrigger …
> Allow missing score types in IDDData conversion

- src/openms/include/OpenMS/FORMAT/OMSFileLoad.h
- src/openms/include/OpenMS/METADATA/ID/DBSearchParam.h
- src/openms/source/FORMAT/OMSFileLoad.cpp
- src/openms/source/FORMAT/OMSFileStore.cpp
- src/topp/TextExporter.cpp
- src/utils/FeatureFinderMetaboIdent.cpp
Term specificity information for digestion enzymes was missing from the comparison operator in `DBSearchParam` and from input/output in OMS (SQLite) files. I've now added it.
Since there may be existing OMS files without the corresponding column in the database schema, I've increased the OMS file version number and added a version check to the file loading code. This makes it possible to still load files with the old schema (version 1).
> Support for enzyme term specificity (DB search params.) in OMS (SQLite) files

- src/tests/topp/CMakeLists.txt
These tests are unstable due to differences in number to string conversions between versions of boost.
This can not be avoided or whitelisted due to the nature of the format (Base64 encoded strings in multi-line blocks).
Currently we see this difference between the boost versions <= 1.71.0 and >=1.78.0. It seems the boost developers are still working on the relevant code and further changes in future versions are likely.
The spec.xml format is only necessary for compatibility with the xQuest Result Viewer, which is low priority right now.
The tests can be activated again, if and when our number to string conversion becomes less dependent on updated external libraries.
<details>
- …
> [TEST] commented out OpenPepXLS's spec.xml tests

- src/topp/FileConverter.cpp
Fixes #6135
Added a flag to FileConverter to disable zlib compression in the ThermoRawFileParser.
Enables compatibility with X!Tandem and other tools that don't support compressed files.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., …
> [PARAM, FEATURE] FileConverter, disable zlib compression flag

- src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
Fixed comparison between signed and unsigned int in EnzymaticDigestion.cpp that was causing nightlies failure.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). …
> fixed signed and unsigned int comparison

- src/openms/include/OpenMS/FORMAT/GNPSMetaValueFile.h
- src/openms/source/FORMAT/GNPSMetaValueFile.cpp
- src/pyOpenMS/pxds/GNPSMetaValueFile.pxd
- src/pyOpenMS/tests/unittests/test000.py
- src/tests/topp/GNPSExport_4_out_meta_values.tsv
- src/topp/GNPSExport.cpp
Small fix for GNPSMetaValueFile. Instead of passing a list of mzML file names, pass a ConsensusMap from which the mzML file names will be used to generate the meta value table.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., …
> [Fix] GNPSMetaValueFile get mzML file names from ConsensusMap

- .github/workflows/openms_clang_format_add_and_commit.yml
Follow up for PR https://github.com/OpenMS/OpenMS/pull/6171.
I forgot to adjust to "all_changed_files" not just for "clang_format" but also "clang_format_add_and_commit.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) …
> infra-fix: don't lint deleted files

- doc/doxygen/public/developer-faq.doxygen
List was missing a ul tag, causing the subsection to not be rendered properly. This has been fixed now:
Ref: #6177 
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). …
> fixed indentation in developer-faq.doxygen by adding closing ul tag

- src/openms/include/OpenMS/DATASTRUCTURES/DateTime.h
- src/openms/source/DATASTRUCTURES/DateTime.cpp
amends #6207 and fixes a segfault when doing this:
```
DateTime a;
DateTime b(std::move(a));
a = b; // segfaults
```
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). …
> fix segfault when assigning to a moved-from DateTime

- src/pyOpenMS/pxds/GNPSMGFFile.pxd
- src/pyOpenMS/pxds/GNPSMetaValueFile.pxd
- src/pyOpenMS/tests/unittests/test000.py
Small fix for the pyopenms tests for GNPSQuantificationFile and GNPSMetaValueFile. Also changed GNPSMGFFile.store that conversion to String of input and output file paths is not necessary anymore.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name …
> [Fix] GNPSExport pyopenms tests

- src/topp/FileConverter.cpp
<details>
</details>
<details> …
> Support for noise data in TRFP conversion

- src/pyOpenMS/pxds/SpectrumSettings.pxd
- src/pyOpenMS/tests/unittests/test000.py
see https://github.com/OpenMS/pyopenms-docs/issues/294#issuecomment-1222537883
<details>
</details>
<details>
- …
> [FIX] sync spectrumtype in pxd

- src/openms/include/OpenMS/ANALYSIS/ID/SiriusAdapterAlgorithm.h
- src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp
- src/pyOpenMS/pxds/SiriusAdapterAlgorithm.pxd
- src/utils/SiriusAdapter.cpp
Since Sirius 5 a login with a personal user account is required. Here, the SiriusAdapter gets new options for the user account email and password. If they are provided, the login command will be executed. The tests and pyopenms run locally with the new login options.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style …
> [Feature] Sirius user account login

- src/pyOpenMS/pxds/ExperimentalDesign.pxd
<details>
</details>
<details> …
> fix pyOpenMS wrapping of ExperimentalDesign

- src/pyOpenMS/tests/unittests/test000.py
changes introduced in #6306 
<details>
</details>
<details> …
> [FIX] adapt tests to changes in ExperimentalDesign Sample numbering

- cmake/add_library_macros.cmake
<details>
</details>
<details> …
> [FIX] only use TARGET_RUNTIME_DLLs on WIN32 otherwise its empty

- cmake/compiler_flags.cmake
- src/openms/CMakeLists.txt
fixes #6417 
<details>
</details>
<details> …
> move unused vars to OpenMS target only to prevent pyOpenMS build failing

- cmake/MacOSX/fix_dependencies.rb
fixes #6444  hopefully
<details>
</details>
<details> …
> fix error in mac dependency script when plugin dir is not given

- src/openms/include/OpenMS/DATASTRUCTURES/ListUtils.h
- src/openms/include/OpenMS/DATASTRUCTURES/String.h
- src/openms/include/OpenMS/DATASTRUCTURES/StringUtils.h
- src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h
- src/openms/source/DATASTRUCTURES/String.cpp
- src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
- src/openms/source/FORMAT/HANDLERS/MzQuantMLHandler.cpp
- src/openms/source/FORMAT/HANDLERS/TraMLHandler.cpp
- src/tests/class_tests/openms/data/MzMLFile_xsd-ranges.mzML
- src/tests/class_tests/openms/source/MzMLFile_test.cpp
- src/tests/class_tests/openms/source/StringUtils_test.cpp
- src/tests/class_tests/openms/source/XMLFile_test.cpp
I stumbled upon this when loading a exotic mzML, which had something like
```
<userParam name="someInt" type="xsd:integer" value="9223372036854775807"/>
```
It turns out, our implementation only supported ranges covered by signed 32bit integers.
Any larger numbers would throw an Exception::ConversionError.
Also, anyone passing a "xsd:decimal" would also get an error, since we treated it as an integer, not a decimal number (float, double). Luckily, no one ever tried!
This PR fixes most of these things in **mzML**, **mzQuantML** and **traML**, but our internal representation of integers is an Int64, i.e. if an mzML file contains a large 64 bit unsigned int
```
<userParam name="aLargeUnsigned64bit" type="xsd:unsignedLong" value="9223372036854775809"/>
```
that's still an error. Fixing this …
> Fix XSD value parsing in XML files

- src/openms/source/ANALYSIS/OPENSWATH/DATAACCESS/DataAccessHelper.cpp
Very minor changes
Previously bug with -pasef flag using TraML file as ion mobility data was not able to be accessed through the light transition object. Fix this here.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) …
> [FIX] -pasef flag with TraML file

- .github/workflows/openms-ci.yml
Alternative: Use different workflows.
<details>
</details>
<details> …
> Try collecting GH job status to display overall status

- CMakeLists.txt
- cmake/AddressSanitizer.cmake
- cmake/add_library_macros.cmake
- cmake/compiler_flags.cmake
- src/openms/CMakeLists.txt
- src/openms/thirdparty/SQLiteCpp/CMakeLists.txt
fixes #6508 
fixes #6504 
fixes #6503 
TODO:  currently C++ compiler flags seem to be forwarded to C (but ignored). This should probably be fixed
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving …
> use automoc only on openms libs, fix asan flag propagation

- src/pyOpenMS/converters/special_autowrap_conversionproviders.py
also removed in py3
<details>
</details>
<details> …
> Remove `long` type from convProv

- cmake/cmake_findExternalLibs.cmake
<details>
</details>
<details> …
> fix pthreads difference with sqlitecpp

- .github/workflows/containerdeploy.yml
so you do not have to convert while pulling. e.g. for nextflow
TODO:
- make spython conversion respect the build arguments we use for docker (sed the resulting file) or mount the checked-out repo instead of pulling it in the container. does not work for the base container though.
- ~~fix 404 error when pushing. Wrong URL? Do we have to avoid sub URLs?~~
<details>
</details>
<details> …
> [Feature] direct singularity images on ghcr.io

- src/pyOpenMS/pyopenms/_dataframes.py
- src/pyOpenMS/tests/unittests/test000.py
Use case is e.g., rescoring with ML methods.
e.g., user could write a simple script to export id date from idXML to df, run a DL method to calculate an updated score, feed it back into the OpenMS datastructures, write idXML out.
This could be plugged into e.g., larger workflows
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format …
> [pyOpenMS] simple helper to update scores from a previously exported dataframe

- src/openms/include/OpenMS/CONCEPT/ClassTest.h
- src/openms/source/CONCEPT/ClassTest.cpp
fixes #6499 by moving code from a TEST macro to a function; this saves a LOT of intermediate code as generated by the preprocessor when compiling; thus uses way less RAM and compiles much faster.
some measurements on Windows. Just look at RAM usage and compile time for the tests...
`before` (sorted by RAM usage):
```
wall_time PeakWorkingSetSize                     cpp
1783  0 days, 00:05:37.510 (337.51 seconds)          5.759 GiB ConstRefVector_test.cpp
1782  0 days, 00:03:20.382 (200.38 seconds)          4.653 GiB     AASequence_test.cpp
1781  0 days, 00:04:53.587 (293.59 seconds)          3.989 GiB         String_test.cpp
1106   0 days, 00:00:53.870 (53.87 seconds)          3.791 GiB      ClassTest_test.cpp
1780  0 days, 00:04:38.675 (278.68 seconds)          3.393 GiB …
```
> Huge test compilation improvement

- src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathWorkflow.h
- src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp
This is related to PR #6648.
I discussed with @hroest, and we decided the best approach to fix the issue of zero scored MS1 Features is to write MS1 chromatograms to disk at the end, the same time when MS2 chromatograms get written out. 
Instead of writing out MS1 chromatgorams in [MS1Extraction_](https://github.com/OpenMS/OpenMS/blob/be2814f4cb9cb0d69641537166f9cc8b9ec9b450/src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp#L875) it is now done in [writeOutFeaturesAndChroms_](https://github.com/OpenMS/OpenMS/blob/be2814f4cb9cb0d69641537166f9cc8b9ec9b450/src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp#L841) instead.
<details>
- The details of the action statuses at the end of the PR or the …
> [FIX] All Zero MS1 Feature Scores

- src/openms/include/OpenMS/FILTERING/ID/IDFilter.h
- src/openms/include/OpenMS/METADATA/ID/IdentificationData.h
- src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentTransformer.cpp
- src/openms/source/FILTERING/ID/IDFilter.cpp
- src/openms/source/METADATA/ID/IdentificationData.cpp
- Use C++ style dependency injection/strategy pattern to removed circular dependency caused by making id filtering / map transformation algorithms friends of the ID class.
- moved some local template code to the implementation file
Note that now data and algorithm are separated and could be used, e.g., in external projects that link to OpenMS.
<details>
</details>
<details>
<summary>Click to …
> Improves the design of IdentificationData a bit

- src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp
Fixes an issue mentioned in #6676
Replaced the use of a non-ASCII character in XQuestResultXMLHandler with its unicode escape code.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., …
> [FIX] fixed the use of a non-ASCII character, second case

- src/pyOpenMS/CMakeLists.txt
Fixes #6458.
In the `_copy_assets` function `configure_file` expects a file and fails if a directory is given (e.g. a `__pycache__` folder. Here, a check is implemented to prevent that.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., …
> [Fix] pyopenms assets don't copy folders

- src/openms_gui/include/OpenMS/VISUAL/EnhancedWorkspace.h
- src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
- src/openms_gui/source/VISUAL/EnhancedWorkspace.cpp
- src/openms_gui/source/VISUAL/Plot1DCanvas.cpp
- src/openms_gui/source/VISUAL/TOPPViewMenu.cpp
fixes #6670.
- Ctrl-W is fixed
- Ctrl-A was ambiguous. Solved by moving selection of all annotations in 1D to `Ctrl-B` (fix for the docs is is here https://github.com/OpenMS/OpenMS-docs/pull/191).
fixes #6642:
- this used to work previously, but (recently?) Qt seems to pass a `0` by default as first argument, which disabled the automatic switch to the current directory of the shown layer. This is fixed now.
<details>
If you click in the column that lists the failed tests you will get …
> TOPPView: fix Ctrl-w and Ctrl-a not working and support recent dir for File->Open

- src/openms_gui/source/VISUAL/LayerData1DPeak.cpp
... caused by capturing local vars in a lambda by reference. The lambda however is evaluated after the local scope ends.
Boom! :/
Fixes #6652.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch …
> fixes #6652 (segfault when editing/deleting peak annotation)

- src/pyOpenMS/pyopenms/plotting.py
- src/pyOpenMS/setup.py
Fixing two issues. in #6701 
1. With the matplotlib update, parameter "b" in grid has changed it's name to "visible"
2. Add precursor ion in ion type
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving …
> [pyOpenMS ]fixing grid error from plotting.py  (due to matplotlib update)

- src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DPeakItem.h
- src/openms_gui/source/VISUAL/ANNOTATION/Annotations1DContainer.cpp
... when adding a custom peak annotation in 1D view, then switching to another spectrum, and switching back to the old spectrum.
Caused by copying a raw pointer which is invalid when returning to the original spec.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have …
> Fix TV crash

- .github/workflows/pyopenms-wheels.yml
- src/pyOpenMS/setup.py
<details>
</details>
<details> …
> Also use pyopenms as package name on our pypi server

- src/pyOpenMS/CMakeLists.txt
important for conda
<details>
</details>
<details> …
> [FIX][PYOMS] only run mac_fix_deps if wheel includes dependencies

- src/openms/source/KERNEL/MassTrace.cpp
With `FeatureFinderMetabo` quantification method `median` AND smoothing enabled, an exception is raised that this method is not implemented yet. However, for some applications like direct infusion median is the appropriate method and should be allowed even if smoothing is enabled (default). Here, the intensity is computed with the median method regardless of smoothing. The feature intensities are the same in both cases. This fixes an unnecessary error with this combination of parameters and should make it easier for people who need to use the median quantification method, they don't need to disable smoothing.
<details>
- …
> Enable mass trace quantification method median with smoothing enabled

- doc/doxygen/install/install-linux.doxygen
Updates the "Building OpenMS on GNU/Linux" documentation page, addressing issue #6789.
> [DOC] improved Linux build docs (fixes #6789)

- src/openms/source/ANALYSIS/ID/PercolatorFeatureSetHelper.cpp
- src/openms/source/FORMAT/PepXMLFile.cpp
<details>
</details>
<details> …
> only calculate features if not already annotated by comet

- src/openms/source/CHEMISTRY/ElementDB.cpp
- src/tests/class_tests/openms/source/ElementDB_test.cpp
fixes ASAN error in elementsdb
<details>
</details>
<details> …
> fix ASAN in ElementsDB

- src/topp/CometAdapter.cpp
Following up on #6819
<details>
</details>
<details> …
> remove decoy_prefix for proper decoy annotation of comet pin file

- src/openms/include/OpenMS/CONCEPT/ClassTest.h
Print name of unexpected std::exceptions
<details>
</details>
<details> …
> Print name of unexpected std::exceptions

- src/openms/include/OpenMS/CHEMISTRY/ModifiedPeptideGenerator.h
- src/openms/include/OpenMS/CHEMISTRY/ProteaseDigestion.h
- src/openms/source/CHEMISTRY/ModifiedPeptideGenerator.cpp
- src/openms/source/CHEMISTRY/ProteaseDigestion.cpp
- src/tests/class_tests/openms/source/ModifiedPeptideGenerator_test.cpp
- Adds a variant for protein digestion that returns indices
- Heavily simplifies modified peptide generator by making it non-recursive, vector-based instead of map-based and incremental by using way more copies of previous results.
- Also found some inconsistencies regarding already existing mods and protein vs peptide terminal mods.
Untested
<details>
</details>
<details>
<summary>Click to …
> [FEATURE] ProtDigest with indices, simpler ModPepGen

- .github/workflows/containerdeploy.yml
attempt to build a contrib container that matches the SHA of the OpenMS/OpenMS release contrib submodule 
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, …
> build contrib container from SHA of submodule

- src/openms/source/FORMAT/GNPSMGFFile.cpp
skips empty spectra from export. previously an exception was thrown
<details>
</details>
<details>
- setting the …
> fix error related to empty spectra in bruker files

- src/openms/source/FORMAT/GNPSMGFFile.cpp
<details>
</details>
<details> …
> fix error related to empty spectra in bruker files (#6897)

- src/pyOpenMS/CMakeLists.txt
<details>
</details>
<details> …
> ignore Cython warnings for py 3.8
