tools/uncrustify_branch.sh

The uncrustify script is modified to create a branch before applying uncrustify.
This way the original pull request can be made with the uncrustify changes moved to a new pull request.

[FEATURE] create uncrustify branch

---

src/utils/RNPxl.cpp

uncrustified branch is ready and will be merged after acceptance

Fix/RT meta value related bug, removed unused comment

---

src/openms/include/OpenMS/ANALYSIS/ID/AScore.h
src/openms/source/ANALYSIS/ID/AScore.cpp
src/tests/class_tests/openms/source/AScore_test.cpp
src/topp/PhosphoScoring.cpp
src/utils/SimpleSearchEngine.cpp

[FIX] fixed bugs in AScore implementation and added deisotoping as

---

doc/doxygen/public/TOPP.doxygen
src/openms/source/APPLICATIONS/ToolHandler.cpp
src/topp/PhosphoScoring.cpp

And improved the documentation of the tool itself.

Added PhosphoScoring tool to TOPP documentation

---

src/pyOpenMS/pxds/AScore.pxd
src/pyOpenMS/pxds/AccurateMassSearchEngine.pxd

fixes for pyOpenMS after the two pull requests #1140 and #1141

[FIX,PYOPENMS] fix and adopt pyOpenMS

---

src/topp/MzTabExporter.cpp

ConsensusXML export is fixed and much more conform to mzTab standard.
Meta values attached to consensus feature identifications and hits are exported in additional columns.
If multiple identifications are attached an error is given and the user instructed to run IDConflictResolver first.

[FIX] improved export of consensusXML

---

src/topp/PeptideIndexer.cpp

printing is now fast on Windows OS

minor amendmend to last fix (better console output)

---

CHANGELOG
tools/changelog_helper.sh

A preliminary changelog for the 2.0 release including a tab-separated table of parameter changes together with a small script to generate it.
As I've been rather inactive lately, I may not be aware of some of the important highlights of this release that need to be mentioned explicitly. Feel free to add more...

Changelog 2.0

---

src/tests/class_tests/openms/source/SwathWindowLoader_test.cpp

should fix the windows test failure for this class
- initialize swath map struct
- add test for sorting

[TEST] fix test

---

src/openms/source/FORMAT/PepXMLFile.cpp
src/tests/topp/IDFileConverter_2_output.idXML
src/tests/topp/IDFileConverter_4_output.idXML

solves https://github.com/OpenMS/OpenMS/issues/1138
related to https://github.com/OpenMS/OpenMS/issues/70

[FIX] make identifier of multiple identification runs unique

---

src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
src/openms/source/FORMAT/MzTabFile.cpp

[FIX] fixed study variable index start at 1. Added global identifiert to

---

src/pyOpenMS/pxds/ConsensusMap.pxd
tools/pychecker_ignore.yaml

add forgotton `push_back` to ConsensusMap as per Marc Rurik

[FEATURE] add ConsensusMap push_back

---

cmake/knime/binaries_lnx.ini
cmake/knime/binaries_mac.ini
cmake/knime/binaries_win.ini
cmake/knime_package_support.cmake

For the packaging of the KNIME plugin some additions had to be made for the new thirdparty executables
featured in our Adapters.

[BUILD] added support for new thirdparty executables in KNIME

---

cmake/knime_package_support.cmake

Fixes error introduced in pull request [#1176]. As @aiche correctly suggested.

[FIX] fix toolnames for KNIME packaging

---

src/openms/include/OpenMS/FORMAT/XTandemInfile.h
src/openms/source/FORMAT/XTandemInfile.cpp
src/pyOpenMS/pxds/XTandemInfile.pxd
src/tests/topp/THIRDPARTY/XTandemAdapter_3_out.idXML
src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/topp/XTandemAdapter.cpp

I added the missing option and created a test for it.

[FIX] added missing option to apply e-value filtering

---

src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp

fixed minor typo in error message

---

src/openms/include/OpenMS/DATASTRUCTURES/SuffixArrayPeptideFinder.h
src/openms/include/OpenMS/DATASTRUCTURES/SuffixArraySeqan.h
src/openms/source/APPLICATIONS/ConsoleUtils.cpp
src/openms/source/DATASTRUCTURES/SuffixArraySeqan.cpp
src/superhirn/source/TRANSFORMATIONS/FEATUREFINDER/SUPERHIRN/BackgroundIntensityBin.cpp
src/topp/PILISIdentification.cpp
src/topp/PTPredict.cpp

fixed the high impact defects (2 assigned remaining)

[FIX ] coverity high impact defects

---

src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.h
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
src/tests/class_tests/openms/source/MultiplexClustering_test.cpp
src/tests/class_tests/openms/source/MultiplexFilteringCentroided_test.cpp
src/tests/class_tests/openms/source/MultiplexFilteringProfile_test.cpp
src/tests/class_tests/openms/source/MultiplexFiltering_test.cpp
src/topp/FeatureFinderMultiplex.cpp

This pull request removes the debug code from FeatureFinderMultiplex and updates the docu. It resolves #935.

Removes debug code from FeatureFinderMultiplex

---

doc/doxygen/install/install-linux.doxygen

please also try out the current documentation and suggest comments / improvements

[DOC] improve linux install doc

---

src/pyOpenMS/pxds/IDFilter.pxd

Ammend to pull request #1212

---

src/tests/topp/INIUpdater_1_noupdate.toppas
src/tests/topp/INIUpdater_3_old_out.toppas

This pull request fixes INIUpdater tests due to a new IDMapper parameter in #1219.

fixes INIUpdater test

---

src/tests/topp/THIRDPARTY/FidoAdapter_4_output.idXML

This needs the Fido/FidoChooseParameters executables built from the updated sources, see https://github.com/hendrikweisser/Fido/commits/master.

Updated problematic FidoAdapter test (fixes #1171)

---

src/topp/MSGFPlusAdapter.cpp

Fixes #1251 (including more documentation). See there for discussion.

Fix MSGFPlusAdapter running in TOPPAS (mzid output)

---

src/utils/CMakeLists.txt

[FIX][BUILD] Fixes linking issue with boost in UTILS #1272

---

src/openms/include/OpenMS/FILTERING/TRANSFORMERS/SpectraMerger.h

The logarithm call is modified for Visual Studio 10. Resolves https://github.com/OpenMS/OpenMS/commit/36c48906f306ad74c63a04b14657bc54456f2d8d#commitcomment-10688220

modified logarithm for Visual Studio 10

---

src/tests/topp/CMakeLists.txt
src/tests/topp/HighResPrecursorMassCorrector_1035_1178_4.featureXML
src/tests/topp/HighResPrecursorMassCorrector_1035_1178_4.mzML
src/tests/topp/HighResPrecursorMassCorrector_1035_1178_4_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_2538_1091_2.featureXML
src/tests/topp/HighResPrecursorMassCorrector_2538_1091_2.mzML
src/tests/topp/HighResPrecursorMassCorrector_2538_1091_2_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_2810_1091_3.featureXML
src/tests/topp/HighResPrecursorMassCorrector_2810_1091_3.mzML
src/tests/topp/HighResPrecursorMassCorrector_2810_1091_3_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_2860_1103_3.featureXML
src/tests/topp/HighResPrecursorMassCorrector_2860_1103_3.mzML
src/tests/topp/HighResPrecursorMassCorrector_2860_1103_3_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_3070_1191_3.featureXML
src/tests/topp/HighResPrecursorMassCorrector_3070_1191_3.mzML
src/tests/topp/HighResPrecursorMassCorrector_3070_1191_3_out.mzML
src/topp/HighResPrecursorMassCorrector.cpp

[FEATURE] correct precursor to feature

---

src/topp/IsobaricAnalyzer.cpp

...to include that input MS2 spectra must be centroided (see issue #1347).

Extended IsobaricAnalyzer documentation

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathHelper.h
src/topp/OpenSwathRTNormalizer.cpp
src/utils/OpenSwathWorkflow.cpp

- [FEATURE] also adopt RTNormalizer

[FEATURE] added ciRT to OpenSwathWorkflow

---

src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp

- further increase speed of appendASCII function by using iterators
- this brings about a 50% speed improvement in the appendASCII function which has a substantial effect on XML parsing speed

[FEATURE] optimized base64 string handling

---

src/pyOpenMS/tests/unittests/test000.py

fixes the python test
this would have to be backported to the master branch as well to go into the pyOpenMS 2.0 release

[TEST FIX] fix pyOpenMS tests

---

src/topp/FeatureFinderMetabo.cpp
src/topp/HighResPrecursorMassCorrector.cpp
src/topp/MapAlignerPoseClustering.cpp
src/topp/MapAlignerSpectrum.cpp
src/topp/MapStatistics.cpp
src/topp/OpenSwathFeatureXMLToTSV.cpp
src/utils/MapAlignmentEvaluation.cpp
src/utils/QCExporter.cpp
src/utils/RTEvaluation.cpp

... plus a current compile error on Windows (Math::round)

Fix TOPP/UTIL documentation

---

src/openms/source/CHEMISTRY/AASequence.cpp
src/openms/source/CHEMISTRY/EdwardsLippertIterator.cpp

- include string explicitly
- use std::string

[FIX] attempt to fix MSVS compilation errors

---

src/openms/source/CHEMISTRY/AASequence.cpp

2nd try to fix the errors on windows

[FIX] (second) attempt to fix MSVS compilation errors

---

src/openms_gui/include/OpenMS/VISUAL/TOPPASVertex.h
src/openms_gui/source/VISUAL/TOPPASInputFileListVertex.cpp
src/openms_gui/source/VISUAL/TOPPASScene.cpp
src/openms_gui/source/VISUAL/TOPPASVertex.cpp

- added missing signal to InputFileList vertex which now resets the downstream pipeline when files are modified
- minor optimization reducing the number of rounds during topological sorting

Fix TOPPAS signals

---

src/openms/include/OpenMS/FILTERING/ID/IDFilter.h
src/openms/source/FILTERING/ID/IDFilter.cpp
src/tests/class_tests/openms/source/IDFilter_test.cpp
src/topp/IDFilter.cpp

addresses issue https://github.com/OpenMS/OpenMS/issues/1268

[FEATURE] added filtering by protein accession stringlist

---

src/openms/include/OpenMS/ANALYSIS/TARGETED/OfflinePrecursorIonSelection.h
src/openms/include/OpenMS/SIMULATION/RawTandemMSSignalSimulation.h
src/openms/source/ANALYSIS/TARGETED/OfflinePrecursorIonSelection.cpp
src/openms/source/SIMULATION/RawTandemMSSignalSimulation.cpp
src/tests/class_tests/openms/source/MSSim_test.cpp
src/tests/class_tests/openms/source/OfflinePrecursorIonSelection_test.cpp
src/tests/class_tests/openms/source/RawTandemMSSignalSimulation_test.cpp
src/topp/InclusionExclusionListCreator.cpp

[FIX] ignored MS2 model switch for fragment prediction (thx Sandro); 
[DOC] better parameter descriptions; code documentation, variable naming and cleanup

[FIX, DOC] Small fixes to MSSimulator

---

src/openms/include/OpenMS/ANALYSIS/ID/AccurateMassSearchEngine.h
src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
src/openms/source/CHEMISTRY/IsotopeDistribution.cpp

- some internal doc
- removal of superfluous code
- minor optimizations

[DOC] minor cleanup of AMS

---

src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithmPEPIons.cpp
src/openms/source/ANALYSIS/PIP/LocalLinearMap.cpp
src/openms/source/ANALYSIS/SVM/SVMWrapper.cpp
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
src/openms/source/FORMAT/FASTAFile.cpp
src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
src/openms/source/FORMAT/PepNovoOutfile.cpp
src/openms/source/FORMAT/SVOutStream.cpp

fix WindowsOS compile errors

---

src/openms/include/OpenMS/FORMAT/XTandemInfile.h
src/openms/source/FORMAT/XTandemInfile.cpp
src/tests/class_tests/openms/data/XTandemInfile_test.xml
src/tests/class_tests/openms/data/XTandemInfile_test_write.xml
src/tests/class_tests/openms/source/XTandemInfile_test.cpp
src/topp/XTandemAdapter.cpp

The use_noise_suppression flag is added to XTandemAdapter. Resolves #1392.

new flag use_noise_suppression in XTandemAdapter

---

src/openms/source/MATH/MISC/CubicSpline2d.cpp

joining loops -- shaving off another 10% -- the more points in the spline, the more effective this is
followup of #1401

Cubic Spline -- 2nd

---

src/openms/include/OpenMS/FORMAT/PercolatorOutfile.h
src/openms/source/FORMAT/PercolatorOutfile.cpp

fix Windows compile errors

---

src/openms/include/OpenMS/CHEMISTRY/Enzyme.h
src/openms_gui/source/VISUAL/MISC/GUIHelpers.cpp
src/pyOpenMS/pxds/EnzymaticDigestion.pxd
src/pyOpenMS/pxds/Enzyme.pxd
src/pyOpenMS/tests/unittests/test000.py

fixes a mac osx compile error introduced in #1454

[FIX] fix compiler errors for GUIHelpers on mac osx

---

doc/TOPP_tutorial/TOPPView_interface.doxygen
src/openms/source/ANALYSIS/ID/AScore.cpp
src/openms_gui/include/OpenMS/VISUAL/Spectrum1DCanvas.h
src/openms_gui/include/OpenMS/VISUAL/Spectrum2DCanvas.h
src/openms_gui/include/OpenMS/VISUAL/Spectrum3DCanvas.h
src/openms_gui/include/OpenMS/VISUAL/SpectrumCanvas.h
src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
src/openms_gui/source/VISUAL/Spectrum3DCanvas.cpp
src/openms_gui/source/VISUAL/SpectrumCanvas.cpp

... in 1D view by holding Shift (+ ArrowKey) -- useful to jump around in sparse data while being zoomed in

TOPPView: enable viewing the next data point 

---

src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
src/openms_gui/source/VISUAL/SpectrumCanvas.cpp

amending #1467
- fixed scroll bug for 'left'
- fixed cppcheck errors

fix for #1467

---

src/openms/include/OpenMS/SYSTEM/StopWatch.h
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/SYSTEM/StopWatch.cpp

A minor restructuring
- add toString() convenience function (I omitted an ostream operator since this would add another dependency and is not really required)
- move code from .h to .cpp

[INTERNAL] StopWatch

---

src/utils/AccurateMassSearch.cpp
src/utils/Digestor.cpp
src/utils/DigestorMotif.cpp
src/utils/IDDecoyProbability.cpp
src/utils/IDEvaluator.cpp
src/utils/IDExtractor.cpp
src/utils/IDMassAccuracy.cpp
src/utils/IDSplitter.cpp
src/utils/QCCalculator.cpp
src/utils/RNPxl.cpp
src/utils/RTAnnotator.cpp
src/utils/RTEvaluation.cpp
src/utils/SequenceCoverageCalculator.cpp
src/utils/SvmTheoreticalSpectrumGeneratorTrainer.cpp

I had done this before for the TOPP tools, but missed the UTILS. Here it is now for the UTILS.

Improved wording of note regarding mzid support

---

doc/TOPP_tutorial/TOPPAS.doxygen
src/openms/include/OpenMS/ANALYSIS/ID/PeptideProteinResolution.h
src/openms/include/OpenMS/FILTERING/TRANSFORMERS/SpectraMerger.h
src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.h
src/openms/source/ANALYSIS/ID/PeptideProteinResolution.cpp
src/openms/source/ANALYSIS/OPENSWATH/ChromatogramExtractor.cpp
src/openms/source/FORMAT/PepXMLFile.cpp
src/openms/source/FORMAT/VALIDATORS/MzMLValidator.cpp

some more spelling errors fixed

[FIX-#618] fix spelling errors

---

src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.h
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerMaxima.cpp

reformat mostly, change order of statements in `if`

[FIX] format maxima and hires the same way

---

src/pyOpenMS/pxds/Residue.pxd

[FIX,PYOPENMS] after #1440

---

src/openms/include/OpenMS/CONCEPT/FuzzyStringComparator.h
src/openms/source/CONCEPT/FuzzyStringComparator.cpp
src/tests/topp/CMakeLists.txt
src/utils/FuzzyDiff.cpp

- implement a matched white list in FuzzyDiff
- use it to addresses the new error seen by Timo in #1206

Implement matched whitelist in FuzzyDiff

---

src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentTransformer.h

second attempt to fix windows (#1542 failed)

[FIX] winfix2

---

src/pyOpenMS/pxds/EnzymaticDigestionLogModel.pxd
src/pyOpenMS/tests/unittests/test000.py

[FIX] pyopenms fix

---

tools/ACTIVE_MAINTAINERS

[NOP] fix name in active maintainers

---

src/topp/MSGFPlusAdapter.cpp

The error message of MSGFPlusAdapter was updated. Resolves #1517.

[DOC] MSGFPlusAdapter error message updated

---

src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedCluster.h
src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.h
src/openms/source/COMPARISON/CLUSTERING/GridBasedCluster.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
src/tests/topp/INIUpdater_1_noupdate.toppas
src/tests/topp/INIUpdater_3_old_out.toppas

Resulted in major speedup (factor ~4) for a dataset I tested.

[NOP] minor optimization to FeatureFinderMultiplex

---

src/openms/source/FORMAT/FeatureXMLFile.cpp

I wish featureXML were faster so this were not necessary

[FEATURE] allow output of progress for featureXML storage

---

src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmPoseClustering.h
src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/PoseClusteringAffineSuperimposer.h
src/openms/source/ANALYSIS/MAPMATCHING/PoseClusteringAffineSuperimposer.cpp
src/tests/class_tests/openms/source/PoseClusteringAffineSuperimposer_test.cpp

- break up 1000 LOC method into smaller pieces
- add docu and comments where I could
- actually explain what is going on !
- replace duplicate code with single method call (two rounds of hashing)
- add interface that works on `std::vector<Peak2D>` instead of `ConsensusMap`
generally clean up code and make it easier to follow

Refactor PoseClustering

---

doc/doxygen/install/install-linux.doxygen

explain how to install OpenMS if you dont have root access

[DOC] installation docs if you dont have root

---

src/tests/topp/CMakeLists.txt

messed up the merge in #1363 - missing tests_properties and confused output name ... 
this should fix it.

[TEST] fix

---

src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp

to elucidate on #1572,
this PR adds more verbosity to the error (also useful for any later errors, which might occur with unstable internet connections etc).
This is no fix for the problem per se, unforturnately... see #1572.

[TOPPAS] make download of TOPPAS a little more verbose

---

src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedCluster.h
src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.h
src/openms/source/COMPARISON/CLUSTERING/GridBasedCluster.cpp
src/openms/source/COMPARISON/CLUSTERING/GridBasedClustering.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp

Should result in a significant speed up of the filtering step

[FIX] minor optimization

---

src/openms/include/OpenMS/KERNEL/MSSpectrum.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.h
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
src/pyOpenMS/pxds/MSSpectrum.pxd
src/tests/class_tests/openms/source/MSSpectrum_test.cpp

New optimization (peak registry build in n log n instead of n²)
Could be done in linear time though for the whole spectrum.
Still, it yields quite big speed imrprovements.

[FEATURE] more speed optimizations

---

src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.h
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp

Extends the optimizations from #1622 to profile mode.

minor optimizations for profile mode

---

src/tests/topp/OpenSwathMzMLFileCacher_1_output_1.mzML
src/tests/topp/OpenSwathMzMLFileCacher_2_output_1.chrom.mzML

small fix for tests: the new files also need indices

[TEST] update new files with indexed mzML

---

src/openms/include/OpenMS/CONCEPT/Helpers.h
src/openms/source/METADATA/MetaInfoDescription.cpp
src/openms/source/METADATA/SpectrumSettings.cpp

- fix DataProcessing comperator
- fix after merging #695
sorry, comparator was wrong

[FIX] DataProcessing comperator fix

---

src/tests/topp/CMakeLists.txt
src/tests/topp/FileFilter_44_input.mzML
src/tests/topp/FileFilter_44_output.mzML

added test for change described in #1641

[TEST] add test for corrupted ms-numpress file

---

.travis.yml

- maybe this fixes the build after #1643 ?

[BUILD] try to fix build

---

src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML
src/tests/topp/THIRDPARTY/MyriMatchAdapter_1_out.idXML
src/tests/topp/THIRDPARTY/XTandemAdapter_2_out.idXML
src/tests/topp/THIRDPARTY/XTandemAdapter_3_out.idXML
src/tests/topp/THIRDPARTY/spectra.mzML
src/topp/MyriMatchAdapter.cpp

[FIX] changed relative path to absolute one so it is the same on every

---

src/openms/include/OpenMS/FORMAT/FileHandler.h
src/openms/include/OpenMS/FORMAT/InspectOutfile.h
src/openms/source/FORMAT/FileHandler.cpp
src/pyOpenMS/pxds/FileHandler.pxd
src/tests/class_tests/openms/source/FileHandler_test.cpp
src/tests/topp/PrecursorMassCorrector_1_output.mzML
src/topp/FileConverter.cpp
src/topp/FileInfo.cpp
src/topp/IDFileConverter.cpp
src/topp/MascotAdapterOnline.cpp
src/topp/OMSSAAdapter.cpp
src/topp/PrecursorMassCorrector.cpp
src/topp/TextExporter.cpp

for hash computation a static public one for use in other parts.

[NOP] made rewriting the SourceFile entry a parameter and private method

---

src/topp/MyriMatchAdapter.cpp

- added more flexible SpectrumFilterLists and ignoreConfigErrors flag
- updated adapter documentation
Fixes #1672

fix MyriMatchAdapter for MyriMatch 2.2

---

src/topp/HighResPrecursorMassCorrector.cpp

- avoid crash when -out_CSV file is requested
- better docs
- more failsafe code and error messages
Fixes  #1651.

Improvements/Fixes to HighResPrecursorMassCorrector

---

src/openms/include/OpenMS/SYSTEM/File.h
src/openms/source/SYSTEM/File.cpp
src/tests/class_tests/openms/source/File_test.cpp

variable (e.g. for parallel installation of KNIME, PD nodes)
@hannesveit

[FEATURE] make OpenMS home directory configurable by environmental

---

share/OpenMS/SCRIPTS/mzTab2tsv_PRT.R
share/OpenMS/SCRIPTS/mzTab2tsv_PSM.R
share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PEP.ttd
share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PRT.ttd
share/OpenMS/TOOLS/EXTERNAL/Rscript_mzTab2tsv_PSM.ttd

The `PRT` section of the `mzTab` format changed slightly. The pull request adjust the R script for the change.

fixes mzTab to tsv R scripts and wrappers

---

src/openms/include/OpenMS/DATASTRUCTURES/String.h

[FEATURE, FIX] fixed bug in comparison operator, added default

---

src/pyOpenMS/tests/integration_tests/test_MRMRTNormalizer.py
src/pyOpenMS/tests/unittests/test000.py
src/pyOpenMS/tests/unittests/test_ChromatogramExtractorAlgorithm.py
src/pyOpenMS/tests/unittests/test_SpectraFilter.py

complete build and test run with Python 3 revealed some failing tests. These are
mostly issues with string handling.
This commit fixes these.

[FIX,TEST] fix tests for Python 3

---

src/openms/source/FORMAT/FeatureXMLFile.cpp
src/tests/class_tests/openms/data/FeatureXMLFile_1.featureXML

[FIX] fixed #1735 added resp. test

---

src/openms/source/FORMAT/ConsensusXMLFile.cpp
src/tests/class_tests/openms/data/ConsensusXMLFile_1.consensusXML
src/tests/topp/FileFilter_18_output.consensusXML
src/tests/topp/FileFilter_19_output.consensusXML
src/tests/topp/IDConflictResolver_2_output.consensusXML

[FIX]#1735 for ConsensusXMLFile

---

src/openms/source/ANALYSIS/OPENSWATH/DATAACCESS/SpectrumAccessOpenMSInMemory.cpp

@hroest @grosenberger this fixes a compile error I get on gcc. Does this fix trigger a compile error on your platform?

[FIX] gcc compile error

---

README.md

- link to openhub
- add link to current docu

[DOC] update README

---

src/openms/include/OpenMS/FORMAT/PepXMLFile.h
src/openms/source/FORMAT/PepXMLFile.cpp
src/tests/class_tests/openms/data/PepXMLFile_test.pepxml
src/tests/class_tests/openms/source/PepXMLFile_test.cpp
src/tests/topp/IDFileConverter_10_output.idXML
src/tests/topp/IDFileConverter_2_output.idXML
src/tests/topp/IDFileConverter_4_output.idXML
src/tests/topp/IDFileConverter_6_output.idXML

[FIX]#1509

---

src/openms/include/OpenMS/FORMAT/PepXMLFile.h
src/openms/source/FORMAT/PepXMLFile.cpp

fix to add missing precursor and fragment mass tolerance  search parameters from comet pepxml

[FIX] added search_parameter reading from comet pep.xml

---

src/openms/include/OpenMS/CHEMISTRY/EnzymaticDigestion.h
src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
src/tests/class_tests/openms/source/EnzymaticDigestion_test.cpp
src/utils/SimpleSearchEngine.cpp

[FEATURE] add option to generate peptides of max length to digestion of

---

src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
src/openms/include/OpenMS/FORMAT/MSNumpressCoder.h
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/FORMAT/MSNumpressCoder.cpp
src/topp/FileFilter.cpp

with Numpress example
i.e.,
```
void TOPPBase::setValidStrings_(const String& name, const std::string vstrings[], int count);
```

more convenient setting of valid strings in TOPPBase

---

src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp

- fix typos in Help
- fix huge inefficiency in initial zero-count filter pop-up;
- layer renaming: prefill dialog with current name

minor improvements to TOPPView

---

src/topp/FileInfo.cpp

Resolves #1549. Needed for #1655.

mzid validation in FileInfo switched on

---

share/OpenMS/TOOLS/EXTERNAL/MascotPercolator.ttd
share/OpenMS/TOOLS/EXTERNAL/Percolator.ttd

We've updated our Percolator installation to the current version from their GitHub. There was a change in some parameters that needs to be reflected in our GenericWrapper for Percolator.

Update wrapper for Percolator

---

src/topp/MzTabExporter.cpp

[FIX] added columns for run level scores in PEP section

---

share/OpenMS/CHEMISTRY/Enzymes.xml

should fix https://github.com/OpenMS/OpenMS/issues/1836

[FIX] fixed conversion of argc enzyme

---

src/tests/topp/CMakeLists.txt

Fixes failed test after #1851.

fixes FileInfo TOPP test

---

src/openms/include/OpenMS/FORMAT/HANDLERS/MzIdentMLHandler.h
src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp

useful for complete pride submissions ;)
addresses multiple identification runs in mzid or multiple fractions of a mass spectrometry experiment

[FIX] fixed multi-identification run merging 

---

doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-macs-bin.doxygen
doc/doxygen/install/install-macs.doxygen
doc/doxygen/install/install-win.doxygen
src/pyOpenMS/FOR_DEVELOPERS
src/pyOpenMS/README
src/pyOpenMS/README.rst

Tried to structure it and make doxygen/HTML syntax more consistent. Also updated a bit of the pyopenms docu.

[DOC] Updated install docu mainly for Linux and Mac

---

src/utils/OpenSwathWorkflow.cpp

This PR fixes a rare problem with #1772 . Replaces #1880 to merge directly with master.

[FIX] Fix for Empty MS1 Chromatogram Segfaults

---

src/pyOpenMS/tests/unittests/test000.py

[TESTS] Updated pyopenms tests according to last pyopenms fix.

---

src/openms/include/OpenMS/CONCEPT/TypeAsString.h
src/tests/class_tests/openms/source/MorphologicalFilter_test.cpp

available in newer non gcc compiler.
also some minor tab changes to the tests

[FIX, TEST, STYLE] fixed tests related to the __PRETTY_FUNCTION__ macro

---

src/tests/topp/CMakeLists.txt

- ensure that temporary files do not overlap and are unique for each
test executed

[FIX] fix names of temporary files

---

src/openms/source/FORMAT/PepXMLFile.cpp

only output error message if more than one modification matches the mass
should fix: https://github.com/OpenMS/OpenMS/issues/1857

[FIX, #1857] Modifications: possibly misleading error message

---

src/topp/ConsensusID.cpp

may fix https://github.com/OpenMS/OpenMS/issues/1914

[FIX] retain spectra_data information in ConsensusID

---

doc/doxygen/install/install-linux-bin.doxygen
doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-macs-bin.doxygen
doc/doxygen/install/install-macs.doxygen
doc/doxygen/install/install-win.doxygen
doc/doxygen/public/ExternalCode.doxygen

Mainly added updated packages that are needed. Restructured a little bit.
Made the doxygen syntax comparable across different pages at some points.
Supersedes PR #1937. Will be merged to develop after release.

Updated documentation for source release 2.0.1

---

doc/doxygen/public/PyOpenMS.doxygen

add better docu for pyOpenMS (esp build docu)

[DOCU] pyopenms documentation

---

src/tests/topp/FileConverter_2_output.mzML
src/tests/topp/FileMerger_2_output.mzML
src/tests/topp/FileMerger_4_output.mzML

[Fix] Fixes tests failing because of non-matching hashes

---

src/tests/topp/FileMerger_2_output.mzML
src/tests/topp/FileMerger_4_output.mzML

[FIX] Forgot hashes for second input file of FileMerger.

---

share/OpenMS/SCRIPTS/InternalCalibration_Models.R
share/OpenMS/SCRIPTS/InternalCalibration_Residuals.R
src/openms/include/OpenMS/FILTERING/CALIBRATION/InternalCalibration.h
src/openms/include/OpenMS/SYSTEM/File.h
src/openms/include/OpenMS/SYSTEM/RWrapper.h
src/openms/include/OpenMS/SYSTEM/sources.cmake
src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp
src/openms/source/SYSTEM/File.cpp
src/openms/source/SYSTEM/RWrapper.cpp
src/openms/source/SYSTEM/sources.cmake
src/tests/topp/CMakeLists.txt
src/topp/InternalCalibration.cpp

with example usage for InternalCalibration.
For the example:
R code is currently placed in share/OpenMS/SCRIPTS, which has the advantage that any user can modify the plots to their need (as opposed to hard-coding the script in C++ strings).
The wrapper can certainly be extended, but the error handling up to this point is quite ok (i.e. the user 
is enabled to fix the problem).

[FEATURE] a basic RWrapper class

---

share/OpenMS/SCRIPTS/InternalCalibration_Models.R
share/OpenMS/SCRIPTS/InternalCalibration_Residuals.R
src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp

- additional safe guards when model building fails

[FIX] InternalCalibration augmenting #1988

---

src/openms_gui/include/OpenMS/VISUAL/Spectrum1DCanvas.h
src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
src/openms_gui/source/VISUAL/SpectrumCanvas.cpp
src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp

[FEATURE] added text box for custom legends / annotations to

---

src/tests/topp/CMakeLists.txt
src/utils/OpenSwathWorkflow.cpp

a few small fixes in logging errors and tests

Fix/small fixes in OpenSWATH 

---

src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp

[FIX] writing ppxl subscores as cv (was user param)

---

README.md

add a "BSD Licence" badge, see https://github.com/hroest/OpenMS/tree/feature/badges

[DOC] add license badge

---

src/openms/include/OpenMS/ANALYSIS/XLMS/OpenXQuestScores.h
src/openms/source/ANALYSIS/XLMS/OpenXQuestScores.cpp
src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
src/utils/PPXL.cpp
src/utils/xQuest.cpp

Implemented multithread support with OpenMP for the XL-MS algorithms for both labeled and unlabeled cross-links.

[FEATURE] OpenMP Multithread support for XL-MS

---

src/utils/TICCalculator.cpp

[FIX] Windows compile error

---

src/pyOpenMS/MANIFEST.in

- exclude examples
- exclude .cpp source file
- exclude large mapping file

[BUILD] adopt manifest to only include relevant files

---

README.md

now that we have a nice new website, maybe we should link to it somewhere ...

[DOC] add link to new website

---

src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGenerator.h
src/openms/source/CHEMISTRY/TheoreticalSpectrumGenerator.cpp
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
src/pyOpenMS/pxds/TheoreticalSpectrumGenerator.pxd
src/tests/class_tests/openms/source/TheoreticalSpectrumGenerator_test.cpp

only create respective immonium ions if amino acid present in sequence

[FEATURE] TSG restrict immonium ions on sequence

---

src/pyOpenMS/addons/String.pyx
src/pyOpenMS/converters/special_autowrap_conversionproviders.py

Reverts OpenMS/OpenMS#2075 - requires new autowrap

Revert "Feature/pyopenms str"

---

src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
src/tests/topp/IDFileConverter_15_output.idXML
src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.mzid

let's see if this fixes the problem

[FIX] also parse retention time from scan time entry

---

src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationDescription.h
src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationModel.h
src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationModelBSpline.h
src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationModelLowess.h
src/openms/include/OpenMS/APPLICATIONS/MapAlignerBase.h
src/topp/MapAlignerIdentification.cpp

Enabled use of the local regression model in MapAlignerIdentification.

[FEATURE] "lowess" transformation model for MapAlignerIdentification

---

src/pyOpenMS/pxds/ReactionMonitoringTransition.pxd

This PR wraps additional functions for ReactionMonitoringTransition.

[FEATURE,PYOPENMS] New functions for RMT

---

src/openms/include/OpenMS/CHEMISTRY/AASequence.h
src/openms/source/CHEMISTRY/AASequence.cpp
src/tests/class_tests/openms/source/AASequence_test.cpp

[FEATURE] remove modification from AASequence residue

---

cmake/knime/remove_parameter_from_ctd.cmake
cmake/knime_package_support.cmake

Changed regex for parameter removal to be more specific. Fixed XTandemAdapter param removal. Added missing Luciphor.
Tries to fix #1828.

[FIX,KNIME] More specific CTD file parameter cleanup and fixes.

---

src/openms/source/APPLICATIONS/TOPPBase.cpp
src/utils/LowMemPeakPickerHiRes_RandomAccess.cpp

See https://raw.githubusercontent.com/WorkflowConversion/CTDSchema/de6110d70afa912dc9aea15203f6d487d4b64037/CTD.xsd for the current CTD version.

Added ctdVersion required attribute to "tool" element

---

src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp

[FIX] remove warnings when closing TOPPAS/TOPPView 

---

doc/CMakeLists.txt

[FIX,BUILD] Fixes problems generating the parameter docu with XCode

---

src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/SYSTEM/UpdateCheck.cpp

should fix  https://github.com/OpenMS/OpenMS/issues/2002

[FIX] change update check message

---

cmake/knime/copy_binaries_ini.cmake
cmake/knime/copy_searchengines.cmake
cmake/knime/copy_share.cmake
cmake/knime/mime.types
cmake/knime/mimetypes.xml
cmake/knime_package_support.cmake
cmake/package_dragndrop_dmg.cmake

Stumbled upon some things while testing KNIME and dmg packaging.
Removes svn specific patterns.
Adds Luciphor in the install scripts.
Extends messages.
Adds mzTab to mimetypes.
Small cleanups.

[BUILD] Preparing knime and install scripts for new release. 

---

src/openms/source/SYSTEM/File.cpp

should be reverted before the release

[FIX] additional debug information on data path

---

cmake/MacOSX/fix_dependencies.rb
cmake/MacOSX/fixdmg.sh
cmake/knime_package_support.cmake
cmake/package_dragndrop_dmg.cmake
src/openms_gui/add_mac_bundle.cmake

Fixes some smaller bugs related to packaging only.

Release2.1.0 packaging changes

---

License.txt

Shortened lines in License for windows installer. Updated thirdparty content.

[FIX] Updated License for Release2.1.0

---

CONTRIBUTING.md

see https://hacktoberfest.digitalocean.com for details

[DOC] add contributing.md for hacktoberfest

---

src/tests/topp/THIRDPARTY/third_party_tests.cmake

For the second MSGF test to avoid failing in compatible new versions.

[FIX] Added whitelist for MSGF Version

---

src/topp/IDFilter.cpp

[PARAM] make the threshold parameter advanced because it was regularly

---

cmake/MacOSX/create_knime_package.sh
cmake/knime_package_support.cmake
src/tests/topp/CMakeLists.txt

PS has been fixed to produce CTD files a while ago. This should reenable it in KNIME.

[FEATURE] reenabled PhosphoScoring in KNIME

---

doc/CMakeLists.txt
doc/OpenMS_tutorial/refman_overwrite.tex.in
doc/TOPP_tutorial/refman_overwrite.tex.in

Improved requirement checks for doc_tutorials and removed deprecated PDF packages.
Addresses #2235.

[DOC] Update Latex packages in PDF docu

---

doc/OpenMS_tutorial/refman_overwrite.tex.in
doc/TOPP_tutorial/refman_overwrite.tex.in

[Fix,Docu] Fixes option clashes in PDF tutorials on some Linux systems.

---

doc/CMakeLists.txt

Forgot substitution of one variable.
Converted indentation to spaces.
Sorry for another PR but I am testing this with the nightlies since I do not have XCode set up. These fixes might actually also concern Visual Studio.

[Fix] More changes to make XCode documentation work

---

share/OpenMS/SCRIPTS/InternalCalibration_Models.R
share/OpenMS/SCRIPTS/InternalCalibration_Residuals.R
src/openms/include/OpenMS/SYSTEM/RWrapper.h
src/openms/source/CONCEPT/LogStream.cpp
src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp
src/openms/source/SYSTEM/RWrapper.cpp

Merge PR #2255

---

share/OpenMS/SCRIPTS/InternalCalibration_Models.R
share/OpenMS/SCRIPTS/InternalCalibration_Residuals.R
src/openms/include/OpenMS/SYSTEM/RWrapper.h
src/openms/source/CONCEPT/LogStream.cpp
src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp
src/openms/source/FILTERING/DATAREDUCTION/MassTraceDetection.cpp
src/openms/source/SYSTEM/RWrapper.cpp

fixes #2251
[FIX] InternalCalibration: much better error descriptions if Rscript executable is not found or broken.
[FIX] InternalCalibration: R script to generate ppm-error plots now works properly with large peptide ID data

InternalCalibration: better debug messages for R scripts

---

share/OpenMS/TOOLS/EXTERNAL/ReadMe.txt
share/OpenMS/TOOLS/EXTERNAL/TEMPLATE.ttd_
src/topp/GenericWrapper.cpp

fixes #2277
[FIX] GenericWrapper now handles required-attribute of parameter lists correctly.
[DOC] GenericWrapper: Some documentation about quoting.

GenericWrapper: handling of 'required' attribute for Input/Output-Lists

---

src/utils/OpenMSInfo.cpp

[FIX] OpenMSInfo sizeof

---

doc/doxygen/install/install-linux-bin.doxygen
doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-win-bin.doxygen

…Including new OS versions, tested install instructions, corrected typos, added links and reflow.

[NOP][DOC] Updated the documentation pages of the installers. 

---

src/openms/source/SYSTEM/UpdateCheck.cpp
src/tests/topp/CMakeLists.txt

@hroest readded update check functionality after PR "[FIX] address missing OpenMS.ini problem"

[FIX] fixed update check after writing of .ini is not mandatory any more

---

src/tests/topp/CMakeLists.txt

a few cases where the -test flag was missing
not sure about write_ini things though...

[TEST] add -test flag

---

src/utils/MultiplexResolver.cpp

The pull request corrects the syntax of a double for-loop structure.

correction of loop syntax

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMassesGenerator.cpp
src/topp/FeatureFinderMultiplex.cpp
src/utils/MultiplexResolver.cpp

Removes some warnings due to variable shadowing and incorrect for-loop syntax.

fixes some warnings

---

src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.cpp

[FIX] param value without brackets [see #2358]

---

cmake/knime/mime.types
cmake/knime/mimetypes.xml
src/openms/include/OpenMS/FORMAT/FileTypes.h
src/openms/source/FORMAT/FileTypes.cpp
src/topp/RTModel.cpp
src/topp/RTPredict.cpp

Fixes #2361 and #632 and some warnings.

[Fix] Kerneldep. RTModel outputs/ RTPredict inputs

---

src/openms/source/ANALYSIS/MAPMATCHING/FeatureGroupingAlgorithmKD.cpp
src/openms/source/ANALYSIS/QUANTITATION/KDTreeFeatureNode.cpp

Found this in a Windows nighlty build.

Replaced GCC Pretty_function with our new definition

---

src/pyOpenMS/pxds/IDMapper.pxd

[PYOPENMS] fix pyopenms wrapper

---

doc/OpenMS_tutorial/refman_overwrite.tex.in
doc/TOPP_tutorial/refman_overwrite.tex.in

http://tex.stackexchange.com/questions/29739/conditional-loading-of-tocloft-causes-errors

[FIX/DOC] Enclosed \@commands in Latex Tutorial

---

share/OpenMS/CV/qc-cv.obo
share/OpenMS/XSL/QcML_report_sheet.xsl
src/utils/QCCalculator.cpp

and adapted cv and stylesheet for report.

[FEAT] added feature numbers, charge info, and RIC in QC, 

---

share/OpenMS/CHEMISTRY/unimod.xml
src/openms/include/OpenMS/ANALYSIS/RNPXL/HyperScore.h
src/openms/include/OpenMS/ANALYSIS/RNPXL/PScore.h
src/openms/include/OpenMS/ANALYSIS/XLMS/OpenProXLUtils.h
src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGeneratorXLMS.h
src/openms/include/OpenMS/KERNEL/MSSpectrum.h
src/openms/source/ANALYSIS/RNPXL/HyperScore.cpp
src/openms/source/ANALYSIS/XLMS/OpenProXLUtils.cpp
src/openms/source/CHEMISTRY/TheoreticalSpectrumGeneratorXLMS.cpp
src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
src/tests/class_tests/openms/data/MzIdentML_XLMS_labelled.mzid
src/tests/class_tests/openms/data/MzIdentML_XLMS_unlabelled.mzid
src/tests/class_tests/openms/source/HyperScore_test.cpp
src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp
src/tests/class_tests/openms/source/PScore_test.cpp
src/utils/OpenProXL.cpp
src/utils/OpenProXLLF.cpp
src/utils/RNPxlSearch.cpp
src/utils/SimpleSearchEngine.cpp

implemented a new TheoreticalSpectrumGeneratorXLMS (for XL-MS search engine), that uses PeakSpectrum with IntegerDataArrays and StringDataArrays instead of RichPeakSpectrum.

Feature/ppxlink, new SpectrumGenerator

---

src/openms/source/COMPARISON/CLUSTERING/ClusteringGrid.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp

Follow-up pull request to #2069. The margin is slightly  increased from `1e-15` to `1e-10`.
Fixes #2401.

increase margin of clustering grid

---

src/tests/topp/OpenSwathWorkflow_11_output.featureXML

- after merging PR #2315 and #2316 the test for the SONAR data changed
and needs to be adopted

[TEST,FIX] fix test

---

src/openms/include/OpenMS/FORMAT/DATAACCESS/MSDataAggregatingConsumer.h
src/openms/include/OpenMS/FORMAT/DATAACCESS/MSDataStoringConsumer.h
src/openms/include/OpenMS/FORMAT/DATAACCESS/sources.cmake
src/openms/source/FORMAT/DATAACCESS/MSDataAggregatingConsumer.cpp
src/openms/source/FORMAT/DATAACCESS/MSDataStoringConsumer.cpp
src/openms/source/FORMAT/DATAACCESS/sources.cmake
src/tests/class_tests/openms/executables.cmake
src/tests/class_tests/openms/source/MSDataAggregatingConsumer_test.cpp
src/tests/class_tests/openms/source/MSDataStoringConsumer_test.cpp

- new consumers that allow storage in memory and aggregation of spectra
- add classes for two new consumers, MSDataAggregatingConsumer and
MSDataStoringConsumerMSDataStoringConsumer
- add tests for both classes

[FEATURE] aggregating, storing consumer consumer

---

src/openms/source/ANALYSIS/OPENSWATH/SONARScoring.cpp

[FIX] fix for isnan

---

src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp

[FIX] bugfix in TOPPAS

---

doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-macs.doxygen
doc/doxygen/install/install-win.doxygen

depending on the system, the user of course has to adjust this...

[DOC] document parameter for number of compile jobs

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMAssay.h
src/openms/include/OpenMS/SIMULATION/IonizationSimulation.h
src/tests/class_tests/openms/source/IonizationSimulation_test.cpp

As new boost > 1.52 produces some different random numbers, some of our tests fail. This branch should be used to document and eventually fix these issues.

Update boost compatibility

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.h
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
src/tests/topp/OpenSwathWorkflow_11_output.featureXML

forgotten fix for Sonar: actually write out the data

[FEATURE] write out new OpenSWATH scores in TSV as well

---

doc/TOPP_tutorial/TOPPAS.doxygen
doc/TOPP_tutorial/TOPP_scripting.doxygen

... tutorial. Also added some missing sections.

[Fix] indentation errors leading to codeblocks in verbatim in PDF

---

share/OpenMS/CV/psi-ms.obo

fixes annoying obo warnings
I will propose to upgrade to 4.0.9 soon as soon at is approved as we will have a bunch of new obo terms in there

[FIX] obo fix

---

doc/doxygen/install/install-win.doxygen
tools/build.bat

- added Doc target to build.bat (fixes #2474)
- improved docu for Windows installer

[DOC, FIX-#2474] improved docu for Windows installer & build.bat

---

src/topp/FalseDiscoveryRate.cpp

performed changes decided in https://github.com/OpenMS/OpenMS/issues/2465

FalseDiscoveryRate: removed redundant parameters, simplified tool

---

src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.cpp
src/utils/LowMemPeakPickerHiRes.cpp

addresses the parameter issues in https://github.com/OpenMS/OpenMS/issues/2459

[PARAM] disable SN estimation by default, pick only MS1 by default

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/DATAACCESS/MRMFeatureAccessOpenMS.h
src/openms/source/KERNEL/MRMTransitionGroup.cpp
src/openswathalgo/include/OpenMS/ANALYSIS/OPENSWATH/OPENSWATHALGO/DATAACCESS/TransitionExperiment.h

... that have implementations already in header files.
Follow-up on https://github.com/OpenMS/OpenMS/pull/2489 together with @cbielow .
Fine for you @hroest  ?

[FIX] Removed OPENMS_DLLAPI from class templates

---

src/pyOpenMS/tests/unittests/testLightTargetedExperiment.py

probably fixes tests after #2518

[TEST] fixes test

---

src/topp/FileInfo.cpp

difference can be negative (estimate via Windows API seems inaccurate) and since we are only using unsigned types, the results could look like
`Memory usage while loading:  18822392323423 MB`
but should have been (rounded to MB, i.e. no change)
`Memory usage while loading: 0 MB`
This PR fixes it.

fix display of memory in FileInfo

---

src/openms/source/CHEMISTRY/AASequence.cpp
src/tests/class_tests/openms/source/AASequence_test.cpp

- fixes #2532 
- I decided to add a few PRECONDITION checks for developers so that we are aware if we do something potentially wrong and try to calculate illegal masses etc.
the downside of this PR is that we dont really have a good way for testing the behavior

[FIX] fix X residue mass

---

src/pyOpenMS/tests/unittests/test000.py

test fix
not sure why it now selects a different mod, but it does

[TEST] fix pyopenms test

---

cmake/modules/FindSQLITE.cmake

[FIX] search in contrib includes for sqlite (addresses #2564)

[FIX] search in contrib includes for sqlite (adresses #2564)

---

src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
src/tests/topp/ExternalCalibration_1_MS1_out.mzML
src/tests/topp/ExternalCalibration_2_MS2_out.mzML
src/tests/topp/FileFilter_31_remove_collision_energy.mzML
src/tests/topp/FileFilter_33_remove_isolation_window.mzML
src/tests/topp/HighResPrecursorMassCorrector_1035_1178_4_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_2538_1091_2_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_2810_1091_3_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_2860_1103_3_out.mzML
src/tests/topp/HighResPrecursorMassCorrector_3070_1191_3_out.mzML

- fixes #2569
- CV terms obo and the source code were out of sync

[FIX] adopt to CV terms

---

src/tests/topp/CMakeLists.txt
src/tests/topp/IDConflictResolver_3_input.consensusXML
src/tests/topp/IDConflictResolver_3_output.consensusXML
src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/topp/IDConflictResolver.cpp

[FIX] Added support for unidentified features (no PepHits) to IDConflictResolver

---

src/openms/include/OpenMS/DATASTRUCTURES/Param.h
src/openms/source/DATASTRUCTURES/Param.cpp
src/openms/source/FORMAT/HANDLERS/ParamXMLHandler.cpp

Should fix #2544 and the IDMapper problem that we currently have in KNIME.

[FIX] Add empty sections with description right when encountered in paramXMLs.

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TransitionTSVReader.h
src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVReader.cpp
src/utils/OpenSwathWorkflow.cpp

allows to skip a few invalid peptides and still read in the whole
library - maybe a good solution for some cases.

[FEATURE] add force flag to OpenSwath

---

doc/doxygen/public/TOPP.doxygen
doc/doxygen/public/UTILS.doxygen
src/openms/source/APPLICATIONS/ToolHandler.cpp
src/topp/FeatureLinkerUnlabeledKD.cpp
src/topp/PhosphoScoring.cpp
src/utils/LowMemPeakPickerHiRes.cpp
src/utils/LowMemPeakPickerHiRes_RandomAccess.cpp
src/utils/MRMTransitionGroupPicker.cpp
src/utils/MetaboliteSpectralMatcher.cpp
src/utils/MultiplexResolver.cpp
src/utils/OpenMSInfo.cpp
src/utils/OpenSwathDIAPreScoring.cpp
src/utils/OpenSwathFileSplitter.cpp
src/utils/OpenSwathRewriteToFeatureXML.cpp
src/utils/PeakPickerIterative.cpp
src/utils/SpectraSTSearchAdapter.cpp
src/utils/TICCalculator.cpp
src/utils/TargetedFileConverter.cpp

correct links to our utils and topp tools

[DOC] fix documentation

---

src/openms/source/METADATA/PeptideIdentification.cpp
src/tests/topp/CMakeLists.txt
src/tests/topp/FalseDiscoveryRate_6_input.idXML
src/tests/topp/FalseDiscoveryRate_6_output.idXML
src/tests/topp/FalseDiscoveryRate_7_input.idXML
src/tests/topp/FalseDiscoveryRate_7_output.idXML
src/topp/FalseDiscoveryRate.cpp
src/topp/MzTabExporter.cpp

- reworked parameters (changed flag to true / false string option with better logic)
- allow FDR control in FDR tool

[PARAM,TOOL] FalseDiscoveryRate filter in tool

---

src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGenerator.h

[DOC] improved TSG documentation

---

src/openms/include/OpenMS/ANALYSIS/RNPXL/PScore.h
src/openms/source/ANALYSIS/RNPXL/PScore.cpp
src/tests/class_tests/openms/source/PScore_test.cpp

fixed https://github.com/OpenMS/OpenMS/issues/2633

[TEST] adapted PScore test

---

cmake/knime_package_support.cmake

Not tested yet!
Affects only Windows?

Include sqlite into KNIME packaging

---

src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLHelper.h
src/openms/source/ANALYSIS/XLMS/XQuestScores.cpp
src/openms/source/MATH/STATISTICS/CumulativeBinomial.cpp

adresses #2644 and a remaining issue in #2443

[FIX] fixed ambiguous function calls with casts and removed C11 code

---

src/pyOpenMS/tests/unittests/test000.py

[TEST] fix tests

---

src/tests/topp/CMakeLists.txt

[TEST/FIX] remove hardcoded tmp directory

---

src/tests/topp/IDMapper_4_input.idXML
src/tests/topp/IDMapper_4_output.featureXML
src/tests/topp/IDMapper_5_input.idXML
src/tests/topp/IDMapper_5_output.featureXML

In IDMapper_test4 and 5. Affecting missed cleavages.

[FIX] Removed high.. potentially overflowing/problematic number

---

doc/doxygen/install/install-macs.doxygen

Especially the installation of QT.

Update documentation for Mac

---

src/pyOpenMS/pxds/FeatureFindingMetabo.pxd

[Fix] Python bindings FFMetabo

---

src/openms/source/ANALYSIS/ID/AScore.cpp

[FIX] AScore, fixed order of conditions in a while-loop

---

README.md

[DOC] Updated to macOS in Readme

---

src/pyOpenMS/pyTOPP/MRMTransitionGroupScorer.py

minor fix and improvement of pyTOPP tool

[PYOPENMS] improve pyTOPP tool

---

.travis.yml
tools/travis/lnx-cibuild.before.sh

[TRAVIS] get coin through package management

---

src/openms/include/OpenMS/CHEMISTRY/EnzymaticDigestion.h
src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
src/tests/class_tests/openms/source/EnzymaticDigestion_test.cpp

fixed wrong generation of peptides if unspecific cleavage was selected

[FIX] EnzymaticDigestion for unspecfic cleavage

---

src/pyOpenMS/tests/unittests/test000.py

[FIX] fix Python 3.x tests

---

src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h

- fixes #2750 
- replaces #2754

[FIX] fix for gcc7

---

License.txt

For #2482 and #2478.
Plus some cleanup

Added licenses of new thirdparty tools.

---

src/pyOpenMS/pxds/BilinearInterpolation.pxd

[PYOPENMS] wrap BilinearInterpolation

---

src/openms/source/APPLICATIONS/ToolHandler.cpp

[FIX] XFDR now in util_map instead of tool_map

---

tools/travis/lnx-cibuild.before.sh
tools/travis/osx-cibuild.before.sh

For Thirdparties. So that Sirius merge works. https://github.com/OpenMS/THIRDPARTY/pull/14

[TRAVIS] introduce more robust svn export

---

src/openms/include/OpenMS/CONCEPT/Exception.h
src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
src/openms/source/CONCEPT/Exception.cpp
src/openms/source/FILTERING/DATAREDUCTION/DataFilters.cpp
src/openms/source/FORMAT/ConsensusXMLFile.cpp
src/openms/source/FORMAT/EDTAFile.cpp
src/openms/source/FORMAT/FASTAFile.cpp
src/openms/source/FORMAT/FeatureXMLFile.cpp
src/openms/source/FORMAT/IdXMLFile.cpp
src/openms/source/FORMAT/InspectInfile.cpp
src/openms/source/FORMAT/MSPFile.cpp
src/openms/source/FORMAT/MascotGenericFile.cpp
src/openms/source/FORMAT/MzIdentMLFile.cpp
src/openms/source/FORMAT/MzQuantMLFile.cpp
src/openms/source/FORMAT/MzTabFile.cpp
src/tests/class_tests/openms/source/DataFilters_test.cpp
src/utils/AccurateMassSearch.cpp

Small fix in AccurateMassSearch, and improvement of the error messages for invalid file types.

Fix for #2783 (AccurateMassSearch, output file types)

---

src/pyOpenMS/pxds/ConsensusMap.pxd
src/pyOpenMS/pxds/FeatureMap.pxd
src/pyOpenMS/pxds/MSExperiment.pxd
src/pyOpenMS/pxds/ProteinIdentification.pxd

follow up for #2765 and pyopenms

Update pxds for recent changes to getPrimaryRunPath

---

src/openms/source/SYSTEM/StopWatch.cpp
src/tests/class_tests/openms/source/StopWatch_test.cpp

and try to add getSystemTime for unix

[FIX/TESTS] StopWatch increase potential system time during a wait 

---

src/tests/topp/THIRDPARTY/OMSSAAdapter_1.ini
src/topp/CometAdapter.cpp
src/topp/MSGFPlusAdapter.cpp
src/topp/MyriMatchAdapter.cpp
src/topp/OMSSAAdapter.cpp

unified several precursor mass tolerance parameters of tools and fixed those that are pretty off

[FIX, PARAM] fixed comets and OMSSAs default tolerance.

---

src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h

[FIX] fix for boost 1.64

---

src/utils/RNPxlSearch.cpp

Compensates for monoisotopic peak misassignments

[FEATURE] add option to search also isotopic peak before the annotated

---

src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h

[FIX] Amend to boost164 fix

---

src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/OptimizePick.h
src/openms/source/TRANSFORMATIONS/RAW2PEAK/TwoDOptimization.cpp

[FIX] correct include path for eigen library

---

src/openms/source/FILTERING/NOISEESTIMATION/SignalToNoiseEstimatorMedianRapid.cpp
src/tests/class_tests/openms/source/UniqueIdGenerator_test.cpp

Extension to the submitted fix for boost 1.64 on Debian.
see  #2837, #2790

[FIX] boost 1.64 

---

src/pyOpenMS/pxds/DeNovoAlgorithm.pxd
src/pyOpenMS/pxds/DeNovoIonScoring.pxd
src/pyOpenMS/pxds/EnzymaticDigestion.pxd
src/pyOpenMS/pxds/ExperimentalDesign.pxd
src/pyOpenMS/pxds/LPWrapper.pxd
src/pyOpenMS/pxds/MSNumpressCoder.pxd
src/pyOpenMS/pxds/MSQuantifications.pxd
src/pyOpenMS/pxds/PeakPickerMaxima.pxd
tools/travis/lnx-cibuild.before.sh

- at the moment, attaching of classes is not possible.
- still needs some work on the autowrap side

[FIX] attaching of classes

---

src/openms/source/ANALYSIS/RNPXL/HyperScore.cpp

small speedup of hyperscore (10%)

[NOP] prevent some copies by making stuff const

---

src/utils/SiriusAdapter.cpp

fix: Wrong format for TOPPAS output. 
(Should not have anything to do with nightly)

[FIX] Format Output TOPPAS

---

src/openms/include/OpenMS/KERNEL/MSSpectrum.h

this fixes the build issue so I would like to merge this quickly. @enetz it currently doesn't check for the presence of the name and if it is missing we probably get a segfault. Best way would probably be to return the iterator but then the function is not easily wrapped with pyOpenMS.

[FIX] fix return a reference to local variable.

---

tools/travis/lnx-cibuild.sh

[TEST/TOPP] Add new tools to PATH in travis

---

src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/utils/SiriusAdapter.cpp

Had to change other database related parameters in SiriusAdapter

[FIX] Further changes database SiriusAdapter

---

src/pyOpenMS/pxds/RNPxlReport.pxd
src/pyOpenMS/tests/unittests/test_StandardTypes.py

[FIX] fix pyOpenMS

---

src/openms/source/FORMAT/DATAACCESS/CsiFingerIdMzTabWriter.cpp
src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp
src/tests/topp/THIRDPARTY/SiriusAdapter_1_output.mzTab
src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/utils/SiriusAdapter.cpp

Synchronizes develop with master again. Necessary for successful third-party tests for SiriusAdapter.

Synchronize develop with master

---

CHANGELOG

Concerns the release 2.3 changelog. Open for changes and more details to individual items.

[RELEASE_2_3] First version of new CHANGELOG

---

tools/checker.php
tools/common_functions.php

The script should no longer crash with recents versions of PHP.

[FIX,TOOLS] Replace ereg by preg_match in checker.php

---

src/pyOpenMS/create_cpp_extension.py
src/pyOpenMS/tests/unittests/collections_.py

http://python-future.org/compatible_idioms.html#octal-constants

[FIX] Change code in Python stuff that is not gonna work in Python 3

---

doc/TOPP_tutorial/TOPP_scripting.doxygen
src/openms/include/OpenMS/ANALYSIS/ID/PercolatorFeatureSetHelper.h
src/openms/include/OpenMS/ANALYSIS/MRM/ReactionMonitoringTransition.h
src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TransitionTSVReader.h
src/openms/include/OpenMS/ANALYSIS/QUANTITATION/ProteinResolver.h
src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLHelper.h
src/openms/include/OpenMS/CHEMISTRY/ResidueModification.h
src/openms/include/OpenMS/DATASTRUCTURES/Compomer.h
src/openms/include/OpenMS/DATASTRUCTURES/KDTree.h
src/openms/include/OpenMS/FILTERING/ID/IDFilter.h
src/openms/include/OpenMS/FORMAT/FASTAFile.h
src/openms/include/OpenMS/FORMAT/MzTabFile.h
src/openms/include/OpenMS/METADATA/ExperimentalDesign.h
src/openms/include/OpenMS/METADATA/InstrumentSettings.h
src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/TwoDOptimization.h
src/openms/source/ANALYSIS/DECHARGING/ILPDCWrapper.cpp
src/openms/source/ANALYSIS/QUANTITATION/ProteinResolver.cpp
src/openms/source/FORMAT/EDTAFile.cpp
src/openms/source/FORMAT/HANDLERS/MzDataHandler.cpp
src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
src/openms/source/METADATA/InstrumentSettings.cpp
src/openms/source/SIMULATION/IonizationSimulation.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/OptimizePick.cpp
src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
src/pyOpenMS/pxds/InstrumentSettings.pxd
src/topp/MzTabExporter.cpp
tools/spellcheck/correct_words.txt

Release 2 3/spellcheck

---

src/pyOpenMS/MANIFEST.in
src/pyOpenMS/create_cpp_extension.py
src/pyOpenMS/fix_pyopenms_dependencies_on_mac.sh
src/pyOpenMS/pyopenms/sysinfo.py

Updated PR against master for https://github.com/OpenMS/OpenMS/pull/2821.

[FIX] pyOpenMS macOS fixes

---

src/tests/class_tests/openms/source/Compomer_test.cpp

[NOP] warning for double promotion

---

cmake/knime_package_support.cmake

Remove Executable from SiriusAdapter Node

[Fix] Executable KNIME SiriusAdapter

---

cmake/MacOSX/TOPP_bash_profile
src/openms/source/SYSTEM/File.cpp

[Fix] find executables for toppas bundle macOS

---

src/utils/SiriusAdapter.cpp

Fixes issue in SiriusAdapter that the SIRIUS_PATH variable has not been used in KNIME.

[FIX] In SiriusAdapter,  SIRIUS_PATH is now being used when set and executable is empty 

---

src/openms/include/OpenMS/ANALYSIS/ID/AhoCorasickAmbiguous.h
src/openms/include/OpenMS/DATASTRUCTURES/SeqanIncludeWrapper.h

fix compile error on Win10/VS2015 (duplicate definition of snprintf)

---

cmake/package_general.cmake
src/openms/include/OpenMS/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.h
src/openms/include/OpenMS/ANALYSIS/ID/AhoCorasickAmbiguous.h
src/openms/include/OpenMS/ANALYSIS/ID/PercolatorFeatureSetHelper.h
src/openms/include/OpenMS/ANALYSIS/ID/SiriusMSConverter.h
src/openms/include/OpenMS/CHEMISTRY/SpectrumAnnotator.h
src/openms/include/OpenMS/FORMAT/DATAACCESS/CsiFingerIdMzTabWriter.h
src/openms/include/OpenMS/FORMAT/DATAACCESS/SiriusMzTabWriter.h
src/openms/include/OpenMS/FORMAT/HANDLERS/XQuestResultXMLHandler.h
src/openms/include/OpenMS/FORMAT/XQuestResultXMLFile.h
src/openms/include/OpenMS/METADATA/ExperimentalDesign.h
src/openms/source/ANALYSIS/ID/AhoCorasickAmbiguous.cpp
src/openms/source/ANALYSIS/ID/PercolatorFeatureSetHelper.cpp
src/openms/source/ANALYSIS/ID/SiriusMSConverter.cpp
src/openms/source/CHEMISTRY/SpectrumAnnotator.cpp
src/openms/source/FORMAT/DATAACCESS/CsiFingerIdMzTabWriter.cpp
src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp
src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp
src/openms/source/FORMAT/XQuestResultXMLFile.cpp
src/openms/source/METADATA/ExperimentalDesign.cpp
src/tests/class_tests/openms/source/AhoCorasickAmbiguous_test.cpp
src/tests/class_tests/openms/source/MetaboliteFeatureDeconvolution_test.cpp
src/tests/class_tests/openms/source/PeptideIndexing_test.cpp
src/topp/CometAdapter.cpp
src/topp/PercolatorAdapter.cpp
src/utils/PSMFeatureExtractor.cpp
src/utils/SiriusAdapter.cpp
src/utils/XFDR.cpp

old remnants fixed (2016 and 2015)

fixed copyright year

---

src/tests/topp/THIRDPARTY/PercolatorAdapter_1_out.idXML

* new test files
* new test files

Fix/percolator category (#2937)

---

src/utils/MSSimulator.cpp

[DOC] add documention for PTM simulation

---

run_integrationtest.py
src/pyOpenMS/run_integrationtest.py

Moved Py File to src/pyOpenMS

---

src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
src/openms/source/APPLICATIONS/TOPPBase.cpp

for use in e.g. KNIME.
Unfortunately CTD 1.7 only supports the use of a doi or url.
I am in touch with Luis to do a schema change, soon.

[Feature] Added support for writing citations to CTD

---

src/openms/include/OpenMS/CONCEPT/Init.h
src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGenerator.cpp
src/openms/source/CONCEPT/Init.cpp
src/openms/source/CONCEPT/sources.cmake

[FEATURE] add library init routine

---

src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp
src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPReader.cpp
src/tests/topp/TargetedFileConverter_1_output.TraML
src/tests/topp/TargetedFileConverter_2_output.TraML

This PR against master replaces PR https://github.com/OpenMS/OpenMS/pull/2971.

[FIX] Patch for OpenSWATH PQP File Conversion (master)

---

src/openms/include/OpenMS/ANALYSIS/ID/AhoCorasickAmbiguous.h
src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h
src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp

converted NFA to DFA, potentially saving 50% of transitions.
Actual speedup is 20-30% for the AC itself.
+ some better internal docs 
+ fixed a bug when PeptideIndexer found no decoy proteins (idXML annoation was incomplete for all proteinhits)

Aho-Corasick DFA

---

src/pyOpenMS/pxds/ChromatogramTools.pxd

Small fix to update ChromatogramTools.pxd to match ChromatogramTools.cpp input

[FIX] updated ChromatogramTools pxd file

---

src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp
src/openms/source/FORMAT/MRMFeatureQCFile.cpp

Implemented testing for empty strings before converting to double or integer values from .csv user input.

[FIX] test input conversion errors in MRMFeatureQCFile

---

CHANGELOG
src/openms/source/APPLICATIONS/ToolHandler.cpp
src/tests/topp/CMakeLists.txt
src/tests/topp/LowMemPeakPickerHiRes_RandomAccess_output.mzML
src/tests/topp/LowMemPeakPickerHiRes_RandomAccess_parameters.ini
src/utils/LowMemPeakPickerHiResRandomAccess.cpp
src/utils/executables.cmake

LowMemPeakPickerHiResRandomAccess

[FIX] renamed LowMemPeakPickerHiRes_RandomAccess to

---

src/openms/include/OpenMS/FORMAT/CsvFile.h
src/openms/source/FORMAT/CsvFile.cpp
src/tests/class_tests/openms/source/CsvFile_test.cpp

Completing the class with a `fstore()` method.

[FEATURE] CsvFile::fstore()

---

doc/doxygen/public/FAQ.doxygen
src/pyOpenMS/pxds/AdductInfo.pxd
src/pyOpenMS/pxds/ChromExtractParams.pxd
src/pyOpenMS/pxds/CumulativeBinomial.pxd
src/pyOpenMS/pxds/ElutionModelFitter.pxd
src/pyOpenMS/pxds/MSDataAggregatingConsumer.pxd
src/pyOpenMS/pxds/MSDataSqlConsumer.pxd
src/pyOpenMS/pxds/MSDataStoringConsumer.pxd
src/pyOpenMS/pxds/OPXLDataStructs.pxd
src/pyOpenMS/pxds/OpenSwathOSWWriter.pxd
src/pyOpenMS/pxds/PercolatorFeatureSetHelper.pxd
src/pyOpenMS/pxds/SpectrumAnnotator.pxd
src/pyOpenMS/pxds/TheoreticalSpectrumGeneratorXLMS.pxd
tools/pychecker_ignore.yaml
tools/travis/lnx-cibuild.before.sh

docu for #3058
add some pyOpenMS additional classes

[DOC] tmpdir docu

---

doc/code_examples/Tutorial_Element.cpp
doc/code_examples/Tutorial_EmpiricalFormula.cpp
doc/code_examples/Tutorial_MSChromatogram.cpp
doc/code_examples/Tutorial_Precursor.cpp
doc/code_examples/executables.cmake

add comments to EmpiricalFormula

[doc] further code/comments for code_examples (Tutorial) 

---

doc/code_examples/Tutorial_Precursor.cpp

Fix for Tutorial_Precursor (automated test)

[FIX] Tutorial_Precursor

---

CHANGELOG
CMakeLists.txt
cmake/MacOSX/TOPP_bash_profile
cmake/install_macros.cmake
cmake/package_dragndrop_dmg.cmake
cmake/package_nsis.cmake
doc/doxygen/install/install-linux-bin.doxygen
src/openms_gui/add_mac_bundle.cmake

This is hopefully the last PR before release.
@timosachsenberg anything else to include here?
Includes #3104.

[Fix] Release fixes

---

tools/PythonExtensionChecker.py

- adopt script
- minor fixes
- add docu

[BUILD] Python extension script

---

src/openswathalgo/source/ANALYSIS/OPENSWATH/OPENSWATHALGO/ALGO/MRMScoring.cpp

[FIX] fix compile error on some systems

---

tools/PythonCheckerLib.py
tools/PythonExtensionChecker.py

[BUILD] make pychecker compatible with Py3

---

src/openms/source/ANALYSIS/OPENSWATH/DATAACCESS/SpectrumAccessSqMass.cpp
src/tests/class_tests/openms/source/SpectrumAccessSqMass_test.cpp

(hopefully) fixes http://cdash.openms.de/testDetails.php?test=46614676&build=252902

[FIX] fix out of bounds error

---

src/pyOpenMS/tests/memoryleaktests/testAll.py

[TEST] test fix

---

tools/create-manylinux.sh

docker script to produce the manylinux wheels

[BUILD] pyOpenMS build script for Linux

---

cmake/knime/binaries_lnx.ini
cmake/knime/binaries_mac.ini
cmake/knime/binaries_win.ini

[Fix] thirdparties binaries ini (Percolator, SpectraST)

---

src/pyOpenMS/pxds/TargetedExperimentHelper.pxd

This fixes it on Windows. Does it make sense?

[FIX] pyopenms enum for win

---

src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp

This PR fixes https://github.com/OpenMS/OpenMS/issues/3172.

[FIX] TargetedTSVFile: TSV import of ProteinId

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/EGHTraceFitter.cpp

[FIX] Negative sigma when fitting asymm. EGH through optimization

---

src/tests/topp/THIRDPARTY/PercolatorAdapter_1.ini
src/tests/topp/THIRDPARTY/PercolatorAdapter_1_out.idXML
src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/topp/PercolatorAdapter.cpp

This PR enables support for a new Percolator hyperparameter to restrict training to the best scoring PSMs.

[FEATURE] Support of new percolator parameter

---

src/tests/topp/THIRDPARTY/CruxAdapter_1_out.idXML
src/tests/topp/THIRDPARTY/third_party_tests.cmake

[TEST/FIX] Try to fix crux tests by using reverse instead of shuffled

---

src/openms/include/OpenMS/FORMAT/DATAACCESS/SwathFileConsumer.h
src/openms/include/OpenMS/FORMAT/SwathFile.h
src/tests/topp/openswath_tmpfile_4.mzML
src/tests/topp/openswath_tmpfile_ms1.mzML

probably needs changes to the test files...

[FIX] set compression

---

src/pyOpenMS/fix_pyopenms_dependencies_on_mac.sh

This PR updates the macOS patching script and avoids the issue reported in #3202.

[FIX,PYOPENMS] Updated patch for macOS

---

src/openms/CMakeLists.txt

By adding contrib includes first

[FIX?] Tries to fix the include mess

---

src/openms/configh.cmake
src/openms/source/SYSTEM/File.cpp

tries to fix https://github.com/OpenMS/OpenMS/issues/3280

[FIX] Default data path lookups

---

doc/doxygen/install/install-win.doxygen
src/openms_gui/source/VISUAL/TOPPASEdge.cpp
src/openms_gui/source/VISUAL/TOPPASScene.cpp

fixes https://github.com/OpenMS/OpenMS/issues/3207

Feature/qt5: TOPPAS fix

---

src/openms/source/FORMAT/HANDLERS/TraMLHandler.cpp
src/tests/topp/ConvertTSVToTraML_1_input.tsv
src/tests/topp/ConvertTSVToTraML_6_output.TraML
src/tests/topp/ConvertTSVToTraML_output.TraML
src/tests/topp/ConvertTraMLToTSV_output.tsv

escape XML characters in TraML

[FIX] fix special XML characters for TraML

---

src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp

Small fix to remove the printing of warnings to the console that are not useful during analysis.

fix: changed log_info to log_debug in MRMFeatureFilter

---

src/pyOpenMS/pyopenms/__init__.py
src/pyOpenMS/setup.py
tools/create-manylinux.sh

Revert "[QT5] pyOpenMS packaging from hroest"

---

src/utils/MSFraggerAdapter.cpp
src/utils/NovorAdapter.cpp
src/utils/SiriusAdapter.cpp

Add error handling to NovorAdapter, MSFraggerAdapter, [fix] SiriusAdapter
MSFragger
- remove symlinks 
- delete additional files (y.1.pepindex; .pepXML (if not optional output)) 
#3336 #3335

[FEATURE] Error handling Adapter; [FIX] MSFragger symlink fix

---

src/utils/OpenSwathWorkflow.cpp

fixes some typos, variable names and file extension checks

minor internal fixes for SWATH UTIL

---

doc/CMakeLists.txt
doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-macs.doxygen
doc/doxygen/install/install-win.doxygen

[DOC] fix install instruction for Qt5 (Windows) and doxygen

---

tools/build.bat

[DOC] additional help in case the script fails

---

src/openms_gui/CMakeLists.txt

OpenMS gui include fix 

---

src/topp/PercolatorAdapter.cpp

@MatthewThe is treating the target+decoy as target correct? Then this should fix this issue

[FIX] target+decoy are now treated as target

---

src/tests/topp/CMakeLists.txt
src/tests/topp/FileFilter_47_input.mzML
src/tests/topp/FileFilter_47_input_select.mzML
src/tests/topp/FileFilter_47_output.mzML
src/tests/topp/FileFilter_48_output.mzML
src/topp/FileFilter.cpp

An initial version of MS2 spectra filter capability in FileFilter.
Open for suggestions. Tests will be added.

[FEATURE] filter spectra by similarity

---

src/openms/CMakeLists.txt
src/openms/cmake_findExternalLibs.cmake
src/openms_gui/CMakeLists.txt
src/openms_gui/include/OpenMS/VISUAL/Spectrum3DOpenGLCanvas.h

Qt was included outside of the macro which could lead to system includes prepended before our
contrib includes.

[FEATURE] Remove OpenGL dependency (use Qt)

---

src/openms_gui/include/OpenMS/VISUAL/LayerData.h
src/openms_gui/source/VISUAL/LayerData.cpp
src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp

changes muteable access to different function
allows fixing places in the code where we apparently need a muteable spectrum

const-fix for currentSpectrum

---

src/openms_gui/source/VISUAL/DIALOGS/TOPPASVertexNameDialog.cpp

[FIX] add missing include

---

src/tests/class_tests/openms/source/MzMLFile_test.cpp
src/tests/class_tests/openms/source/MzXMLFile_test.cpp

- add tests for the `transform` functions of MzMLFile and MzXMLFile
- whitespace fixes

[TEST] add transform tests

---

src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/topp/CometAdapter.cpp
src/topp/CruxAdapter.cpp
src/topp/LuciphorAdapter.cpp
src/topp/MSGFPlusAdapter.cpp
src/topp/MaRaClusterAdapter.cpp
src/topp/PercolatorAdapter.cpp
src/topp/XTandemAdapter.cpp
src/utils/MSFraggerAdapter.cpp
src/utils/NovorAdapter.cpp

- Use of QTempDirectory with auto remove functionality if debug level <2
- Always parse std err and std out if exit code != 0
- More unified logging
One could even go further and abstract external process creation/logging as well as improve the temp file handling in TOPPBase (e.g. to cleanup in the destructor).

[FEATURE] More unified and improved error handling in Adapters.

---

README.md

[FEATURE] link pyopenms online docu

---

README.md

side question: is there such a thing as too many badges?

readme: add badge link

---

src/utils/ProteomicsLFQ.cpp

Compiler error: consensus_fraction is not in the correct scope for lines 341 and 344.

[BUILD] fixed scoping of consensus_fraction

---

src/openms/include/OpenMS/FILTERING/DATAREDUCTION/MassTraceDetection.h
src/openms/include/OpenMS/KERNEL/MSExperiment.h
src/openms/source/FILTERING/DATAREDUCTION/MassTraceDetection.cpp
src/utils/ProteomicsLFQ.cpp

This PR enables the estimation of the fwhm.

[FEATURE] first draft of fwhm estimation

---

src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
src/tests/class_tests/openms/source/EnzymaticDigestion_test.cpp
src/utils/SimpleSearchEngine.cpp

fix bug in unspecific digestion of unmodified strings

---

src/topp/CometAdapter.cpp

Comet sets Carbamidomethyl (C) as default modification even if not specified in the parameter file.

added carbamidomethyl exception if not specified

---

src/pyOpenMS/pxds/MassTraceDetection.pxd

Added missing python binding for MassTraceDetection.

Added python binding for MassTraceDetection

---

src/openms/source/CHEMISTRY/AASequence.cpp

[FEATURE] take specificity into account for [] as well

---

share/OpenMS/examples/FRACTIONS/BSA_design.tsv
src/openms/include/OpenMS/METADATA/ExperimentalDesign.h
src/openms/source/KERNEL/ConsensusMap.cpp
src/openms/source/METADATA/ExperimentalDesign.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.cpp
src/topp/FeatureFinderMultiplex.cpp

- moved some code from FFM tool to algorithm
- FIX: update meta value "map_index" if consensus maps are appended
- more verbose import of experimental design from consensus map

[FIX, FEATURE] some code refactoring and small fixes

---

src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp

fixes https://github.com/OpenMS/OpenMS/issues/3590

[FIX] scan type not displayed in ID View -> crash on export

---

src/openms_gui/include/OpenMS/VISUAL/SpectraIdentificationViewWidget.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp

simplified code a bit and fixes https://github.com/OpenMS/OpenMS/issues/3581 in id view

[FIX] jump to column in TOPPView

---

src/openms/source/MATH/MISC/EmgGradientDescent.cpp

[FIX] add OPENMS_DLLAPI to emg template specializations

---

src/openms/include/OpenMS/FORMAT/XTandemXMLFile.h
src/openms/source/FORMAT/XTandemXMLFile.cpp

[Fix]ed XTandem bug with multiply ocurring proteins.

---

src/pyOpenMS/doc/Manual.tex

As far as I see the other changes have already been done

update pyopenms doc

---

src/openms/include/OpenMS/ANALYSIS/MRM/ReactionMonitoringTransition.h
src/openms/include/OpenMS/ANALYSIS/TARGETED/TargetedExperimentHelper.h
src/openms/include/OpenMS/CHEMISTRY/Residue.h

[DOC] add documentation

---

CHANGELOG
src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp

sync with release/2.4.0

---

CHANGELOG

This is a place to collect changes for the changelog

Update CHANGELOG for 2.4

---

src/utils/RNPxlSearch.cpp

second call to RNPxlReport::annotate is not required

[NOP] removed superflous reannotation

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathHelper.h
src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathWorkflow.h
src/openms/include/OpenMS/ANALYSIS/OPENSWATH/SwathMapMassCorrection.h
src/openms/include/OpenMS/APPLICATIONS/OpenSwathBase.h
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp
src/utils/OpenSwathWorkflow.cpp

add substantial amount of documentation and rename methods to improve documentation and readability of OpenSwath
replaces https://github.com/Roestlab/OpenMS/pull/3

[DOC] OpenSwath documentation

---

doc/doxygen/public/Main.doxygen
doc/doxygen/public/OpenMS_Tutorial_html.doxygen

link to the 2.4 release of the PyOpenMS docu

[FEATURE] add PyOpenMS docu

---

src/pyOpenMS/pxds/AASequence.pxd
src/pyOpenMS/tests/unittests/test000.py
src/pyOpenMS/tests/unittests/test_DIAScoring.py
src/pyOpenMS/tests/unittests/test_tutorial.py
tools/travis/lnx-cibuild.before.sh

change annoying
```
peptide = AASequence.fromString("DFPIANGER", True)
```
to
```
peptide = AASequence.fromString("DFPIANGER")
```

[FIX] small changes to AASequence pyOpenMS

---

src/openms/include/OpenMS/DATASTRUCTURES/Param.h
src/openms/include/OpenMS/FORMAT/DATAACCESS/SwathFileConsumer.h
src/openms/include/OpenMS/FORMAT/SwathFile.h
src/openms/source/FORMAT/SwathFile.cpp
src/tests/topp/CMakeLists.txt
src/utils/OpenSwathFileSplitter.cpp
src/utils/OpenSwathWorkflow.cpp

- improve docs
- optimize loop end condition
- avoid new/delete
- use platform specific temp dir (which also changes with environment automatically)
- force directory separator at the end of tempDir to avoid late crash due to file-not-found for internal temp files

minor improvments to SWATHWorkflow

---

doc/OpenMS_tutorial/OpenMS_Tutorial.doxygen

[UPDATE] De novo identification tutorial

---

src/openms/include/OpenMS/ANALYSIS/ID/IDConflictResolverAlgorithm.h
src/openms/include/OpenMS/CONCEPT/LogConfigHandler.h
src/openms/include/OpenMS/CONCEPT/StreamHandler.h
src/openms/include/OpenMS/MATH/STATISTICS/QuadraticRegression.h
src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h
src/openms/source/CONCEPT/LogConfigHandler.cpp
src/openms/source/CONCEPT/StreamHandler.cpp

remove pollution of overall namespace by `using` directive

[FIX] fix using directive

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h
src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.h
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.cpp

Swathqc - fixes carried over

---

src/openms/source/METADATA/MetaInfo.cpp

disclaimer: edited online with web edit

[FIX] ASan

---

src/openms/include/OpenMS/ANALYSIS/RNPXL/sources.cmake
src/openms/include/OpenMS/FILTERING/DATAREDUCTION/Deisotoper.h
src/openms/include/OpenMS/FILTERING/DATAREDUCTION/sources.cmake
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathHelper.cpp
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp
src/openms/source/ANALYSIS/RNPXL/sources.cmake
src/openms/source/FILTERING/DATAREDUCTION/Deisotoper.cpp
src/openms/source/FILTERING/DATAREDUCTION/sources.cmake
src/openms/source/FORMAT/SwathFile.cpp
src/pyOpenMS/pxds/Deisotoper.pxd
src/tests/class_tests/openms/executables.cmake
src/tests/class_tests/openms/source/Deisotoper_test.cpp
src/topp/OpenSwathChromatogramExtractor.cpp
src/utils/OpenSwathWorkflow.cpp
src/utils/RNPxlSearch.cpp
src/utils/SimpleSearchEngine.cpp

to make it more prominently visible (its universal)
+ some minor code restructuring

Rename RNPXLDeisotoper to Deisotoper

---

src/openms/include/OpenMS/FORMAT/MSstatsFile.h
src/openms/include/OpenMS/FORMAT/sources.cmake
src/openms/source/FORMAT/MSstatsFile.cpp
src/openms/source/FORMAT/sources.cmake
src/openms/source/KERNEL/ConsensusMap.cpp
src/openms/source/SIMULATION/DigestSimulation.cpp
src/pyOpenMS/pxds/MSstatsFile.pxd
src/tests/class_tests/openms/source/MSstatsFile_test.cpp
src/utils/MSstatsConverter.cpp

moved some code from the converter to separate class

[REFACTOR] move MSstatsFile to separate class

---

src/openms/include/OpenMS/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.h
src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/CoarseIsotopePatternGenerator.cpp
src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.cpp
src/pyOpenMS/pxds/EmpiricalFormula.pxd
src/pyOpenMS/pxds/IsotopeDistribution.pxd
src/pyOpenMS/tests/unittests/test000.py
src/tests/class_tests/openms/source/FineIsotopeDistribution_test.cpp
src/tests/class_tests/openms/source/IsotopeDistribution_test.cpp

- fixes getMin / getMax in the isotope distribution for the general case
- removes  isNormalized and isConvolutionUnit()
- updates docu
- adds tests

Isotope dist

---

src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationDescription.h
src/openms/source/ANALYSIS/MAPMATCHING/TransformationDescription.cpp
src/pyOpenMS/pxds/TransformationDescription.pxd

make some basic statistics on deviations before/after applying the transformation model available to down-stream tools

[FEATURE] return transformation statistics

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp

Prompted by discussion in #3791.

Small logging improvement in FeatureFinderIdentification

---

src/openms/source/FORMAT/DATAACCESS/CsiFingerIdMzTabWriter.cpp
src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp
src/tests/topp/THIRDPARTY/SiriusAdapter_1_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_2_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_3_output.mzTab

[FIX] Corresponding tests (1-3)
[UPDATE] THIRDPARTY (SIRIUS 4.0 -> SIRIUS 4.0.1)
Preprocessing and CSI:FingerID tests were stable

[UPDATE] SiriusAdapter (with SIRIUS 4.0.1)

---

src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp

this bug might cause random crashes while running on multiple cores

[FIX] applied a fix from develop to release/2.4.0

---

cmake/knime/mime.types
cmake/knime/mimetypes.xml

[FIX] Added percolator Tab file as possible mime type in KNIME

---

src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h

[FIX] PepIdxer correctly parsing Xtandem results

---

src/openms_gui/include/OpenMS/VISUAL/TOPPViewIdentificationViewBehavior.h
src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp

applied TOPPView ID view fix from #3821 to the release 2.4 branch

release/2.4.0 TOPPView ID view fix

---

cmake/knime/mime.types
cmake/knime/mimetypes.xml

[ADD] pqp to KNIME MimeType

---

src/pyOpenMS/CMakeLists.txt
src/pyOpenMS/dist-scripts/create-manylinux.sh
src/pyOpenMS/tests/unittests/test000.py
src/pyOpenMS/tests/unittests/test_DIAScoring.py
src/pyOpenMS/tests/unittests/test_tutorial.py

a collection of fixes required for pyOpenMS 2.4 release

[FIX] Windows fix

---

src/tests/topp/CMakeLists.txt

Hot fix for debug mode.
Built on #3808 but uses the correct flag.

Fixes #3764

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.cpp

Member variables updated from ini params. Fixes #3890.

ini params correctly passed to FeatureFinderMultiplex algorithm

---

README.md

fixes the links to the docu, see https://github.com/hroest/OpenMS/tree/fix/readme

[FIX] readme links to docu

---

src/openms/source/CHEMISTRY/ModificationsDB.cpp
src/tests/class_tests/openms/source/AASequence_test.cpp

- check for lower-case unimod identifier
- fixes #3887

[FIX] ensure unimod also works in lower case

---

src/openms/source/ANALYSIS/OPENSWATH/DIAHelper.cpp

fix segfault if AASequence is empty

[FIX] bugfix

---

src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureSelector.cpp
src/tests/class_tests/openms/source/MRMFeatureSelector_test.cpp

Added check to MRMFeatureSelector::computeScore_ to account for NaN and Inf.

[FIX] Bug in MRMFeatureSelector

---

src/utils/DecoyDatabase.cpp

[FIX] switch to boost regex

---

doc/doxygen/install/common-cmake-parameters.doxygen
doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-win.doxygen

[DOC] installation manual for Qt5

---

src/openms/include/OpenMS/ANALYSIS/ID/SimpleSearchEngineAlgorithm.h
src/openms/include/OpenMS/ANALYSIS/RNPXL/ModifiedPeptideGenerator.h
src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLHelper.h
src/openms/source/ANALYSIS/ID/SimpleSearchEngineAlgorithm.cpp
src/openms/source/ANALYSIS/RNPXL/ModifiedPeptideGenerator.cpp
src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp
src/openms/source/ANALYSIS/XLMS/OpenPepXLAlgorithm.cpp
src/openms/source/ANALYSIS/XLMS/OpenPepXLLFAlgorithm.cpp
src/pyOpenMS/pxds/ModifiedPeptideGenerator.pxd
src/pyOpenMS/pxds/OPXLHelper.pxd
src/tests/class_tests/openms/source/ModifiedPeptideGenerator_test.cpp
src/tests/class_tests/openms/source/OPXLHelper_test.cpp
src/utils/RNPxlSearch.cpp

also prepares some speed optimizations

[FEATURE] refactor ModPepGenerator and expose to pyOpenMS

---

src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp

Update the gradient only for last layer.
Fixes #3012

update gradient only for last layer

---

src/openms/include/OpenMS/FORMAT/MzTab.h
src/openms/source/FORMAT/MzTab.cpp
src/openms/source/FORMAT/MzTabFile.cpp
src/topp/MzTabExporter.cpp

Reverts OpenMS/OpenMS#4047
This broke our tests, please do not break the tests.

Revert "columns for mz and rt for individual feature handles to mzTab"

---

src/topp/FileFilter.cpp

to get rid of the stale branch

Minor documentation update

---

src/utils/MSstatsConverter.cpp

Update Param MSstatsConverter

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/OpenSwathScores.h
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathOSWWriter.cpp
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.cpp
src/openms/source/ANALYSIS/OPENSWATH/TransitionPQPFile.cpp
src/openswathalgo/include/OpenMS/OPENSWATHALGO/ALGO/MRMScoring.h
src/openswathalgo/source/OPENSWATHALGO/ALGO/MRMScoring.cpp
src/pyOpenMS/pxds/MRMScoring.pxd
src/tests/class_tests/openms/source/MRMFeatureFinderScoring_test.cpp
src/tests/class_tests/openswathalgo/MRMScoring_test.cpp

This PR tries to fix two small bugs with PQP and OSW files.
PQP: For some reason, String MetaValues could not be converted to integers anymore.
OSW: ``left join`` resulted in a SQL error. If the gene table is present, we should always link them, right?

[FIX] PQP & OSW SQLite bugs

---

src/openms/source/FORMAT/DATAACCESS/CsiFingerIdMzTabWriter.cpp
src/openms/source/FORMAT/DATAACCESS/SiriusMzTabWriter.cpp
src/tests/topp/THIRDPARTY/SiriusAdapter_1_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_2_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_3_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_4_foutput.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_7_output.mzTab

Add "opt_global_" to optional/custom entries in adherence to the mztab standard.

[FIX] SiriusAdapter mzTab adherence to standard 

---

src/openms/include/OpenMS/FORMAT/MzTab.h
src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
src/openms/source/ANALYSIS/ID/MetaboliteSpectralMatching.cpp

charge was wrong type in mzTab file

mzTab charge to int

---

share/OpenMS/SCRIPTS/ropenms.R

We tested the new R library "reticulate" and found it very usefull to applying pyopenms tools within R.
Here is an R script that shows some basic usage of these functionalitys in R.

ropenms script

---

src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
src/tests/topp/FeatureFinderMetabo_1_output.featureXML
src/topp/FeatureFinderMetabo.cpp

fixes https://github.com/OpenMS/Tutorials/issues/158

[FIX] Do not write zero intensity features in FFMetabo

---

src/utils/AssayGeneratorMetabo.cpp

Outputs SIRIUS workspace to allow easier handling of fragmentation trees for decoy generation with passatuto. (Current solution.)

[ADD] Output SIRIUS workspace (AssayGeneratorMetabo)

---

src/topp/CometAdapter.cpp
src/topp/PercolatorAdapter.cpp

fixes #4129 
I'm not sure what the origin of the problem was though. Just fixing symptoms.
Maybe someone with recent insight can double-check that is what we want.

Percolatoradapter (AA before and after do not neccessarily exist)

---

src/openms/include/OpenMS/ANALYSIS/ID/PrecursorPurity.h
src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationDescription.h
src/openms/include/OpenMS/ANALYSIS/MRM/ReactionMonitoringTransition.h
src/openms/include/OpenMS/ANALYSIS/RNPXL/HyperScore.h
src/openms/include/OpenMS/ANALYSIS/RNPXL/PScore.h
src/openms/include/OpenMS/ANALYSIS/RNPXL/RNPxlFragmentAnnotationHelper.h
src/openms/include/OpenMS/FILTERING/DATAREDUCTION/Deisotoper.h
src/openms/include/OpenMS/METADATA/ID/AppliedProcessingStep.h

docu fixes where documentation would not show up in Doxygen...

[FIX] docu fix

---

src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp

Add icons to visually distinguish spectra, features, consensusfeatures in 2D and 3D view

---

src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
src/openms_gui/source/VISUAL/Spectrum2DWidget.cpp

TICs are now always drawn with DM_CONNECTEDLINES

[FIX] fix drawing of projections if mz is mapped to x-axis

---

src/openms/include/OpenMS/ANALYSIS/DENOVO/CompNovoIdentification.h
src/openms/include/OpenMS/ANALYSIS/DENOVO/CompNovoIdentificationBase.h
src/openms/source/ANALYSIS/DENOVO/CompNovoIdentification.cpp
src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp

Init isotopes only when needed and not yet init.

---

src/topp/PercolatorAdapter.cpp

* Changed the peptide sequence PTM notation to use square brackets instead of round brackets, which is the notation used in Percolator.
* Changed the default SVM score for unmatched PSMs to -100.0, as the previous value of 0.0 is the score for PSMs at the FDR threshold. Typically the lowest scoring PSM has a SVM score of about -4 or -10, depending on the search engine.
* Changed the log message of unmatched PeptideHits into a debug message. In a regular percolator run this message pops up thousands of times when multiple PSMs are reported per spectrum, even though nothing is wrong.

[FIX] Fixed Percolator PTM notation and default svm score

---

cmake/knime_package_support.cmake

Remove out_type parameters from KNIME nodes to reduce confusion

---

src/openms/source/APPLICATIONS/TOPPBase.cpp

Just had a hard time finding the cause of an issue without it.

[Feature] Print Stdout/Err of external commands when debug mode is on

---

cmake/MacOSX/fix_dependencies.rb
tools/create_class.rb

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/openms/openms/issues).

Apply fixes from CodeFactor

---

src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp

turn these warnings only on in debug mode

[FIX] fix some warnings during RT alignment

---

CMakeLists.txt
src/openms/include/OpenMS/config.h.in
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp

allow setting of nested OMP using CMake

[BUILD] add nested parallelism to cmake interface

---

src/openms/include/OpenMS/APPLICATIONS/MapAlignerBase.h
src/topp/MapRTTransformer.cpp

I thing that 'Either' is wrong here if its possible to specify both.

minor wording fixes

---

src/openms_gui/include/OpenMS/VISUAL/Spectrum1DCanvas.h
src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp

Disable automated m/z annotations in TOPPView by default

---

src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLHelper.h
src/openms/source/ANALYSIS/XLMS/OPXLHelper.cpp

This should fix a complaint by the  AddressSanitizer in the nightly build

[FIX] simplified OPXLHelper::computeDeltaScores

---

src/openms/include/OpenMS/FORMAT/XTandemXMLFile.h
src/openms/source/FORMAT/XTandemXMLFile.cpp

[Fix] reading of optional parameter groups in XTandem output files.

---

src/openms/source/FORMAT/MzTab.cpp
src/topp/MSGFPlusAdapter.cpp

when it wrongly returned exit code 0 upon failure
(see https://github.com/MSGFPlus/msgfplus/issues/75)

[FIX] detect MSGF+ crash 

---

src/openms/include/OpenMS/MATH/MISC/EmgGradientDescent.h
src/openms/source/MATH/MISC/EmgGradientDescent.cpp
src/tests/class_tests/openms/source/EmgGradientDescent_test.cpp

Also move said methods from `protected` to `public`.

[STYLE] Improve EmgGradientDescent's methods names

---

src/openms/source/ANALYSIS/ID/FalseDiscoveryRate.cpp

now no empty hit is added on resize

[FIX] empty hits

---

src/openms_gui/include/OpenMS/VISUAL/TOPPASScene.h
src/openms_gui/include/OpenMS/VISUAL/TOPPASVertex.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
src/openms_gui/source/VISUAL/TOPPASScene.cpp
src/openms_gui/source/VISUAL/TOPPASVertex.cpp

* fix a rare segfault when closing the app (due to nullptr dereference)
* feature: better topological sorting which avoids invalidating nodes when changing the pipeline/parameters

Some TOPPAS improvements

---

src/openms_gui/include/OpenMS/VISUAL/TOPPASInputFileListVertex.h
src/openms_gui/include/OpenMS/VISUAL/TOPPASMergerVertex.h
src/openms_gui/include/OpenMS/VISUAL/TOPPASOutputFileListVertex.h
src/openms_gui/include/OpenMS/VISUAL/TOPPASSplitterVertex.h
src/openms_gui/include/OpenMS/VISUAL/TOPPASToolVertex.h
src/openms_gui/include/OpenMS/VISUAL/TOPPASVertex.h
src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp
src/openms_gui/source/VISUAL/TOPPASInputFileListVertex.cpp
src/openms_gui/source/VISUAL/TOPPASMergerVertex.cpp
src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
src/openms_gui/source/VISUAL/TOPPASSplitterVertex.cpp
src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
src/openms_gui/source/VISUAL/TOPPASVertex.cpp

just rewriting some code to make TOPPAS more readable

Internal cleanup

---

src/openms/include/OpenMS/CONCEPT/UniqueIdInterface.h
src/openms/include/OpenMS/DATASTRUCTURES/ConvexHull2D.h
src/openms/include/OpenMS/DATASTRUCTURES/DPosition.h
src/openms/include/OpenMS/KERNEL/BaseFeature.h
src/openms/include/OpenMS/KERNEL/ConsensusFeature.h
src/openms/include/OpenMS/KERNEL/Feature.h
src/openms/include/OpenMS/KERNEL/MRMFeature.h
src/openms/include/OpenMS/KERNEL/MRMTransitionGroup.h
src/openms/include/OpenMS/KERNEL/Peak2D.h
src/openms/include/OpenMS/KERNEL/RichPeak2D.h
src/openms/source/KERNEL/BaseFeature.cpp
src/openms/source/KERNEL/ConsensusFeature.cpp
src/openms/source/KERNEL/Feature.cpp
src/openms/source/KERNEL/MRMFeature.cpp
src/openms/source/METADATA/MetaInfoInterface.cpp
src/pyOpenMS/pxds/Acquisition.pxd
src/pyOpenMS/pxds/AcquisitionInfo.pxd
src/pyOpenMS/pxds/DataProcessing.pxd
src/tests/class_tests/openms/source/BaseFeature_test.cpp
src/tests/class_tests/openms/source/ConsensusFeature_test.cpp
src/tests/class_tests/openms/source/ConvexHull2D_test.cpp
src/tests/class_tests/openms/source/Feature_test.cpp
src/tests/class_tests/openms/source/MRMFeature_test.cpp
src/tests/class_tests/openms/source/Map_test.cpp
src/tests/class_tests/openms/source/Peak2D_test.cpp
src/tests/class_tests/openms/source/RichPeak2D_test.cpp
src/tests/class_tests/openms/source/UniqueIdInterface_test.cpp

add more move constructors and assignment operators

Feature: Move constructors

---

src/tests/class_tests/openms/source/ConsensusFeature_test.cpp
src/tests/class_tests/openms/source/ConvexHull2D_test.cpp
src/tests/class_tests/openms/source/MRMFeature_test.cpp
src/tests/class_tests/openms/source/Map_test.cpp

fixes MSVS introduced in #4276

[FIX] fix tests for MSVS after move semantics were added

---

src/openms/include/OpenMS/ANALYSIS/ID/MessagePasserFactory.h
src/openms/source/ANALYSIS/ID/BayesianProteinInferenceAlgorithm.cpp
src/openms/source/ANALYSIS/ID/FalseDiscoveryRate.cpp
src/openms/thirdparty/evergreen/src/Engine/PriorityScheduler.hpp
src/tests/class_tests/openms/data/BayesianProteinInference_2_test.idXML
src/tests/class_tests/openms/data/BayesianProteinInference_3_test.idXML
src/tests/class_tests/openms/source/BayesianProteinInferenceAlgorithm_test.cpp

Remove unreferenced proteins. Fix FDR difference calculation for corner case. Add more tests. Update parameter defaults.
Add debug ifdefs.

[FIX] Minor fixes for Epifany

---

src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
src/topp/FeatureFinderIdentification.cpp

Add citation to FF-ID

---

doc/TOPP_tutorial/TOPP_scripting.doxygen
doc/doxygen/public/TOPP.doxygen
src/openms/source/SIMULATION/IonizationSimulation.cpp
src/openms/source/SIMULATION/RawMSSignalSimulation.cpp
src/tests/class_tests/openms/source/IonizationSimulation_test.cpp
src/tests/class_tests/openms/source/MSSim_test.cpp
src/topp/QualityControl.cpp
src/utils/MSSimulator.cpp

added citation and docs (especially for the random noise sections)

[DOC] documentation update for MSSimulator

---

src/pyOpenMS/addons/ADD_TO_ALL_OTHER.pyx

in preparation for newer autowrap versions, we need to fix relative imports

[FIX] Python 3 fix

---

src/topp/InternalCalibration.cpp

allow -force for IC when no calibration curve could be found - emitting unchanged mzML

[FEATURE] InternalCalibration fallback when no calibration points

---

src/openms/include/OpenMS/METADATA/ID/MoleculeQueryMatch.h
src/openms/source/ANALYSIS/ID/AccurateMassSearchEngine.cpp
src/openms/source/QC/FragmentMassError.cpp
src/tests/class_tests/openms/source/FragmentMassError_test.cpp
src/topp/InternalCalibration.cpp
src/utils/AccurateMassSearch.cpp

... changes to AMS (following up on #4361) and some minor change to computing QC fragment masses

minor documentation

---

src/topp/PrecursorIonSelector.cpp

might fix https://github.com/OpenMS/OpenMS/issues/4364

make file type explicit in PIS

---

src/openms/include/OpenMS/KERNEL/MassTrace.h
src/openms/source/FILTERING/DATAREDUCTION/MassTraceDetection.cpp
src/openms/source/KERNEL/MassTrace.cpp
src/tests/class_tests/openms/source/MassTrace_test.cpp
src/tests/topp/CMakeLists.txt
src/tests/topp/FeatureFinderMetabo_5_output.featureXML

Add the ability to quantify mass traces based on the highest peak. Addresses https://github.com/OpenMS/OpenMS/issues/4371

Peak height mass trace

---

CMakeLists.txt
cmake/add_library_macros.cmake

This should be tested on multiple compiler versions first.

[FEATURE] use compile feature instead of fixed CXX standard to require only a minimum

---

src/openms/include/OpenMS/ANALYSIS/ID/PrecursorPurity.h
src/openms/include/OpenMS/ANALYSIS/XLMS/OPXLSpectrumProcessingAlgorithms.h
src/openms/source/ANALYSIS/ID/PrecursorPurity.cpp
src/openms/source/ANALYSIS/XLMS/OPXLSpectrumProcessingAlgorithms.cpp
src/openms/source/ANALYSIS/XLMS/OpenPepXLAlgorithm.cpp
src/openms/source/ANALYSIS/XLMS/OpenPepXLLFAlgorithm.cpp
src/pyOpenMS/pxds/OPXLSpectrumProcessingAlgorithms.pxd
src/pyOpenMS/pxds/PrecursorPurity.pxd
src/tests/class_tests/openms/source/PrecursorPurity_test.cpp
src/utils/RNPxlSearch.cpp

also includes an internal change in RNPxlSearch to use the new PrecursorPurity class
(most of the changes there are removed trailing whitespaces)

[FEATURE] parallelized PrecursorPurity and spectrum preprocessing in OpenPepXL

---

src/openms/include/OpenMS/FORMAT/HANDLERS/MzXMLHandler.h
src/openms/source/FORMAT/HANDLERS/MzXMLHandler.cpp

Fix mz xml for max quant

---

src/utils/DigestorMotif.cpp

[FIX] fixes underflow (segfault)

---

src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/topp/CometAdapter.cpp

xref https://github.com/OpenMS/OpenMS/issues/4407

rename comet pin_out tsv

---

src/utils/RTEvaluation.cpp

might fix: https://github.com/OpenMS/OpenMS/issues/4428
Currently there is no test for this tool. Suggestions?

RTEvaluation add missing argument

---

doc/doxygen/install/install-win.doxygen

* Warn about VS2015 and VS2017 due to OpenMP bug
* Some small fixes

Update Windows installation instructions for VS2019

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmPicked.cpp

follow up to https://github.com/OpenMS/OpenMS/issues/4461

a bit clearer warning message

---

src/tests/topp/CMakeLists.txt

I guess this won't hurt .. but help me a bit

make diff parameter order consistent in tests

---

doc/TOPP_tutorial/TOPP_scripting.doxygen

update docs for write_ini 

---

src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/topp/PercolatorAdapter.cpp
src/utils/SpectraSTSearchAdapter.cpp

fixes part of https://github.com/OpenMS/OpenMS/issues/4407

PercolatorAdapter: rename tab to tsv

---

.gitpod.Dockerfile
.gitpod.yml
README.md

test gitpod

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

like every good open-source project should have :)
Adapted from guidelines written by the [The Carpentries Project](https://github.com/carpentries/handbook/blob/master/topic_folders/policies/code-of-conduct.md).

an initial version of a Code of Conduct

---

src/utils/Epifany.cpp
src/utils/ProteomicsLFQ.cpp

There was a small error when writing the debug file because unreferenced proteins were not correctly filtered.
I added a potential PSM/peptide FDR filtering.

[Fix] proteomics lfq fdr

---

src/openms/include/OpenMS/MATH/STATISTICS/PosteriorErrorProbabilityModel.h
src/openms/source/MATH/STATISTICS/PosteriorErrorProbabilityModel.cpp
src/pyOpenMS/pxds/PosteriorErrorProbabilityModel.pxd
src/pyOpenMS/tests/unittests/test000.py
src/tests/class_tests/openms/source/PosteriorErrorProbabilityModel_test.cpp
src/topp/IDPosteriorErrorProbability.cpp

Happened for OMSSA in our Tutorial.

[Fix] idpep outlier handling

---

src/utils/RTEvaluation.cpp

- csv output was not csv so I just made it tsv (which is better anyway)
- latex was missing line ends

RTEvaluation: fix output formats

---

src/openms/include/OpenMS/CHEMISTRY/ModificationsDB.h
src/openms/source/CHEMISTRY/ModificationsDB.cpp

- add docu
- small fixes
- rename functions
- a few fixes after #4452

[DOC] documentation

---

share/OpenMS/CHEMISTRY/Elements.xml

This PR fixes the #4563 and adds Indium (and its isotopes) along with the other elements mentioned in the issue. 
If there are other elements you'd like me to add feel free to let me know.
-James

Adding isotopic abundances for several elements

---

src/topp/PhosphoScoring.cpp

xref https://github.com/OpenMS/OpenMS/issues/4406

PhosphoScoring: set format for out parameter

---

src/topp/MSGFPlusAdapter.cpp

rarely used as we need to index we a t/d database

make add_decoys an advanced option in MSGF+ adapter

---

src/openms/include/OpenMS/KERNEL/ConsensusMap.h
src/tests/topp/MS3TMT10Plex_test.consensusXML
src/topp/IsobaricAnalyzer.cpp

[FEATURE] Remove unquant. ConsFeats w/o ID after IsobaricAnalyzer

---

src/openms/include/OpenMS/COMPARISON/CLUSTERING/HashGrid.h
src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp

[FIX] implement HashGrid.find to avoid "at" with exceptions

---

src/pyOpenMS/pxds/TransformationModelLowess.pxd

fixes #4585
I hope this syntax is correct?!

[FIX] wrap changed static method in TransformationModelLowess

---

doc/TOPP_tutorial/TOPP_advanced.doxygen
doc/TOPP_tutorial/TOPP_scripting.doxygen
src/topp/FileConverter.cpp
src/utils/Epifany.cpp

fixes #4642, amends #4610

---

src/utils/ProteomicsLFQ.cpp

[FIX] add fall-back if alignment not possible

---

src/utils/ProteomicsLFQ.cpp

check for missing identifications

---

src/openms/include/OpenMS/FORMAT/FileHandler.h
src/openms/include/OpenMS/SYSTEM/File.h
src/openms/source/FORMAT/FileHandler.cpp
src/openms/source/FORMAT/PepXMLFile.cpp
src/openms/source/SYSTEM/File.cpp
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
src/openms_gui/source/VISUAL/TOPPASToolVertex.cpp
src/pyOpenMS/pxds/File.pxd
src/pyOpenMS/pxds/FileHandler.pxd
src/tests/class_tests/openms/source/FileHandler_test.cpp
src/tests/class_tests/openms/source/File_test.cpp
src/topp/CometAdapter.cpp
src/topp/LuciphorAdapter.cpp
src/topp/MascotAdapterOnline.cpp
src/topp/MyriMatchAdapter.cpp
src/utils/MSFraggerAdapter.cpp
src/utils/MzMLSplitter.cpp
src/utils/OpenSwathDIAPreScoring.cpp
src/utils/ProteomicsLFQ.cpp
src/utils/SpectraSTSearchAdapter.cpp

some easier and more safe way of renaming of files.

[FEATURE] clean up file suffix renaming

---

src/topp/PercolatorAdapter.cpp

Here comes the PR, as discussed previously.
We can also change it in another way if you have a better idea.

Percolator: change comment when using psm or peptide fdr

---

src/openms/include/OpenMS/ANALYSIS/ID/ConsensusIDAlgorithm.h
src/openms/include/OpenMS/ANALYSIS/ID/ConsensusIDAlgorithmIdentity.h
src/openms/include/OpenMS/ANALYSIS/ID/ConsensusIDAlgorithmSimilarity.h
src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithm.cpp
src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithmIdentity.cpp
src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithmSimilarity.cpp
src/pyOpenMS/pxds/ConsensusIDAlgorithm.pxd
src/tests/class_tests/openms/source/ConsensusIDAlgorithmAverage_test.cpp
src/tests/class_tests/openms/source/ConsensusIDAlgorithmBest_test.cpp
src/tests/class_tests/openms/source/ConsensusIDAlgorithmRanks_test.cpp
src/tests/class_tests/openms/source/ConsensusIDAlgorithmWorst_test.cpp
src/tests/topp/CMakeLists.txt
src/tests/topp/ConsensusID_1_input.idXML
src/tests/topp/ConsensusID_1_output.idXML
src/tests/topp/ConsensusID_4_output.idXML
src/tests/topp/ConsensusID_5_output.idXML
src/tests/topp/ConsensusID_6_input.idXML
src/tests/topp/ConsensusID_6_output.idXML
src/tests/topp/ConsensusID_7_output.idXML
src/topp/ConsensusID.cpp
src/topp/PercolatorAdapter.cpp

[Feature] consensus id per spectrum

---

src/topp/CometAdapter.cpp
src/topp/MSGFPlusAdapter.cpp

[FIX] writing of protein terminal mods correctly in Comet and MSGF adapter

---

src/topp/MSGFPlusAdapter.cpp

[FEATURE] add new MSGF options

---

src/openms/configh.cmake
src/openms/include/OpenMS/config.h.in
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/SYSTEM/SysInfo.cpp

- support peak memory usage calculation on Linux 
- report it for all platforms (which support it) per default

report peak mem usage on Linux

---

src/topp/CometAdapter.cpp

[FIX] term. mods with specific origin in Comet

---

src/openms_gui/include/OpenMS/VISUAL/DIALOGS/PythonModuleRequirement.h
src/openms_gui/include/OpenMS/VISUAL/DIALOGS/SwathTabWidget.h
src/openms_gui/include/OpenMS/VISUAL/InputFileList.h
src/openms_gui/include/OpenMS/VISUAL/OutputDirectory.h
src/openms_gui/source/VISUAL/DIALOGS/PythonModuleRequirement.cpp
src/openms_gui/source/VISUAL/DIALOGS/SwathTabWidget.cpp
src/openms_gui/source/VISUAL/DIALOGS/SwathTabWidget.ui
src/openms_gui/source/VISUAL/InputFileList.cpp
src/openms_gui/source/VISUAL/OutputDirectory.cpp
src/openms_gui/source/VISUAL/ParamEditor.ui
src/utils/TargetedFileConverter.cpp

yet another step ....
followup on #4647 and #4706

Swath wizard

---

src/openms/source/KERNEL/MSChromatogram.cpp

Hi,
I think this might fix the segfault in debug mode.
Also closer to the original set union code.

potential fix for MSChromatogram merge

---

src/topp/IDFilter.cpp

[Review] code review comments

---

src/openms_gui/include/OpenMS/VISUAL/DIALOGS/TOPPASToolConfigDialog.h
src/openms_gui/source/VISUAL/DIALOGS/TOPPASToolConfigDialog.cpp

- make the initial Parameter editor big enough
- label store and load buttons for INI files more precisely

Minor INI/TOPPAS improvements

---

src/tests/topp/FileInfo_1_output.txt
src/tests/topp/FileInfo_2_output.txt
src/tests/topp/FileInfo_3_output.txt
src/tests/topp/FileInfo_4_output.txt
src/tests/topp/FileInfo_5_output.txt
src/tests/topp/FileInfo_6_output.txt
src/tests/topp/FileInfo_9_output.txt
src/topp/FileInfo.cpp

add distribution information for charge and activation-method of MS2 data in raw(mzML etc) files

FileInfo: more information for Raw files

---

src/openms/source/FORMAT/PercolatorOutfile.cpp

Suggested change from issue: #4350

Adapt Regex when parsing XTandem Percolator output files

---

cmake/knime/mime.types
cmake/knime/mimetypes.xml

Sync mimetypes and filetypes

---

src/topp/InspectAdapter.cpp

Try "txt" as intermediate format for InspectAdapter

---

src/tests/topp/THIRDPARTY/OMSSAAdapter_1_out.idXML
src/topp/OMSSAAdapter.cpp

add references to original data and native ids

write out native ids and spectrum references

---

src/openms/source/METADATA/ProteinIdentification.cpp
src/tests/class_tests/openms/source/ProteinIdentification_test.cpp

Also adds tests for that function.

Fix ProteinIdentification::SearchParameters::getChargeRange (solves #4872)

---

src/tests/class_tests/openms/source/FIAMSDataProcessor_test.cpp
src/tests/topp/FileInfo_1_output.txt
src/tests/topp/FileInfo_2_output.txt
src/tests/topp/FileInfo_3_output.txt
src/tests/topp/FileInfo_4_output.txt
src/tests/topp/FileInfo_5_output.txt
src/tests/topp/FileInfo_6_output.txt
src/tests/topp/FileInfo_7_output.txt
src/tests/topp/FileInfo_9_output.txt
src/topp/FileInfo.cpp

* extend mslevel + fragmentation method information 
also fixes a test on Apple Clang (amends #4838)

[FEATURE] Fileinfo: more info

---

src/topp/PTModel.cpp
src/topp/PTPredict.cpp

PR adds registration of output and input files of PTModel and PTPredict. #4401 
Needs to be tested once more before merging!

fix output/input files to PTModel and PTPredict

---

doc/CMakeLists.txt
doc/doxygen/Doxyfile.in

Partly Fixes #4875 . More to come

Exclude some files for dot creation from doc install

---

src/openms/include/OpenMS/SYSTEM/FileWatcher.h
src/openms/source/SYSTEM/FileWatcher.cpp
src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
src/openms_gui/include/OpenMS/VISUAL/MISC/GUIHelpers.h
src/openms_gui/include/OpenMS/VISUAL/SpectraViewWidget.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/TOPPViewSpectraViewBehavior.cpp
src/tests/class_tests/openms_gui/source/GUI/TOPPView_test.cpp

Toppview refactor

---

doc/doxygen/public/UTILS.doxygen
src/utils/MetaboliteAdductDecharger.cpp

Fixing docu issues for release.

[FIX] docu for tools

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/DATAACCESS/MRMFeatureAccessOpenMS.h
src/openms/include/OpenMS/FILTERING/NOISEESTIMATION/SignalToNoiseEstimator.h
src/openms/include/OpenMS/FILTERING/NOISEESTIMATION/SignalToNoiseEstimatorMeanIterative.h
src/openms/include/OpenMS/FILTERING/NOISEESTIMATION/SignalToNoiseEstimatorMedian.h
src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerIterative.h
src/openms/source/ANALYSIS/OPENSWATH/PeakPickerMRM.cpp
src/openms/source/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMRM.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerCWT.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.cpp
src/pyOpenMS/addons/SignalToNoiseEstimatorMedian.pyx
src/pyOpenMS/pxds/SignalToNoiseEstimator.pxd
src/pyOpenMS/pxds/SignalToNoiseEstimatorMeanIterative.pxd
src/pyOpenMS/pxds/SignalToNoiseEstimatorMedian.pxd
src/tests/class_tests/openms/source/SignalToNoiseEstimatorMeanIterative_test.cpp
src/tests/class_tests/openms/source/SignalToNoiseEstimatorMedian_test.cpp
src/tests/class_tests/openms/source/SignalToNoiseEstimator_test.cpp
src/topp/EICExtractor.cpp
src/topp/FileFilter.cpp

augments #4775 by fixing python bindings

subsitute vector<double> for map<PeakType, double> in SignalToNoiseEstimator

---

tools/travis/lnx-cibuild.before.sh

update build dependency for our pyOpenMS builds on travis
Also please:

bump autowrap in travis CI

---

.github/workflows/rebase.yml

writing /rebase in a comment will automatically attempt to rebase current PR to develop
Also please:

[CI] rebase using /rebase

---

src/topp/MassTraceExtractor.cpp
src/topp/OpenSwathAnalyzer.cpp
src/topp/OpenSwathAssayGenerator.cpp
src/topp/OpenSwathChromatogramExtractor.cpp
src/topp/OpenSwathDecoyGenerator.cpp
src/topp/OpenSwathFeatureXMLToTSV.cpp
src/topp/OpenSwathRTNormalizer.cpp
src/utils/AccurateMassSearch.cpp
src/utils/TargetedFileConverter.cpp

[DOC] add missing INI documentation for TOPP tools

---

src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp

Made `strict_` param of `MRMFeatureFinderScoring` an optional parameter.

made strict_ param in MRMFeatureFinderScoring an optional parameter

---

CHANGELOG
CHANGELOG_PARAMS

Updates param changelog for 2.6

[DOC] Param changelog for 2.6

---

CHANGELOG_PARAMS

Updated param CHANGELOG to parameter changes in OpenSWATHWorkflow
Also please:

updated OpenSWATH param changelog

---

cmake/Windows/NSIS.template.in
src/openms/include/OpenMS/FORMAT/IdXMLFile.h

The link to the documentation needed to be updated.
Also please:

update path to documentation

---

cmake/Windows/NSIS.template.in

[FIX] add SwathWizard to StartMenu

---

src/openms/include/OpenMS/FORMAT/ExperimentalDesignFile.h
src/openms/include/OpenMS/METADATA/ExperimentalDesign.h

Update documenation for ExperimentalDesign

---

src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/SwathWizard.cpp
src/openms_gui/source/VISUAL/DIALOGS/SwathTabWidget.cpp
src/openms_gui/source/VISUAL/SpectraSelectionTabs.cpp
src/openms_gui/source/VISUAL/SpectraViewWidget.cpp
src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
src/openms_gui/source/VISUAL/TOPPViewSpectraViewBehavior.cpp

- fixes #4948
- adds a data flowchart for SwathWizard to the doxygen docs

Toppview Chromatogram Speedup

---

src/pyOpenMS/CMakeLists.txt
src/pyOpenMS/tests/unittests/test_AcquisitionInfo.py

Fixed bug where test_AcquisitionInfo wasnt being run. Fixed syntax error in file.

[fix] fixed space issue in test_AcquisitionInfo.py and added it to CmakeLists

---

src/openms/thirdparty/evergreen/src/PMF/LabeledPMF.hpp
src/utils/Epifany.cpp

Make assertion to an exception so we realize when we have to skip the connected component.
Allow score switching internally.

[FIX] Small Epifany fixes

---

src/pyOpenMS/CMakeLists.txt
src/pyOpenMS/addons/ADD_TO_ALL_OTHER.pyx
src/pyOpenMS/create_cpp_extension.py
src/pyOpenMS/pxds/TransformationModelBSpline.pxd
src/pyOpenMS/pxds/TransformationModelInterpolated.pxd
src/pyOpenMS/pxds/TransformationModelLowess.pxd
src/pyOpenMS/tests/unittests/test000.py
src/pyOpenMS/tests/unittests/test_AcquisitionInfo.py

Merge some changes to enable compiling pyopenms with only 1 module. Fix some tests with languagelevel=3

Ll3 modifications

---

src/openswathalgo/source/OPENSWATHALGO/ALGO/Scoring.cpp
src/tests/class_tests/openswathalgo/Scoring_test.cpp

some changes that were applied to master but never found it's way back to develop
Also please:

[FIX] reapply changes from master

---

src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/INIFileEditor-resources/INIFileEditor.plist.in
src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/SwathWizard-resources/SwathWizard.plist.in
src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPAS-resources/TOPPAS.plist.in
src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView-resources/TOPPView.plist.in

TOPPView support for HiRes displays #4968

TOPPView support for HiRes displays (macOS)

---

src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp

Fixes https://github.com/OpenMS/OpenMS/issues/4969 projection button not toggled
Also please:

[fix, #4969] projection button issue

---

src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/APPLICATIONS/ToolHandler.cpp
src/utils/FeatureFinderSuperHirn.cpp

See https://github.com/bioconda/bioconda-recipes/pull/24604#issuecomment-701465355

Make documentation links point to the exact version of the tool

---

doc/doxygen/common/header.html

Works by putting a little html file into the docu folder, as soon as the release is outdated.
Unfortunately, I forgot it again for this release.

[DOC] Add opt-in include to display a warning and link to latest docu

---

src/openms/include/OpenMS/FILTERING/ID/IDFilter.h
src/openms/source/FILTERING/ID/IDFilter.cpp
src/pyOpenMS/pxds/IDFilter.pxd
src/tests/class_tests/openms/data/IDFilter_test5.idXML
src/tests/class_tests/openms/source/IDFilter_test.cpp
src/topp/IDFilter.cpp

Addresses https://github.com/OpenMS/OpenMS/issues/4900

[FEATURE] retain top n spectra (better spectrum = better PSM)

---

src/tests/topp/CMakeLists.txt
src/tests/topp/FeatureFinderIdentification_4_output.featureXML

replaces https://github.com/OpenMS/OpenMS/pull/5002

fix name clash of FeatureFinderIdentification test 

---

AUTHORS
src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.h
src/openms_gui/include/OpenMS/VISUAL/ANNOTATION/sources.cmake
src/openms_gui/source/VISUAL/ANNOTATION/Annotation1DVerticalLineItem.cpp
src/openms_gui/source/VISUAL/ANNOTATION/sources.cmake
src/openms_gui/source/VISUAL/Spectrum1DCanvas.cpp

A simple prototype of annotation item, Annotation1DVerticalLineItem

[FEATURE] first prototype of Annotation1DVerticalLineItem

---

src/openms/include/OpenMS/FORMAT/MzTab.h
src/openms/source/FORMAT/MzTab.cpp
src/tests/topp/CMakeLists.txt

mzTab move static to member

---

src/topp/MapAlignerTreeGuided.cpp

Update MapAlignerTreeGuided command line documentation

---

.gitpod.yml
.vscode-gitpod/c_cpp_properties.json
.vscode-gitpod/launch.json
.vscode-gitpod/settings.json

Now one should be able to start debugging right away without additional setup. Also adds e.g. a doxygen and cmake extension and updates intellisense. We could think about clangd instead of Intellisense in the future.

[GITPOD] Better integration of CMake plugin with debugger + update of extensions

---

doc/doxygen/install/common-cmake-parameters.doxygen
doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-win.doxygen
src/openms/include/OpenMS/FILTERING/ID/IDFilter.h
src/openms/include/OpenMS/FORMAT/FileHandler.h
src/openms/include/OpenMS/FORMAT/HANDLERS/IndexedMzMLHandler.h
src/openms/include/OpenMS/FORMAT/HANDLERS/MzMLHandler.h
src/openms/include/OpenMS/FORMAT/OPTIONS/PeakFileOptions.h
src/openms/include/OpenMS/FORMAT/TextFile.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFiltering.h
src/openms_gui/include/OpenMS/VISUAL/Spectrum2DCanvas.h
src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp
src/topp/CometAdapter.cpp
src/topp/IDRipper.cpp
src/topp/InternalCalibration.cpp
src/topp/MSGFPlusAdapter.cpp
src/topp/OMSSAAdapter.cpp
src/topp/ProteinResolver.cpp
src/topp/XTandemAdapter.cpp
src/utils/AssayGeneratorMetabo.cpp
src/utils/MRMTransitionGroupPicker.cpp
src/utils/MetaboliteSpectralMatcher.cpp

Fixes a lot of doxygen errors.

[DOC] fix doxygen warnings

---

.gitpod.yml
src/tests/topp/ConsensusID_1_input.idXML
src/tests/topp/ConsensusID_1_output.idXML
src/tests/topp/ConsensusID_4_output.idXML
src/tests/topp/ConsensusID_5_output.idXML
src/tests/topp/ConsensusID_6_output.idXML
src/topp/ConsensusID.cpp

Otherwise you get invalid idXMLs during writing the results. Unfortunately, our tests did not include proteins so it was not covered.

[FIX] ConsID not taking over proteins in "linking" mode

---

src/openms_gui/include/OpenMS/VISUAL/TOPPViewIdentificationViewBehavior.h
src/openms_gui/include/OpenMS/VISUAL/TVBehaviorBase.h
src/openms_gui/include/OpenMS/VISUAL/sources.cmake
src/openms_gui/source/VISUAL/TOPPViewIdentificationViewBehavior.cpp
src/openms_gui/source/VISUAL/TOPPViewSpectraViewBehavior.cpp
src/openms_gui/source/VISUAL/TVBehaviorBase.cpp
src/openms_gui/source/VISUAL/sources.cmake

Not much happening here yet. Removed a bit of code duplication and prepare for other refactoring.

[REFACTOR] introduce behavior base class

---

doc/code_examples/Tutorial_AASequence.cpp
src/openms/include/OpenMS/CHEMISTRY/AASequence.h
src/openms/source/ANALYSIS/ID/SimpleSearchEngineAlgorithm.cpp
src/openms/source/ANALYSIS/OPENSWATH/MRMAssay.cpp
src/openms/source/ANALYSIS/OPENSWATH/MRMDecoy.cpp
src/openms/source/ANALYSIS/OPENSWATH/MRMIonSeries.cpp
src/openms/source/ANALYSIS/TARGETED/InclusionExclusionList.cpp
src/openms/source/CHEMISTRY/AASequence.cpp
src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp
src/openms/source/FILTERING/ID/IDFilter.cpp
src/openms/source/FORMAT/HANDLERS/MzIdentMLHandler.cpp
src/openms/source/FORMAT/MzTab.cpp
src/openms/source/QC/MzCalibration.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/IsotopeModel.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/SeedListGenerator.cpp
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp
src/openms_gui/source/VISUAL/SpectrumCanvas.cpp
src/pyOpenMS/pxds/AASequence.pxd
src/tests/class_tests/openms/source/AASequence_test.cpp
src/tests/class_tests/openms/source/MzCalibration_test.cpp
src/topp/PercolatorAdapter.cpp
src/topp/RTPredict.cpp
src/utils/MetaProSIP.cpp
src/utils/QCCalculator.cpp

Add convenience function for mz calculation to AASequence.

[FEATURE] added getMZ as convinience method to AASequence

---

src/openms/include/OpenMS/APPLICATIONS/TOPPBase.h
src/openms/include/OpenMS/APPLICATIONS/ToolHandler.h
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/APPLICATIONS/ToolHandler.cpp
src/tests/class_tests/openms/source/TOPPBase_test.cpp

Fix for #5014
Fixes the tool categories for some tools. 
Adds functionality to check for duplicated entries (TOPP, Utils) 
Let me know if that is what you had in mind.

[FIX] tool categories & additional checks.

---

src/openms_gui/include/OpenMS/VISUAL/DataSelectionTabs.h
src/openms_gui/include/OpenMS/VISUAL/TVControllerBase.h
src/openms_gui/include/OpenMS/VISUAL/TVIdentificationViewController.h
src/openms_gui/include/OpenMS/VISUAL/TVSpectraViewController.h
src/openms_gui/include/OpenMS/VISUAL/sources.cmake
src/openms_gui/source/VISUAL/DataSelectionTabs.cpp
src/openms_gui/source/VISUAL/TVControllerBase.cpp
src/openms_gui/source/VISUAL/TVIdentificationViewController.cpp
src/openms_gui/source/VISUAL/TVSpectraViewController.cpp
src/openms_gui/source/VISUAL/sources.cmake

Minor name changes to better reflect design.

[REFACTOR] some small name changes

---

src/openms/source/FORMAT/MascotGenericFile.cpp

added decoy parameter to mascot search

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
src/utils/ProteomicsLFQ.cpp

fix for removed decoys in pLFQ

---

src/tests/topp/THIRDPARTY/MascotAdapterOnline_1_out.idXML

Nightlies fail due to MascotOnlineAdapter_test not working correctly. 
Edit: Probably the Mascot online test is only activated in nightly builds.

[FIX] Mascot - test 

---

src/openms/source/FORMAT/MRMFeatureQCFile.cpp
src/tests/class_tests/openms/source/MRMFeatureQCFile_test.cpp

- Small bug in MRMFeatureQCFile where an empty vector in a member of MRMFeatureQC would throw an error

Fix: Bug in MRMFeatureQCFile

---

src/openms/include/OpenMS/CHEMISTRY/ModificationsDB.h
src/openms/include/OpenMS/CONCEPT/LogStream.h
src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h
src/openms/include/OpenMS/FORMAT/MzTab.h
src/openms/include/OpenMS/FORMAT/SqliteConnector.h
src/openms/include/OpenMS/MATH/STATISTICS/GaussFitter.h
src/openms/include/OpenMS/MATH/STATISTICS/LinearRegression.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/IsotopeWaveletTransform.h
src/openms/include/OpenMS/config.h.in
src/openms/source/ANALYSIS/OPENSWATH/SwathMapMassCorrection.cpp
src/openms/source/ANALYSIS/OPENSWATH/TransitionTSVFile.cpp
src/openms/source/CHEMISTRY/AASequence.cpp
src/openms/source/CHEMISTRY/ModificationsDB.cpp
src/openms/source/DATASTRUCTURES/LPWrapper.cpp
src/openms/source/FORMAT/PepXMLFile.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
src/tests/class_tests/openms/source/ModificationsDB_test.cpp

[FIX] Sort results from getModFromDiffMass

---

src/openms/source/MATH/STATISTICS/PosteriorErrorProbabilityModel.cpp

Allow SSEngine in IDPEP

---

src/openms/include/OpenMS/FORMAT/PepXMLFile.h
src/openms/source/FORMAT/PepXMLFile.cpp
src/topp/CometAdapter.cpp

Note: If your PR is failing you can check out http://cdash.openms.de/index.php?project=OpenMS and look for your PR with detailed error messages.

Use pointer

---

src/openms/include/OpenMS/FORMAT/MascotRemoteQuery.h
src/openms/source/FORMAT/MascotRemoteQuery.cpp
src/tests/topp/THIRDPARTY/MascotAdapterOnline_2_out.idXML
src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/topp/MascotAdapterOnline.cpp

Note: If your PR is failing you can check out http://cdash.openms.de/index.php?project=OpenMS and look for your PR with detailed error messages.

query decoy result

---

CHANGELOG
src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPASBase.h
src/openms_gui/include/OpenMS/VISUAL/RecentFilesMenu.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/RecentFilesMenu.cpp

add a `recentFiles` menu to TOPPAS

---

.gitpod.Dockerfile
.gitpod.yml

add clang-tidy

---

src/openms/include/OpenMS/MATH/MISC/MathFunctions.h

Make quantile function safer

---

src/openms/source/FORMAT/HANDLERS/MzIdentMLDOMHandler.cpp
src/tests/class_tests/openms/data/MzIdentMLFile_msgf_mini.mzid
src/tests/class_tests/openms/source/MzIdentMLFile_test.cpp

allow reading in a mod as protein-nterm in mzIdentML

---

src/topp/PercolatorAdapter.cpp

fix percolator URL

---

src/utils/FeatureFinderMetaboIdent.cpp

Extend FeatureFinderMetaboIdent documentation to include what spectrum types are expected.

[DOC] FFMetaboIdent

---

src/openms/source/FORMAT/MascotRemoteQuery.cpp
src/tests/topp/THIRDPARTY/MascotAdapterOnline_1.ini
src/tests/topp/THIRDPARTY/MascotAdapterOnline_1_out.idXML
src/tests/topp/THIRDPARTY/MascotAdapterOnline_2_out.idXML
src/topp/MascotAdapterOnline.cpp

mascot batch processing

---

.travis.yml

Removing warnings from travis. Might be worthwhile to update the Linux dist as well.

update travis script

---

src/openms/source/FORMAT/MascotRemoteQuery.cpp
src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp
src/topp/TextExporter.cpp

fix TOPPAS crash when double clicking disconnected output node

---

src/openms/include/OpenMS/FORMAT/MascotGenericFile.h
src/openms/include/OpenMS/FORMAT/MzMLFile.h
src/openms/source/APPLICATIONS/SearchEngineBase.cpp
src/openms/source/FORMAT/MzMLFile.cpp

[FIX] SearchEngineBase: inspect spectra's data if metainfo not available
[FIX] annotate MGF data as centroided

[FIX] SearchEngineBase

---

src/openms/include/OpenMS/ANALYSIS/ID/AhoCorasickAmbiguous.h
src/openms/include/OpenMS/APPLICATIONS/ParameterInformation.h
src/openms/include/OpenMS/CONCEPT/VersionInfo.h
src/openms/include/OpenMS/DATASTRUCTURES/ToolDescription.h
src/openms/include/OpenMS/FORMAT/GzipInputStream.h
src/openms/include/OpenMS/FORMAT/OPTIONS/PeakFileOptions.h
src/openms/include/OpenMS/KERNEL/ConsensusMap.h
src/openms/source/DATASTRUCTURES/ToolDescription.cpp
src/openms/source/FORMAT/Bzip2InputStream.cpp
src/openms/source/FORMAT/GzipInputStream.cpp
src/openms/source/KERNEL/ConsensusMap.cpp
tools/travis/lnx-cibuild.before.sh

Compile error fixes OpenMS/OpenMS#5186 

---

src/openms/include/OpenMS/ANALYSIS/MAPMATCHING/TransformationDescription.h
src/openms/include/OpenMS/DATASTRUCTURES/String.h

more gcc 9 fixes

---

src/openms/include/OpenMS/DATASTRUCTURES/ConstRefVector.h

fix default operators

---

src/pyOpenMS/addons/SwathMap.pyx
src/pyOpenMS/create_cpp_extension.py
src/pyOpenMS/pxds/smart_ptr.pxd

[fix] replaced boost:shared_ptr with std:shared_ptr in pyopenms

---

doc/doxygen/public/Main.doxygen

Links now to latest instead of 2.4.0 
fixes #5194

pyopenms_dev_to_latest

---

src/openms/include/OpenMS/ANALYSIS/ID/PeptideProteinResolution.h
src/openms/source/ANALYSIS/ID/BasicProteinInferenceAlgorithm.cpp
src/openms/source/ANALYSIS/ID/PeptideProteinResolution.cpp
src/pyOpenMS/pxds/PeptideProteinResolution.pxd
src/tests/class_tests/openms/data/PeptideProteinResolution_in.idXML
src/tests/class_tests/openms/data/PeptideProteinResolution_in2.idXML
src/tests/class_tests/openms/data/PeptideProteinResolution_out.idXML
src/tests/class_tests/openms/data/PeptideProteinResolution_out2.idXML
src/tests/class_tests/openms/executables.cmake
src/tests/class_tests/openms/source/BasicProteinInferenceAlgorithm_test.cpp
src/tests/class_tests/openms/source/PeptideProteinResolution_test.cpp
src/utils/ProteomicsLFQ.cpp

fix bug in BPIA and add tie resolution

---

src/openms/include/OpenMS/KERNEL/ComparatorUtils.h

[FIX] remove potential source for multiple def. error

---

CMakeLists.txt
share/OpenMS/CV/psi-ms.obo
share/OpenMS/MAPPING/ms-mapping.xml
src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp
src/tests/class_tests/openms/data/MzMLFile_1.mzML
src/tests/class_tests/openms/source/FileHandler_test.cpp
src/tests/class_tests/openms/source/MzMLFile_test.cpp
src/tests/topp/FileConverter_23_output.mzML
src/tests/topp/THIRDPARTY/third_party_tests.cmake

Some of the SIRIUS tests are not running on Jenkins due to either THIRDPARTY or test configuration
http://cdash.openms.de/viewTest.php?onlyfailed&buildid=121031

Test: Sirius Tests Jenkins

---

src/openms/include/OpenMS/CHEMISTRY/ModificationsDB.h
src/openms/include/OpenMS/CHEMISTRY/ProteaseDB.h
src/openms/source/APPLICATIONS/ToolHandler.cpp
src/openms/source/CHEMISTRY/ModificationsDB.cpp
src/openms/source/CHEMISTRY/ProteaseDB.cpp
src/utils/OpenMSDatabasesInfo.cpp
src/utils/executables.cmake

See title. I think testing would be superfluous and tedious since we would need to adapt the test files every time the DB is updated.

[FEATURE] Add OpenMSDatabasesInfo Util to list supported Enzymes and Mods in tsv

---

src/openms/source/FORMAT/FileHandler.cpp
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/DataSelectionTabs.cpp
src/pyOpenMS/pxds/FileHandler.pxd

Additional filetypes in TOPPView.
Addresses #5231 partly

add additional peakfiletypes in TOPPView

---

src/topp/PercolatorAdapter.cpp

Update PercolatorAdapter.cpp version number (merge after THIRDPARTY update)

---

src/topp/PercolatorAdapter.cpp

[NOP] Simplify condition in thread check

---

src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h
src/openms/source/FORMAT/HANDLERS/XQuestResultXMLHandler.cpp

Fixes #5253 
I cannot test it since it ran through on my Apple clang version 11.0.3 (clang-1103.0.32.29) before already.

[FIX?] xerces_unique_ptr templates

---

src/topp/FileMerger.cpp

[DOC] Extend description in FileMerger

---

doc/doxygen/install/install-linux.doxygen

[DOC] fixed min. required gcc version (from 4.9 to 7.0)

[DOC] fixed min. required gcc version

---

.gitpod.yml

Prebuilds were broken so we now build on workspace creation (takes a while)

Build gitpod on workspace creation

---

src/topp/FileConverter.cpp

Adds support for sqmass as output for FileConverter.

[FEATURE] Allows sqmass as output of FileConverter

---

src/pyOpenMS/pxds/PrecursorCorrection.pxd

fix python bindings

---

src/openms/source/DATASTRUCTURES/Param.cpp

Added some necessary checks that where missing in Param after the removal of non-standard dependencies.
Closes Issue #5295 

[FIX] Add missing checks in Param

---

src/openms/include/OpenMS/DATASTRUCTURES/Param.h
src/openms/source/DATASTRUCTURES/Param.cpp
src/pyOpenMS/pxds/BinnedSpectrum.pxd
src/pyOpenMS/pxds/ConfidenceScoring.pxd
src/pyOpenMS/pxds/DataValue.pxd
src/pyOpenMS/pxds/ISpectrumAccess.pxd
src/pyOpenMS/pxds/MRMTransitionGroup.pxd
src/pyOpenMS/pxds/MSSpectrum.pxd
src/pyOpenMS/pxds/OPXLHelper.pxd
src/pyOpenMS/pxds/OSWFile.pxd
src/pyOpenMS/pxds/Param.pxd
src/pyOpenMS/pxds/ParamValue.pxd
src/pyOpenMS/pxds/Tagger.pxd

Fixes some of the inconveniences introduced with python 3 switch and unicode strings

added string conversion to param and other classes

---

src/pyOpenMS/pyTOPP/CTDsupport.py
src/pyOpenMS/pyTOPP/common.py
src/pyOpenMS/pyTOPP/pyTOPPExample.py

[pyTOPP] initial support for CTD 

---

src/openms/include/OpenMS/FILTERING/DATAREDUCTION/FeatureFindingMetabo.h
src/openms/include/OpenMS/KERNEL/MassTrace.h
src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
src/openms/source/KERNEL/MassTrace.cpp
src/tests/class_tests/openms/data/FeatureFindingMetabo_output1.featureXML
src/tests/topp/FeatureFinderMetabo_1_output.featureXML
src/tests/topp/FeatureFinderMetabo_2_noEPD_output.featureXML
src/tests/topp/FeatureFinderMetabo_4_output.featureXML
src/tests/topp/FeatureFinderMetabo_5_output.featureXML

Add max peak hight over all mass traces as meta value

Fixes OpenMS/OpenMS#5232

---

src/pyOpenMS/pxds/MSExperiment.pxd
src/pyOpenMS/pxds/MSSpectrum.pxd
src/pyOpenMS/pxds/MzMLFile.pxd

[PY-Bindings] add some doc to MSExperiment and MzMLFile

---

src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderDefs.h
src/tests/topp/ProteinQuantifier_9_output_mztab.mzTab
src/tests/topp/ProteinQuantifier_input.consensusXML
src/topp/ProteinQuantifier.cpp

[FIX] ProteinQuantifier error with empty protein ID. 

---

src/utils/MSFraggerAdapter.cpp

force users to accept license terms

---

src/openms/source/APPLICATIONS/ToolHandler.cpp
src/topp/DatabaseSuitability.cpp

'DatabaseSuitability' from utils to topp tools in 'ToolHandler'

---

src/openms/source/MATH/STATISTICS/PosteriorErrorProbabilityModel.cpp

MSFragger engine is now included in the PEPModel.cpp including the score scaling

Include MSFragger engine in the PEPModel

---

src/openms/source/MATH/STATISTICS/PosteriorErrorProbabilityModel.cpp

Just the fix for the prior PR with a missing comma.

Bugfix MSFragger engine

---

src/openms/thirdparty/evergreen/src/FFT/FFT.hpp
src/openms/thirdparty/evergreen/src/Tensor/TensorUtils.hpp

test reducing template recursion level

---

.gitignore
src/openms/include/OpenMS/ANALYSIS/SEQUENCE/NeedlemanWunsch.h
src/openms/include/OpenMS/ANALYSIS/SEQUENCE/sources.cmake
src/openms/include/OpenMS/FORMAT/FASTAFile.h
src/openms/source/ANALYSIS/SEQUENCE/NeedlemanWunsch.cpp
src/openms/source/ANALYSIS/SEQUENCE/sources.cmake
src/openms/source/FORMAT/FASTAFile.cpp
src/openms/source/QC/MQEvidenceExporter.cpp

fixes currently broken develop

fix wrong gitignore; add missing sources.cmake

---

src/topp/MapAlignerIdentification.cpp
src/topp/MapAlignerPoseClustering.cpp

https://github.com/OpenMS/OpenMS/issues/1318

Warn if only one file provided as input to MapAlingerPoseClustering

---

src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h

Disallow IL_equivalent with enzymes that potentially distinguish them.

---

src/openms/source/ANALYSIS/SEQUENCE/NeedlemanWunsch.cpp

[FIX] segfault in NeedlemanWunsch

---

CHANGELOG
src/openms/source/SYSTEM/File.cpp
src/openms/source/SYSTEM/UpdateCheck.cpp

addresses https://github.com/OpenMS/OpenMS/issues/3681

[fix] updated the config storage path for linux

---

src/openms/source/APPLICATIONS/ConsoleUtils.cpp
src/openms/source/APPLICATIONS/ParameterInformation.cpp
src/openms/source/APPLICATIONS/TOPPBase.cpp
src/openms/source/APPLICATIONS/ToolHandler.cpp
src/openms/source/CHEMISTRY/AASequence.cpp

Small change in code arrangements

Small Code Arrangement changes

---

src/openms/source/FORMAT/MzTab.cpp

Remove unnecessary code to handle windows path. Now fixed directly in File:basename

remove now unnecessary code to extract basename

---

src/openms/source/ANALYSIS/ID/ConsensusIDAlgorithm.cpp
src/openms/source/CHEMISTRY/AASequence.cpp
src/openms/source/FILTERING/ID/IDFilter.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/SeedListGenerator.cpp

Code changes for the improvement of readability.

Code Arrangement changes #2

---

src/pyOpenMS/pxds/CVMappingRule.pxd
src/pyOpenMS/pxds/CVMappingTerm.pxd
src/pyOpenMS/pxds/CVMappings.pxd
src/pyOpenMS/pxds/CVReference.pxd
src/pyOpenMS/pxds/DPosition.pxd
src/pyOpenMS/pxds/DRange.pxd
src/pyOpenMS/pxds/DecoyGenerator.pxd
src/pyOpenMS/pxds/DefaultParamHandler.pxd
src/pyOpenMS/pxds/Digestion.pxd
src/pyOpenMS/pxds/DigestionEnzyme.pxd
src/pyOpenMS/pxds/DigestionEnzymeProtein.pxd
src/pyOpenMS/pxds/DigestionEnzymeRNA.pxd
src/pyOpenMS/pxds/DocumentIdentifier.pxd
src/pyOpenMS/pxds/Element.pxd
src/pyOpenMS/pxds/ElementDB.pxd
src/pyOpenMS/pxds/ElutionModelFitter.pxd
src/pyOpenMS/pxds/ElutionPeakDetection.pxd
src/pyOpenMS/pxds/EmgFitter1D.pxd
src/pyOpenMS/pxds/EmgGradientDescent.pxd
src/pyOpenMS/pxds/EmgModel.pxd

Added wrap-doc method #3

---

share/OpenMS/CV/psi-ms.obo
src/openms/source/FORMAT/MzQCFile.cpp
src/tests/topp/QCCalculator_2_output.mzQC

update CV URL

---

src/openms/include/OpenMS/ANALYSIS/ID/PercolatorFeatureSetHelper.h
src/openms/source/ANALYSIS/ID/PercolatorFeatureSetHelper.cpp
src/utils/PSMFeatureExtractor.cpp

MSFragger remove unused parameter

---

src/pyOpenMS/pxds/EnzymaticDigestion.pxd
src/pyOpenMS/pxds/ProteaseDigestion.pxd
src/pyOpenMS/pxds/RNaseDigestion.pxd

Follow up on https://github.com/OpenMS/OpenMS/pull/5396.
An additional example for digestUnmodified.

[ADD] Docstring example for digestUnmodified

---

src/openms/source/QC/TIC.cpp
src/openms/source/SYSTEM/File.cpp
src/openms/source/SYSTEM/UpdateCheck.cpp
src/tests/class_tests/openms/source/MSDataChainingConsumer_test.cpp

cpplint issues regarding the next release.
#5400

[STYLE] ccplint issues

---

src/openms/source/ANALYSIS/TARGETED/PrecursorIonSelectionPreprocessing.cpp
src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsoSpecWrapper.cpp
src/openms/source/DATASTRUCTURES/Adduct.cpp
src/openms/source/DATASTRUCTURES/CalibrationData.cpp
src/openms/source/DATASTRUCTURES/ChargePair.cpp
src/openms/source/DATASTRUCTURES/Compomer.cpp
src/openms/source/DATASTRUCTURES/ConvexHull2D.cpp
src/openms/source/DATASTRUCTURES/DefaultParamHandler.cpp
src/openms/source/DATASTRUCTURES/GridFeature.cpp
src/openms/source/DATASTRUCTURES/LPWrapper.cpp
src/openms/source/DATASTRUCTURES/MassExplainer.cpp
src/openms/source/DATASTRUCTURES/Param.cpp
src/openms/source/DATASTRUCTURES/ParamValue.cpp
src/openms/source/KERNEL/MSSpectrum.cpp
src/openms/source/MATH/MISC/NNLS/NNLS.cpp
src/openms/source/MATH/MISC/RANSACModel.cpp
src/openms/source/MATH/MISC/RANSACModelLinear.cpp
src/openms/source/MATH/MISC/RANSACModelQuadratic.cpp
src/openms/source/MATH/MISC/SplineBisection.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp
src/tests/class_tests/openms/source/MSSim_test.cpp

Code Arrangement Changes for improved readability.

Code Arrangement changes #3

---

CHANGELOG

Changelog: main features

---

tools/rest_server_update_helper.sh

update rest server helper script to exclude new GUI tools

---

src/openms/source/CHEMISTRY/Residue.cpp

added missing ion names

---

cmake/knime_package_support.cmake
src/pyOpenMS/tests/unittests/test_DIAScoring.py

Jpfeuffer patch 1

---

src/openms/source/ANALYSIS/DECHARGING/FeatureDeconvolution.cpp
src/openms/source/ANALYSIS/ID/IDBoostGraph.cpp
src/openms/source/ANALYSIS/ID/IDDecoyProbability.cpp
src/openms/source/ANALYSIS/ID/IDMapper.cpp
src/openms/source/ANALYSIS/ID/IDRipper.cpp
src/openms/source/ANALYSIS/ID/PeptideProteinResolution.cpp
src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmPoseClustering.cpp
src/openms/source/MATH/STATISTICS/AveragePosition.cpp
src/openms/source/MATH/STATISTICS/GammaDistributionFitter.cpp
src/openms/source/MATH/STATISTICS/GaussFitter.cpp
src/openms/source/MATH/STATISTICS/GumbelDistributionFitter.cpp
src/openms/source/MATH/STATISTICS/GumbelMaxLikelihoodFitter.cpp
src/openms/source/MATH/STATISTICS/LinearRegression.cpp
src/openms/source/MATH/STATISTICS/LinearRegressionWithoutIntercept.cpp
src/openms/source/MATH/STATISTICS/PosteriorErrorProbabilityModel.cpp
src/openms/source/MATH/STATISTICS/QuadraticRegression.cpp
src/openms/source/MATH/STATISTICS/ROCCurve.cpp
src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
src/utils/ProteomicsLFQ.cpp

Code Arrangement changes for better readability - 4.

Code Arrangement changes #4

---

src/openms/source/ANALYSIS/DECHARGING/FeatureDeconvolution.cpp
src/openms/source/ANALYSIS/ID/IDBoostGraph.cpp
src/openms/source/ANALYSIS/ID/IDDecoyProbability.cpp
src/openms/source/ANALYSIS/ID/IDMapper.cpp
src/openms/source/ANALYSIS/ID/IDRipper.cpp
src/openms/source/ANALYSIS/ID/PeptideProteinResolution.cpp
src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmPoseClustering.cpp
src/openms/source/DATASTRUCTURES/ParamValue.cpp
src/openms/source/MATH/STATISTICS/AveragePosition.cpp
src/openms/source/MATH/STATISTICS/GammaDistributionFitter.cpp
src/openms/source/MATH/STATISTICS/GaussFitter.cpp
src/openms/source/MATH/STATISTICS/GumbelDistributionFitter.cpp
src/openms/source/MATH/STATISTICS/GumbelMaxLikelihoodFitter.cpp
src/openms/source/MATH/STATISTICS/LinearRegression.cpp
src/openms/source/MATH/STATISTICS/LinearRegressionWithoutIntercept.cpp
src/openms/source/MATH/STATISTICS/PosteriorErrorProbabilityModel.cpp
src/openms/source/MATH/STATISTICS/QuadraticRegression.cpp
src/openms/source/MATH/STATISTICS/ROCCurve.cpp
src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
src/utils/ProteomicsLFQ.cpp
tools/changelog_helper.sh

Zero double values are now encoded as "0.0" and not "0.0e00" in ini files

[FIX] encoding of 0.0 double values in ini files

---

src/openms/include/OpenMS/ANALYSIS/ID/IDDecoyProbability.h
src/pyOpenMS/pxds/FIAMSDataProcessor.pxd
src/pyOpenMS/pxds/FIAMSScheduler.pxd
src/pyOpenMS/pxds/FileHandler.pxd
src/pyOpenMS/pxds/FileTypes.pxd
src/pyOpenMS/pxds/FilterFunctor.pxd
src/pyOpenMS/pxds/Fitter1D.pxd
src/pyOpenMS/pxds/GaussFilter.pxd
src/pyOpenMS/pxds/GaussFitter.pxd
src/pyOpenMS/pxds/GaussTraceFitter.pxd
src/pyOpenMS/pxds/GoodDiffFilter.pxd
src/pyOpenMS/pxds/Gradient.pxd
src/pyOpenMS/pxds/GridBasedCluster.pxd
src/pyOpenMS/pxds/HPLC.pxd
src/pyOpenMS/pxds/HiddenMarkovModel.pxd
src/pyOpenMS/pxds/HyperScore.pxd
src/pyOpenMS/pxds/IBSpectraFile.pxd
src/pyOpenMS/pxds/IDConflictResolverAlgorithm.pxd
src/pyOpenMS/pxds/IDDecoyProbability.pxd
src/pyOpenMS/pxds/Identification.pxd
src/pyOpenMS/pxds/IdentificationData.pxd

Added wrap-doc methods #5

---

.gitpod.yml

[FIX] adapt to new Gitpod version

---

src/openms/source/ANALYSIS/DENOVO/CompNovoIdentification.cpp
src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp
src/openms/source/ANALYSIS/ID/ProtonDistributionModel.cpp
src/openms/source/ANALYSIS/ID/SimpleSearchEngineAlgorithm.cpp
src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp
src/openms/source/ANALYSIS/ID/SiriusMSConverter.cpp
src/openms/source/DATASTRUCTURES/Compomer.cpp
src/openms/source/FILTERING/CALIBRATION/InternalCalibration.cpp
src/openms/source/FILTERING/CALIBRATION/MZTrafoModel.cpp
src/openms/source/FILTERING/CALIBRATION/TOFCalibration.cpp
src/openms/source/FILTERING/DATAREDUCTION/DataFilters.cpp
src/openms/source/FILTERING/DATAREDUCTION/Deisotoper.cpp
src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
src/openms/source/FILTERING/ID/IDFilter.cpp
src/openms/source/FORMAT/Base64.cpp
src/openms/source/FORMAT/EDTAFile.cpp
src/openms/source/FORMAT/FeatureXMLFile.cpp
src/openms/source/FORMAT/FileHandler.cpp
src/openms/source/FORMAT/HDF5Connector.cpp
src/openms/source/FORMAT/InspectOutfile.cpp
src/openms/source/FORMAT/KroenikFile.cpp
src/openms/source/METADATA/AbsoluteQuantitationStandards.cpp
src/openms/source/METADATA/DocumentIDTagger.cpp
src/openms/source/METADATA/ExperimentalDesign.cpp
src/openms/source/METADATA/PeptideIdentification.cpp
src/openms_gui/source/VISUAL/FilterList.cpp
src/openms_gui/source/VISUAL/LayerData.cpp

Code Arrangement changes #5

---

src/openms/source/CHEMISTRY/ElementDB.cpp

Adding Isotope of Zirconium (96) and Correcting Boron name.
References : 
>https://www.sisweb.com/referenc/source/exactmas.htm
>https://www.ciaaw.org/zirconium.htm

Adding Isotope of Zr

---

src/openms/source/CHEMISTRY/AASequence.cpp
src/openms/source/CHEMISTRY/DecoyGenerator.cpp
src/openms/source/CHEMISTRY/DigestionEnzyme.cpp
src/openms/source/CHEMISTRY/ElementDB.cpp
src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/IMSAlphabet.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/IMSElement.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/IMSIsotopeDistribution.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/RealMassDecomposer.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/Weights.cpp
src/openms/source/CHEMISTRY/ModificationDefinitionsSet.cpp
src/openms/source/CHEMISTRY/ModificationsDB.cpp
src/openms/source/CHEMISTRY/ModifiedNASequenceGenerator.cpp
src/openms/source/CHEMISTRY/NASequence.cpp
src/openms/source/CHEMISTRY/NucleicAcidSpectrumGenerator.cpp
src/openms/source/CHEMISTRY/ProteaseDigestion.cpp
src/openms/source/CHEMISTRY/RNaseDigestion.cpp
src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGeneratorSet.cpp
src/openms/source/CHEMISTRY/Tagger.cpp
src/openms/source/CHEMISTRY/WeightWrapper.cpp
src/openms/source/SYSTEM/ExternalProcess.cpp
src/openms/source/SYSTEM/File.cpp
src/openms/source/SYSTEM/RWrapper.cpp
src/openms/source/SYSTEM/SysInfo.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/BiGaussFitter1D.cpp

Code changes for better readability.

Code Arrangement Changes #6

---

src/openms/source/CHEMISTRY/AASequence.cpp
src/openms/source/CHEMISTRY/DecoyGenerator.cpp
src/openms/source/CHEMISTRY/DigestionEnzyme.cpp
src/openms/source/CHEMISTRY/ElementDB.cpp
src/openms/source/CHEMISTRY/EmpiricalFormula.cpp
src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp
src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/IMSAlphabet.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/IMSElement.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/IMSIsotopeDistribution.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/RealMassDecomposer.cpp
src/openms/source/CHEMISTRY/MASSDECOMPOSITION/IMS/Weights.cpp
src/openms/source/CHEMISTRY/ModificationDefinitionsSet.cpp
src/openms/source/CHEMISTRY/ModificationsDB.cpp
src/openms/source/CHEMISTRY/ModifiedNASequenceGenerator.cpp
src/openms/source/CHEMISTRY/NASequence.cpp
src/openms/source/CHEMISTRY/NucleicAcidSpectrumGenerator.cpp
src/openms/source/CHEMISTRY/ProteaseDigestion.cpp
src/openms/source/CHEMISTRY/RNaseDigestion.cpp
src/openms/source/CHEMISTRY/SvmTheoreticalSpectrumGeneratorSet.cpp
src/openms/source/CHEMISTRY/Tagger.cpp
src/openms/source/CHEMISTRY/WeightWrapper.cpp
src/openms/source/SYSTEM/ExternalProcess.cpp
src/openms/source/SYSTEM/File.cpp
src/openms/source/SYSTEM/RWrapper.cpp
src/openms/source/SYSTEM/SysInfo.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/BiGaussFitter1D.cpp
src/tests/class_tests/openms/source/EmpiricalFormula_test.cpp

sync style changes to release

---

src/openms_gui/source/VISUAL/TOPPViewMenu.cpp

[TOPPView] Use copy of local member parent for showing About dialog

---

src/openms/include/OpenMS/ANALYSIS/ID/FalseDiscoveryRate.h
src/openms/include/OpenMS/ANALYSIS/ID/IDScoreGetterSetter.h
src/openms/source/ANALYSIS/ID/FalseDiscoveryRate.cpp
src/openms/source/ANALYSIS/ID/IDScoreGetterSetter.cpp
src/pyOpenMS/pxds/FalseDiscoveryRate.pxd
src/tests/class_tests/openms/data/FalseDiscoveryRate_picked_in.idXML
src/tests/class_tests/openms/source/FalseDiscoveryRate_test.cpp

Implements picked protein FDR based on decoy prefices.

[Feature] picked protein fdr

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/TransitionPQPFile.h
src/openms/include/OpenMS/ANALYSIS/XLMS/XQuestScores.h
src/openms/include/OpenMS/CHEMISTRY/TheoreticalSpectrumGeneratorXLMS.h
src/openms/include/OpenMS/CONCEPT/UniqueIdInterface.h
src/openms/include/OpenMS/FORMAT/XQuestResultXMLFile.h
src/pyOpenMS/pxds/TICFilter.pxd
src/pyOpenMS/pxds/TOFCalibration.pxd
src/pyOpenMS/pxds/Tagger.pxd
src/pyOpenMS/pxds/Tagging.pxd
src/pyOpenMS/pxds/TargetedExperiment.pxd
src/pyOpenMS/pxds/TargetedExperimentHelper.pxd
src/pyOpenMS/pxds/TextFile.pxd
src/pyOpenMS/pxds/TheoreticalSpectrumGenerator.pxd
src/pyOpenMS/pxds/TheoreticalSpectrumGeneratorXLMS.pxd
src/pyOpenMS/pxds/TraMLFile.pxd
src/pyOpenMS/pxds/TransformationDescription.pxd
src/pyOpenMS/pxds/TransformationModel.pxd
src/pyOpenMS/pxds/TransformationModelBSpline.pxd
src/pyOpenMS/pxds/TransformationModelInterpolated.pxd
src/pyOpenMS/pxds/TransitionPQPFile.pxd
src/pyOpenMS/pxds/TransitionTSVFile.pxd
src/pyOpenMS/pxds/TwoDOptimization.pxd
src/pyOpenMS/pxds/UniqueIdInterface.pxd
src/pyOpenMS/pxds/Weights.pxd
src/pyOpenMS/pxds/WindowMower.pxd
src/pyOpenMS/pxds/XMLFile.pxd
src/pyOpenMS/pxds/XQuestResultXMLFile.pxd
src/pyOpenMS/pxds/XQuestScores.pxd

adding-wrap-doc-method-16

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/BiGaussModel.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/EGHTraceFitter.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/ElutionModelFitter.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/EmgFitter1D.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/EmgModel.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/ExtendedIsotopeFitter1D.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/ExtendedIsotopeModel.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinder.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMRM.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmPicked.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmPickedHelperStructs.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderMultiplexAlgorithm.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/Fitter1D.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/GaussFitter1D.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/GaussModel.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/GaussTraceFitter.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/IsotopeFitter1D.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/IsotopeModel.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/IsotopeWavelet.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/LevMarqFitter1D.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexClustering.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexDeltaMassesGenerator.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteredMSExperiment.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/SeedListGenerator.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/TraceFitter.cpp

code arrangement changes for better readability.

Code Arrangement changes-12

---

src/openms/source/SIMULATION/DetectabilitySimulation.cpp
src/openms/source/SIMULATION/DigestSimulation.cpp
src/openms/source/SIMULATION/EGHFitter1D.cpp
src/openms/source/SIMULATION/EGHModel.cpp
src/openms/source/SIMULATION/IonizationSimulation.cpp
src/openms/source/SIMULATION/LABELING/BaseLabeler.cpp
src/openms/source/SIMULATION/LABELING/ICPLLabeler.cpp
src/openms/source/SIMULATION/LABELING/ITRAQLabeler.cpp
src/openms/source/SIMULATION/LABELING/LabelFreeLabeler.cpp
src/openms/source/SIMULATION/LABELING/O18Labeler.cpp
src/openms/source/SIMULATION/LABELING/SILACLabeler.cpp
src/openms/source/SIMULATION/MSSim.cpp
src/openms/source/SIMULATION/RTSimulation.cpp
src/openms/source/SIMULATION/RawMSSignalSimulation.cpp
src/openms/source/SIMULATION/RawTandemMSSignalSimulation.cpp
src/openms/source/SYSTEM/ExternalProcess.cpp
src/openms/source/SYSTEM/File.cpp
src/openms/source/SYSTEM/RWrapper.cpp
src/openms/source/SYSTEM/SysInfo.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/OptimizePeakDeconvolution.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/OptimizePick.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerCWT.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerMaxima.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakShape.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/TwoDOptimization.cpp

code arrangement changes for better readability.

Code Arrangement Changes-11

---

src/openms/include/OpenMS/ANALYSIS/ID/IDScoreGetterSetter.h

[Fix] picked protein fdr

---

src/topp/MSGFPlusAdapter.cpp
src/topp/MaRaClusterAdapter.cpp
src/topp/MapNormalizer.cpp
src/topp/MapStatistics.cpp
src/topp/MascotAdapterOnline.cpp
src/topp/MassTraceExtractor.cpp
src/topp/MyriMatchAdapter.cpp
src/topp/OMSSAAdapter.cpp
src/topp/OpenSwathAnalyzer.cpp
src/topp/OpenSwathChromatogramExtractor.cpp
src/topp/OpenSwathFeatureXMLToTSV.cpp
src/topp/PeakPickerHiRes.cpp
src/topp/PepNovoAdapter.cpp
src/topp/PercolatorAdapter.cpp
src/topp/PhosphoScoring.cpp
src/topp/PrecursorIonSelector.cpp
src/topp/PrecursorMassCorrector.cpp
src/topp/ProteinQuantifier.cpp
src/topp/ProteinResolver.cpp
src/topp/QualityControl.cpp
src/topp/RTModel.cpp
src/topp/SpecLibSearcher.cpp
src/topp/TOFCalibration.cpp
src/topp/TextExporter.cpp
src/topp/XFDR.cpp
src/topp/XTandemAdapter.cpp

Code Arrangement changes-15

---

src/pyOpenMS/pxds/AASequence.pxd
src/pyOpenMS/pxds/BSpline2d.pxd
src/pyOpenMS/pxds/BaseFeature.pxd
src/pyOpenMS/pxds/BilinearInterpolation.pxd
src/pyOpenMS/pxds/BinnedSpectrum.pxd
src/pyOpenMS/pxds/CVMappingRule.pxd
src/pyOpenMS/pxds/CVMappingTerm.pxd
src/pyOpenMS/pxds/CVTerm.pxd
src/pyOpenMS/pxds/CalibrationData.pxd
src/pyOpenMS/pxds/ChargePair.pxd
src/pyOpenMS/pxds/ChromatogramExtractor.pxd
src/pyOpenMS/pxds/ChromatogramPeak.pxd
src/pyOpenMS/pxds/ChromatogramSettings.pxd
src/pyOpenMS/pxds/ChromeleonFile.pxd
src/pyOpenMS/pxds/Compomer.pxd
src/pyOpenMS/pxds/ConsensusFeature.pxd
src/pyOpenMS/pxds/ConsensusIDAlgorithm.pxd
src/pyOpenMS/pxds/ConsensusMap.pxd
src/pyOpenMS/pxds/ContinuousWaveletTransform.pxd
src/pyOpenMS/pxds/ControlledVocabulary.pxd
src/pyOpenMS/pxds/ConvexHull2D.pxd
src/pyOpenMS/pxds/CsvFile.pxd

adding-wrap-doc-method-17

---

share/OpenMS/CV/qc-cv-legacy.obo
src/openms/source/FORMAT/QcMLFile.cpp
src/tests/topp/QCCalculator_1_output.qcML
src/utils/QCEmbedder.cpp
src/utils/QCExporter.cpp
src/utils/QCImporter.cpp

- [ x ] Make sure that you are listed in the AUTHORS file

[fix] add qc-cv legacy CVs

---

share/OpenMS/CV/qc-cv-legacy.obo
src/openms/source/FORMAT/QcMLFile.cpp
src/tests/topp/QCCalculator_1_output.qcML
src/utils/QCEmbedder.cpp
src/utils/QCExporter.cpp
src/utils/QCImporter.cpp

Legacy release

---

src/utils/ProteomicsLFQ.cpp

PLFQ Write chromatograms for debugging

---

cmake/knime_package_support.cmake
share/OpenMS/SCHEMAS/FeatureXML_1_8.xsd
share/OpenMS/SCHEMAS/FeatureXML_1_9.xsd
src/openms_gui/source/VISUAL/TOPPViewMenu.cpp
src/pyOpenMS/pxds/BilinearInterpolation.pxd
src/pyOpenMS/pxds/BinnedSpectrum.pxd
src/pyOpenMS/pxds/CVMappingRule.pxd
src/pyOpenMS/pxds/CVMappingTerm.pxd
src/pyOpenMS/pxds/CVTerm.pxd
src/pyOpenMS/pxds/ChargePair.pxd
src/pyOpenMS/pxds/ConvexHull2D.pxd
src/pyOpenMS/pxds/ISpectrumAccess.pxd
src/pyOpenMS/pxds/Instrument.pxd
src/pyOpenMS/pxds/InstrumentSettings.pxd
src/pyOpenMS/pxds/InterpolationModel.pxd
src/pyOpenMS/pxds/LPWrapper.pxd
src/pyOpenMS/pxds/MRMFeature.pxd
src/pyOpenMS/pxds/MSDataStoringConsumer.pxd
src/pyOpenMS/pxds/MarkerMower.pxd
src/pyOpenMS/pxds/MassExplainer.pxd
src/pyOpenMS/pxds/MassTrace.pxd
src/tests/topp/CMakeLists.txt
src/utils/AssayGeneratorMetabo.cpp
src/utils/SiriusAdapter.cpp

Corresponding to #5540
Fixing the pyopenms introduced merge conflicts, without changing the actual release/2.7.0 branch.

Merge Release 2.7.0

---

src/pyOpenMS/addons/Param.pyx

Untested. For an easy
`print(Algorithm().getDefaults())`
including descriptions

[Feature] Try to add descriptions to Param class repr in pyopenms

---

src/pyOpenMS/addons/AASequence.pyx

[fix] aaseq python ext.

---

src/openms/include/OpenMS/KERNEL/MSSpectrum.h
src/openms/source/SYSTEM/File.cpp

std::iota needs to be included from numeric.h

[RELEASE] Fix compile errors

---

src/pyOpenMS/pxds/PeptideHit.pxd
src/pyOpenMS/pxds/PeptideIdentification.pxd
src/pyOpenMS/pxds/PeptideIndexing.pxd
src/pyOpenMS/pxds/PercolatorOutfile.pxd
src/pyOpenMS/pxds/PrecursorIonSelectionPreprocessing.pxd
src/pyOpenMS/pxds/Product.pxd
src/pyOpenMS/pxds/ProteaseDB.pxd
src/pyOpenMS/pxds/QTCluster.pxd
src/pyOpenMS/pxds/ReactionMonitoringTransition.pxd
src/pyOpenMS/pxds/Residue.pxd
src/pyOpenMS/pxds/ResidueModification.pxd
src/pyOpenMS/pxds/Ribonucleotide.pxd
src/pyOpenMS/pxds/SampleTreatment.pxd
src/pyOpenMS/pxds/SeedListGenerator.pxd
src/pyOpenMS/pxds/SemanticValidator.pxd
src/pyOpenMS/pxds/SequestInfile.pxd
src/pyOpenMS/pxds/SequestOutfile.pxd
src/pyOpenMS/pxds/SimpleSVM.pxd
src/pyOpenMS/pxds/SpectrumAccessOpenMS.pxd
src/pyOpenMS/pxds/SqrtMower.pxd

adding-wrap-doc-method-22

---

.gitpod.Dockerfile
.vscode-gitpod/settings.json
src/openms/include/OpenMS/FORMAT/PepXMLFile.h
src/openms/include/OpenMS/METADATA/SpectrumLookup.h
src/openms/source/FORMAT/PepXMLFile.cpp
src/openms/source/METADATA/SpectrumLookup.cpp
src/pyOpenMS/pxds/PepXMLFile.pxd
src/tests/topp/IDFileConverter_10_output.idXML
src/tests/topp/IDFileConverter_16_output.idXML
src/tests/topp/IDFileConverter_2_output.idXML
src/tests/topp/THIRDPARTY/MyriMatchAdapter_1_out.idXML

Maybe fixes #5538
Also allows reading unknown scores from pepXML as requested on Gitter.

[FIX] Consider fixed mods for terms, reading pepXML

---

src/openms/source/FORMAT/PepXMLFile.cpp

Forgot the change for C-term. adds to #5538

[FIX] Forgot C-term fixed mod lookup in pepXML

---

CMakeLists.txt
cmake/modules/cotire.cmake
doc/CMakeLists.txt
doc/code_examples/CMakeLists.txt
src/CMakeLists.txt
src/openms_gui/CMakeLists.txt
src/tests/class_tests/CMakeLists.txt
src/tests/class_tests/openms/CMakeLists.txt
src/tests/class_tests/openms_gui/CMakeLists.txt
src/tests/class_tests/openswathalgo/CMakeLists.txt
src/topp/CMakeLists.txt
src/utils/CMakeLists.txt

Quick and dirty attempt to enable LTO

[CMAKE] option to enable LTO

---

src/openms/include/OpenMS/FORMAT/OPTIONS/PeakFileOptions.h
src/openms/include/OpenMS/KERNEL/Peak2D.h
src/pyOpenMS/pxds/NLargest.pxd
src/pyOpenMS/pxds/Normalizer.pxd
src/pyOpenMS/pxds/OnDiscMSExperiment.pxd
src/pyOpenMS/pxds/OpenPepXLLFAlgorithm.pxd
src/pyOpenMS/pxds/OpenSwathDataAccessHelper.pxd
src/pyOpenMS/pxds/OpenSwathHelper.pxd
src/pyOpenMS/pxds/OptimizePeakDeconvolution.pxd
src/pyOpenMS/pxds/OptimizePick.pxd
src/pyOpenMS/pxds/ParamValue.pxd
src/pyOpenMS/pxds/ParamXMLFile.pxd
src/pyOpenMS/pxds/ParentPeakMower.pxd
src/pyOpenMS/pxds/Peak2D.pxd
src/pyOpenMS/pxds/PeakFileOptions.pxd
src/pyOpenMS/pxds/PeakIndex.pxd
src/pyOpenMS/pxds/PeakMarker.pxd
src/pyOpenMS/pxds/PeakPickerSH.pxd
src/pyOpenMS/pxds/PeakTypeEstimator.pxd
src/pyOpenMS/pxds/PeptideEvidence.pxd

adding-wrap-doc-method-21

---

src/openms/include/OpenMS/DATASTRUCTURES/StringUtilsSimple.h

trying to prevent some of the clang warnings on cdash

[FIX] use static inline for namespace

---

src/pyOpenMS/addons/ADD_TO_ALL.pyx
src/pyOpenMS/addons/ConsensusMap.pyx
src/pyOpenMS/pxds/ConsensusMap.pxd
src/pyOpenMS/pxds/PeptideAndProteinQuant.pxd
src/pyOpenMS/pxds/RANSAC.pxd
src/pyOpenMS/pxds/RealMassDecomposer.pxd
src/pyOpenMS/pxds/SeedListGenerator.pxd
src/pyOpenMS/pxds/Types.pxd

Use int types with correct sizes

[pyopenms] Fix pyopenms int size (on windows)

---

src/openms_gui/source/VISUAL/TVToolDiscovery.cpp

Async may spawn one thread per topp tool. That's no problem but apparently 
spawning hundreds of processes (=tool execution for ini file reading, one for each thread) seems to hit
a hard limit in file handles or available pipes.
Simplest form of process pool implementation I can come up with :)

Fix tool scan in TOPPView

---

src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.h
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp

only detect features on MS1 (don't mix levels)

---

src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.h
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
src/tests/class_tests/openms/source/ElutionModelFitter_test.cpp

Support setting of spectra using move.
Added test for ElutionModelFitter

Emf test and ffmid move

---

src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.h
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp
src/pyOpenMS/pxds/FeatureFinderAlgorithmMetaboIdent.pxd
src/tests/topp/CMakeLists.txt
src/tests/topp/FeatureFinderMetaboIdent_1_output.featureXML
src/utils/FeatureFinderMetaboIdent.cpp

Potentially needs update in the tutorials.

add backlink to MS run in FFmetaboIdent

---

src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.h
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp
src/pyOpenMS/pxds/FeatureFinderIdentificationAlgorithm.pxd
src/topp/FeatureFinderIdentification.cpp
src/utils/ProteomicsLFQ.cpp

ffid annotate spectra file path already in algorithm

---

src/openms_gui/source/VISUAL/TableView.cpp

fix TOPPView checkbox state export

---

src/openms/include/OpenMS/SYSTEM/File.h
src/openms/source/SYSTEM/File.cpp

static function did also return reference to temporary

fix return to reference

---

src/openms/source/TRANSFORMATIONS/FEATUREFINDER/ElutionModelFitter.cpp

workaround for rare segfault in elution peak detection

---

.gitmodules

Create submodule for pyopenms-extra to simplify e.g. renames and pinning documentation to an OpenMS version

[SUBMODULE] add pyopenms-extra as submodule

---

src/topp/FileFilter.cpp

add FileFilter option to overwrite precursor charge

add FileFilter option to overwrite precursor charge

---

src/openms/include/OpenMS/ANALYSIS/TARGETED/TargetedExperiment.h
src/openms/source/ANALYSIS/TARGETED/TargetedExperiment.cpp

follow up from #5611, now also implements the move assignment and constructor

[FIX] add move constructor and assignment operator

---

.github/workflows/openms_clang_format.yml

clang-format version 13

---

.github/workflows/openms_clang_format.yml

Only run if a cpp or h was changed.

Only run clang-format if sth was changed

---

src/openms/include/OpenMS/KERNEL/MSSpectrum.h
src/openms_gui/source/VISUAL/DIALOGS/LayerStatisticsDialog.cpp
src/openms_gui/source/VISUAL/LayerDataIdent.cpp

Fixes some compile warning recently introduced
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that do not …

fix compile warnings

---

.github/workflows/cppcheck.yml

We can now manually check cppcheck output by opening the report step of the action.
- setting the label NoJenkins will skip tests for this PR on jenkins (saves …

test of cppcheck action

---

src/openms/include/OpenMS/ANALYSIS/ID/IDRipper.h

add dll export

---

src/pyOpenMS/addons/MSSpectrum.pyx

Finally saw it after cleaning up pyopenms logs

[FIX] Major error in pyopenms addon MSSpectrum

---

src/openms/include/OpenMS/DATASTRUCTURES/StringUtils.h

Reduce warnings on unused functions

---

src/openms/source/FORMAT/OMSFileStore.cpp

Fixes #5752 
- setting the label NoJenkins will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)

[PERFORMANCE] add index for peakannotations

---

src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
src/openms_gui/source/VISUAL/SpectraTreeTab.cpp
src/tests/class_tests/openms/source/SVMWrapper_test.cpp

Fixes some compile warnings resulting in failing github actions. …

compile fixes

---

src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp
src/openms_gui/source/VISUAL/SpectraTreeTab.cpp
src/tests/class_tests/openms/source/SVMWrapper_test.cpp

Revert "compile fixes"

---

src/openms/CMakeLists.txt
src/openms/include/OpenMS/ANALYSIS/ID/PeptideIndexing.h
src/openms/include/OpenMS/MATH/STATISTICS/LinearRegression.h
src/openms/source/MATH/STATISTICS/LinearRegression.cpp

move Wm5 dep to cpp

---

src/pyOpenMS/CMakeLists.txt

[FEATURE] add pyopenms option to not bundle dependencies. removes need for patch in conda

---

src/openms/include/OpenMS/ANALYSIS/ID/AhoCorasickAmbiguous.h
src/openms/include/OpenMS/CONCEPT/Exception.h
src/openms/include/OpenMS/METADATA/ID/IdentificationDataConverter.h
src/openms/source/ANALYSIS/ID/AhoCorasickAmbiguous.cpp
src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
src/openms/source/ANALYSIS/OPENSWATH/SwathMapMassCorrection.cpp
src/openms/source/MATH/STATISTICS/LinearRegression.cpp
src/tests/class_tests/openms/source/ModifiedPeptideGenerator_test.cpp
src/topp/IDFileConverter.cpp

mostly from failing nightly builds and some recently introduced which were not caught by CI
- setting the label NoJenkins will skip tests for this PR on jenkins …

a few fixes

---

src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h
src/openms_gui/include/OpenMS/VISUAL/SpectraIDViewTab.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp

Attempt to fix some compile warnings.
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect …

fix some compile warnings

---

src/openms/include/OpenMS/DATASTRUCTURES/DataValue.h
src/openms/source/DATASTRUCTURES/DataValue.cpp

Add slightly additional output as requested in https://github.com/OpenMS/OpenMS/issues/4833
Ideally, we could also output the meta value name that caused an exception.
- `/reformat` (experimental) applies the clang-format style changes as additional …

more error information in DataValue exception

---

src/openms/source/DATASTRUCTURES/DataValue.cpp

print also value of data value
- …

more detailed error message in DataValue conversion

---

src/openms_gui/source/VISUAL/AxisPainter.cpp
src/openms_gui/source/VISUAL/AxisTickCalculator.cpp
src/openms_gui/source/VISUAL/PlotCanvas.cpp

fixes #5868 which was introduced in #5703
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not …

TOPPView: fix log scale display (caused by negative intensity in visible area)

---

src/openms/include/OpenMS/CHEMISTRY/ElementDB.h
src/openms/source/CHEMISTRY/ElementDB.cpp

[FEATURE] fix monoisotopic definition

---

src/tests/topp/CMakeLists.txt
src/tests/topp/FeatureFinderMetaboIdent_1_output.featureXML
src/utils/FeatureFinderMetaboIdent.cpp

Annotate file name, handle test scenario, remove whitelisting
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on …

Fixes 5894

---

src/openms/include/OpenMS/ANALYSIS/OPENSWATH/IonMobilityScoring.h
src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.h
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
src/openms/source/ANALYSIS/OPENSWATH/OpenSwathScoring.cpp
src/topp/OpenSwathAnalyzer.cpp
src/utils/MRMTransitionGroupPicker.cpp

add some documentation / and `const` to OpenSwath

[DOC] documentation of OpenSwath

---

src/openms/include/OpenMS/CHEMISTRY/Residue.h
src/openms/include/OpenMS/CHEMISTRY/ResidueModification.h
src/openms/source/CHEMISTRY/Residue.cpp
src/openms/source/CHEMISTRY/ResidueModification.cpp
src/tests/class_tests/openms/source/Residue_test.cpp

- add documentation
- ensure that `setFormula` recalculates the average and mono weights

Recalculate average and mono weight in Residue setFormula

---

src/openms/source/CHEMISTRY/ElementDB.cpp

Added more elements with the reference below, excluding the elements present in PR #5451 
Reference:
https://pubchem.ncbi.nlm.nih.gov/
https://www.rsc.org/periodic-table/
https://www.ciaaw.org/

Adding more Elements

---

src/openms/source/QC/MQEvidenceExporter.cpp

[FIX] isnan error

---

src/openms_gui/source/VISUAL/SpectraIDViewTab.cpp

[FIX] Warning: unused variables

---

src/openms_gui/source/VISUAL/MISC/GUIHelpers.cpp

[FIX] suppress warnings till 5.11

---

src/openms/source/ANALYSIS/DECHARGING/MetaboliteFeatureDeconvolution.cpp
src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp
src/openms/source/ANALYSIS/ID/FIAMSDataProcessor.cpp
src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmSpectrumAlignment.cpp
src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmTreeGuided.cpp
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp
src/openms/source/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.cpp
src/openms/source/ANALYSIS/TARGETED/PrecursorIonSelectionPreprocessing.cpp
src/openms/source/FILTERING/SMOOTHING/GaussFilter.cpp
src/openms/source/TRANSFORMATIONS/RAW2PEAK/PeakPickerCWT.cpp
src/utils/ProteomicsLFQ.cpp

fixes https://github.com/OpenMS/OpenMS/issues/5880
with some grepping in the generated ctd files and the sources I found some boolean parameters that need restructions
in order to get a proper (ie more easily translatable to Galaxy tool wrapper) ctd file .. also CLI might profit from this.
As usual I'm just stumbling around in the sources and you should assume that I'm not really knowing what I'm doing :) i.e.
- not sure if all changes are correct (hoping for the tests)
- not sure if all changes are needed
- not sure if there are more parameters that I overlooked
Somehow I remember that the order of `true` and `false` might be important?
For my own reference.. For ctd grep-ing  I used
```bash
grep 'type="string"' ctd/ -r | grep 'value="true"' | grep -v restrictions
grep 'type="string"' …
```

fix some unrestricted boolean parameters

---

src/pyOpenMS/CMakeLists.txt

functionality should be superseded by FindPython

Remove deprecated PythonLibs find module usage

---

src/openms_gui/source/VISUAL/APPLICATIONS/TOPPASBase.cpp

[Fix] toList() is deprecated

---

src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h

This PR suppressing compiler warning for mac incase of Unused Functions. for eg: `src/openms/include/OpenMS/DATASTRUCTURES/Utils/MatrixUtils.h:53:3: warning: unused function 'convertOpenMSMatrix2EigenMatrixXd' [-Wunused-function]`
1.  convertOpenMSMatrix2EigenMatrixXd() -  `/src/openms/source/ANALYSIS/QUANTITATION/IsobaricIsotopeCorrector.cpp, Line:77` & `/src/openms/source/SIMULATION/LABELING/ITRAQLabeler.cpp, Line:233`
2.  matrixIsIdentityMatrix() - `/src/openms/source/ANALYSIS/QUANTITATION/IsobaricIsotopeCorrector.cpp, Line:69` & `/src/openms/source/ANALYSIS/QUANTITATION/IsotopeLabelingMDVs.cpp, Line:80`
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get …

suppress-unused-function-warnings

---

src/pyOpenMS/CMakeLists.txt

Do not package deps into wheelhouse

[FIX] No deps pyopenms

---

src/openms_gui/source/VISUAL/TOPPASScene.cpp
src/openms_gui/source/VISUAL/TableView.cpp
src/openms_gui/source/VISUAL/TreeView.cpp

[FIX] few more toList() left

---

.github/workflows/openms-ci.yml

- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on …

run github actions CI for every push/PR

---

src/pyOpenMS/pyopenms/Plotting.py

Catch corner cases and add docs

[FIX] Make plotting.py more robust

---

.github/workflows/pyopenms-wheels.yml

Currently we only have the last built package.

fix and move pyopenms whls before they get deleted again on lnx

---

share/OpenMS/examples/external_code/CMakeLists.txt
share/OpenMS/examples/external_code/README.md

Update CMakeLists.txt and Readme.md for creating an external project.
Thanks @jpfeuffer for help in figuring this out :)
- setting the label "NoJenkins" will …

fix external project

---

src/tests/class_tests/openms/source/SVMWrapper_test.cpp

- commenting with `rebuild jenkins` …

minimal revert attempt to fix SVMWrapper_test

---

src/pyOpenMS/CMakeLists.txt
src/pyOpenMS/fix_pyi_imports.py

Otherwise PyCharm does not seem to pick up types from other submodules.

[FIX,PYOMS,TYPING] add global imports to every pyi

---

src/openms/include/OpenMS/ANALYSIS/NUXL/NuXLPresets.h

- commenting with `rebuild jenkins` …

Formaldehyde DNA presets added

---

.gitmodules
AUTHORS
CHANGELOG

Fixes https://github.com/OpenMS/pyopenms-docs/issues/269.
Steps and Tests.
1. Inside `OpenMS/src/pyOpenMS/pyopenms-extra` run `git submodule update --init` .
2. Update `submodule` and `url` in `.gitmodules`.
3. Inside `OpenMS/src/pyOpenMS/` run `git mv pyopenms-extra pyopenms-docs`.
4. Repeat 1.
5. `git submodule sync`
Links correctly to SHA [`f3264f9`](https://github.com/OpenMS/pyopenms-docs/tree/f3264f97ba64ff326f996fe3c45c86a19a0515c1).
<details>
</details>
<details>
<summary>Click to …

Rename pyopenms-extra to pyopenms-docs

---

.github/FUNDING.yml

add FUNDING.yml with our opencollective account
https://github.com/OpenMS/OpenMS/issues/6052

added funding.yml

---

src/openms_gui/source/VISUAL/Plot2DCanvas.cpp

Fixes #5985 
<details>
</details>
<details>
- commenting with `rebuild jenkins` will …

[FIX]: suppressed deprecated QRegion::rects()

---

src/openms/include/OpenMS/FILTERING/TRANSFORMERS/SpectraMerger.h
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp

Fixes #5929
<details>
</details>
<details>
- commenting with `rebuild jenkins` will …

[FIX]: wrange-loop-contruct

---

src/openms/include/OpenMS/FILTERING/TRANSFORMERS/SpectraMerger.h
src/openms/source/ANALYSIS/OPENSWATH/MRMFeatureFilter.cpp

Here discussed: [6098](https://github.com/OpenMS/OpenMS/pull/6098)
<details>
</details>
<details>
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not …

[FEATURE] Some refining ... added auto and changed var names.

---

src/pyOpenMS/CMakeLists.txt

fixes #6124
<details>
</details>
<details> …

[FIX/PYOPENMS] update min. req. autowrap version

---

src/tests/topp/THIRDPARTY/third_party_tests.cmake

[FIX] DatabaseSuitability Tests only executed when CometAdapter is found

---

src/openms/source/CONCEPT/CommonEnums.cpp

removed accidently introduced pragma in cpp file
<details>
</details>
<details> …

fix unneded pragma warning in cpp

---

src/utils/MSFraggerAdapter.cpp

Added the compatible versions of MSFragger into the documentation of the adapter. 
<details>
</details>
<details>
- …

Added version of MSFragger into the MSFraggerAdapter documentation

---

src/openms/include/OpenMS/ANALYSIS/NUXL/NuXLPresets.h

<details>
</details>
<details>
- commenting with `rebuild jenkins` will retrigger …

FA_DNA presets updated

---

src/openms/source/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.cpp

removed unknown_feature_counter unused variable

fixed compilation error unknown_feature_counter unused variable

---

src/topp/GNPSExport.cpp

Added the MapRTTransformer as a step for the GNPSExport documentation.
<details>
</details>
<details>
- setting the …

[Fix] add MapRTTransformer step in GNPSExpoert docs

---

src/openms/include/OpenMS/DATASTRUCTURES/DPosition.h
src/openms/include/OpenMS/KERNEL/MobilityPeak1D.h
src/openms/include/OpenMS/KERNEL/Mobilogram.h
src/openms/include/OpenMS/KERNEL/RangeManager.h
src/openms/source/KERNEL/MobilityPeak1D.cpp
src/openms/source/KERNEL/Mobilogram.cpp
src/tests/class_tests/openms/source/MSSpectrum_test.cpp
src/tests/class_tests/openms/source/MobilityPeak1D_test.cpp
src/tests/class_tests/openms/source/Mobilogram_test.cpp
src/tests/class_tests/openms/source/RangeManager_test.cpp

Add a container for ion mobility (Mobilogram) and the contained peaks (MobilityPeak1D).
Along the way, issues with RangeManager are fixed (missing move ctor), which prevents derived classes (such as Mobilogram) to have properly defaulted move c'tor (at least in VS2019).
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style …

Ion Mobilogram support

---

doc/doxygen/install/install-win.doxygen

...
<details>
</details>
<details> …

fix windows installation instructions

---

src/pyOpenMS/tests/unittests/test000.py

Added file descriptions with file names to the ConsensusMap. Required for the GNPS meta value file.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat …

[Fix] GNPSMetaValueFile pyopenms test

---

src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp
src/openms/source/FORMAT/DATAACCESS/SiriusFragmentAnnotation.cpp
src/tests/topp/THIRDPARTY/third_party_tests.cmake
src/utils/SiriusAdapter.cpp

Fixes #6253
fixes #6247 
fixes #6250 
turns out log parsing worked already but only was recorded when sirius completely fails.

Several sirius fixes

---

doc/doxygen/Doxyfile.in

fixes https://github.com/OpenMS/OpenMS/issues/6258
<details>
</details>
<details> …

fix CSS include

---

src/openms/source/FORMAT/GNPSMetaValueFile.cpp
src/pyOpenMS/tests/unittests/test000.py
src/tests/topp/GNPSExport_4_out_meta_values.tsv

As requested in  #6246
<details>
</details>
<details> …

[Feature] Index column for GNPS meta value file

---

.github/workflows/pyopenms-wheels.yml
src/pyOpenMS/CMakeLists.txt
src/pyOpenMS/tests/integration_tests/test_MRMRTNormalizer.py
src/pyOpenMS/tests/unittests/test_MRMFeatureFinderScoring.py

fixes #6270
turns out pytest is compatible out of the box
<details>
</details>
<details> …

Switch from nose to pytest

---

src/openms/include/OpenMS/KERNEL/AreaIterator.h
src/openms/include/OpenMS/KERNEL/DimMapper.h
src/tests/class_tests/openms/source/DimMapper_test.cpp

<details>
</details>
<details> …

fix compile bug

---

src/openms/include/OpenMS/FILTERING/SMOOTHING/SavitzkyGolayFilter.h
src/openms/include/OpenMS/KERNEL/AreaIterator.h
src/openms/include/OpenMS/KERNEL/MSExperiment.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/InterpolationModel.h

...
<details>
</details>
<details> …

fix some frequent warnings

---

src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp

fixes #6215
<details>
</details>
<details> …

force OpenGL 2.1 on macOS

---

src/openms_gui/source/VISUAL/TVToolDiscovery.cpp

fixes https://github.com/OpenMS/OpenMS/issues/6235
<details>
</details>
<details> …

sync output in tool discvoery

---

src/openms/include/OpenMS/ANALYSIS/ID/PrecursorPurity.h
src/openms/source/ANALYSIS/ID/PrecursorPurity.cpp
src/pyOpenMS/pxds/PrecursorPurity.pxd

<details>
</details>
<details> …

handle negative and zero charge

---

.github/workflows/openms-ci.yml
.github/workflows/pyopenms-wheels.yml
README.md
doc/OpenMS_tutorial/OpenMS_Tutorial.doxygen
doc/doxygen/public/developer-faq.doxygen
tools/jenkins/README.MD

fixes repo part of #6307 
<details>
</details>
<details> …

[FIX] update abibuilder urls

---

src/pyOpenMS/create_cpp_extension.py

implements part of #6310 
<details>
</details>
<details> …

pyopenms class doc link

---

src/openms/include/OpenMS/ANALYSIS/ID/IDScoreSwitcherAlgorithm.h
src/utils/ProteomicsLFQ.cpp

Fixes first round of small bugs/edge cases that might have been introduced in refactoring plfq.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat …

fix some bugs recently introduced in large refactoring

---

src/openms/source/ANALYSIS/QUANTITATION/PeptideAndProteinQuant.cpp

<details>
</details>
<details> …

[fix] don't crash on empty peptide hits vector in PeptideAndProteinQuant

---

src/openms_gui/source/VISUAL/TOPPASOutputFileListVertex.cpp

fixes https://github.com/OpenMS/OpenMS/issues/6303
<details>
</details>
<details> …

remove dependency to QtConcurrent

---

src/openms/include/OpenMS/ANALYSIS/ID/IDScoreGetterSetter.h
src/openms/source/ANALYSIS/ID/FalseDiscoveryRate.cpp

fix wrong parameter passed to idscoregetter function
<details>
</details>
<details> …

correct parameters

---

src/openms/thirdparty/evergreen/src/CMakeLists.txt

fixes #6314
fixes #6315
<details>
</details>
<details> …

Move install location of thirdparty headers into openms include dir

---

.github/workflows/pyopenms-wheels.yml

<details>
</details>
<details> …

Upload to nightly pypi repo

---

LICENSE.md

The alternative is to change the existing one. What do you prefer?
<details>
</details>
<details>
- setting the …

Create GitHub readable license file.

---

.gitpod.yml
cmake/cmake_findExternalLibs.cmake
cmake/package_deb.cmake
src/openms/CMakeLists.txt
src/openms/include/OpenMS/DATASTRUCTURES/LPWrapper.h
src/openms/source/DATASTRUCTURES/LPWrapper.cpp

<details>
</details>
<details> …

[Deps] make GLPK really optional

---

cmake/Windows/NSIS.template.in
src/openms/CMakeLists.txt

Fixes windows install directories for sqlite
<details>
</details>
<details>
- setting the label "NoJenkins" will …

Win install fixes

---

src/openms/source/ANALYSIS/ID/SimpleSearchEngineAlgorithm.cpp

fixes #6372 
<details>
</details>
<details> …

write identifier in SSE

---

src/openms/include/OpenMS/CHEMISTRY/NASequence.h
src/openms/source/CHEMISTRY/NASequence.cpp

Expanded documentation in NASequence.h
<details>
</details>
<details> …

[nop] Added documentation for some NASequence functions that needed it.

---

src/pyOpenMS/addons/AASequence.pyx
src/pyOpenMS/addons/FloatDataArray.pyx
src/pyOpenMS/addons/IntegerDataArray.pyx
src/pyOpenMS/addons/StringDataArray.pyx

<details>
</details>
<details> …

[FIX] fixes some signedness comparison warnings in pyx files

---

.github/workflows/pyopenms-wheels.yml

<details>
</details>
<details> …

Fix install-qt-action

---

doc/doxygen/install/install-linux.doxygen

- wildmagic not needed anymore
- glpk now optional
<details>
</details>
<details> …

Update linux build instructions

---

CMakeLists.txt
cmake/MacOSX/fix_dependencies.rb
cmake/knime_package_support.cmake

allow Qt built with RPATH (new default in brew). remove Resampler since it pulls in GUI libs.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails …

restructure and fix knime packaging. mainly on macOS

---

doc/doxygen/install/install-win.doxygen

We require Visual Studio 2019 (version 16.8.4 from January 2021) -- earlier versions, most notably VS2019 16.7.4 do not compile anymore.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., …

up the minimum required VS2019 version

---

cmake/knime_package_support.cmake
cmake/multithreading.cmake

<details>
</details>
<details> …

[FEATURE] better KNIME packaging. Ship redist on Win and strip on lnx/mac

---

src/utils/ProteomicsLFQ.cpp

<details>
</details>
<details> …

[FIX] PLFQ mztab config bug

---

src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
src/openms_gui/include/OpenMS/VISUAL/TVToolDiscovery.h
src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/TVToolDiscovery.cpp

In TOPPView tool discovery
<details>
</details>
<details> …

restrict number of spawned processes

---

AUTHORS
CONTRIBUTING.md

Added a link in the section "Reporting a New Issue" to go directly to the New Issue page.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to …

Clarified bug/feature reporting in CONTRIBUTING.md

---

cmake/MacOSX/fix_dependencies.rb

<details>
</details>
<details> …

Fix boolean logic

---

src/pyOpenMS/pxds/SpectrumLookup.pxd

<details>
</details>
<details> …

SpectrumLookup: add regex format to pyOpenMS doc

---

.github/workflows/openms-ci.yml
doc/doxygen/install/install-linux.doxygen
src/tests/class_tests/openms/source/DetectabilitySimulation_test.cpp
src/tests/class_tests/openms/source/PrecursorIonSelectionPreprocessing_test.cpp

- fix some svm related fluctuations in tests.
- update ci and build instructions
<details>
</details>
<details>
- …

Fix clang ci

---

src/openms/include/OpenMS/METADATA/MetaInfoInterface.h
src/openms/source/METADATA/MetaInfoInterface.cpp

closes #6480 
<details>
</details>
<details> …

prevent life-time issue in metainfointerface  by returning by value

---

src/openms/include/OpenMS/ANALYSIS/ID/AhoCorasickAmbiguous.h
src/openms/source/ANALYSIS/ID/AhoCorasickAmbiguous.cpp
src/openms/source/ANALYSIS/ID/FalseDiscoveryRate.cpp
src/openms/source/ANALYSIS/ID/IonIdentityMolecularNetworking.cpp
src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp
src/openms/source/ANALYSIS/OPENSWATH/MRMScoring.cpp
src/openms/source/ANALYSIS/OPENSWATH/TargetedSpectraExtractor.cpp
src/openms/source/ANALYSIS/RNPXL/RNPxlReport.cpp
src/openms/source/KERNEL/ConsensusMap.cpp

no really performance critical things
<details>
</details>
<details> …

fixes some (potential) copies

---

src/openms/include/OpenMS/FORMAT/DATAACCESS/SiriusMzTabWriter.h
src/tests/topp/THIRDPARTY/SiriusAdapter_10_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_1_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_2_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_3_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_8_output.mzTab
src/tests/topp/THIRDPARTY/SiriusAdapter_9_output.mzTab

Fixes #6465
<details>
</details>
<details> …

[Feature] Update to Sirius 5.6.3 snapshot

---

.github/workflows/openms-ci.yml
cmake/knime_package_support.cmake
doc/doxygen/install/install-linux.doxygen
vcpkg.json

<details>
</details>
<details> …

remove sqlite from linux build instructions

---

src/openms/thirdparty/SQLiteCpp/include/SQLiteCpp/Database.h

don't use std::filesystem because of missing support on e.g. Mac 
<details>
</details>
<details>
- setting the …

exclude std::filesystem dependent functions

---

cmake/export_macros.cmake

fixes #6313
<details>
</details>
<details> …

Use INSTALL_CMAKE_DIR variable

---

src/openms/source/DATASTRUCTURES/String.cpp

might fix the karma issue (depending on if bug only affects subnormal numbers etc.)
<details>
</details>
<details> …

might fix karma issue

---

.github/workflows/openms-ci.yml

Edit: Seems like a 35+ mins improvement.
<details>
</details>
<details> …

Try ninja on GHA Win

---

.github/workflows/openms_clang_format.yml
.github/workflows/openms_clang_format_add_and_commit.yml
.github/workflows/pyopenms-wheels.yml

Update to the correct URL
<details>
</details>
<details> …

Update Uni-tuebingen pypi url

---

CONTRIBUTING.md

Some minor typos in CONTRIBUTING.md

[DOC] minor typos

---

src/openms/include/OpenMS/ANALYSIS/QUANTITATION/sources.cmake

probably small oversight
<details>
</details>
<details> …

add missing header file

---

cmake/cmake_findExternalLibs.cmake

probably a left over
<details>
</details>
<details> …

remove qt sql from findExternalLibs

---

.github/workflows/pyopenms-wheels.yml

We really should use a supported versions file to fix that for all builds.
<details>
</details>
<details>
- setting …

Fix py versions to newer ones on manylinux action

---

cmake/package_dragndrop_dmg.cmake
cmake/package_general.cmake

<details>
</details>
<details> …

small packaging err on macOS

---

src/pyOpenMS/converters/special_autowrap_conversionproviders.py

fixes part of #6559
<details>
</details>
<details> …

remove unicode from convProv

---

src/pyOpenMS/converters/special_autowrap_conversionproviders.py
src/pyOpenMS/fix_pyi_imports.py

<details>
</details>
<details> …

Fix numpy typing in pyopenms

---

src/openms/include/OpenMS/ANALYSIS/ID/BayesianProteinInferenceAlgorithm.h
src/openms/include/OpenMS/ANALYSIS/ID/FIAMSDataProcessor.h
src/openms/include/OpenMS/ANALYSIS/ID/FIAMSScheduler.h
src/openms/include/OpenMS/ANALYSIS/ID/FalseDiscoveryRate.h
src/openms/include/OpenMS/MATH/STATISTICS/PosteriorErrorProbabilityModel.h
src/openms/include/OpenMS/METADATA/ID/IdentificationData.h
src/openms/include/OpenMS/QC/FragmentMassError.h
src/openms/include/OpenMS/QC/MissedCleavages.h
src/openms/include/OpenMS/SYSTEM/RWrapper.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/GaussTraceFitter.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteredPeak.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/TraceFitter.h
src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/PeakPickerHiRes.h
src/openms_gui/include/OpenMS/VISUAL/APPLICATIONS/TOPPViewBase.h
src/openms_gui/include/OpenMS/VISUAL/DIALOGS/PythonSelector.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataBase.h
src/openms_gui/include/OpenMS/VISUAL/Painter1DBase.h
src/openms_gui/include/OpenMS/VISUAL/Painter2DBase.h
src/openms_gui/include/OpenMS/VISUAL/Plot1DCanvas.h
src/openms_gui/include/OpenMS/VISUAL/Plot2DCanvas.h
src/openms_gui/include/OpenMS/VISUAL/SpectraTreeTab.h

a few fixes on the long list of doxygen warnings...
<details>
</details>
<details> …

Fix doc warnings

---

src/openms/source/ANALYSIS/OPENSWATH/OpenSwathTSVWriter.cpp

Recently in https://github.com/OpenMS/OpenMS/pull/6268 added extra output to OpenSwath .osw file. Update .tsv file to also contain this extra output
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving …

[FEATURE] add IM output to OpenSwath tsv file

---

share/OpenMS/examples/FRACTIONS/BSA1_F1_msgf_idx_fdr_idpep_switched_filter.idXML
share/OpenMS/examples/FRACTIONS/BSA1_F2_msgf_idx_fdr_idpep_switched_filter.idXML
share/OpenMS/examples/FRACTIONS/BSA2_F1_msgf_idx_fdr_idpep_switched_filter.idXML
share/OpenMS/examples/FRACTIONS/BSA2_F2_msgf_idx_fdr_idpep_switched_filter.idXML
share/OpenMS/examples/FRACTIONS/BSA3_F1_msgf_idx_fdr_idpep_switched_filter.idXML
share/OpenMS/examples/FRACTIONS/BSA3_F2_msgf_idx_fdr_idpep_switched_filter.idXML
src/openms/include/OpenMS/METADATA/ProteinIdentification.h
src/openms/source/ANALYSIS/ID/IDRipper.cpp
src/openms/source/METADATA/ProteinIdentification.cpp
src/tests/topp/PSMFeatureExtractor_1_out.idXML
src/tests/topp/PSMFeatureExtractor_3_out.idXML
src/tests/topp/ProteomicsLFQ_6_out.consensusXML
src/tests/topp/THIRDPARTY/MSGFPlusAdapter_1_out.idXML

copy only metadata to prevent excessive copies of protein hits
<details>
</details>
<details> …

IDRipper: prevent unneeded copies 

---

src/tests/topp/PSMFeatureExtractor_2_out.mzid

<details>
</details>
<details> …

bump THIRDPARTY

---

src/openms_gui/include/OpenMS/VISUAL/Plot3DCanvas.h
src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp
src/openms_gui/source/VISUAL/Plot3DCanvas.cpp
src/openms_gui/source/VISUAL/Plot3DOpenGLCanvas.cpp
src/openms_gui/source/VISUAL/Plot3DWidget.cpp

when pressing `Ctrl` an intermediate 2D view pops up and allows to select a RT-mz region. 
This worked, however, the resulting 3D view would zoom into the wrong region since axis coordinates from pixel to widget coordinates were swapped. I.e. swapping RT <> m/z.
This PR fixes this along with some mild cleanup for the goto-dialog.
<details>
</details>
<details>
- …

TOPPView: fixes 3D view zooming

---

src/openms/include/OpenMS/FILTERING/DATAREDUCTION/FeatureOverlapFilter.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.h
src/openms/source/FILTERING/DATAREDUCTION/FeatureOverlapFilter.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
src/tests/class_tests/openms/source/FeatureOverlapFilter_test.cpp
src/tests/topp/FeatureFinderMetaboIdent_1_output.featureXML

Replaces the overlap check using the quadtree datastructure.
<details>
</details>
<details> …

Replace the FFMID O(n*n) overlap check with an efficient, quadtree-based approach

---

src/tests/topp/FeatureFinderMetaboIdent_1_input.tsv
src/tests/topp/FeatureFinderMetaboIdent_1_output.featureXML

Extend test data so we also see the output for overlap removal of similar and handling of equal entries
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, …

additional test data to generate overlap cases

---

src/openms/include/OpenMS/COMPARISON/CLUSTERING/ClusterHierarchical.h
src/openms/include/OpenMS/COMPARISON/SPECTRA/BinnedSpectrum.h
src/openms/include/OpenMS/KERNEL/DimMapper.h
src/openms/include/OpenMS/KERNEL/RangeManager.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/EmgScoring.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/InterpolationModel.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataBase.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataChrom.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataConsensus.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataFeature.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataIdent.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataIonMobility.h
src/openms_gui/include/OpenMS/VISUAL/LayerDataPeak.h
src/openms_gui/include/OpenMS/VISUAL/VISITORS/LayerStatistics.h

mostly in RangeManager, which repeatedly shows up due to being a templated class
<details>
</details>
<details>
- …

Fix warnings

---

src/openms/CMakeLists.txt
src/openms/include/OpenMS/FILTERING/DATAREDUCTION/FeatureOverlapFilter.h
src/openms/include/OpenMS/FILTERING/DATAREDUCTION/sources.cmake
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.h
src/openms/source/FILTERING/DATAREDUCTION/FeatureOverlapFilter.cpp
src/openms/source/FILTERING/DATAREDUCTION/sources.cmake
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderAlgorithmMetaboIdent.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp
src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringProfile.cpp
src/openms/thirdparty/Quadtree/CMakeLists.txt
src/openms/thirdparty/Quadtree/LICENSE
src/openms/thirdparty/Quadtree/include/Box.h
src/openms/thirdparty/Quadtree/include/Quadtree.h
src/openms/thirdparty/Quadtree/include/Vector2.h
src/tests/class_tests/openms/executables.cmake
src/tests/class_tests/openms/source/FeatureOverlapFilter_test.cpp
src/tests/topp/FeatureFinderMetaboIdent_1_output.featureXML

Significant speedup of FFMetaboIdent
<details>
</details>
<details>
- setting the label "NoJenkins" will skip tests …

[FEATURE] Add a filter class that can filter FeatureMaps on overlaps

---

src/tests/class_tests/openms/source/File_test.cpp

switch to http (because SSL might not be compiled into qt)
<details>
</details>
<details> …

use http in test

---

cmake/Windows/NSIS.template.in

fixes #6600 
fixes #6598 
<details>
</details>
<details> …

[FIX] WinInstaller Default Alluser and no docs

---

doc/doxygen/parameters/DefaultParamHandlerDocumenter.cpp

Fixes missing headers in DefaultParameterHandlerDocumenter introduced in https://github.com/OpenMS/OpenMS/pull/6466
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). …

[fix] added missing includes

---

src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp

should fix https://github.com/OpenMS/OpenMS/issues/6637
<details>
</details>
<details> …

and _in suffix in runTOPPTool_

---

CMakeLists.txt
cmake/cmake_findExternalLibs.cmake
src/openms/CMakeLists.txt
src/openms/include/OpenMS/FORMAT/sources.cmake
src/openms/source/FORMAT/sources.cmake
src/tests/class_tests/openms/CMakeLists.txt
src/tests/class_tests/openms/executables.cmake

make HDF5 optional
<details>
</details>
<details> …

make hdf5 optional

---

CMakeLists.txt
doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-macs.doxygen
doc/doxygen/install/install-win.doxygen

to 3.21
<details>
</details>
<details> …

Fix Min Cmake version

---

dependabot.yml

<details>
</details>
<details> …

Try dependabot automatic submodule updates

---

src/openms/include/OpenMS/METADATA/ID/IdentificationData.h
src/openms/source/METADATA/ID/IdentificationData.cpp
src/tests/class_tests/openms/source/IdentificationData_test.cpp

add move const. and assignment to ID datastructure
<details>
</details>
<details> …

ID Datastructure rule of 6

---

CMakeLists.txt

<details>
</details>
<details> …

[KNIME] also use install_name_dir at build time

---

cmake/MacOSX/fix_dependencies.rb
cmake/knime_package_support.cmake

<details>
</details>
<details> …

[FIX][KNIME] fixup script to handle knime case on macos

---

src/openms/include/OpenMS/CONCEPT/LogConfigHandler.h
src/openms/include/OpenMS/CONCEPT/LogStream.h
src/openms/source/CONCEPT/LogConfigHandler.cpp
src/openms/source/CONCEPT/LogStream.cpp
src/pyOpenMS/addons/LogConfigHandler.pyx
src/pyOpenMS/pxds/LogConfigHandler.pxd
src/tests/class_tests/openms/source/LogConfigHandler_test.cpp

maybe fixes https://github.com/OpenMS/pyopenms-docs/issues/375
<details>
</details>
<details> …

[FEATURE] allow setting global log level easily.

---

src/openms/source/CHEMISTRY/ElementDB.cpp
src/tests/class_tests/openms/source/FLASHDeconvAlgorithm_test.cpp
src/tests/class_tests/openms/source/FLASHDeconvHelperStructs_test.cpp
src/tests/class_tests/openms/source/MassFeatureTrace_test.cpp
src/tests/class_tests/openms/source/MzMLFile_test.cpp

mainly in tests
<details>
</details>
<details> …

fix memory leaks

---

src/openms/include/OpenMS/DATASTRUCTURES/DRange.h
src/openms_gui/include/OpenMS/VISUAL/DIALOGS/Plot2DGoToDialog.h
src/openms_gui/source/VISUAL/DIALOGS/Plot2DGoToDialog.cpp
src/openms_gui/source/VISUAL/DIALOGS/Plot2DGoToDialog.ui
src/openms_gui/source/VISUAL/Plot2DWidget.cpp
src/openms_gui/source/VISUAL/Plot3DWidget.cpp
src/tests/class_tests/openms/source/DRange_test.cpp

fix bug: wrong labels/swapped RT/mz dimensions in 2d GoTo dialogs and clean up a bit.
<details>
</details>
<details>
- `/reformat` (experimental) applies the clang-format style changes as additional commit. Note: your branch must have a different name (e.g., yourrepo:feature/XYZ) than the receiving branch (e.g., OpenMS:develop). Otherwise, reformat fails to …

TOPPView: fix goto dialogs

---

tools/pychecker_ignore.yaml

<details>
</details>
<details> …

SVMPrediction

---

src/tests/topp/THIRDPARTY/CometAdapter_1_out.idXML
src/tests/topp/THIRDPARTY/CometAdapter_2_out.idXML
src/tests/topp/THIRDPARTY/CometAdapter_3_out.idXML
src/tests/topp/THIRDPARTY/CometAdapter_4_out.idXML
src/topp/CometAdapter.cpp

<details>
</details>
<details> …

Adjust cometadapter tests

---

src/openms/source/FORMAT/PepXMLFile.cpp

<details>
</details>
<details> …

parse new comet entries

---

src/tests/topp/THIRDPARTY/CometAdapter_1_out.idXML
src/tests/topp/THIRDPARTY/CometAdapter_2_out.idXML
src/tests/topp/THIRDPARTY/CometAdapter_3_out.idXML
src/tests/topp/THIRDPARTY/CometAdapter_4_out.idXML

Comet tests following up #6813
<details>
</details>
<details> …

Add comet tests with new pepxml output

---

src/openms/include/OpenMS/CHEMISTRY/RibonucleotideDB.h
src/openms/source/CHEMISTRY/RibonucleotideDB.cpp

Fixes https://github.com/OpenMS/OpenMS/issues/6767
<details>
</details>
<details> …

[fix] fixed memory leaks in RibonucleotideDB class

---

src/openms/include/OpenMS/MATH/STATISTICS/StatisticFunctions.h
src/openms/include/OpenMS/METADATA/ID/ObservationMatchGroup.h
src/openms/include/OpenMS/METADATA/ID/ProcessingSoftware.h
src/openms/include/OpenMS/METADATA/ID/ProcessingStep.h
src/openms/include/OpenMS/METADATA/MSQuantifications.h
src/openms/include/OpenMS/QC/DBSuitability.h
src/openms/include/OpenMS/QC/QCBase.h
src/openms/include/OpenMS/SIMULATION/EGHModel.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/EmgScoring.h
src/openms/include/OpenMS/TRANSFORMATIONS/FEATUREFINDER/IsotopeWaveletTransform.h
src/openms/source/ANALYSIS/ID/ProtonDistributionModel.cpp
src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentAlgorithmIdentification.cpp
src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentEvaluationAlgorithmPrecision.cpp
src/openms/source/ANALYSIS/MAPMATCHING/MapAlignmentEvaluationAlgorithmRecall.cpp
src/openms/source/ANALYSIS/MAPMATCHING/QTClusterFinder.cpp
src/openms/source/METADATA/MSQuantifications.cpp
src/openms/source/QC/DBSuitability.cpp
src/tests/topp/THIRDPARTY/DatabaseSuitability_out.tsv

to increase softwipe score :)
<details>
</details>
<details> …

Cpp check fixes

---

src/utils/MetaProSIP.cpp

<details>
</details>
<details> …

MetaProSIP: typo

---

src/openms/source/DATASTRUCTURES/Param.cpp
src/openms/source/FORMAT/ParamXMLFile.cpp
src/tests/class_tests/openms/source/Param_test.cpp

Should fix iterator tracing with empty subtrees

[FIX] Param merging with empty subsections

---

src/openms/source/ANALYSIS/ID/SimpleSearchEngineAlgorithm.cpp
src/openms/source/CHEMISTRY/DecoyGenerator.cpp

fixes https://github.com/OpenMS/OpenMS/issues/6888
<details>
</details>
<details> …

Honor MissedCleavages in SimpleSearchEngine

---

src/pyOpenMS/CMakeLists.txt

fixes #6903
fixes #6797 
<details>
</details>
<details> …

[fix][pyopenms] adhoc sign libs that are copied into wheel

---

src/pyOpenMS/Jenkinsfile

<details>
</details>
<details> …

some comments / documentation

---

.github/workflows/pyopenms-wheels.yml
src/pyOpenMS/Jenkinsfile
src/pyOpenMS/tests/memoryleaktests/testAll.py

<details>
</details>
<details> …

Pyopenms jenkinsfile (for macOS silicon)

---

src/utils/MSFraggerAdapter.cpp

<details>
</details>
<details> …

remove unicode character from description in MSFraggerAdapter.cpp

---

doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-macs.doxygen
doc/doxygen/install/install-win.doxygen

bump from 3.21 to 3.24
<details>
</details>
<details> …

fix minimal cmake version

---

src/tests/topp/THIRDPARTY/MascotAdapterOnline_2_out.idXML

fixes https://github.com/OpenMS/OpenMS/issues/6937
<details>
</details>
<details> …

update mascot test

---

.github/workflows/update_year_number.yml
doc/doxygen/install/install-linux.doxygen
doc/doxygen/install/install-macs.doxygen
doc/doxygen/install/install-win.doxygen
src/tests/topp/THIRDPARTY/MascotAdapterOnline_2_out.idXML

without the tutorial-removal
<details>
</details>
<details> …

update Release3.0.0 

---

src/tests/class_tests/openms/source/SimpleSVM_test.cpp

RBF seems a bit slow but this is about twice as fast
<details>
</details>
<details> …

SimpleSVM test speedup
